### ISSUE TITLE
fix: @isEnumTSC error

### ISSUE THREAD

**Issue by Artyom-Ganev** [typestack/class-validator#1003]
### Description

I'm using `class-validator ^0.13.1` in Nest JS app to validate enum filed value of DTO and get errors:
![image](https://user-images.githubusercontent.com/13161268/113487149-06e0eb00-94bf-11eb-9452-19be46aeece1.png)
![image](https://user-images.githubusercontent.com/13161268/113487161-1fe99c00-94bf-11eb-8c2d-d56f18051f2e.png)

Here is what I see in my `node_modules`:
![image](https://user-images.githubusercontent.com/13161268/113487189-56bfb200-94bf-11eb-91b4-2f93acb8f763.png)
![image](https://user-images.githubusercontent.com/13161268/113487200-6212dd80-94bf-11eb-9ecf-92098b411a82.png)

**Minimal code-snippet showcasing the problem**
```ts
enum PlayerRole {
  GAME_OWNER = 'gameOwner',
  OWNER = 'owner',
}

export class CreatePlayerDto {
  @IsNotEmpty()
  @IsString()
  readonly name: string;

  @IsNotEmpty()
  @isEnum(PlayerRole, {}) // or @isEnum(PlayerRole)
  readonly role: PlayerRole;
}
```

### Expected behavior
JS/TS doesn't support function overloading, that's why:
1. There should be only one isEnum function.
2. It should support single argument usage as it's written in docs.

### Actual behavior
TSC throws error when @isEnum is used with single argument or with 2 arguments, when second is options.

**Comment by korki43** [comment]
Use the uppercase decorator function. `isEnum` is not a decorator but can be used to programatically check if a value is an enum. 

Usage of `IsEnum` (decorator):

```ts
class CreatePlayerDto {
  @IsEnum(PlayerRole)
  role: PlayerRole
}
```

Usage of `isEnum` (function):
```ts
if(isEnum(myRole, PlayerRole)){
  // `myRole` is in enum `PlayerRole`
}
```

**Comment by Artyom-Ganev** [comment]
Thank you, It works!
