### ISSUE TITLE
question: Is there a way to group decorators together?

### ISSUE THREAD

**Issue by flisboac** [typestack/class-validator#1005]
**I was trying to...**
Group multiple decorators together, in one convenient decorator that fully describes a singular concept/field.

For example, let's say I have a "tags" concept in my entity, and some constraints to go with it:
- The list may be optional (leaving that to explicit usage of `@IsDefined()` and `@IsOptional()`) though), but if provided...
- The property must be an array
- Each element of the array must be a string
- Each string in the array must match a specific pattern

An example:

```typescript
class UpdateResourceCommand {
  // ...

  @IsOptional()
  @IsArray({ message: 'Must be an array' })
  @IsString({ each: true, message: 'Each tag value must be a string.' })
  @Matches(/^[^,\r\n]+$/, { each: true, message: 'Invalid tag format.' })
  tags?: string[];
}
```

What I wanted to do instead was to try and create a single decorator, so that my class definition becomes like so:

```typescript
class UpdateResourceCommand {
  // ...

  @IsOptional()
  @IsTags()
  tags?: string[];
}
```

**The problem:**

It would be cool if we could create a new decorator by meshing together multiple decorators, that would then be applied to a target in the order they're declared. For example:

```typescript
export function IsTags(validationOptions?: ValidationOptions) {
  return (object: Object, propertyName: string) => {
    // ...
    constraints: [
      @IsArray({ message: 'Must be an array' }),
      @IsString({ each: true, message: 'Each tag value must be a string.' }),
      @Matches(/^[^,\r\n]+$/, { each: true, message: 'Invalid tag format.' }),
    ],
    validator: {
      validate(value: unknown, args: ValidationArguments) {
        const { constraints } = args;
        // ???
        // How to apply constraints?
      },
    },
  };
}
```

What I wanted to achieve was to reutilize other decorator implementations, including reutilizing their messages (if any), but it seems the `validate` functon merely returns a boolean (or a promise of it).

Is there any way to reutilize other decorators and group them together in a similar manner? (apart from the default approach of implementing the decorator fully, instead of reutilizing other constraints).

**Comment by sanex3339** [comment]
Hi. Any solutions?

**Comment by sanex3339** [comment]
Did something like this:
```
/**
 * @returns {PropertyDecorator}
 */
export const IsDomainDestUrl = (): PropertyDecorator => {
    return (target: any, key: string | symbol): void => {
        ValidateIf(({domainDest}: TInputOptions) => {
            return domainDest !== DEFAULT_PRESET.domainDest;
        })(target, key);
        IsUrl({
            require_protocol: false,
            require_host: false
        })(target, key);
        IsAllowedForObfuscationTargets([
            ObfuscationTarget.Browser,
            ObfuscationTarget.BrowserNoEval,
        ])(target, <keyof IOptions>key);
    };
};
```
