### ISSUE TITLE
feature: url safe base64 validation

### ISSUE THREAD

**Issue by korki43** [typestack/class-validator#1013]
### Description
There should be a way to validate url safe base64. 

### Proposed solution

Add `validator.IsBase64Options` as optional constraints to the `isBase64` decorator.

**Comment by mug-cat** [comment]
Interesting how this is not getting any attention at all

**Comment by gustavotoyota** [comment]
Just bumped into this problem.

**Comment by braaar** [comment]
Seems like a no brainer, since this is just catching up to the upstream features.

Anyone want to make a PR?

**Comment by kiehnek** [comment]
It seems like this repo was abandoned. The last non-automated commit was 10 months ago despite a lot of of open issues/PRs. 

For now you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix this by yourself.

**Comment by braaar** [comment]
> It seems like this repo was abandoned. The last non-automated commit was 10 months ago despite a lot of of open issues/PRs.
> 
> For now you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix this by yourself.

I have made [this issue](https://github.com/typestack/class-validator/issues/1719) about the matter. Chime in if you're interested in trying to revive the project!

**Comment by NoNameProvided** [comment]
Fixed in https://github.com/typestack/class-validator/pull/1845.
