### ISSUE TITLE
question: Can we use @Min & @Max with decimals?

### ISSUE THREAD

**Issue by bugoverdose** [typestack/class-validator#1014]
When I was changed @Min(1) to @Min(0.5) in my NestJS project, I started having errors. Everything was compiled OK, of course, but I had errors when I tried to send graphql queries. 

Is this a bug with @Min or have I mistaken? 

ex)  
@Min(0.5)
@Min(5)
rating: number;

**Comment by korki43** [comment]
You can use `@Min()` and `@Max()` with decimals. Just make sure you're really using the uppercased decorators and you're using the graphql `Float` type in your schema. Also please share the error you're getting.

**Comment by bugoverdose** [comment]
I fixed the bug. Apparently, it had nothing to do with class-validators and graphQL. I made a mistake on the database with the column types. Thanks for the comment, anyway. It helped me fix the problem super-fast.
