### ISSUE TITLE
question: Is it possible to apply decorator to every field in the class?

### ISSUE THREAD

**Issue by heyitsarpit** [typestack/class-validator#1029]
Here's an example of a class that I'm validating, 
I would like to create a new class with the `@IsOptiona()` decorator applied to each field. 

```js
export class CreateCompanyDto {
    @Length(2, 150)
    name: string;

    @IsOptional()
    @IsUrl()
    logoImageUrl: string;

    @IsUrl()
    websiteUrl: string;
}
``` 

Currently, I have to write it out by hand, but the class is rather large, and it's getting cumbersome to write it all out.

```js
export class UpdateCompanyDto {
    @IsOptional()
    @Length(2, 150)
    name: string;

    @IsOptional()
    @IsUrl()
    logoImageUrl: string;

    @IsOptional()
    @IsUrl()
    websiteUrl: string;
}
```

Is there a way to derive `UpdateCompanyDto` from `CreateCompanyDto` but with `@IsOptional()` applied to each field?

**Comment by NoNameProvided** [comment]
Yes, you can use groups to validate using the subset of decorators in the class. (On a personal note, I prefer and use the solution you use because it's explicit.)
