### ISSUE TITLE
Inject service to ValidatorConstraint

### ISSUE THREAD

**Issue by truewt** [typestack/class-validator#103]
Hi,

First of all thanks for such a great libraries (class-validator, routing-controllers, typeorm, typedi, typeorm-typedi-extensions), it's a pleasure using them since they simplify a lot of things and make code readable at the highest level.

I started using all the mentioned libraries a while ago together in my own project, to create a REST API and so far I managed to handle all the issues I had either with looking at source, reading documentation/readme or via existing issues/questions. However, I couldn't find any information on how to correctly inject service into custom validator (created with ValidatorConstraint and ValidatorConstraintInterface + decorator function, to use it as it's own validator like the other validators), which would be used to query database via typeorm to check for existence of some entity. So far I just declared class which is implementing ValidatorConstraintInterface as a Service (from typedi) and put my own service (which then gets repository) into the constructor, so it's successfully injected. Here is a code snippet of the constraint (I didn't include imports here, but they are present in the file):

```
@Service()
@ValidatorConstraint({ name: "isUnique", async: true })
export class IsUniqueConstraint implements ValidatorConstraintInterface {

  constructor(
    private validatorService: ValidatorService
  ) {}

  validate(value: any, args: ValidationArguments): Promise<boolean> {
    return this.validatorService.isUnique(
      value,
      args.property,
      args.object.constructor
    );
  }

  defaultMessage(args: ValidationArguments): string {
    return `${args.property} must be unique`;
  }

}

export function IsUnique(validationOptions?: ValidationOptions) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: IsUniqueConstraint
    });
  };
}
```

Using this in a User entity (used in typeorm as Entity and in routing-controllers for validation as well):
```
@Entity("u1")
export class User {
  @PrimaryGeneratedColumn()
  @IsEmpty()
  user_id: number;

  @Column({
    length: 255,
    unique: true
  })
  @IsEmail()
  @IsUnique({
    message: 'email must be unique'
  })
  email: string;

  @Column({
    length: 256
  })
  @MinLength(8)
  password: string;
}
```

So far so good, everything works as expected when I'm trying out validation of existing email in database. But the problem arises when all values are validated without errors and are ready to be inserted into database. I have also created custom repository (typeorm) for that User entity and it may be used in a future - currently I don't have any other code then extending of Repository class as shown here: [@OrmCustomRepository](https://github.com/typeorm/typeorm-typedi-extensions#user-content-ormcustomrepository). When I call `createConnection` from typeorm in my bootstrap method, I figured out that when it's actually executing, entity in EntityRepository is undefined as long as I'm using my own IsUnique validator. Otherwise entity is correctly set to User and everything works as expected. What I suspect here to be a problem is dependency injection, because User class is Entity only and it should probably also be a Service, so it could somehow inject ValidatorService. I tried this already, but here also the typeorm should fetch User in Container and it's probably not, since this is unusual. I also tried using Validator decorator instead of IsUnique and put ValidatorConstraint into it, but it didn't work. I call useContainer in my bootstrap method separately for class-validator, typeorm and then for routing-controllers. All injections (other then the problem for EntityRepository - but there is no any injection I guess?) are working. I also moved some code around and tried numerous other things, but couldn't solve this problem, so that's why I would be very happy if anyone could help me out with this problem.

I will appreciate any help, even workarounds are welcome if this is not supported yet (I believe that I made a mistake somewhere and I'm wrong on this one). In case you need any other information I didn't provide yet, I will try to reply as soon as possible.

Thank you in advance!

**Comment by NoNameProvided** [comment]
Please reopen if you still encountering this issue.
