### ISSUE TITLE
question: Add FQDN validation with wildcard

### ISSUE THREAD

**Issue by fasenderos** [typestack/class-validator#1045]
Hi all, I need to validate FQDN with wildcard e.g.: `*.example.com` and I made a PR on [validator.js](https://github.com/validatorjs/validator.js/pull/1647) that add the `allow_wildcard` option to `isFQDN`, but it is still in pending. I hope it will be merged soon.

In the meantime if `class-validator` decorators can support "custom" options not provided by validator.js, I can make the same PR here, If you think it could be usefull.

Thanks

**Comment by NoNameProvided** [comment]
That PR is merged, next released version will contain the option.
