### ISSUE TITLE
question: How to use for dynamic properties?

### ISSUE THREAD

**Issue by cihatsaman** [typestack/class-validator#1050]
I have published my question already on [**StackOverflow**](https://stackoverflow.com/questions/67346348/typescript-class-validator-for-property-of-class). Decorators are executing before the set of values of input elements. So, the title looks empty all time, and validation fails always.
What I am missing? How can I use that library for valid to upcoming value from inputs?
You can see the example of the project with that [link](https://cihatsaman.github.io/sampleproject/).

**Comment by NoNameProvided** [comment]
Sorry, I am not able to provide general support for programming-related questions. If you have a specific question regarding to this library please provide some code for a minimal reproduction
