### ISSUE TITLE
question: breaking change between 0.13.0 and 0.13.1 with `@IsPhoneNumber` decorator

### ISSUE THREAD

**Issue by btilford** [typestack/class-validator#1062]
### Description
Support for using `ZZ` as a region being dropped will require pretty significant changes to any application that was built to support international phone numbers. Since this release was a patch pretty much all apps are going to get this update and break.

https://github.com/typestack/class-validator/pull/872/files#diff-6fc27b13597f8d14c527d6d6199b4b424c4d6f5f56fac7c89d347eaff58ee2cfR12-R13

### Expected behavior
Breaking changes don't happen on patch releases which NPM and other package managers will auto update to.

**Comment by NoNameProvided** [comment]
You are right. That slipped through, it should have been a minor change while we are below 1.0.
