### ISSUE TITLE
question: OR'ing validation rules

### ISSUE THREAD

**Issue by fmagno** [typestack/class-validator#1072]
Is there a mechanism of OR'ing validation rules?

As I understand it, the default behaviour is to AND decorators, for example here, `someValue` must  be an odd number AND cannot be greater than 30.

``` typescript
class Something {
    @IsOdd()
    @Max(30)
    someValue: number
}
```

How can an OR be implemented? For example, `someValue` must be both:

- Even OR at least 3
AND
- Odd OR 90 at most

``` typescript
class Something {
    @IsEven() || @Min(3)
    @IsOdd() || @Max(90)
    someValue: number
}
```

**Comment by luukvhoudt** [comment]
I guess a custom validator is the cleanest and possibly the only way out.

Although this a question I would suggest changing this issue into a feature, because this issue occurs in many use cases.

I think a new decorator should be introduced, e.g. `@DecorateIf(...)`

This is what I got for now (untested), this unfortunately doesn't propagate the validation message from the provided decorator to this new decorator.

```ts
import { buildMessage, ValidateBy, ValidationOptions } from 'class-validator';

export type DecorateIfHandler = (value: any) => boolean;

export const DECORATE_IF = 'decorateIf';

export function decorateIf(value: unknown, condition: DecorateIfHandler, decorate: DecorateIfHandler): boolean {
	const shouldDecorate = condition(value);

	return !shouldDecorate || (shouldDecorate && decorate(value));
}

export function DecorateIf(
	condition: DecorateIfHandler,
	decorate: DecorateIfHandler,
	validationOptions?: ValidationOptions,
): PropertyDecorator {
	return ValidateBy(
		{
			name: DECORATE_IF,
			constraints: [condition, decorate],
			validator: {
				validate: (value, args) => decorateIf(value, args.constraints[0], args.constraints[1]),
				defaultMessage: buildMessage(eachPrefix => eachPrefix + '$property is invalid', validationOptions),
			},
		},
		validationOptions,
	);
}
```

This is how you could use it:

```ts
class Something {
	@DecorateIf(v => isEven(v), v => min(v, 3), {
		message: 'someValue should be at least 3',
	})
	@DecorateIf(v => isOdd(v), v => max(v, 90), {
		message: 'someValue should be less then 90',
	})
	someValue: number;
}
```

**Comment by NoNameProvided** [comment]
Currently, there is no way to use `or` relationship between built-in decorators. As mentioned the cleanest way to go is to use custom validators. 

The ability to define `or` relationship between decorators is something we may/should support in core. 

If you still need the feature please open a [discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) about it. From now on discussions is the place where the community can brainstorm ideas and specify required functionality and proposed API surface before implementation. 

To be clear this means one cannot just open a feature request anymore without putting the effort in to specify it. For this feature, I think it would be worth looking around how others implement these features, what an easy-to-use API should look like, etc. 

Closing this question as answered.
