### ISSUE TITLE
how to validate array of objects

### ISSUE THREAD

**Issue by adnan-kamili** [typestack/class-validator#108]
I tried following but it didn't work:

```javascript
    @IsArray()
    @ValidateNested()
    customFields: CustomFieldViewModel[];
```

**Comment by Poitrin** [comment]
What’s the error message?
Are the items in the customFields array all instances of the CustomFieldViewModel class?

**Comment by NoNameProvided** [comment]
There is an open issue for this (#83). `@ValidateNested()` doesn't work with custom objects. 

If you have the same issue, please close this as it is the duplicate of #83

**Comment by NoNameProvided** [comment]
Closing this in favor of #83.
