### ISSUE TITLE
fix: IsString has "each" property, but "IsNumber" doesn't

### ISSUE THREAD

**Issue by DavideCarvalho** [typestack/class-validator#1085]
### Description

**Minimal code-snippet showcasing the problem**
 

```ts

```

**Comment by paulgrove** [comment]
I want to report the same issue, `@IsNumber`'s `IsNumberOptions` does not support property `each`.
I have had to write a custom Validation Decorator as a workaround.

**Comment by xiaoda001** [comment]
`@IsNumber({}, { each: true })`

**Comment by NoNameProvided** [comment]
As @xiaodaxuetu said, the `@IsNumber` two parameters:
- first one is about how to validate numbers
- second is the validation option that has the `each: true` option

This is true for multiple decorators.
