### ISSUE TITLE
question: Is it possible to return multiple messages?

### ISSUE THREAD

**Issue by Sicria** [typestack/class-validator#1105]
Is it possible to return multiple error messages from the custom validator?

I'm trying to create a validator for a password field to ensure it has length requirements, but also has character requirements (uppercase/number etc). I see you can return a message via `defaultMessage` but I'm not seeing a way to return different messages based on different cases.

Is it that the custom validators are supposed to be very basic and I should split them up a bit?

**Comment by RAGGA-TIME** [comment]
I did some attempts. hope can help you!😃

Reference Code

`javascript
/**
 * 自定义函数
 * @value 获取字段的值
 */
@ValidatorConstraint({ name: 'CustomFunction' })
export class CustomFunctionConstraint implements ValidatorConstraintInterface {
    validate(value: any, args: ValidationArguments): boolean {
        return args.constraints[0](value).bool as boolean
    }
    defaultMessage(args: ValidationArguments): string {
        const msg: string = args.constraints[0](args.value, args)?.msg || '';
        return msg
    }
}
export function CustomFunction(property: PlainObject, validationOptions?: ValidationOptions) {
    return function (object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            constraints: [property],
            validator: CustomFunctionConstraint,
        });
    };
}

/* class property  **/
@CustomFunction((val: any): { bool: boolean, msg?: string } => {
        if (val === '' || typeof(val) === 'number') {
            return { bool: true };
        } else {
            return { bool: false, msg: 'id is not empty!' };
        }
})
 public id: number | string;
`

validationOptions no need to fill in message.

**Comment by RAGGA-TIME** [comment]
I did some attempts. hope can help you!😃

Reference Code

`
/**
*自定义函数
*@value 获取字段的值
*/
@ValidatorConstraint({ name: 'CustomFunction' })
export class CustomFunctionConstraint implements ValidatorConstraintInterface {
validate(value: any, args: ValidationArguments): boolean {
return args.constraints[0](value).bool as boolean
}
defaultMessage(args: ValidationArguments): string {
const msg: string = args.constraints[0](args.value, args)?.msg || '';
return msg
}
}
export function CustomFunction(property: PlainObject, validationOptions?: ValidationOptions) {
return function (object: Object, propertyName: string) {
registerDecorator({
target: object.constructor,
propertyName: propertyName,
options: validationOptions,
constraints: [property],
validator: CustomFunctionConstraint,
});
};
}
/* class property **/
@CustomFunction((val: any): { bool: boolean, msg?: string } => {
if (val === '' || typeof(val) === 'number') {
return { bool: true };
} else {
return { bool: false, msg: 'id is not empty!' };
}
})
public id: number | string;
`

validationOptions no need to fill in message.

**Comment by RAGGA-TIME** [comment]
I did some attempts. hope can help you!😃

Reference Code

`@ValidatorConstraint({ name: 'CustomFunction' }) 
export class CustomFunctionConstraint implements ValidatorConstraintInterface { 
    validate(value: any, args: ValidationArguments): boolean {
        return args.constraints[0](value).bool as boolean
    }
    defaultMessage(args: ValidationArguments): string {
        const msg: string = args.constraints[0](args.value, args)?.msg || '';
        return msg;
    }
} 


export function CustomFunction(property: PlainObject, validationOptions?: ValidationOptions) {
    return function (object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            constraints: [property],
            validator: CustomFunctionConstraint
        });
    };
} 

/* class property **/ 
@CustomFunction((val: any): { bool: boolean, msg?: string } => {
    if (val === '' || typeof(val) === 'number') {
        return { bool: true };
    } else {
        return { bool: false, msg: 'id is not empty!' };
    }
})
public id: number | string;`

validationOptions no need to fill in message.

**Comment by RAGGA-TIME** [comment]
I did some attempts. hope can help you!😃

Reference Code

@ValidatorConstraint({ name: 'CustomFunction' }) 
export class CustomFunctionConstraint implements ValidatorConstraintInterface { 
    validate(value: any, args: ValidationArguments): boolean {
        return args.constraints[0](value).bool as boolean
    }
    defaultMessage(args: ValidationArguments): string {
        const msg: string = args.constraints[0](args.value, args)?.msg || '';
        return msg;
    }
} 


export function CustomFunction(property: PlainObject, validationOptions?: ValidationOptions) {
    return function (object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            constraints: [property],
            validator: CustomFunctionConstraint
        });
    };
} 

/* class property **/ 
@CustomFunction((val: any): { bool: boolean, msg?: string } => {
    if (val === '' || typeof(val) === 'number') {
        return { bool: true };
    } else {
        return { bool: false, msg: 'id is not empty!' };
    }
})
public id: number | string;

validationOptions no need to fill in message.

**Comment by RAGGA-TIME** [comment]
I did some attempts. hope can help you!😃

Reference Code

```javascript
@ValidatorConstraint({ name: 'CustomFunction' }) 
export class CustomFunctionConstraint implements ValidatorConstraintInterface { 
    validate(value: any, args: ValidationArguments): boolean {
        return args.constraints[0](value).bool as boolean
    }
    defaultMessage(args: ValidationArguments): string {
        const msg: string = args.constraints[0](args.value, args)?.msg || '';
        return msg;
    }
} 


export function CustomFunction(property: PlainObject, validationOptions?: ValidationOptions) {
    return function (object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName: propertyName,
            options: validationOptions,
            constraints: [property],
            validator: CustomFunctionConstraint
        });
    };
} 

/* class property **/ 
@CustomFunction((val: any): { bool: boolean, msg?: string } => {
    if (val === '' || typeof(val) === 'number') {
        return { bool: true };
    } else {
        return { bool: false, msg: 'id is not empty!' };
    }
})
public id: number | string;
```

validationOptions no need to fill in message.

**Comment by NoNameProvided** [comment]
If this is something you are still interested in, please open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) so the community can brainstorm, iterate, define the ideal API and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
