### ISSUE TITLE
Is it possible to provide one more configuration parameter return after first rule failed.

### ISSUE THREAD

**Issue by ivanzwb** [typestack/class-validator#111]
For my point view, most of the use case only need return first failed rule as defined rule sequence and message for each property.
It can improve performance.

Thanks.

**Comment by jerradpatch** [comment]
But most users dont want to have to keep clicking submit for each error.

**Comment by janis91** [comment]
@jerradpatch I think as Validation can also be used in other contexts than in Angular for example - where user input validation would be the main use case - his point is totally valid. I personally use the library for validating on server side in Node.js. I would be very happy to reject the request on the first error that occurs. For me it's not necessary to give feedback to an old back-end that cannot understand this error messages anyway.

**Comment by NoNameProvided** [comment]
I am closing this in favor of #148. Thanks for your report!
