### ISSUE TITLE
How would write validation for the following?

### ISSUE THREAD

**Issue by BruceHem** [typestack/class-validator#112]
```
{
    "p_code":"ABA", // ABA or ACD
    "p_options":{
        "a": "5",
        "b": "5"
    }
}
```

How can I validate that when p_code is ABA, p_options.a is required? and when p_code is ACD, p_options.b is required?

**Comment by NoNameProvided** [comment]
There is no way to do this right now.

**Comment by jfstephe** [comment]
Are you not validating the wrapping object? If the outer brackets were of type 'p_container' then whatever wanted to use that type could use a custom validator for that type? Could be wrong here, I'm new to this lib.
