### ISSUE TITLE
question: How can I validate a single property without groups?

### ISSUE THREAD

**Issue by SpeedOfSpin** [typestack/class-validator#1129]
I have a simple model

```
export class LoginModel {
    @IsNotEmpty({ message: "You must enter an email address" })
    @IsEmail({}, { message: "Email address is not in a valid format" })
    public emailAddress: string = "";

    @IsNotEmpty({ message: "You must enter a password" })
    public password: string = "";

    public rememberMe: boolean = false;
}
```

I would like to be able to only validate a **single** property and not the whole model. I have seen that a workaround is to use groups but this won't work for use case. How would I be able to only validate a single property from this model.

Thanks!

**Comment by NoNameProvided** [comment]
You either use groups or sub-classing: eg you have a minimal class and that is extended later to get the full one: 

```ts
export class PartialLoginModel {
  @IsNotEmpty({ message: "You must enter a password" })
  public password: string = "";
}

export class LoginModel extends PartialLoginModel {
    @IsNotEmpty({ message: "You must enter an email address" })
    @IsEmail({}, { message: "Email address is not in a valid format" })
    public emailAddress: string = "";

    public rememberMe: boolean = false;
}
```

Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
