### ISSUE TITLE
Update to validator.js 8.0

### ISSUE THREAD

**Issue by RichieRock** [typestack/class-validator#113]
Hi! 

There have been many nice features (including a PR of mine) and fixes in the validator.js library. Currently this uses "^7.0.0". Could you update the validator.js to a newer version?

https://github.com/chriso/validator.js/blob/8.0.0/CHANGELOG.md

**Comment by NoNameProvided** [comment]
Hi @RichieRock! 

Sorry for the late reply! This is now tracked in #154.
