### ISSUE TITLE
feat: add empty string check to `@IsOptional` decorator

### ISSUE THREAD

**Issue by JesseHelmes** [typestack/class-validator#1136]
### Description

Could it be possible to add the empty string to the `@IsOptional` decorator as well? This way the decorator would also not allow empty strings and this could be useful in combination with `@IsMail`, because if you have an empty string you get an error back that the string needs to be a mail.

### Proposed solution

Add the following extra check to `@IsOptional` decorator:

`object[propertyName] !== ''` or `object[propertyName].length !== 0`

**Comment by NoNameProvided** [comment]
This won't be added. `@IsOptional` is for checking for `undefined` or `null`. 

You can easily achieve what you want with using an extra decorator. This is true in general, you should use decorators as Lego and combine them instead of asking to extend existing ones. 

Example:

```ts
import { IsEmail, IsOptional, MinLength, validate } from 'class-validator';

class MyPayload {

  @IsOptional()
  @IsEmail()
  @MinLength(1)
  email: string;

  constructor(email?: string) {
    this.email = email;
  }
}

  // Will pass
  validate(new MyPayload()).then(console.log);
  validate(new MyPayload('valid@email.com')).then(console.log);
  // Will fail
  validate(new MyPayload('invalid')).then(console.log);
  validate(new MyPayload('')).then(console.log);
```

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.

**Comment by braaar** [comment]
@JesseHelmes – I would recommend using `class-transformer` to solve this. I use a transform that turns `''` into `null`. Perform the transformations using `plainToInstance` before running validation.

Here's my implementation:
```ts
import * as t from 'class-transformer';

/**
 * @param input a string, `null` or `undefined`
 * @returns `null` if the input is `null` or `''`, otherwise returns the input
 */
export function makeEntityString(
  input: string | null | undefined,
): string | null | undefined {
  if (input === '' || input === null) {
    return null;
  } else if (input === undefined) {
    return undefined;
  } else {
    return input;
  }
}

export function transformString(
  params: t.TransformFnParams,
): string | null | undefined {
  return makeEntityString(params.value);
}
```

Usage:

```Ts
class MyClass {
  @Transform(transformString)
  @IsOptional()
  hello?: string | null;
}
