### ISSUE TITLE
Is it possible to validate one field without groups?

### ISSUE THREAD

**Issue by Horat1us** [typestack/class-validator#114]
For example I have class:
```typescript
class ExampleModel extends Model {
    @MinLength(10)
    @IsAlphanumeric()
    public password: string;

    @IsEmail()
    @IsDefined()
    public email: string;
}
```
Can I validate only email or password, without validating other fields?

**Comment by mickliddy** [comment]
I'd also like to be able to do this; to reuse the validation for each field in a web form.

**Comment by NoNameProvided** [comment]
It should work just the way you wrote it @Horat1us. class-validator checks only know properties of an object and will leave the others untouched.

**Comment by Horat1us** [comment]
@NoNameProvided I want to validate only one attribute, when other filled.
For example I have object:
```js
let model: Model = {
    a: 'someValidValue',
    b: 'invalidValue',
} 
```
In this case I want to validate only `a` property, without validating `b`, because it may be slow and use HTTP request for validation.

**Comment by ericzon** [comment]
Hi @Horat1us ,

Can you explain a little bit more your use case? Why is not suitable group validation for this case?

````
class MyDto {
    @Length(10, {
        groups: [ 'my-custom-case-1', 'my-custom-case-2' ]
    })
    a: string,

    @Length(20, {
        groups: [ 'my-custom-case-1' ]
    })
    b: string
} 
````

In your case, you only need to validate group 'my-custom-case-2'  against incoming dto.

I hope it helps

**Comment by NoNameProvided** [comment]
Can you please elaborate on your use-case a little more? If you dont want to validate it, just do not decorate it:

```ts
class ExampleModel extends Model {
    @MinLength(10)
    @IsAlphanumeric()
    public password: string;

    public email: string;
}
```

In this example, `email` will pop-up in intellisense but won't be validated.

**Comment by Horat1us** [comment]
@ericzon Now I use groups for this case. But if I have 20 attributes it really redundant to create unique group for each attribute.

@NoNameProvided I want to validate email, but another time. Groups is redundant in case `1 group = 1 attribute`

**Comment by ajitgauli** [comment]
@NoNameProvided I have a similar problem. From my UI, I need to call validate on blur and in this case I'd only want to validate the field I just blurred from. And blur from next field I'd want to validate that field only and so on. If only we could pass in property name or better yet the path to property (to handle nested objects) as ValidatorOptions, it would be possible to avoid unnecessary extra validations. As @Horat1us suggested, currently a way around to achieve this is to use groups but having 1 group per field just so that we can target it only is a lot of code bloat.

**Comment by Horat1us** [comment]
@ajitgauli do you have suggestions how we can implement it?

**Comment by SpeedOfSpin** [comment]
I would really like this feature as well. Rather than passing in the instance of my class, I just want to be able to validate a SINGLE property on that class when I do an onBlur for instance as @ajitgauli as stated above. thanks.

**Comment by JosipReh** [comment]
Any update on this?

**Comment by LucienLee** [comment]
A workaround way is that you only pass one field and validate with `skipMissingProperties` option.

```ts
const exampleModel = new ExampleModel();
exampleModel.password = '123abc'

const errors = await validate(exampleModel, { skipMissingProperties: true })
```

**Comment by SpeedOfSpin** [comment]
> A workaround way is that you only pass one field and validate with `skipMissingProperties` option.
> 
> ```ts
> const exampleModel = new ExampleModel();
> exampleModel.password = '123abc'
> 
> const errors = await validate(exampleModel, { skipMissingProperties: true })
> ```

I can't get this working. If I create a new class all the properties still exist. I think it's really important to be able to only validate single fields.

**Comment by e-g1gor** [comment]
> @ajitgauli do you have suggestions how we can implement it?

I would propose something like this - https://github.com/typestack/class-validator/pull/1480

**Comment by blandygbc** [comment]
I've managed to do this way:
```typescript
let { useremail } = req.body;
let userRepositoy = getRepository(User);

let errMap = await validate(userRepositoy.create({ useremail }), { skipMissingProperties: true })
                     .then( errors => {
                             return errors.map(v => v.constraints)
                           });

if (undefined !== errMap && errMap.length > 0) {
    return res
          .status(403)
          .send({              
               //data: errMap.map(v => v!.isEmail).toString()  <- Alternative way to access
               message: errMap[0]!['isEmail'].toString()
          })
}
```
Work like a charm!

**Comment by juni0r** [comment]
I agree it would be immensely useful to be able to validate individual properties for forms. Instead of passing a list of fields to `validate`, I'd suggest and API to obtain a validator function, since this would integrate nicely with a lot of existing UI  frameworks.

Quasar, for instance, allows for a simpe validator function on form fields which gets passed in the field value and returns and error message.

I'm thinking of something along the lines of:
```js
import { propValidatorSync } from 'class-validator'

const emailValidator = propValidatorSync(User, 'email')

const emailRule = (val) =>
  emailValidator(val).map(({ constraints }) =>
    Object.values(constraints).join(', '))
```
which can then be used in the UI

```vue
<q-input
  v-model="model"
  label="Email"
  :rules="[emailRule]"
/>
```

@blandygbc Your workaround isn't quite feasible in my case, since the model props have default values which will be set on creation, so obtaining an 'empty' model requires even more trickery.

**Comment by blandygbc** [comment]
> @blandygbc Your workaround isn't quite feasible in my case, since the model props have default values which will be set on creation, so obtaining an 'empty' model requires even more trickery.

You're right, my model does not have any default values and will not work otherwise. =(

**Comment by braaar** [comment]
In which frameworks and paradigms does it make sense to construct classes from form input data for validating on blur? I would assume that in most cases a schema based validation framework would be more suited for form validation than `class-validator`. 

I might be showing my ignoreance here, but I've never come across a paradigm where it's desirable to work with form data as classes. What does such a class do?

In react I often use [react-hook-form](https://react-hook-form.com/) which plays ball with [zod](https://github.com/colinhacks/zod) very well.

**Comment by NoNameProvided** [comment]
You can also use sub-classing to validate:

```ts
class PartialEntity {
  @SomeDecorator()
  someProperty: string;
}

class FullEntity extends PartialEntity {
  @SomeDecorator()
  otherProperty: string;
}
```

The best would be for this if one can define a class constructor to validate a plain object. This is on my TODO list. 

```ts
// This code currently DOES NOT WORK.
validate({ password: payload.password }, SomeClassDefinition)
```

I am closing this as answered for now. I think we discussed all possible approaches to solving this with the currently available options.
