### ISSUE TITLE
question: isAlpha enhancement from validatorjs

### ISSUE THREAD

**Issue by TBG-FR** [typestack/class-validator#1144]
I was trying to use `isAlphanumeric` validator, wondering if there was an option to allow one extra character while doing so (a space or `-` for example). Looks like it has been implemented in validatorjs [PR1286 - isAlpha enhancement ](https://github.com/validatorjs/validator.js/pull/1286) but I don't find it in class-validator...

**The problem:**
Usage in validatorjs : `.isAlpha('en-US', {ignore: ' '})`
Usage in class-validator : `.isAlpha('en-US', { ??? })`
![image](https://user-images.githubusercontent.com/18146038/122941255-8327f380-d375-11eb-8353-49db5f2d8de2.png)

Is it something not yet implemented, or is it normal ?

**Comment by NoNameProvided** [comment]
It's something not yet implemented. Now it is tracked in https://github.com/typestack/class-validator/issues/1842. 

Closing this as answered.
