### ISSUE TITLE
fix: Unable to resolve signature of property decorator when called as an expression.

### ISSUE THREAD

**Issue by zhengAnBin** [typestack/class-validator#1146]
### Description
Use Class-Validator in DTOs

**Minimal code-snippet showcasing the problem**
```ts
@isNotEmpty({ message: '' })  // ts error
@ApiProperty({ description: '手机号', example: '13222222222', required: true })
phone: number;
```

### Actual behavior
ts:
Unable to resolve signature of property decorator when called as an expression.
  This expression is not callable.
    Type 'Boolean' has no call signatures.

**Comment by alef-carvalho** [comment]
same problem with me!

**Comment by vineryap** [comment]
Had the same issue and found out after a few hours that it is a typo.
`isNotEmpty` should be `IsNotEmpty` (capital `I`)

Mentioned [here](https://github.com/typestack/class-validator/issues/684#issuecomment-670968215)

**Comment by zhengAnBin** [comment]
thank you

**Comment by NoNameProvided** [comment]
As mentioned by others, the decorators start with a capital letter: `@IsNotEmpty`. The `isNotEmpty` is the validator function that is used by the decorator. 

Closing this as there is no action to take.
