### ISSUE TITLE
Each item validation message

### ISSUE THREAD

**Issue by allangirao** [typestack/class-validator#1150]
I was trying to validate an array of string with
```
class Validator {
  @Length(5,30, {each: true}
  public names: string[];
}
```
It works, but the message I receive is a single one for the entire array.
Is there a way that I can receive an array of errors with an error (if exists) for each item on array?

If I try to validate:
```
{
  names: [ 'Joseph', 'John', 'Mary', 'Naomi']
}
```
I want an error with kinda like the structure below:
```
{
  names: [ 
    [],
    ['value must be longer than or equal to 5 characters'].
    ['value must be longer than or equal to 5 characters'].
    []
  ]
}
```

Not:
```
{ names: ['each value in names must be longer than or equal to 5 characters'] }
```

**Comment by kryptamine** [comment]
I am also stuck with this issue, is there any updates?

**Comment by NoNameProvided** [comment]
I think this is something we should consider.

If the issue still persists and affects you, you may open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) (if one is not opened in the meantime) where the community can brainstorm, iterate and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.
