### ISSUE TITLE
Npm publish new version

### ISSUE THREAD

**Issue by patrickhousley** [typestack/class-validator#116]
Can you please publish a new NPM version for the below issue.
#101 #102 #107

**Comment by 19majkel94** [comment]
ping @pleerock - he is very busy in TypeORM right now 😉

**Comment by 11000100111000** [comment]
@pleerock please :)

**Comment by Dirrk** [comment]
@pleerock can you please publish a new version

**Comment by vilius-rugaitis** [comment]
Please publish a new version on npm, the IsOptional behaviour should be really updated :-)

**Comment by pleerock** [comment]
I made a new publish, sorry for the delay.
