### ISSUE TITLE
Is it possible to use @MaxDate decorator alongside with @IsDateString

### ISSUE THREAD

**Issue by KasparRosin** [typestack/class-validator#1161]
I attempted to create a validator that validates frontend request

```typescript
@IsDateString()
@MaxDate(new Date())
dateInput: Date | undefined
```

However, i this throws an error `maximal allowed date for dateInput is ...`.
I also tried `@MaxDate(new Date().toIsoString())`.

**Comment by KasparRosin** [comment]
Was able to work around this issue with `class-transformer`

```
  @Type(() => Date)
  @IsDate()
  @MaxDate(new Date())
```

But I'm still wondering if there is a way to do this without using `class-transformer`

**Comment by NoNameProvided** [comment]
You either transform it with `class-transformer` or you can write a custom `@MaxDateString` validator that accepts a data string, parses it to `Date` instance, and compare after. 

Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
