### ISSUE TITLE
question: can we check query string with class-validator

### ISSUE THREAD

**Issue by saifoelloh** [typestack/class-validator#1168]
I attempted to create a validator that validates frontend request
![image](https://user-images.githubusercontent.com/34400441/124535250-02bac580-de40-11eb-8882-718dc993a803.png)

Can I create a validator for that queries, especially the nested object?

**Comment by NoNameProvided** [comment]
You can validate it yes. You need to create a class representing the supported query parameters for each route, then you can validate the received query parameter objects with that class. (After converting the received plain object to the class instance with eg: `class-transformer`.)

If you use `routing-controllers` or NestJS then this is supported out of the box.
