### ISSUE TITLE
Complex Equality check `something` OR `something else`

### ISSUE THREAD

**Issue by me-dira** [typestack/class-validator#1200]
**I was trying to...**
Make a field to **equal** `something` **OR** `Something else`.
**The problem:**
Can not do that because `@equals` **Decorator** just checks one possible equality.
That is very important and i cant ignore it. I read the documentation but there was no useful information or method to use for this kind of validation. tanks for your help.

 

Check one example here :
```
    @IsNotEmpty()
    @Equals('user' || 'organization')
    type: "user" | "organization";
```

**Comment by jbjhjm** [comment]
You can use `@IsIn(['user','organization'])`

**Comment by mehdi-ra** [comment]
Thank you for that information it solves the problem
