### ISSUE TITLE
Several vulnerabilities are introduced in your package class-validator

### ISSUE THREAD

**Issue by paimon0715** [typestack/class-validator#1206]
Hi,  @NoNameProvided @vlapo, I'd like to report four vulnerabilities introduced by package **validator**:
### Issue Description

   As far as I know, there are four vulnerabilities detected in **_validator_** (versions:<13.6.0). Unfortunately, **_class-validator@0.12.2_** directly depends on **validator@13.0.0**. The vulnerabilities are as follows:
 1.Vulnerability **SNYK-JS-VALIDATOR-1090599** :[https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599)
 2.Vulnerability **SNYK-JS-VALIDATOR-1090600** :[https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600)
 3.Vulnerability **SNYK-JS-VALIDATOR-1090601** :[https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601)
 4.Vulnerability **SNYK-JS-VALIDATOR-1090602** :[https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602)

  As your can see, the above vulnerable package is referenced by **_class-validator@0.12.2_** via:
 `class-validator@0.12.2 ➔ validator@13.0.0`

As you konw, **_class-validator@0.12.2_** is so popular that a large number of downstream projects depend on it ([266,377 downloads per week](https://www.npmjs.com/package/class-validator/v/0.12.2?activeTab=versions) and about **2,412** downstream projects e.g., [@acies/core 1.2.356](https://www.npmjs.com/package/@acies/core) (latest version), @things-factory/board-ui 3.4.5 (latest version)), the vulnerabilities can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 1. `@things-factory/apptool-base@3.4.5 ➔ @things-factory/shell@3.4.5 ➔ class-validator@0.12.2 ➔ validator@13.0.0`
 2. `@things-factory/apptool-ui@3.4.5 ➔ @things-factory/apptool-base@3.4.5 ➔ @things-factory/shell@3.4.5 ➔ class-validator@0.12.2 ➔ validator@13.0.0`
 3. `@things-factory/attachment-base@3.4.5 ➔ @things-factory/auth-base@3.4.5 ➔ @things-factory/email-base@3.4.5 ➔ @things-factory/shell@3.4.5 ➔ class-validator@0.12.2 ➔ validator@13.0.0`
**......**

If  you can remove the vulnerable package from **_class-validator@0.12.\*_**, then its fixed version can help downstream users avoid the above vulnerabilities.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from class-validator@0.12.\* ?**

### Fixing suggestions

In **_class-validator@0.12.*_**, you just need to perform the following upgrade:
`validator 13.0.0 ➔ 13.6.0`; 

**Note:**
_validator@13.6.0(>=13.6.0) has fixed the vulnerabilities ([SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600), [SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) and [SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602))_

Thanks again for your work!

Best regards,
Paimon

**Comment by braaar** [comment]
validator was bumped to 13.7.0 in #1409

**Comment by NoNameProvided** [comment]
These vulnerabilities are fixed in `validator@13.7.0` or higher. We use the updated version since the https://github.com/typestack/class-validator/commit/c6984bb16fd28658f19b987927375018eebd02c0 commit that has been released in `class-validator@0.13.2` (in https://github.com/typestack/class-validator/pull/1409).
