### ISSUE TITLE
Transform and validate issue

### ISSUE THREAD

**Issue by florentsuc** [typestack/class-validator#121]
Hi @pleerock,

I'm using two of your projects: `class-validator` and class-transformer, and I'm trying to transform an input object, and then validate it. _I'm using Nest.js, but IMO this issue is not related._

Let's say we have a Test class: 

```ts
export class Test {
  @IsDate()
  @Type(() => Date)
  date: Date;
}
```

And here is our validation pipe:

```ts
@Pipe()
export class ValidationPipe implements PipeTransform<any> {
  async transform(value, metadata) {
    const object = plainToClass(metatype, value);
    const errors = await validate(object);
    if (errors.length > 0) {
      throw new HttpException('Validation failed', HttpStatus.BAD_REQUEST);
    }
    return object;
  }
}
```
I'm trying to validate the following object, so it should return an error because of the **invalid date**.

```json
{
  "date": "blabla"
}
```

The `plainToClass` method returns `date: "Invalid Date"` but the `validate` method returns **no error**.

Is this an issue, or am I using it in a bad way?

Thanks,

Florent

**Comment by NoNameProvided** [comment]
Hi @florentsuc! 

This is was happening because the `@IsDate` decorator checked only if the date an instance of the `Date` object, aka 
```ts
new Date('blabla') instanceof Date == true
```

This has been changed already and now it will fail on `Date` objects with `Invalid Date`.

This will be included in the next release.
