### ISSUE TITLE
question: What is the best way to implement i18n in error messages?

### ISSUE THREAD

**Issue by Mateozmaldonado17** [typestack/class-validator#1211]
I was trying to implement internationalization in custom error messages, somebody know a best practice to implement it?

**Comment by kokoraka** [comment]
Waiting this feature too, @NoNameProvided 

Perhaps we can help something about this.

**Comment by Mateozmaldonado17** [comment]
my solution was, create an Interceptor in NestJS, detect the message of the catch and that catch look for it inside the interceptor in the i18n JSON.

**Comment by NoNameProvided** [comment]
I18N is currently not supported by the library. 

If you have ideas about how it should work you can start a conversation in the [Feature Ideas section](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) on the discussions tab.
