### ISSUE TITLE
question: How to validate the Array of Class

### ISSUE THREAD

**Issue by vyredo** [typestack/class-validator#1212]
In the [docs example](https://github.com/typestack/class-validator#validating-arrays), We have class Post and Post has property tags, which is an array

```ts
import { MinLength, MaxLength } from 'class-validator';

export class Post {
  @MaxLength(20, { each: true })
  tags: string[];
}

```
This will validate each item in `post.tags`

To convert it to an object it will be 
```ts
Post {
  tags: ['string1', 'string2', ,'string3']
}
```

**The problem:**
I wish to validate Response from server, and the response's type is `Array<Post>` <br />
which is 
```
[
  Post {
     tags: ['string1', 'string2', ,'string3']
  },
  Post {
     tags: ['string1', 'string2', ,'string3']
  },
  Post {
     tags: ['string1', 'string2', ,'string3']
  }
]
```

How do I create a class with this kind of type? or How to validate Array<object>?

**Comment by johny1614** [comment]
I have made my own method for such thing. If somebody wants to - merge it.
`import { ClassConstructor, plainToClass } from 'class-transformer';
import { validate, ValidationError } from 'class-validator';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { handleErrors } from 'util/responseValidation/handleErrors';
import { DTO } from 'util/ui/modules/util/httpclient/DTO';

export function validateArrayResponse<T extends DTO>(anemiaConstructor: ClassConstructor<T>): (source$: Observable<Array<T>>) => Observable<Array<T>> {
	return source$ => source$.pipe(
		map((arrResponse: Array<unknown>) => {
			if (!Array.isArray(arrResponse)) {
				const msg = `ResponseValidator has found error. The value is supposed to be an Array of ${anemiaConstructor.name} 
				but is instead: ${arrResponse}`;
				// eslint-disable-next-line no-console
				console.warn(msg, arrResponse);
				return arrResponse;
			}
			return arrResponse.map((response: T) => {
				const classObject: T = plainToClass(anemiaConstructor, response);
				validate(classObject).then((errors: Array<ValidationError>) => handleErrors(errors, classObject.getClassName()));
				return classObject;
			});
		})
	);
}
`

**Comment by NoNameProvided** [comment]
Currently, the `validate` function expects a class instance, so this is not possible natively. However luckily the solution is simple, where you call your validation logic you can check if the received value is an array or not. Something similar to this:

```ts
const dataToValidate = xy // this comes from somewhere

if(Array.isArray(dataToValidate)) {
 validationResult = await Promise.allSettled(dataToValidate.map(data => validate(data, validationOptions))
} else {
 validationResult = [await validate(data, validationOptions)]
}
```
