### ISSUE TITLE
validate: accept  empty string or isdate 

### ISSUE THREAD

**Issue by huytientai** [typestack/class-validator#1226]
**I was trying to validate the string field : it accept empty string or isDate**
  I have a search form with date input. if user choose a date and search , it have to validate isDate . But if user not choose a date(input="" =>empty string) and it still accept for it 

@IsOptional()
  @Type(() => Date)
  @IsDate()
  from_time: string;

i already tried it but it not accept for empty string.
Help me pls

**Comment by NoNameProvided** [comment]
Sorry, I cannot understand your problem. 

Closing this as not reproducible. 

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
