### ISSUE TITLE
fix: Mocha with `check-leaks` enabled throws an error: global leak(s) detected: 'classValidatorMetadataStorage'

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [typestack/class-validator#1236]
### Description

When running tests with mocha and enabled `check-leaks` option,  they fail with `global leak(s) detected: 'classValidatorMetadataStorage'`

Could you please explain why mocha detects this as memory leak ? 

Possible fixes (workarounds):
- Set `check-leaks: false`
- Add `globals: ['classValidatorMetadataStorage']` in order to omit this error.

### Expected behavior
Tests with mocha should run without any errors.

### Actual behavior
Error: global leak(s) detected: 'classValidatorMetadataStorage'

**Comment by NoNameProvided** [comment]
This is by design. This package uses a global variable to share metadata between different instances.

Edit: just to clarify that leak warning means we introduce a global variable, not that the library itself has a memory leak.
