### ISSUE TITLE
fix: IsFQDN work with IsOptional not correctly

### ISSUE THREAD

**Issue by Garfield550** [typestack/class-validator#1252]
### Description

When a property has `IsFQDN` and `IsOptional`, `validateOrReject(obj, { skipMissingProperties: true })` throw error.

**Minimal code-snippet showcasing the problem**
 

```ts
class Entity {
  @IsFQDN()
  @IsOptional()
  domain?: string = '';
}
```

### Expected behavior

`await validateOrReject(obj, { skipMissingProperties: true });` pass

### Actual behavior

Got an error: domain must be a valid domain name

**Comment by jbjhjm** [comment]
The `domain`prop is initialized in constructor.
Assuming you pass a `new Entity()` to validateOrReject, its data will be `{domain:''}`.
IsOptional only skips validation on `undefined` or `null`.
