### ISSUE TITLE
Routing-Controllers + class-validator bug?

### ISSUE THREAD

**Issue by 11000100111000** [typestack/class-validator#128]
When using the automatic validation from routing-controllers for some reason the email "patch@patch" is valid when we are using these validators and the "patch" validator group
```js
@IsEmail({
        allow_display_name: false,
        allow_utf8_local_part: true,
        require_tld: true
    }, {
        groups: ["post", "patch", "login"]
    })
    @IsOptional({
        groups: ["patch"]
    })
    public email;
```
Doing it the manual way like so works however
```js
let user = new UserValidation();
user.email = "patch@patch";
validate(user, {groups: ["patch"]}).then(console.log);
```

**Comment by MahBoy** [comment]
Experiencing the same kind issue @pleerock

**Comment by NoNameProvided** [comment]
Hi! 

I have opened an issue with this in routing-controllers and closing this issue here.
