### ISSUE TITLE
fix: add predicate for isBoolean

### ISSUE THREAD

**Issue by heyqbnk** [typestack/class-validator#1300]
### Description
Hey, I have found one little bug in types. `isBoolean` should have a predicate which states, that `value is boolean`.

**Minimal code-snippet showcasing the problem**
Here is a simple example. TypeScript will keep thinking, `val` is `123`, but `isBoolean` should make him think, its boolean.

```ts
function getRandomType(): string | number | boolean {
  return 'No random in our life';
}

const val = getRandomType(); // val here is string, or number, or boolean

if (isBoolean(val)) {
  const someAnotherVal = val; // someAnotherVal will have type string, or number, or boolean, but it should be clear boolean
}
```

### Expected behavior
TypeScript knows that value has type `boolean`.

### Actual behavior
`isBoolean` returns boolean value without predicate, so, it does not say anything for TypeScript.

**Comment by NoNameProvided** [comment]
I think this is already in `0.14.0`.
