### ISSUE TITLE
feature: add decorator that will check if each array value are from given set

### ISSUE THREAD

**Issue by SET001** [typestack/class-validator#1323]
### Description

There is already `ArrayContains` decorator that checks if the array contains all values from the given array of values. Making some items required params. But there are cases when we need to ensure that elements in the array have values within a given set.

### Proposed solution
This [PR](https://github.com/typestack/class-validator/pull/1324) contains proposed implementation for such a decorator

**Comment by NoNameProvided** [comment]
We already have a solution for this in the form of `IsIn` decorator.

```ts
import { IsIn, validate } from 'class-validator';

class MyPayload {
  @IsIn(['A', 'B'], { each: true })
  letters: string[];

  constructor(letters?: string[]) {
    this.letters = letters;
  }
}

// Will pass
validate(new MyPayload(['A'])).then(console.log);
validate(new MyPayload(['A', 'B'])).then(console.log);
// Will fail
validate(new MyPayload(['C'])).then(console.log);
validate(new MyPayload(['A', 'C'])).then(console.log);
```

In general, you should try to use the provided decorators as Lego to build what you need. If some functionality can be achieved in reasonable effort then we won't add a dedicated decorators for it as it just bloats the list of decorators.  

Closing this as wontfix.
