### ISSUE TITLE
question: Is everything alright with class-validator vulnerabilities checks?

### ISSUE THREAD

**Issue by talesmgodois** [typestack/class-validator#1342]
Hi everyone, Today a critical vulnerability has shown on our CI/CD

![image](https://user-images.githubusercontent.com/3044796/137026884-451b308c-2ced-41f4-9290-08e4e819ed9b.png)

SO I entered the link provided, https://github.com/advisories/GHSA-fj58-h2fr-3pp2, to me and saw the following:
![image](https://user-images.githubusercontent.com/3044796/137027076-20bfa370-2d57-4b34-901a-8f0e8e0980e6.png)

My question is, should I get this error when I am using version 0.13.1? Shouldn't be only for version <= 0.10.2??

Idk how these vulnerabilities are marked, but, is there any possibility that this was marked wrong to use <=10.2 instead of <=0.10.2 as it should?

**Comment by dantehemerson** [comment]
Same here, I'm using class-validator@0.13.1 and I'm getting the next **critical serverity** vulnerability on Github
![137038567-3cc68a67-1679-4254-963f-549efbe01985](https://user-images.githubusercontent.com/18385321/137038847-8df68268-a250-4c64-b9ff-3afb8e44a889.jpg)

**Comment by tofikabdullayev** [comment]
Same

**Comment by szygendab** [comment]
Same error here even if using v 0.13.1

**Comment by iordanivanov** [comment]
Same here

**Comment by nternouski** [comment]
Same here with the last version (0.13.1)

**Comment by nandastone** [comment]
The [advisory](https://github.com/advisories/GHSA-fj58-h2fr-3pp2) contains a typo:

![CleanShot 2021-10-15 at 11 43 02](https://user-images.githubusercontent.com/199204/137418968-2bc6fad9-beac-48ea-9bd2-325c6929e474.png)

If using https://www.npmjs.com/package/audit-ci, you can upgrade the package then whitelist it via the `allowlist` option.

**Comment by joebowbeer** [comment]
https://github.com/naugtur/npm-audit-resolver

**Comment by joebowbeerxealth** [comment]
The quote is an excerpt from private correspondence with Rob Schultheis.
