### ISSUE TITLE
question: Using forbidUnknownValues with ManyToMany relationships (circular structure) 

### ISSUE THREAD

**Issue by sudohalt** [typestack/class-validator#1347]
**I was trying to...**
Set `forbidUnknownValues: true` for validation (since it is recommended).

So I added the following snippet of code:

```
  @BeforeInsert()
  @BeforeUpdate()
  async validate(): Promise<void> {
    try {
      await validateOrReject(this, { forbidUnknownValues: true });
    } catch (errors) {
      const errorMsg = `Validation failed: ${errors}: ${JSON.stringify(
        this,
        null,
        3,
      )}`;
      throw new Error(errorMsg);
    }
  }
```

**The problem:**
I have `ManyToMany` relationships in my code and I get the following error when `forbidUnknownValues` is set to `true`:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Project'
    |     property 'users' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'User'
    |     property 'projects' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
```

The two entities in question both have ManyToMany relationships to each other since a project can be used by many users and a user can have many projects.

Project has the following field:
```
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => User)
  @ManyToMany(() => User, (user) => user.projects)
  @JoinTable({
    name: "projects_users",
    joinColumn: {
      name: "project_id",
    },
    inverseJoinColumn: {
      name: "user_id",
    },
  })
  public users!: User[];
```

and User has the following field:
```
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => Project)
  @ManyToMany(() => Project, (project) => project.users)
  @JoinTable({
    name: "projects_users",
    joinColumn: {
      name: "user_id",
    },
    inverseJoinColumn: {
      name: "project_id",
    },
  })
  public projects!: Project[];
```

**Comment by NoNameProvided** [comment]
I don't provide support for solving programming problems. If you think this is a bug in `class-validator` then please provide a minimal reproducible example showcasing the problem. The example should:

- be as short as possible while clearly showcasing the problem
- has no external dependencies, only this lib
- the expected and actual behavior should be explained

Closing this as invalid.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
