### ISSUE TITLE
[Improvement] Populate TypeORM entity with class validator properties

### ISSUE THREAD

**Issue by BogdanUngureanu** [typestack/class-validator#135]
Hi, what do you think about having the following improvements for the validation class?
- Populate the validation class from the request's parameter list (e.g. express request params, koa params, etc).
- After the validation passes, a TypeORM entity could be automatically populated with the fields from the validation class.

We could have something like this as an API:

`public player(ctx: Context) {
        let form = CreatePlayerForm.fromRequest(ctx.params);
        validate(form);
        form.populateEntity(Player);
    }`

This functionality could be obtained by creating a base form class that will have two methods:
- fromRequest
- populateEntity

In my opinion, we would remove a lot of unnecessary code needed to populate the validation class and then again the entity properties. 

I've already implemented something like this and can create a PR with the changes, but I don't know if this functionality is needed and if it respects your code quality (since I'm still learning TypeScript).

Looking for your feedback, guys.

**Comment by pleerock** [comment]
you should take a look on [routing-controllers](https://github.com/pleerock/routing-controllers) library which kinda already provides such functionality.

**Comment by pleerock** [comment]
routing-controllers provides good integration with class-validator. You can get your parameters / body content and validate very easily. If you want to have even better integration with typeorm take a look on [this extension](https://github.com/typeorm/typeorm-routing-controllers-extensions).

**Comment by BogdanUngureanu** [comment]
I didn't knew about the integration with the routing-controllers, thanks!

As for the typeorm integration, I don't think it's a good idea to populate the entity directly from the request since a malicious user could update a column that is used for internal usage.

For example, let's assume we have a "users" entity that has a "role" column. With that approach, a malicious user could grant to his account a different role by simply sending a request with the "role" field.

In my opinion, a intermediary form class should be used for populate the entity based on the properties defined.  

As an example, we could have a "CreateUserForm" validation class that will have an email, name and password fields (without the role). When the user performs a request, the validation class will populated and, if it's valid, the entity will be generated with the email, name and password properties (defined within the CreateUserForm class). 

What's your opinion on this?

**Comment by NoNameProvided** [comment]
With class-validator and class-transformer you can strip not needed properties or throw an error. I am closing this as your requested features is exactly what routing-controller does. I encourage you to take a look!
