### ISSUE TITLE
question: still being maintained?

### ISSUE THREAD

**Issue by ctfrancia** [typestack/class-validator#1350]
There is a critical issue with this package and I want to help out, but seeing the pull requests and last publish this looks to be no longer maintained. I'd certainly be willing to help with this, just want to make sure that I'm not the only one.

**Comment by ctfrancia** [comment]
I'm using nestjs as well that's why I am slightly worried about this if nest is recommending a package no longer maintained then maybe there needs to be a pivot with either nestjs to use a maintained package or maybe look into helping this package to update it. But if Nestjs _does_ help this package then it doesn't matter if the pull requests just accumulate like they already appear to be doing.

**Comment by NoNameProvided** [comment]
Yes. See https://github.com/typestack/class-validator/issues/1775 for details.
