### ISSUE TITLE
question: I have Arabic and English versions of custom error messages that I wanna use, and I wanna map all messages together

### ISSUE THREAD

**Issue by abdullaNasser** [typestack/class-validator#1362]
**I was trying to...**
I have Arabic and English versions of custom error messages that I wanna use with validation decorators, and I wanna map all messages together, so I can use them over and over across my app.

**The problem:**
I don't know if there's good practice to handle multi language messages and I don't know if there is a way to map all messages together and mention them to every decorator.
If there 's any recommended solution, it will be great.

**Comment by NoNameProvided** [comment]
I18N is currently not supported by the library. 

If you have ideas about how it should work you can start a conversation in the [Feature Ideas section](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) on the discussions tab.
