### ISSUE TITLE
feature: add message option to IsEmail

### ISSUE THREAD

**Issue by EmreSURK** [typestack/class-validator#1372]
### Description
I am using that package in a non-English language but can not give a message object as an IsEmail Option.

**Comment by Ricardo-Costa** [comment]
I faced the same trouble

**Comment by RonHouben** [comment]
The message is available like this:
`@IsEmail({}, { message: 'Message in my other language' })`

**Comment by braaar** [comment]
@EmreSURK, were you able to figure this out? If so, please close the issue :)
