### ISSUE TITLE
fix: @IsJSON is not working properly.

### ISSUE THREAD

**Issue by omer-to** [typestack/class-validator#1374]
### Description

`@IsJSON` is not working properly.

**Minimal code-snippet showcasing the problem**
 

```ts
import { IsJSON } from 'class-validator';

export class Post {
      @IsJSON()
      body: string
}

const post = new Post()
post.body = JSON.stringify('Hi')

async function run() {
      const validations = await validate(post)
      console.log(validations)
}

run()
```

### Expected behavior

It is a JSON string, so I expect `validations` to be an empty array.
### Actual behavior

It gives a validation error.

---
Here is the output of the terminal
```ts
[
  ValidationError {
    target: Post { body: '"Hi"' },
    value: '"Hi"',
    property: 'body',
    children: [],
    constraints: { isJson: 'body must be a json string' }
  }
]
```

**Comment by ImranSasudin** [comment]
@omer-to I think IsJson only validate if the string is a string that is converted from JSON object. So you need to pass key value.

**Comment by NoNameProvided** [comment]
This is working as expected with a real JSON object.

```ts
import { IsJSON, validate } from 'class-validator';

class MyPayload {
  @IsJSON()
  value?: string;

  constructor(value?: string) {
    this.value = value;
  }
}

// Will pass as expected
validate(new MyPayload('{ "prop": 1 }')).then(console.log);
validate(new MyPayload('{}')).then(console.log);

// This will fail
validate(new MyPayload('"Hi"')).then(console.log);
```

Your example fails because our upstream validator library runs the following code snippet after parsing the content to JSON:
```ts
(!!obj && typeof obj === 'object');
```

Because `"Hi"` is not an object but a primitive value it fails this validation.
