### ISSUE TITLE
fix: validateNested is not working

### ISSUE THREAD

**Issue by omer-to** [typestack/class-validator#1375]
### Description

`@ValidateNested` is not working properly. It doesn't validate at all.

**Minimal code-snippet showcasing the problem**
 

```ts
import 'reflect-metadata'
import { Type } from 'class-transformer';
import { validate, IsNumberString, ValidateNested } from 'class-validator';

class BodyMeasurement {
      @IsNumberString()
      weight: string

      @IsNumberString()
      height: string
}

class Event {
      @Type(() => BodyMeasurement)
      @ValidateNested()
      body: BodyMeasurement
}

const ev = new Event()

async function run() {
      const validations = await validate(ev)
      console.log(validations) // logs an empty array meaning that it is valid
}

run()
```

### Expected behavior

I expect to see that there are validation errors for height and weight.

### Actual behavior

The validation passes.

**Comment by harveyappleton** [comment]
@omer-to I think I experienced the same thing, but also added `@IsNotEmpty` alongside `@ValidateNested()` which worked for me. Otherwise, I think the nested body (in your Event example) is optional.

**Comment by omer-to** [comment]
@harveyappleton Yes, you are right. But the validation message is not what I expect.
When I put `@IsNotEmpty` decorator as well, I get the following validation:
```ts
[
  ValidationError {
    target: Body {},
    value: undefined,
    property: 'body',
    children: [],
    constraints: { isNotEmpty: 'body should not be empty' }
  }
]
```

In fact, I want to get `weight should be string`, `height should be string`

**Comment by md-shah** [comment]
@omer-to Seems like the ValidateNested is not working for me also. Can someone help?

```
@Allow()
@ArrayMinSize(1)
@ValidateNested({ each: true })
@ArrayUnique((o: ProductDto) => o.productCode)
@Type(() => ProductDto)
@ApiProperty({ type: [ProductDto] })
product: ProductDto[];
  ```

**Comment by vixson** [comment]
This issue has been going on for a while now and nobody can give a clear and solid confirmation for the fix.

Please @NoNameProvided here is a Stackblitz of the implementation
https://stackblitz.com/edit/class-validator-validate-nested-not-validating?file=index.ts
This validates only a flat instance but does nothing on nested instances

Please anyone from Typestack
Kindly fork an Official Implementation to show the resolution of this issue thank you.

**Comment by braaar** [comment]
> This issue has been going on for a while now and nobody can give a clear and solid confirmation for the fix.
> 
> Please @NoNameProvided here is a Stackblitz of the implementation https://stackblitz.com/edit/class-validator-validate-nested-not-validating?file=index.ts This validates only a flat instance but does nothing on nested instances
> 
> Please anyone from Typestack Kindly fork an Official Implementation to show the resolution of this issue thank you.

`ValidateNested` requires that the nested objects you validate are class instances.

[Here is my fork of your stackblitz](https://stackblitz.com/edit/class-validator-validate-nested-not-validating-xp1oq9?file=index.ts) with correct usage of `class-validator`

**Comment by braaar** [comment]
`class-validator` can only validate classes. 

If you try to validate a plain object, TypeScript will not warn you about it, unfortunately (at least as far as I know, maybe there is a trick you can use), but your code is not set up properly.

**Comment by braaar** [comment]
> @harveyappleton Yes, you are right. But the validation message is not what I expect. When I put `@IsNotEmpty` decorator as well, I get the following validation:
> 
> ```ts
> [
>   ValidationError {
>     target: Body {},
>     value: undefined,
>     property: 'body',
>     children: [],
>     constraints: { isNotEmpty: 'body should not be empty' }
>   }
> ]
> ```
> 
> In fact, I want to get `weight should be string`, `height should be string`

In your case, it seems you want to write a transformer or a constructor that makes it so that you populate the `body` field with a class instance of `Body`. Something like this:

```ts
class Event {
      constructor() {
            this.body = new Body();            
      }

      @Type(() => BodyMeasurement)
      @ValidateNested()
      body: BodyMeasurement
}
```

If you're going to validate an object, it has to be a class instance. That goes for nested objects as well.

**Comment by braaar** [comment]
**Your issue was closed**
This means that it was not helpful for `class-validator` to keep this issue open. 
 
Issues are tools for improving the project and should be concrete and actionable. If an issue is no longer relevant or is difficult to work with, it will be closed. The project maintainers need to be selective with their attention and time. 

**What now?**
If you need further help using `class-validator` you can ask a question in the [question and answer section of the discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers).

If you are still experiencing an issue, see [our guide](https://github.com/typestack/.github/blob/master/CONTRIBUTING.md#opening-issues) on how to write helpful issues, and submit a new, improved issue.
