### ISSUE TITLE
@IsEmail() does not support a custom message

### ISSUE THREAD

**Issue by st-clair-clarke** [typestack/class-validator#138]
Hi,
Given

```
class EmailModel {
  @IsEmail({message: "Invalid email message" }) //  {...} is error
  @IsNotEmpty( { message: PimMessages.required } )
  address: string = ''
}
```

Why does the @IsEmail() not support the `{message: "Invalid email message" }` object. Webstorm flags it as error (not supported)

Thanks

**Comment by ericzon** [comment]
@st-clair-clarke in IsEmail you need to provide the validation options as second parameter. Try on this form:
```
@IsEmail({}, { message: 'Invalid email message' })
```
The first parameter are options related with email validation.

**Comment by NoNameProvided** [comment]
Hi @st-clair-clarke! 

I hope @ericzon answered your question! I will go ahead and close this question but feel free to continue the discussion if something is not clear.
