### ISSUE TITLE
question: Is it possible to transform the errors?

### ISSUE THREAD

**Issue by kluplau** [typestack/class-validator#1384]
**I would like**
I would like to have errors transformed, so it's possible for the frontend to match keys with the errors, something like this:
```javascript
{
    "statusCode": 400,
    "message": [
        {
                "key": "username",
                "message": "username must be shorter than or equal to 5 characters"
        },
        {
                "key": "password",
                "message": "password should contain at least 1 uppercase, 1 number 1 lowercase"
        },
        {
                "key": "password",
                "message": "password must be longer than or equal to 8 characters"
        }
    ],
    "error": "Bad Request"
}
```

Or like this

```javascript
{
    "statusCode": 400,
    "message": {
        "username": [
            "username must be shorter than or equal to 5 characters"
        ],
        "password": [
             "password should contain at least 1 uppercase, 1 number 1 lowercase", 
             "password must be longer than or equal to 8 characters"
        ]
    },
    "error": "Bad Request"
}
```

**The problem:**
The problem is that now when you get the errors back from the API then you have to make sure that the errors start with the key, then extract the error start starts with the key name, and attach the error to the element in the form.

**Comment by NoNameProvided** [comment]
You can write any custom logic to transform the received errors from the `class-validator` in your application code. If you don't want to call the transformation everywhere, then you can wrap your validation in a function that runs validation and then returns all errors in your desired format.
