### ISSUE TITLE
question: Validating Nested Array of Objects with Transform

### ISSUE THREAD

**Issue by SuperRamakant** [typestack/class-validator#1398]
**I was trying to validate Nested Array of Objects with Transform*

   @ValidateNested({ each: true })
    @IsArray()
    @Type(() => SomeDto)
    @Transform(({ value }: TransformFnParams) => mergeAndSum(value))
    something: SomeDto[] = [];

const mergeAndSum = (value) => {
    let group = {};
   //transformation
    return mergedPkgs;
};

**The problem:**
Not getting the error thrown when implementing with **Transform** method

**Comment by dieyne** [comment]
I think that u can remove the @Type decorator and be sure that ur @Transform decorator must return an array of SomeDto and each SomeDto inside the transform decorator must be instanciate by SomeDto constructor

**Comment by SuperRamakant** [comment]
@dieyne can you please share an example if possible? with Transform is there a way to validate the property?

**Comment by dieyne** [comment]
Yes, this is an example.
```@Field(() => [UserInput], { nullable: false })
  @Transform((value) => {
    return value.value.map((item) => {
      return new UserInput({ ...item, role: [UserRole.CLIENT] });
    });
  })
  @ValidateNested()
  user: UserInput[];

**Comment by SuperRamakant** [comment]
@dieyne ,
thanks once again for your reply.

can you please share UserInput - in my case the SomeDto is an empty constructor i.e

```
SomeDto {

    @IsString()
    @Transform(({ value }: TransformFnParams) => typeof value === 'string' && value.trim())
    @IsNotEmpty()
    name: string;

    @IsOptional()
    @IsString()
    @Transform(({ value }: TransformFnParams) => typeof value === 'string' && value.trim())
    description: string;
}
```

**Comment by dieyne** [comment]
UserInput 
```
export class UserInput {
  constructor(partial: Partial<UserInput>) {
    Object.assign(this, partial);
  }
// UserInput  Fields here 
  @IsEmail({}, { message: `L'email est invalide` })
  @UserExists()
  @Field({ nullable: false })
  email: string;
}
```

I think Object.assign will work for you
```
 @Transform((value) => {
    return value.value.map((item) => {
      return Object.assign(new SomeDto(), item);
    });
  })
  @ValidateNested({each: true})
  something: SomeDto[];

**Comment by SuperRamakant** [comment]
@dieyne ,
This works well when used for primitive data types, what if my UserInput Fields have non-primitive data-type i.e another object to be validated like this:
/```
/ UserInput  Fields here 
  @IsEmail({}, { message: `L'email est invalide` })
  @UserExists()
  @Field({ nullable: false })
  email: string;
 @ValidateIf((packageDto: PackageDto) => packageDto.name === 'custom')
    @ValidateNested()
    @Type(() => DimensionDto)
    size: DimensionDto;
}

export class DimensionDto {
    @IsNumber()
    @IsPositive()
    length: number;
    @IsNumber()
    @IsPositive()
    width: number;
    @IsNumber()
    @IsPositive()
    height: number;
}
```

**Comment by SuperRamakant** [comment]
@dieyne ,
Thank you so much, this worked well.

**Comment by dieyne** [comment]
Ok cool.

**Comment by SuperRamakant** [comment]
@dieyne ,
how to validate non-primitive data types.
export class UserInput {
  constructor(partial: Partial<UserInput>) {
    Object.assign(this, partial);
  }
// UserInput  Fields here 
  @IsEmail({}, { message: `L'email est invalide` })
  @UserExists()
  @Field({ nullable: false })
  email: string;
  @IsNotEmptyObject()
  @Type(() => DimensionDto)
  @ValidateNested()
  size: DimensionDto;
}
export class DimensionDto {
    @IsNumber()
    @IsPositive()
    length: number;
    @IsNumber()
    @IsPositive()
    width: number;
    @IsNumber()
    @IsPositive()
    height: number;
}

Response:

{
    "statusCode": 400,
    "message": [
        "something.0.size must be a non-empty object"
    ],
    "error": "Bad Request"
}.

In this transform keeps on getting in the loop, and if I remove  @ValidateNested() then it works as expected but then the dimensions aren't validated. 

Can you please help further?

**Comment by SuperRamakant** [comment]
@dieyne ,

Finally I have figured out - 
Transform with Type does works given the transformed objects are also instantiating the SomethingDto.
After implementing the above suggestion with Type did exactly what was needed.

**Comment by dieyne** [comment]
Ok cool. You can publish your solution for those who need it

**Comment by SuperRamakant** [comment]
Here's the solution:

```
@ValidateNested({ each: true })
@IsArray()
@type(() => SomeDto)
@Transform(({ value }: TransformFnParams) => mergeAndSum(value))
something: SomeDto[] = [];

const mergeAndSum = (value) => {
let group = {quantiy: 1};
//transformation
value.map((v) => Object.Assign(new SomeDto(), {...v, ...group}))
return mergedPkgs;
};
```

thanks to @dieyne for helping me figure out that whenever you transform an Array of objects ensure that you are doing it the right way which is via Instantiation of the class you want to transform and validate with.
