### ISSUE TITLE
Does IsDecimal do what it should do?

### ISSUE THREAD

**Issue by kaytrance** [typestack/class-validator#1423]
Why `IsDecimal()` decorator description says that "Checks if the string contains only letters and numbers. If given value is not a string, then it returns false." and it does not check of the value was decimal or not?

While `isDecimal()` contains proper description and probably does that it means.

For example `@IsDecimal` on a field with value 123.45 passes validation while it should not, imo.

```ts
import { ValidationOptions } from '../ValidationOptions';
import ValidatorJS from 'validator';
export declare const IS_DECIMAL = "isDecimal";
/**
 * Checks if the string is a valid decimal.
 * If given value is not a string, then it returns false.
 */
export declare function isDecimal(value: unknown, options?: ValidatorJS.IsDecimalOptions): boolean;
/**
 * Checks if the string contains only letters and numbers.
 * If given value is not a string, then it returns false.
 */
export declare function IsDecimal(options?: ValidatorJS.IsDecimalOptions, validationOptions?: ValidationOptions): PropertyDecorator;
```

**Comment by nur557** [comment]
Why do you think `123.45` shouldn’t pass validation?

**Comment by nur557** [comment]
Under the hood this libarary uses `validator`, [on their page, in this table](https://github.com/validatorjs/validator.js#validators) you can see details about `isDecimal`.

**Comment by braaar** [comment]
It seems like the docstring for `IsAlphanumeric` has been copied over to `IsDecimal`

@kaytrance, judging by your description you probably want to use `IsAlphanumeric` for your use case. 

https://github.com/typestack/class-validator/blob/develop/src/decorator/string/IsAlphanumeric.ts
```ts
/**
 * Checks if the string contains only letters and numbers.
 * If given value is not a string, then it returns false.
 */
export function isAlphanumeric(value: unknown, locale?: ValidatorJS.AlphanumericLocale): boolean {
  return typeof value === 'string' && isAlphanumericValidator(value, locale);
}
```

We need to update the docstring for `IsDecimal`

**Comment by NoNameProvided** [comment]
As @braaar said, the JSDOC was incorrect. It has been updated in https://github.com/typestack/class-validator/commit/42b9ca263cf855d2004c0dce23e38d23546148ac.

Closing as solved.
