### ISSUE TITLE
Exclude property name from decorators message by default

### ISSUE THREAD

**Issue by MistyKuu** [typestack/class-validator#143]
Currently by default property name is included in the message for each decorator. Is there a way to disable this behaviour? It kinda doesn't make sense to make it default because this should be a business message that something went wrong. Do you really want to display non meaningful field name there?
Example:

> userAge cannot be empty

**Comment by NoNameProvided** [comment]
How would you describe the error then? This error message is for programmers, you need to build your own layer above it. Eg we transform form error messages to a format how angular expects form errors.

**Comment by MistyKuu** [comment]
I really thought it's a message that you should be able to display directly. I'm using redux-forms in react and I have my own layer that converts validation errors into error object however a `message` is something that I display to users under every field so there is no need for displaying a field name. Currently for every attribute I use I have to create my own wrapper which basically overrides a 'message' into something meaningful like for `IsNonEmpty` attribute I have `Required`. It would be nice to have like a global setting to include/exclude property names from the default message.

**Comment by thrixton** [comment]
I second this request.
In a lot of cases, the errors returned **will** be used on the frontend, especially for an MVP.

I have a workaround as I transform the errors and can easily trim the start if it is the property name but that's not always feasible.

**Comment by Beej126** [comment]
fyi, see #169, i [just posted](https://github.com/typestack/class-validator/issues/169#issuecomment-773751761) sample of easy message override however wanted

**Comment by NoNameProvided** [comment]
If this is something you are still interested in, please open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) so the community can brainstorm, iterate, define the ideal API and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.
