### ISSUE TITLE
fix: `ValidationDecoratorOptions.propertyName` should allow symbols

### ISSUE THREAD

**Issue by notaphplover** [typestack/class-validator#1439]
### Description

Typescript `PropertyDecorator` is defined as follows:

```typescript
declare type PropertyDecorator = (target: Object, propertyKey: string | symbol) => void;
```

I'm open to contribute to this repo in order to solve this issue :)

### Expected behavior

Since I expect `registerDecorator` to be used to generate `PropertyDecorator` as suggested in docs, I expect it to allow symbol values at `propertiesName` in order to be used.

### Actual behavior

`ValidationDecoratorOptions.propertyName` is typed as `string`.

**Comment by NoNameProvided** [comment]
That property is used internally. Closing this as wontfix.
