### ISSUE TITLE
question: <your-title-goes-here>

### ISSUE THREAD

**Issue by necm1** [typestack/class-validator#1440]
I was trying to to add `IsOptional` decorator to my property combined with the `MinLength` decorator and sadly `MinLength` throws a error.

**The problem:**
My string is empty and `IsOptional` only accepts `undefined` or `null` strings. Wouldn't it be possible to convert it to `undefined` or even `null` if we get a empty string? So it wouldn't throw any error.

btw. I'm using NestJS so I cannot really catch & replace it with undefined.

ProfileDto
```
/**
 * @class ProfileDto
 */
export class ProfileDto {
  @IsOptional()
  @MinLength(3, {
    context: {
      exception: new FullNameMinLengthDtoException(),
    },
  })
  @MaxLength(20, {
    context: {
      exception: new FullNameMaxLengthDtoException(),
    },
  })
  fullname?: string;
}
```

**Comment by braaar** [comment]
It seems like you wish to use [class-transformer](https://github.com/typestack/class-transformer) and use a transform to turn empty strings into `undefined`.

**Comment by NoNameProvided** [comment]
The suggestion by @braaar is correct. Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
