### ISSUE TITLE
question: ValidateNested with dot syntax

### ISSUE THREAD

**Issue by fasenderos** [typestack/class-validator#1444]
I'm having trouble validating nested objects when I try to update a specific prop of a nested object e.g.:

```ts
class Nested {
  @IsString()
  @IsOptional()
  readonly propA: string;

  @IsString()
  @IsOptional()
  readonly propB: string;
}

export class UpdateDto {
  @IsOptional()
  @Type(() => Nested)
  @ValidateNested()
  readonly nested: Nested;
}
```

If I try to pass a dotted key like `{ "nested.propA": "test" }` I get the following error:

```ts
{
    "statusCode": 400,
    "message": [
        "property nested.propA should not exist"
    ],
    "error": "Bad Request"
}
```

The simplest solution can be adding in the parent object the dotted keys eg:

```ts
class Nested {
  @IsString()
  @IsOptional()
  readonly propA: string;

  @IsString()
  @IsOptional()
  readonly propB: string;
}

export class UpdateDto {
  @IsString()
  @IsOptional()
  readonly name: string;

  @IsOptional()
  @Type(() => Nested)
  @ValidateNested()
  readonly nested: Nested;

  @IsString()
  @IsOptional()
  readonly 'nested.propA': string;    <==== THIS

  @IsString()
  @IsOptional()
  readonly 'nested.propB': string;    <==== THIS
}
```
With that approach, I can pass both the entire object and a single prop, but it seems really redundant to me.

Any other way to validate using a "dot" syntax? The DB is `mongo` where the dot syntax can be used to update a specific prop of a nested object.

Thanks.

**Comment by NoNameProvided** [comment]
I don't understand your problem. 

If this is a feature request to allow flattening nested objects to the top level with dot syntax, then this will not be implemented. 

Closing this as answered.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
