### ISSUE TITLE
question: How to validate an object with an array inside

### ISSUE THREAD

**Issue by Guilherm456** [typestack/class-validator#1451]
**I was trying to...**
Hello, I'm trying to create a class for NestJS, where it receives one of the parameters is an object with an array inside, with that, I wanted to create a validation to not allow these parameters to come empty, but I've tried basically everything. An example of what the class looks like:
`class InfluenzaStructureDTO {
  @IsNotEmptyObject()
  @ValidateNested({ each: true })
  ambiente: {
    AMB: ParametersDTO[];
    CONV: ParametersDTO[];
    DISTRIBUICAOHUMANO: ParametersDTO[];
  };`

Where the "ParametersDTO" has the following class:
`export class ParametersDTO {
  @IsNotEmpty()
  @IsString()
  name: string;

  @IsNotEmpty()
  value: string | number;
};`

I've already tried passing the "ambiente" parameter as a separate class, but to no avail anyway, as I've also used
`@IsNotEmpty({each:true})
@Type(()=> ParameterDTO
@IsNotEmptyObject()
@ValidateNested({each:true})
@ArrayMinSize(1)`

But none of these commands worked, I don't know if I'm applying it incorrectly.
Some examples of what I've tried:
![image](https://user-images.githubusercontent.com/18385445/146071241-5f36d92c-1977-476a-abed-672829bb7cd5.png)
![image](https://user-images.githubusercontent.com/18385445/146071287-102e69af-b394-4798-a9ee-f7b5fc49b7e0.png)

**The problem:**
When I pass the parameter with empty array, it allows no errors. In the image below I'm passing the "TRA" with an empty array and it allows:
![image](https://user-images.githubusercontent.com/18385445/146071033-92b641db-b31c-4066-9bc0-b68f19b4dd50.png)

**Comment by loadko** [comment]
Try this:
```typescript
@IsArray()
@ArrayNotEmpty()
@ArrayMinSize(1)
@ValidateNested({ each: true })
@Type(() => ParametersDTO)
TRA: ParametersDTO[]
```

**Comment by Guilherm456** [comment]
I got it, I was forgetting to validate a parent object with `@Type`.
But my validation was also missing the "IsArray", thank you very much @loadko
