### ISSUE TITLE
Feature request: Fail on first ValidationError.

### ISSUE THREAD

**Issue by janis91** [typestack/class-validator#148]
It would be very nice to have a configuration option like 'failFast' or something like that available. It makes testing much easier and in case of big validation tasks it also gives a big performance boost:
if something is wrong it will fail fast and doesn't have to wait for the rest of the validation.

What do you think?

**Comment by NoNameProvided** [comment]
Sound reasonable to me. :)

**Comment by NoNameProvided** [comment]
Closing in favor of #178
