### ISSUE TITLE
I want to customize the return type

### ISSUE THREAD

**Issue by SenvenQi** [typestack/class-validator#149]
I want to customize the return type, but you don't have such a configuration, and I want to do a better way to return to the custom type.

**Comment by NoNameProvided** [comment]
Can you elaborate more?

**Comment by SenvenQi** [comment]
Because I'm using react, I want setState (error), but I didn't think of a better way to get this error message to change state.Because the return type must be ValidationError.I don't have a better way to do it。

**Comment by kalyuk** [comment]
@SenvenQi Look here, I've attached an example of my decision
https://github.com/typestack/class-validator/issues/132

**Comment by SenvenQi** [comment]
@kalyuk  thank you.

**Comment by NoNameProvided** [comment]
@SenvenQi Does @kalyuk solution solved your problem? Can we close this?

**Comment by SenvenQi** [comment]
yes
