### ISSUE TITLE
question: Is there a way to change the default message for a validation decorator?

### ISSUE THREAD

**Issue by nur557** [typestack/class-validator#1510]
I’d like the validation message for `@isNumber` to simply say “$property must be a number” instead of “$property must be a number conforming to the specified constraints”. Is there a way to do this in one place?

**Comment by Rober9614** [comment]
Hello x4th 


You can setting  decorator details, and put customs errors.

Important, constructor take 2 objects: 

```ts
options?: IsNumberOptions, validationOptions?: ValidationOptions
```
Only need set object: ValidationOptions in specific decorator, if you don't need modified object "IsNumberOptions" 
you can send null or  empty "{}"

For example: 

```ts
import { IsNumber } from "class-validator";

export class TestDto {

    @IsNumber({}, { message: 'Custom error here :) ' })
    Id: number;

}

export class Test2Dto {

    @IsNumber(null, { message: 'Custom error here :) ' })
    Id: number;

}

```

**Comment by NoNameProvided** [comment]
There is currently no way to define a _default_ error message. This is something we should consider. 

If you are still interested please open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) with the proposed API. From there the community can brainstorm, iterate and reach a consensus about how this should work.
