### ISSUE TITLE
question: merging into PR branches causes semantic-pull-request check to fail

### ISSUE THREAD

**Issue by braaar** [typestack/class-validator#1524]
### Description
Updating a PR branch by clicking the button that prompts you to do so creates a commit with a non-conventional commit message, causing the semantic-pull-requests check to fail. 

**Minimal code-snippet showcasing the problem**
[See example PR with a very simple docstring change where this occurred](https://github.com/typestack/class-validator/pull/1502)

### Expected behavior
I would expect that either the automated merge commit would use conventional commit message, or that semantic-pull-request would ignore that commit.

### Actual behavior
- Fork the repository
- Make your changes using conventional commit messages (e.g. `fix: bla bla bla`)
- Create a PR with your fix, using correct syntax for your PR title
- (a week passes, your branch is now out of date)
- Click the update button, merging `develop` into your branch with message `Merge branch 'develop' into <your-branch>`
- Semantic pull requests check now fails 

### Possible solutions:

Reconfigure the semantic-pull-request action to only check the PR title by changing this line:
https://github.com/typestack/class-validator/blob/75e135c59ecb1a649c61436b52c95c1404704866/.github/semantic.yml#L1
to:
```yml
titleOnly: true
```
OR

Allow merge commits by changing this line:
https://github.com/typestack/class-validator/blob/75e135c59ecb1a649c61436b52c95c1404704866/.github/semantic.yml#L2
to:
```yml
allowMergeCommits: true
```

**Comment by braaar** [comment]
As far as I can tell, the majority of PRs are failing this check, and the most recently merged PRs have been failing this check as well. 

I think the current setup is unreasonably strict. Merges are quite common and I don't see why we should have an extra roadblock in the contribution process. With the current rules contributors have to close their PRs, redo all their changes in a new up to date fork and create a new PR in order to meet the strict requirements for commit messages, unless they have the foresight to perform the merge manually with a custom conventional commit message.

**Comment by NoNameProvided** [comment]
This is on purpose. The solution for this is to rebase your feature branch onto develop when opening PRs. This way there will be no merge commits generated by Github.
