### ISSUE TITLE
Version 0.13.2 is broken

### ISSUE THREAD

**Issue by ghost** [typestack/class-validator#1535]
Due to this commit:

https://github.com/typestack/class-validator/commit/70278abaf1bd4087c3f373b17dc03385b6dbedfd

there are a lot of errors for types, need to revert it.

This is related to: 

https://github.com/typestack/class-validator/issues/1412

and maybe to this:

https://github.com/typestack/class-validator/issues/1517

**Comment by chriswoodle** [comment]
Yea, getting the same issue. Easy temp workaround is to downgrade back to `0.13.1`. Looks like @types/validator needs to be added back as a `dependency`: https://github.com/nestjs/class-validator/issues/79#issuecomment-1041921291
![image](https://user-images.githubusercontent.com/11614325/154341071-f5cc5f0b-b555-4ece-b7f4-0f6245f168a6.png)

**Comment by NoNameProvided** [comment]
https://github.com/typestack/class-validator/commit/12f8d86d8507563dfb8e53b6c2e7c490c08e121e

**Comment by NoNameProvided** [comment]
This feature/fix has been released in `0.14.0`.
