### ISSUE TITLE
fix: IsHalfWidth docblock references IsFullWidth

### ISSUE THREAD

**Issue by shanehandley-lt** [typestack/class-validator#1545]
### Description
This docblock is confusing as it is identical to IsFullWidth when using an IDE:

![IsFullWidth](https://user-images.githubusercontent.com/68725881/153676962-d7caf0c7-e595-40ea-b49c-10f0d4701e31.png)

**Minimal code-snippet showcasing the problem**
N/A

### Expected behavior
The docblock should match the intent of the function

### Actual behavior
The docblock actually matches the `IsFullWidth` intent

**Comment by NoNameProvided** [comment]
This feature/fix has been released in `0.14.0`.
