### ISSUE TITLE
feature: add `@IsISO4217` decorator to check currency codes

### ISSUE THREAD

**Issue by bassochette** [typestack/class-validator#1549]
### Description

`validator.js` offers validation for currency codes against the ISO4217 standard. 

### Proposed solution

Implement the `@IsIso4217()` decorator.

**Comment by bassochette** [comment]
I'd be glad to implement it and send a PR

**Comment by braaar** [comment]
Check out [the existing validator in validator.js](https://github.com/validatorjs/validator.js/blob/master/src/lib/isISO4217.js). It's a fairly new addition, so it hasn't been added here yet.

**Comment by braaar** [comment]
Last time I checked I think I saw that validator.js has been bumped so that 4217 should be available to implement right away, but don't quote me on that 😅

**Comment by bassochette** [comment]
> 

I saw it in validator.js and needed it today sooooo pull request time ;)

**Comment by mehulbaid** [comment]
please merge

**Comment by NoNameProvided** [comment]
This feature/fix has been released in `0.14.0`.
