### ISSUE TITLE
Checking isNumber of NaN value gives the validation as ok

### ISSUE THREAD

**Issue by ericzon** [typestack/class-validator#155]
First of all, thanks for this great library. Keep up the good work.

As I see on your readme, isNumber validator says:
isNumber(value); // Checks if a given value is a real number.

I'm using it for query validation. I've passed a string ('abcd') to test validation and it says that the dto is correct. Looking on the code, I see that class-validator uses lodash method _.isNumber. Searching a little bit more, I found this issue on the Lodash repo:
````
_.isNumber(NaN) === true
````

https://github.com/lodash/lodash/issues/1373

Looking this, maybe it would be better to improve @IsNumber validation, to get a more realistic result.

P.S: Yes, I've transformed the incoming query using class-transformer and checked that the field is transformed to number as NaN before validation.

Thanks

**Comment by NoNameProvided** [comment]
Hey @ericzon! 

Thanks for the report! It has been fixed and will be released in the version. The new signature for `@IsNumber` is

```ts
@IsNumber(allowNan: boolean = false)
```
