### ISSUE TITLE
question: Is there a way to validate strings?

### ISSUE THREAD

**Issue by AlexandrosMelissas** [typestack/class-validator#1566]
**I was trying to...**
validate a uuid or a string
**The problem:**
I can't seem to find a way how to validate a plain string without turning it into a field of a class first.

**Comment by kevin-mitchell** [comment]
Could you use `@Matches(pattern: RegExp, modifiers?: string)` ?

> Checks if string matches the pattern. Either matches('foo', /foo/i) or matches('foo', 'foo', 'i').

https://github.com/typestack/class-validator/blob/6a5762196b06655d51dddfff7807a5a87fc12216/src/decorator/string/Matches.ts

edit: Also, `@IsUUID(version?: "3"|"4"|"5"|"all")` is there as you probably know for specifically validating UUIDs

**Comment by AlexandrosMelissas** [comment]
Sorry i forgot to add a small detail. 
I'm trying to validate with ``` await validate() ``` or ``` validateOrReject() ``` method

**Comment by AlexandrosMelissas** [comment]
I just saw class-validator also exports methods instead of decorators. Problem solved.
