### ISSUE TITLE
Question: Is the name property in ValidatorConstraint unique?

### ISSUE THREAD

**Issue by meness** [typestack/class-validator#1574]
Hi guys,

Should I give a unique name to custom validators? In other words, can I have multiple decorators like this on different classes?
```typescript
@ValidatorConstraint({ name: 'isUnique', async: true })
```

Thanks.

**Comment by NoNameProvided** [comment]
Hi @meness! 

Yes, you should use unique names for your custom validators.  I cannot say with 100% confidence yop of my head that it will cause issues, but it is better to be safe than sorry.
