### ISSUE TITLE
question: how to set default value?

### ISSUE THREAD

**Issue by JasenYang** [typestack/class-validator#1586]
**I was trying to...**
If the property doesn't set the value, how can I get the default value

```ts
export class UserDto {
  @IsNotEmpty()
   name: string;

  @IsBoolean()
  isEnabled = false;
}

const userdto: UserDto = { name:"Marry" }

console.log(userdto.isEnabled);
```

I hoped it outputs the value `false` but it does not work. How can I achieve this?

**Comment by NoNameProvided** [comment]
Your question has nothing to do with `class-validator`. Assigning a plain object to a variable with a class type will not make the object magically a class. You need to create an instance of the class for that to work.  

```ts
export class UserDto {
  @IsNotEmpty()
  name: string;

  @IsBoolean()
  isEnabled = false;
}

const userdto: UserDto = new UserDto();

userdto.name = 'Marry';

console.log(userdto.isEnabled); // outputs false
```
