### ISSUE TITLE
fix: using `excludeExtraneousValues` flag is breaking everything

### ISSUE THREAD

**Issue by RoyLeibo** [typestack/class-validator#1588]
Hi,

I have a DTO class of a user in NestJS.
I am using many validations using class-validator package in order to enforce my logic.
If a field that doesn't exists on the DTO definition, I would like to ignore it and even throw an error.
This is why I was trying to use the 'excludeExtraneousValues' flag.
When I do use it, it ignores all the fields, even the ones that defined in the DTO.

```ts
import { ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDefined,
  IsEmail,
  IsOptional,
  IsPhoneNumber,
  MaxLength,
  ValidateIf,
} from 'class-validator';

export default class UserDTO {
  
  @ApiPropertyOptional()
  @MaxLength(254)
  @IsEmail()
  @IsDefined()
  @ValidateIf((object) => object.email || !object.phone_number)
  email?: string;

  @ApiPropertyOptional()
  @MaxLength(15)
  @IsPhoneNumber()
  @IsDefined()
  @ValidateIf((object) => object.phone_number || !object.email)
  phone_number?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @MaxLength(40)
  name?: string;
}
```

As I mentioned, I am using NestJS.
This is the ValidationPipe definition:

```ts
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      stopAtFirstError: true,
      transformOptions: { excludeExtraneousValues: true },
    }),
  );
```

Following the addition of 'excludeExtraneousValues' flag, I cannot send any value, even the ones that is defined.

Is it a bug or am I missing something?

**Comment by Angelin01** [comment]
I'm pretty sure this is an issue for [class-transformer](https://github.com/typestack/class-transformer/).
Either way, [the documentation states that if you use `excludeExtraneousValues: true` that you must also use `Expose()`](https://github.com/typestack/class-transformer#enforcing-type-safe-instance). [While this behavior is being considered a bug by many users](https://github.com/typestack/class-transformer/issues/740), it is documented behavior.

**Comment by NoNameProvided** [comment]
Closing this as invalid. This issue should be opened in the `class-transformer` repository.

**Comment by simon1389** [comment]
@RoyLeibo I think the option you are looking for is the `whitelist: true` (maybe in combination with `forbidNonWhitelisted: true`) as this  would ignore/remove all properties sent in the request, which are not defined in your DTO (or throws an error if forbidNonWhitelisted is set to true)
