### ISSUE TITLE
question: is there a way to send back an error message as an object instead of string ?

### ISSUE THREAD

**Issue by DimitriMathot** [typestack/class-validator#1593]
**I was trying to...**
Send an object {formName : errorMessage} instead of a simple string to avoid deserialization of my string in my web application.
Do you have any idea how to manage this ?

**Comment by NoNameProvided** [comment]
Currently not possible but this is something we should consider.

If the issue still affects you, you may open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) where the community can brainstorm, iterate and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.
