### ISSUE TITLE
question: <your-title-goes-here>

### ISSUE THREAD

**Issue by Gercov** [typestack/class-validator#1617]
How can I make all these fields optional together? That is, either all 3 fields are in the class, or none
```
export class AdReturnQuery extends PaginationQuery {
  @IsInt()
  @Type(() => Number)
  readonly id: number | null = null;

  @IsInt()
  @Type(() => Number)
  readonly referenceID: number | null = null;

  @IsInt()
  @Type(() => Number)
  readonly postID: number | null = null;
}
```

**Comment by braaar** [comment]
Could you title this issue a bit better, perhaps?

I would suggest encapsulating these in a separate class and make that object as a whole optional. You can then use `@ValidateNested` to validate the fields themselves (they would all be required in that class).

Alternatively, you can solve this with `@ValidateIf()` and a function that checks for the value of the three fields.

**Comment by Gercov** [comment]
> Could you title this issue a bit better, perhaps?
> 
> I would suggest encapsulating these in a separate class and make that object as a whole optional. You can then use @ValidateNested to validate the fields themselves (they would all be required in that class).

Thanks
