### ISSUE TITLE
question: What is difference between @IsDefined x @IsNotEmpty()?

### ISSUE THREAD

**Issue by mknparreira** [typestack/class-validator#1633]
It's not clear to me the main difference between `@IsDefined` and `@IsNotEmpty`.

According to documentation, both do the same: It checks if the given value is not empty, !== null, and undefined.

Besides that, while doing my research, I noticed that `@IsNotEmpty` is more used than `@IsDefined`.

Thus, may I use both or there is some difference that I don´t get it?  Thanks for help

**Comment by martin-yin** [comment]
```typescript
/**
 * Checks if value is defined (!== undefined, !== null).
 */
export function isDefined(value: any): boolean {
  return value !== undefined && value !== null;
}

/**
 * Checks if given value is not empty (!== '', !== null, !== undefined).
 */
export function isNotEmpty(value: unknown): boolean {
  return value !== '' && value !== null && value !== undefined;
}
```
The difference between `@IsNotEmpty` and `@IsDefined` is that `@IsNotEmpty` determines whether it is an empty string. 

`@IsDefined` does not judge strings！

**Comment by NoNameProvided** [comment]
Closing this as answered.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
