### ISSUE TITLE
question: Why is the typeFunction executed

### ISSUE THREAD

**Issue by JeonSoongu** [typestack/class-validator#1645]
type.decorator.js

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Type = void 0;
const storage_1 = require("../storage");
/**
 * Specifies a type of the property.
 * The given TypeFunction can return a constructor. A discriminator can be given in the options.
 *
 * Can be applied to properties only.
 */
function Type(typeFunction, options = {}) {
    console.log(typeFunction);
    return function (target, propertyName) {
        console.log(target.constructor);
        const reflectedType = Reflect.getMetadata('design:type', target, propertyName);
        console.log(reflectedType);
        storage_1.defaultMetadataStorage.addTypeMetadata({
            target: target.constructor,
            propertyName: propertyName,
            reflectedType,
            typeFunction,
            options,
        });
    };
}
exports.Type = Type;
//# sourceMappingURL=type.decorator.js.map
```

custom decorator

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IsGreaterThan = void 0;
const class_validator_1 = require("class-validator");
const error_constant_1 = require("../constants/error.constant");
function IsGreaterThan(property, validationOptions) {
    console.log('custom deco');
    return function (object, propertyName) {
        console.log(propertyName);
        (0, class_validator_1.registerDecorator)({
            name: 'IsGreaterThan',
            target: object.constructor,
            propertyName: propertyName,
            constraints: [property],
            options: validationOptions,
            validator: {
                validate(value, args) {
                    console.log(value);
                    const [relatedPropertyName] = args.constraints;
                    const relatedValue = args.object[relatedPropertyName];
                    if (value < relatedValue)
                        return false;
                    return true;
                },
                defaultMessage: () => error_constant_1.ERROR_MSG.GREATER_STARTDATE,
            },
        });
    };
}
exports.IsGreaterThan = IsGreaterThan;
//# sourceMappingURL=greater-than.decorator.js.map
```
dto
```ts
export class Dto {
  @ApiProperty({ description: 'RFC 3339', example: formatRFC3339(new Date()) })
  @IsNotEmpty()
  @Type(() => Date)
  readonly startAt: Date;

  @ApiProperty({ description: 'RFC 3339', example: formatRFC3339(new Date()) })
  @IsNotEmpty()
  @Type(() => {
    console.log(this);
    return Date;
  })
  @IsGreaterThan('startAt')
  readonly endAt: Date;
}
```

Looking at the principle of operation, it is a case of failure if the start date is greater than the end date by receiving the string value in the date data and changing it to a date type.

According to the principle of operation of the decorator, since the result is returned from the bottom, shouldn't there be an error because the custom decorator is a string type?
But it works fine. Also, I wonder why the type decorator approaches only once during class reporting time. The order of data insertion and API request is as follows.

console.log(typeFunction);
console.log('custom deco');
console.log(propertyName);
console.log(reflectedType);
console.log(this);
console.log(value);

```ts
  @ApiProperty({ description: 'RFC 3339', example: formatRFC3339(new Date()) })
  @IsNotEmpty()
  @IsGreaterThan('startAt')  
  @Type(() => {
    console.log(this);
    return Date;
  })
  readonly endAt: Date;
```

I don't know why the two consoles are always the same even if I change the order.

console.log(this);
console.log(value);

Why does the anonymous function always run first?
Where is the code that calls an anonymous function in a type deco?

Are all decorators called once at class declaration and then not approached? The type function is called only at the time of class declaration, and then the console in the type function is not stamped even if the API is called.

The title means that I don't know why the anonymous function, the factor of the type decoration, is executed when the type decoration is executed only once.

**Comment by NoNameProvided** [comment]
Sorry I cannot understand your problem. 

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
