### ISSUE TITLE
About to avoid bad terms

### ISSUE THREAD

**Issue by Naarasoares** [typestack/class-validator#1646]
I did not found this suggestion here so, I wanna to open a discussion here about to use neutral terms to replace bad terms that we are using to validate forbidden  properties on a object, so instead we use 'whiteList' like we had on the 'ValidatorOptions' we can replace for example 'allowedList'

**Comment by braaar** [comment]
I'll convert this to a discussion

**Comment by NoNameProvided** [comment]
Discussion is continued in: https://github.com/typestack/class-validator/discussions/1797
