### ISSUE TITLE
Release Notes Link in README.md Not Working

### ISSUE THREAD

**Issue by MHeironimus** [typestack/class-validator#165]
The release notes link (https://github.com/pleerock/class-validator/tree/master/doc/release-notes.md) in the README.md file is not working.

> See information about breaking changes and release notes here.

**Comment by MHeironimus** [comment]
Should this point to [https://github.com/typestack/class-validator/blob/master/CHANGELOG.md](https://github.com/typestack/class-validator/blob/master/CHANGELOG.md)?

**Comment by NoNameProvided** [comment]
Thanks! Fixed in 1db8505cc7b790140ddd5314dcc7b5e551d2ec75.
