### ISSUE TITLE
fix: `optionsArg` for `@IsMACAddress({}) is set to `any` type in VSCode

### ISSUE THREAD

**Issue by carlocorradini** [typestack/class-validator#1653]
### Description

When using `@IsMACAddress({})` decorator the `optionsArg` is set to `any` in VSCode even though `isMacAddress.d.ts` has the correct type:
![image](https://user-images.githubusercontent.com/21266147/169571940-8d4a67d5-08e1-465e-85b4-248003185b24.png)

I don't know if this is related to VSCode only or is a more general issue.

**Minimal code-snippet showcasing the problem**
 

```ts
class Test {
  // {} does not show any type hints
  @IsMACAddress({})
  address!: string;
}
```

### Expected behavior
`optionsArgs` showing `ValidatorJS.IsMACAddressOptions` options.

### Actual behavior
No type hint and `optionsArg` is set to `any`:
![image](https://user-images.githubusercontent.com/21266147/169571302-3baff2c3-4b19-4061-9394-e8cebbc6530a.png)

**Comment by NoNameProvided** [comment]
Your types may be stuck, restarting your editor will solve the problem.
