### ISSUE TITLE
Deep checking does not work

### ISSUE THREAD

**Issue by splincode** [typestack/class-validator#167]
```ts

class Application {
  
  @IsInt()
  id: number  = null;

  customer: Customer  = null;

}

class Customer {

  @IsInt()
  id: number  = null;

  person: RelatedPerson;

}

class RelatedPerson {
   
  @MinLength(8)
  @MaxLength(8)
  tokenNumber: string = null;

}

```

application - is instance
![image](https://user-images.githubusercontent.com/12021443/35794537-2b78b960-0a67-11e8-952d-771420238c69.png)

But validate returned empty array! Why? this.application.customer and this.application.customer.person - is invalid

```
validate(application ).then(errors => {
  console.log(errors); // [ ]
});
```

**Comment by EndyKaufman** [comment]
Use it https://github.com/typestack/class-validator/blob/master/sample/sample3-nested-objects/Post.ts#L11
