### ISSUE TITLE
question: how do I validate an array with mixed types (custom)

### ISSUE THREAD

**Issue by motawy-citrus** [typestack/class-validator#1682]
**I was trying to validate an array of object that can be of different types**

For example: 

```ts
const objA = { ... }; // Some properties
const objB = { ... }; // Different properties from objA
const objC = { ... }; // Different properties from objA and objB

const mixedTypesArray = Array<objA | objB | objC>
```

**The problem:**
How do I validate this array?

**Comment by NoNameProvided** [comment]
Currently, this is possible with a custom validator only.

If you have some ideas about how this should work, you can start a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) and the community may collaborate to agree on the best method.
