### ISSUE TITLE
How to transform input value 

### ISSUE THREAD

**Issue by chacha95** [typestack/class-validator#1684]
**I was trying to...**
Hi.
I want to change input value to uppercase.
For example, input value is 'asc', class validator decorator change input value to 'ASC'.
How can I do that?

**The problem:**
```Typescript
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  readonly sortOrder = 'ASC';
```

**Comment by pawelkondraciuk** [comment]
You shouldn't be doing this. Class-validator only validates values.

**Comment by braaar** [comment]
As you have received an answer, would you mind closing this issue, @jinhyuckcha? It helps reduce the workload of the maintainers :)
