### ISSUE TITLE
feature: Make `minDate` and `maxDate` support specifying dynamic date

### ISSUE THREAD

**Issue by CodyTseng** [typestack/class-validator#1691]
### Description

Sometime we need to check if the value is a date that's after now or a dynamic date.

### Proposed solution

I have an idea. Make `minDate` and `MaxDate` accept a function as the `date` parameter. The function return a date and will be executed when validate. Like the following code:

```ts
// MinDate(date: Date | (() => Date))
@MinDate(() => new Date())
someProperty
```

**Comment by NoNameProvided** [comment]
This feature/fix has been released in `0.14.0`.
