### ISSUE TITLE
question: How @IsPhoneNumber('US') actually works?

### ISSUE THREAD

**Issue by redeemefy** [typestack/class-validator#1695]
**I was trying to...**
I'm trying to validate a phone number from the United States
```typescript
...
@IsOptional()
@IsPhoneNumber('US')
readonly phone_number: string
...
```

**The problem:**
The validation gets bypassed with a number from Colombia, South America or without `+1` prefix.
```json
...
  "phone_number": "+573166239876" // Colombia is bypassing validation
...
// or
  "phone_number": "3168769876"
```

If I try to pass a code that actually doesn't exit like `1119308765` it does return the validation message.

What I'm expecting out of `@IsPhoneNumber('US')` is that
1. The `+1` it's required since is the code for `US`.
2. Also, it validates state codes `+1(615)...` for Tennessee or `+1(787)...` for Puerto Rico

1. How does the decorator actually works?
2. What are my options?

**Comment by braaar** [comment]
If you take a look at [the source code for this decorator](https://github.com/typestack/class-validator/blob/develop/src/decorator/string/IsPhoneNumber.ts), you can see that the package `libphonenumber-js` is used. 

You can take a look at `libphonenumber-js` [on npm](https://www.npmjs.com/package/libphonenumber-js)

This project mostly uses external packages to perform the actual validation logic, the most notable of which being [validator.js](https://github.com/validatorjs/validator.js). 

Another option could be to use `IsMobilePhone` instead, which uses validator.js.

**Comment by braaar** [comment]
I think I now understand the actual issue here. This is the behaviour described in #1702

**Comment by NoNameProvided** [comment]
Tracking in https://github.com/typestack/class-validator/issues/1702.
