### ISSUE TITLE
question: Why does `IsNumber(options)`'s options not have an `always` property.

### ISSUE THREAD

**Issue by SeyTo** [typestack/class-validator#1696]
**I was trying to...**
I need to group validations such as `{ groups: ["update", "create"] }`. So each property required a `{ always: true }` so that the property is validated for any group.
```js
export class PkgDto {
  @IsDefined({ groups: ["update", "find"] })
  @IsEmpty({ groups: ["create"] })
  id: number;
  @IsNumber({ always: true }) // no always property.
  vacation_id: number;
  @IsString({ always: true })
  name: string;
}
``` 

**The problem:**
No property `always` in `IsNumber(options)`

Is this intentional or did I miss a logic here?

**Comment by braaar** [comment]
It seems `IsNumber` uses its own options type, not `ValidationOptions` like the rest of them. 

https://github.com/typestack/class-validator/blob/develop/src/decorator/typechecker/IsNumber.ts

Edit: It uses both, but as two separate parameters. I'm not sure what is the best pattern here. Extending ` ValidationOptions` to make one big options object that takes all the parameters would seem reasonable to me

**Comment by NoNameProvided** [comment]
As mentioned `IsNumber` expects `ValidationOptions` as the second parameter. Every decorator that has it's own custom input options expects the general `ValidationOptions` as the second parameter.
