### ISSUE TITLE
question: How to validate number array min/max value

### ISSUE THREAD

**Issue by amustaque97** [typestack/class-validator#1709]
**I was trying to...**
 
 

I'm trying to create a DTO `GetData` where I have a severity column which accepts only 3 values in the number system format. Like Severity: 0, 1 and 2. I'm writing DTO like below

```typescript
class GetData {
    @MaxLength(3, { each: true })
    @Min(0)
    @Max(2)
    severity: number[];
```

**The problem:**
The problem is whenever I assign values to GetData.severity I get the following error: 
```console
each value in severity must not be less than 0
each value in severity must not be greater than 2
```

I'm passing values  _1 and 2_

**Comment by braaar** [comment]
`@MaxLength` is a way of validating string lengths. `@ArrayMaxSize` is used for validating the length of an array.

In order to validate the min/max size of the numbers in an array you should use the `each` option, like so:

```ts
class GetData {
    @ArrayMaxSize(3) // max length of array is 3
    @Min(0, {each: true}) // each number in array is 0 or higher
    @Max(2, {each: true}) // each number in array is 2 or lower
    severity: number[];
}
```

**Comment by amustaque97** [comment]
worked like a charm. Thank you. Closing the issue.
