### ISSUE TITLE
Is this project in need of more maintainers?

### ISSUE THREAD

**Issue by braaar** [typestack/class-validator#1719]
As far as I can tell, the [last pull request to get merged](https://github.com/typestack/class-validator/pull/830) was one and a half years ago. Since then, the project has seen a few bug fixes from @NoNameProvided and a lot of automated bumps, but there have been several high quality PRs opened and reviewed by the community. 

Last year, several people [raised concerns](https://github.com/typestack/class-validator/issues/178#issuecomment-831178151) over the level activity here, and I believe there are many highly qualified and dedicated open source developers who would be willing to take on more responsibility on this project. 

I'm relatively fresh in the game, so I don't know how this process usually works, but my thinking is that I want to make it as easy as possible for the current maintainers to find good candidates. I think the best way to show that you are dedicated and willing to take such a responsibility is by contributing wherever you can, even with the boring stuff. 

I would encourage people who are frustrated with the lack of activity here to go through unresolved issues and try to resolve them and get their authors to close them. We have a backlog to get through! (353 issues at the time of writing, and uhh, now it's 354 with this one)

I ❤️ `class-validator`

**Comment by braaar** [comment]
I suppose it's relevant to tag the other Typestack folks: @saulotoledo @jotamorais @MichalLytek @rustamwin

**Comment by eeemzs** [comment]
I agree with you. I have had a pull request for a good to have feature as well, then after it is approved, I need to apply this feature support on NestJS repository, going somewhere with two tickets.  But apperantly this will take months! It is too sad for such a beatiful project is not actively maintained.

**Comment by tciuro** [comment]
Re: "and get their authors to close them"

That's the key. Looks like the authors are no longer interested? There hasn't been any feedback from @saulotoledo @jotamorais @MichalLytek or @rustamwin since you asked on Aug. 16, now over a month ago. Total radio silence from the team. 🤔

I was looking for an issue I saw with `$value` not passing through in the validation and saw [this PR](https://github.com/typestack/class-validator/pull/1467) waiting to be approved since... Dec. 27, 2021. Wow. It actually seems to fix two issues: https://github.com/typestack/class-validator/issues/1046 and https://github.com/typestack/class-validator/issues/921

**Comment by braaar** [comment]
> and get their authors to close them

By this I meant getting people to close their own issues since we have no active maintainers to do it for them.

**Comment by tciuro** [comment]
Ah! Got it.

Do you know if it's being discussed to fork the project and continue development?

**Comment by jotamorais** [comment]
> Re: "and get their authors to close them"
> 
> That's the key. Looks like the authors are no longer interested? There hasn't been any feedback from @saulotoledo @jotamorais @MichalLytek or @rustamwin since you asked on Aug. 16, now over a month ago. Total radio silence from the team. thinking
> 
> I was looking for an issue I saw with `$value` not passing through in the validation and saw [this PR](https://github.com/typestack/class-validator/pull/1467) waiting to be approved since... Dec. 27, 2021. Wow. It actually seems to fix two issues: #1046 and #921

Hi everyone,

I apologize for the long hiatus and would like to provide two main justifications - temporary relocation (country) and being really busy at work.
I will spare a few minutes everyday to go through the PRs. It will help immensely if the community could point out the most pressing issues with PRs available and then we can consolidate those into a `next` release. How does that sound?

Beyond the PRs, we will also need help with issue triage (labeling, closing, etc) and also answering questions, providing guidance and having discussions to steer the project's future.

I do not have enough privileges to add more contributors to the project (would love to), but I can try and help on things that we already a solution in place or have clear direction on what to do.

Similar: [#1272](https://github.com/typestack/class-transformer/issues/1272)

**Comment by tciuro** [comment]
Good to hear from you, @jotamorais!

That sounds great. As you mentioned, I'd start with the PRs and slowly clean the queue. Is there a way to vote and rank issues on GitHub? Some companies have a system where users can vote and help prioritize the issues. Not sure how we could proceed.

**Comment by braaar** [comment]
Us regular folks are not able to set labels on other people's issues, so the best we can do it to vote with thumbs up reactions, or perhaps create some issues where we list PRs that are good to be merged and the issues they will close.

I think if we coordinate a bit (in this issue, I guess?) we can make issues each with their own "theme" so to speak. 
Some examples:
- Documentation PRs
- PRs that directly implement new validators from validator.js.
- Bugfixes and tweaks. 

We could leave the more difficult stuff for last - in depth refactoring and new features and such. 

I think I will try to make an issue like this for new validators.

**Comment by braaar** [comment]
I made an epic that tracks feature PRs for new validators #1747

**Comment by braaar** [comment]
> Ah! Got it.
> 
> Do you know if it's being discussed to fork the project and continue development?

I don't like to bring up the F word unless the situation is truly dire. I think we should push through and do as much as we can to reduce the workload for the maintainers. Ultimately that is less work than forking and attempting to salvage the community, in my opinion.

**Comment by jotamorais** [comment]
> > Ah! Got it.
> > Do you know if it's being discussed to fork the project and continue development?
> 
> I don't like to bring up the F word unless the situation is truly dire. I think we should push through and do as much as we can to reduce the workload for the maintainers. Ultimately that is less work than forking and attempting to salvage the community, in my opinion.

@braaar  Thanks for putting  #1747 together. I'm reviewing and testing. 
Should anyone find any other PR/issue to include, please, add a reference in that epic.

**Comment by saulotoledo** [comment]
It is great to see some movement here. I apologize for the delayed answer as well. It has been a difficult moment.
Like you, I tried to contribute some time ago. At the time, @NoNameProvided was doing a very nice refactoring, but I could not follow all the work due to work and life changes. I am a bit outdated with the project directions, and I would need to talk with the other developers before contributing. But I am glad that @jotamorais could answer you, so you are in good hands.
I also do not have permission to manage the repository. The last person I know that had such permissions was @NoNameProvided, and it has been a while since our last conversations (@jotamorais, have you had recent contact with him?)
Right now it will be very difficult for me to be active in the reviews, but I can try to help when possible. This project is very important for people using NodeJS and I would like to do the possible to help keep it active.

**Comment by braaar** [comment]
I made an overview issue for bugfixes similar to the one I make for simple features:
https://github.com/typestack/class-validator/issues/1751

Some of these fixes are one liners and should be possible to review and merge right away.

**Comment by ytetsuro** [comment]
> Is there a way to vote and rank issues on GitHub?

[I known solution is this.](https://github.com/isaacs/github/issues/1782)

**Comment by braaar** [comment]
Today I learned that NestJS have made a fork of this project. It's very inactive, though, so it doesn't look like it's going to outgrow this project any time soon. NestJS has not fully dropped this package yet, but they seem to be planning to do so in a major release. Ideally we should get things back up and running before that happens if we want to maintain interest in this project.

@jotamorais @saulotoledo, do you guys have any means of reaching @NoNameProvided? I think it's quite necessary to ask him to hand out some write permissions so that others can carry the torch.

**Comment by jotamorais** [comment]
> Today I learned that NestJS have made a fork of this project. It's very inactive, though, so it doesn't look like it's going to outgrow this project any time soon. NestJS has not fully dropped this package yet, but they seem to be planning to do so in a major release. Ideally we should get things back up and running before that happens if we want to maintain interest in this project.
> 
> @jotamorais @saulotoledo, do you guys have any means of reaching @NoNameProvided? I think it's quite necessary to ask him to hand out some write permissions so that others can carry the torch.

I contacted via the internal Github project permission page but I still haven't heard since. I have no other mean to connect or contact.

**Comment by braaar** [comment]
Ok, hopefully we can get some more maintainers with write access on board soon. 

It's only a matter of time before NestJS switches over to using their fork, which could quickly become a TypeGraphQL situation. For those not familiar with the situation, NestJS basically forked [TypeGraphQL](https://github.com/MichalLytek/type-graphql) and turned it into their own [NestJS/graphql](https://github.com/nestjs/graphql), which was a huge suckerpunch to the original project. NestJS is a big avenue for introducing people to this project, and if they cut us loose we will be left with a lot fewer contributions and will eventually be considered obsolete (many feel that way already, but I don't think it's too late).

**Comment by rustamwin** [comment]
> I contacted via the internal Github project permission page but I still haven't heard since. I have no other mean to connect or contact.

Try on twitter `NoNameProvided_`

**Comment by saulotoledo** [comment]
@rustamwin Actually we received some news from @NoNameProvided during the weekend already. He will paste news here soon.

**Comment by NoNameProvided** [comment]
Hi all! 

I have opened an issue with some explanation and future plans here: https://github.com/typestack/class-validator/issues/1775. I will leave this discussion open for now, but please continue the discussion there.

**Comment by NoNameProvided** [comment]
> Today I learned that NestJS have made a fork of this project.

@braaar can you link it for me here please? I may contact folks over there to discuss future plans.

**Comment by braaar** [comment]
> > Today I learned that NestJS have made a fork of this project.
> 
> @braaar can you link it for me here please? I may contact folks over there to discuss future plans.

[Here it is](https://github.com/nestjs/class-validator).

Here you can see that they aren't using it yet:
https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/package.json#L60-L78

It's [published on NPM](https://www.npmjs.com/package/@nestjs/class-validator/), though

**Comment by braaar** [comment]
We now have 100 fewer open issues than when I created this issue! 🎉 
The progress is coming along nicely. For anyone interested in getting involved with triage work, reach out!

I think this issue can be safely closed now that activity has resumed. See #1775 if you are interested in more "meta"-discussion like this.
