### ISSUE TITLE
host_whitelist and host_blacklist should be arrays of hosts (string)

### ISSUE THREAD

**Issue by RDeluxe** [typestack/class-validator#172]
https://github.com/typestack/class-validator/blob/1db8505cc7b790140ddd5314dcc7b5e551d2ec75/src/validation/ValidationTypeOptions.ts#L36

I checked quickly the code [here ](https://github.com/chriso/validator.js/blob/master/src/lib/isURL.js) and it seems to me that host_whitelist and host_blacklist should be arrays of hosts. I don't see how they can be use with the current implementation. Am I missing something ?

**Comment by NoNameProvided** [comment]
Thanks for the heads up, after checking, it seems it must be a boolean `false` or `string[]`.
