### ISSUE TITLE
fix: Grammar in ReadME at @isEnum

### ISSUE THREAD

**Issue by basitanwer** [typestack/class-validator#1724]
### Description
Grammar in ReadME at @isEnum

**Minimal code-snippet showcasing the problem**
@IsEnum(entity: object) | Checks if the value is an valid enum

Should really be

@IsEnum(entity: object) | Checks if the value is **a** valid enum

**Comment by braaar** [comment]
Nice, thanks! Now we wait 😅

**Comment by NoNameProvided** [comment]
Thanks landed in https://github.com/typestack/class-validator/commit/87c0ef39e843714836178a83f5d6eef38519b89b.
