### ISSUE TITLE
question: toClassOnly still expose the name in instanceToPlain

### ISSUE THREAD

**Issue by oldriverno1** [typestack/class-validator#1728]
I have a DTO class and I want some specific key to be covert with different name only in instanceToPlain operation

the dto class:

```js
export class CreateEventDto {
  @Expose({ toClassOnly: true, name: 'type' }) 
  eventTypeId: number;
}
```

I can get it to work in plainToInstance
for example:
```js
const obj = { type: 2 };
console.log(plainToInstance(CreateEventDto, obj));  // log CreateEventDto { eventTypeId: 2 }
```

but if I convert it again using instanceToPlain, the result is showing  { type: 2 } instead of { eventTypeId: 2 }

```js
const obj = { type: 2 };
const dto = plainToInstance(CreateEventDto, obj);
console.log(dto);  // log CreateEventDto { eventTypeId: 2 }
console.log(instanceToPlain(dto)); // log { type: 2 }, but I expect it to be { eventTypeId: 2 }
```

Is there anything I'm doing wrong? or any proper way to this kind of conversion?
Thanks for answering :)

**Comment by braaar** [comment]
This seems like a `class-transformer` issue?

**Comment by oldriverno1** [comment]
@braaar Yup I think I left the question on the wrong repo, thanks for reminding.
