### ISSUE TITLE
question: How to work with epoch

### ISSUE THREAD

**Issue by shawshankkumar** [typestack/class-validator#1729]
Hi, I was trying to create a simple sign up route and I had my usual email, password and name. Now, I am working with epoch timestamp and I need that to be optional. A client may choose to send the createdAt field, if they do, that will be used. Else a default value of +new Date() will be given. Now, I am unable to do that. I was able to create an optional field but how do I validate a epoch time stamp? What's the recommended way? The best I could come up with at the moment was :
 
     @IsEmail()
    email: string;
  
    @Length(5)
    @IsString()
    password: string;

    @Length(2)
    @IsString()
    name: string;

    @IsOptional()
    @Length(13, 13)
    createdAt: number = +new Date;
    
 I have mostly worked with yup and join in Node and have started using class-validator today. So any improvements and other better methods are more than welcome. Cheers!

**Comment by braaar** [comment]
I don't think there is a validator for epoch in `class-validator` or its main validation library validator.js.

If you wish to implement your own validator, you can use `@Validate` and provide a function that takes one argument and returns true or false. 

I'm also not sure if there is a way to sanitize the data during validation. You may have to do that as an extra step before/after validation, perhaps by reading the output of the `validate` function and checking to see if the `createdAt` field is missing. Or you can simply implement this in a serialization method of some kind when you first take in the data, before validating.

**Comment by shawshankkumar** [comment]
Right. Thank you!

**Comment by braaar** [comment]
If you're satisfied, please close the issue, @shawshankkumar. We don't have active maintainers who can close issues right now.

**Comment by shawshankkumar** [comment]
> If you're satisfied, please close the issue, @shawshankkumar. We don't have active maintainers who can close issues right now.

Sure thing.
