### ISSUE TITLE
question: How can get a property validators?

### ISSUE THREAD

**Issue by mib-kamel** [typestack/class-validator#1731]
I am making a library which integrates with class-validator

I need to check if the property has the validator @IsOptional() or not to use the answer in an IF condition?

Is that possible?

**Comment by braaar** [comment]
This should be possible, yes.

Study the code in these folders to learn more: 
- https://github.com/typestack/class-validator/tree/develop/src/validation
- https://github.com/typestack/class-validator/tree/develop/src/metadata

**Comment by NoNameProvided** [comment]
Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
