### ISSUE TITLE
How to validate multiple types

### ISSUE THREAD

**Issue by bosens-China** [typestack/class-validator#1737]
I have a property of regions, he can be string or Array<string>, but I don't know how to write the validator

``` js
 @IsOptional()
  @IsArray()
  @IsString()
  regions: string | Array<string>;
```
pass string
``` js
"regions must be an array"
```

**Comment by martin-yin** [comment]
If the decorator provided does not meet your needs, you can use a custom decorator  

https://github.com/typestack/class-validator#custom-validation-decorators

![1663213426809](https://user-images.githubusercontent.com/19162008/190309054-68c45323-8add-4b99-be64-8e793340ee4b.png)
