### ISSUE TITLE
fix: add type for locale in `@IsAlphanumeric` and `@IsAlpha` decorators

### ISSUE THREAD

**Issue by ufec** [typestack/class-validator#1739]
### Description
As the title says, the first parameter of `IsAlphanumeric` and `IsAlpha` decorator does not have correct prompt.

When I use the above two decorators, I need to customize the error prompt information, but I must fill in the first parameter, but the first parameter does not give me a correct value prompt. I need to find a suitable value range under the validator library according to the error prompt, which is a waste of time.

The validator library provides the type of the correct value range of the first parameter of the two decorators by default

**Comment by NoNameProvided** [comment]
Landed in https://github.com/typestack/class-validator/commit/5b0b9626eb56516041cb4892b55b304464faebe5 and https://github.com/typestack/class-validator/commit/72d1eedfa01e2ff009864c7ce4234b613545fb70.

**Comment by NoNameProvided** [comment]
I am closing issues only after a change is released. I will close this for you after release. Thanks.

**Comment by NoNameProvided** [comment]
This feature/fix has been released in `0.14.0`.
