### ISSUE TITLE
epic: implement validators from validator.js

### ISSUE THREAD

**Issue by braaar** [typestack/class-validator#1747]
### Description
The goal of this issue is to have an overview over presumably uncontroversial feature PRs that implement new validation decorators for validators from the upstream library [validator.js](https://github.com/validatorjs/validator.js)

### Proposed solution
Review and merge the open PRs that implement such validators

**Ready for maintainer review**
- https://github.com/typestack/class-validator/pull/1550

**Need some work still**
- https://github.com/typestack/class-validator/pull/1115
- https://github.com/typestack/class-validator/pull/1626
- https://github.com/typestack/class-validator/pull/1735/

**List of new-ish features in validator.js that don't have a PR yet**
- https://github.com/typestack/class-validator/issues/1497
- https://github.com/typestack/class-validator/issues/1013

(comment if you know any!)
I'll try to look through issues to see if I can spot some.

@jotamorais

**Comment by braaar** [comment]
Here's another feature PR that seems ready for review:
- https://github.com/typestack/class-validator/pull/1765

**Comment by Kinggodhoon** [comment]
Has the project been suspended?

**Comment by braaar** [comment]
> Has the project been suspended?

There has been no word from @NoNameProvided in a while, but we have heard from @jotamorais and @saulotoledo last month, who are members of Typestack. See #1719

**Comment by Kinggodhoon** [comment]
thank you!

**Comment by NoNameProvided** [comment]
Just to chime in, it's not a project goal to implement every single validator from validator.js, so please open an issue before adding an implementation.

**Comment by braaar** [comment]
I think this issue has outlived its usefulness by now
