### ISSUE TITLE
feature: decorator like ValidateIf but it should validate

### ISSUE THREAD

**Issue by fake364** [typestack/class-validator#1750]
### Description

when I found out about ValidateIf , I thought that this decorator validates field by function that returns Boolean result. So actually when this function returns false, validate dto function recognizes that this field has error. But ValidateIf just enables validation of other decorators if it's function returns true. It looked obvious to me, that this kind of validation decorator should haave existed but I couldn't find one. It would be useful to have flexibility in validation, but not using existing hard limited set of specific decorators and I don't want to specify millions of custom ones
### Proposed solution

@ValidateBy((value)=>value.reverse(). includes('hello')) // just example
Function that we pass in decorator receives all arguments that ValidateIf does and should return Boolean result , and field has error if this function returns false

**Comment by braaar** [comment]
This exists, and it's called `@Validate`

Example 

```ts
// Kyle is not a valid name
@Validate(o => o.name !== 'Kyle')
name: string; 
```


Edit: this is wrong usage of the `Validate` decorator, ignore this comment

**Comment by fake364** [comment]
@braaar Thanks for reply but unfortunately https://codesandbox.io/s/pedantic-wave-8b5tb7?file=/src/index.ts it's still empty

**Comment by braaar** [comment]
I can only apologise for my misleading explanation. You need to put your validation function in a class implementing the ValidatorConstraintInterface, like this:

```ts
@ValidatorConstraint({ name: 'customText', async: false })
export class CustomTextLength implements ValidatorConstraintInterface {
  validate(text: string, args: ValidationArguments) {
    return text.length > 1 && text.length < 10; // for async validations you must return a Promise<boolean> here
  }

  defaultMessage(args: ValidationArguments) {
    // here you can provide default error message if validation failed
    return 'Text ($value) is too short or too long!';
  }
}
```

I suppose it would be possible to make a new version of this that accepts a simple function returning a boolean.

**Comment by fake364** [comment]
@braaar thanks!

**Comment by braaar** [comment]
> @braaar thanks!

Could you close this issue?
