### ISSUE TITLE
feat: create documentation website

### ISSUE THREAD

**Issue by RSS1102** [typestack/class-validator#1753]
### Description

`READ. ME` The me is too difficult to read, and it is difficult for maintainers to track and change problems in time.
### Proposed solution

I think each module can be maintained in multiple`. md` files. Then the document website is automatically generated by ci operation `. md ` file.There are many, many mature libraries that can be operated in this way, such as: [vitepress ](https://github.com/vuejs/vitepress ) . (There may be better tools).

---

I see that great defenders seem to be experiencing some problems in life, so this is just my suggestion and hope. (By the way, if you need me to do this work, you can remind me that I will try it [although I have not actually performed the actual code operation in this area])

**Comment by braaar** [comment]
I think this is a nice idea. The TypeStack org has a [documentation website for TypeDI](https://docs.typestack.community/typedi/) using [GitBook](https://www.gitbook.com/). Is that worth a look? 

[Here is the source](https://github.com/typestack/typedi/tree/develop/docs) for that website. Seems simple enough to me

**Comment by RSS1102** [comment]
> 

yeah,this's look like good.same as my think(Although the style is not so beautiful i think).

**Comment by braaar** [comment]
This is already a part of the roadmap, I realise #178
