### ISSUE TITLE
fix: IsNumber and Max

### ISSUE THREAD

**Issue by MufidJamaluddin** [typestack/class-validator#1768]
### Description

Validation code:

```ts
    @IsNumber({ allowNaN: false, allowInfinity: false })
    @Min(0)
    @Max(Number.MAX_SAFE_INTEGER, {
       message: 'promoAmount must be a valid number'
    })
    promoAmount: number;
```

### Expected behavior

If we send `promoAmount` attribute with `200.00` as it value, no error message happened.

### Actual behavior

The error message was `promoAmount must be a valid number`, but `200.00` < `Number.MAX_SAFE_INTEGER` which is 9007199254740991.

**Comment by NoNameProvided** [comment]
Cannot reproduce. The `200.00` value is accepted as expected:

```ts
import { IsNumber, Max, Min, validate } from 'class-validator';

class MyPayload {
  @IsNumber({ allowNaN: false, allowInfinity: false })
  @Min(0)
  @Max(Number.MAX_SAFE_INTEGER, {
      message: 'promoAmount must be a valid number'
  })
  promoAmount: number;

  constructor(promoAmount: number) {
    this.promoAmount = promoAmount;
  }
}

const test = new MyPayload(200.00);

validate(test).then(console.log); // returns empty array as expected

```

It is worth noting that using `@Max(Number.MAX_SAFE_INTEGER)` makes no sense as NodeJS cannot represent numbers greater than `Number.MAX_SAFE_INTEGER`. This means you will never encounter a value that is greater than that.
