### ISSUE TITLE
Target: es5 but ansicolor is not compatible with IE11

### ISSUE THREAD

**Issue by baxevanis** [typestack/class-validator#180]
Hi all
It seems that when we try to use the latest version of class validator it does not work with IE11.

I can see that the target for class-validator is set to es5 which IE11 is happy about, but as ansicolor is a dependency to the latest version, IE11 complains about this

https://github.com/xpl/ansicolor/blob/master/ansicolor.js#L40

We are using 0.8.1 version where this dependency was not there but with the latest one it breaks :/

For any additional info plz let me know!

Thank you

**Comment by NoNameProvided** [comment]
Hey, thanks for a report! I will fix this ASAP, but as a Mac user I don't have easy access to an IE11, but I will borrow a WIN tomorrow at work to fix this.

**Comment by NoNameProvided** [comment]
@baxevanis What error do you get exactly? And how do you build exactly?

**Comment by NoNameProvided** [comment]
Please try with `0.8.5`, let me know if it's still failing.
