### ISSUE TITLE
fix: Issue with package size (comparing v0.12.2 and v0.13.2)

### ISSUE THREAD

**Issue by ahmad-opensesame** [typestack/class-validator#1803]
### Description
I was using the latest version 0.13.2 on a serverless project (packed using webpack)
The package size was exceeding 8Mb and after checking the packed file I found that it includes "libphonenumber-js" as the larger dependency, noting that I am not using "IsPhoneNumber" decorator inside my code.

### Expected behavior
I should not see the module "libphonenumber-js" inside my packages

### Workaround
After looking for the issue, I found that an earlier pull request was resolving this issue by adding "google-libphonenumber-js" which have less packed size, and there was a workaround to exclude it also. 

I had to downgrade the class-validator module to v0.12.2 to reduce my package size. The sized decreased by around 2.5Mb, which is a huge difference.

Is there anyone else facing this issue? Is there a workaround for version 0.13.2 ?

References:
Fixed version (using google-libphonenumber): https://github.com/typestack/class-validator/blob/v0.12.2/src/decorator/string/IsPhoneNumber.ts
Missing PR changes: https://github.com/typestack/class-validator/pull/568 from @vlapo

**Comment by NoNameProvided** [comment]
The library is written in a three-shakable way. You should be able to bundle your code during the build phase and if you don't use the phone validator it will be omitted from the final build. 

I have plans to move decorators into their own sub-packages, so you install what you need, but that is a significant effort so you should not wait for that to happen.
