### ISSUE TITLE
fix: Determining `inheritedMetadatas` during jest+ts-jest tests collects metadatas that do not belong to the target

### ISSUE THREAD

**Issue by sdokara** [typestack/class-validator#1810]
### Description
This is a very edge-casey situation that I ran into. 

I have a web service project in typescript@4.9.3 on Node 16 with typeorm@0.2.32 classes being decorated. Everything runs perfectly in normal mode: `tsc` transpiles stuff and `node` runs it without issues. The validator collects the metadata properly.
But, when running tests with `jest` that uses `ts-jest` as the transformer (with default configuration), the transpiled output acts kinda weird.

For all decorated classes, in `src/metadata/MetadataStorage.ts:109`, when computing `inheritedMetadatas`, there's an `if`:
```ts
if (metadata.target instanceof Function && !(targetConstructor.prototype instanceof metadata.target))
    return false;
```
Now, during tests, `metadata.target instanceof Function` yields `false` even though it **is** the class **and** `typeof metadata.target` does indeed yield `'function'`. I have no idea how this is happening. I'm able to monkey-patch it by using `typeof`.

This used to work with older versions of my dependencies, but I wasn't able to pinpoint the culprit.

**Comment by mzpeartx** [comment]
I am seeing a similar behavior. My current workaround was to downgrade to version `0.11.1`.

**Comment by NoNameProvided** [comment]
I would guess this is due to a difference in how ts-jest compiles the code and you probably need to add some options to your test config. 

I have some faded memories of someone having a similar issue quite some time ago, but there the problem was a change in babel transform that strips the metadata. Maybe you are affected by the same problem?

**Comment by mzpeartx** [comment]
@NoNameProvided That makes sense. I'll have to do a little digging, thanks for the suggestion!

**Comment by NoNameProvided** [comment]
Closing this as invalid. I cannot provide support with general programming-related questions. 

I hope you will find the bug.
