### ISSUE TITLE
question: get transformed JS object from ValidationMetadata

### ISSUE THREAD

**Issue by zelid** [typestack/class-validator#183]
How to access decorated class metadata and use it to build a custom JS object?

There is a simple class with validation decorators:
```ts
export class LoginInput {
  @IsEmail() email: string = ''

  @Length(5, 20)
  password: string = ''
}
```

How to access it's ValidationMetadata and use it to produce plain JS object?
For example:
```ts
{
  email: [
    {
      required: true,
      message: 'Please provide a valid email.',
      trigger: 'blur',
    },
  ],
  password: [
    {
      required: true,
      message: 'Please fill in the password.',
      trigger: 'blur',
    },
    {
      type: 'string',
      min: 5,
      message: 'The password length cannot be less than 5 bits',
      trigger: 'blur',
    },
    {
      type: 'string',
      max: 20,
      message: 'The password length cannot exceed 20 bits',
      trigger: 'blur',
    },
  ],
}
```

The goal is to use well-shaped class-validator rules in external UI plugin that expects validation descriptor in a custom format (UI framework already has validation tightly coupled with it's components) while being able to use class-validator on LoginInput in all other places (validation on submit and validation on the server)

**Comment by NoNameProvided** [comment]
There is no documented way of doing this, but you can get the used metadata storage via 

```ts
import { MetadataStorage, getFromContainer } from "class-validator";

getFromContainer(MetadataStorage)
```

It will return an object and you will be intersted in the `validationMetadatas` property what holds an array of all registerd constraints against your classes. It looks something like this:

```ts
[
  {
    "type": "isEmail",
    "propertyName": "email",
    "constraints": [
      null
    ],
    "message": "Please provide a valid email."
  },
  {
    "type": "maxLength",
    "propertyName": "password",
    "constraints": [
      20
    ],
    "message": "Password must be shorted or equal to $constraint1 character."
  },
  {
    "type": "minLength",
    "propertyName": "password",
    "constraints": [
      5
    ],
    "message": "Password must be longer than $constraint1 character."
  }
]
```

The `required` key can be computed from checking if the property has a `IsOptional` decorator assigned or not. 

I hope this answer your question. I will go ahead and close this issue but feel free to continue the discussion here if something is not clear.
