### ISSUE TITLE
fix: `@IsEmail()` accepting `!@gmail.com` and `#@gmail.com`

### ISSUE THREAD

**Issue by reddyakanksha98** [typestack/class-validator#1839]
### Description
If I'm passing an email with only exclamation or with hash, it's still accepting the value, and not throwing any error.

```ts
@ApiProperty({
  description: 'User email',
  example: 'akanksha@gmail.com',
})
@IsDefined()
@IsNotEmpty()
@IsEmail()
email: string;
  
{ "email": "!@gmail.com" }
```

### Expected behavior
It should not accept the above email, as it doesn't have any alphanumeric characters, and it's not checking the min length of an email also.

### Actual behavior
It's accepting the values without throwing any error.

And if possible, please share what's the allowed characters of this @IsEmail( ) decorator.

**Comment by NoNameProvided** [comment]
The email validation comes from the `validator` upstream library. You need to open this issue in [their repository](https://github.com/validatorjs/validator.js).

**Comment by reddyakanksha98** [comment]
Hello there, thanks for the reply. Could you share what are the options we have in @IsEmail( ) decorator, and what are the allowed characters for this, like alpha-numeric, and special symbols.. if possible?

_@IsEmail(options?: IsEmail Options)_
