### ISSUE TITLE
Is there a way to get the lowest level constraints messages without building an iterator to get there?

### ISSUE THREAD

**Issue by dicgf8** [typestack/class-validator#185]
I have ValidateNested and just need the message from the constraint that caused the issue.

Current Code:
```javascript
function retrieveValidationErrorMessage(err: ValidationError): string {
	if (err.children && err.children.length > 0) {
		return retrieveValidationErrorMessage(err.children[0]);
	} else {
		return Object.keys(err.constraints).map(key => err.constraints[key])[0];
	}
}
```

**Comment by NoNameProvided** [comment]
You need to traverse down at the moment, but this part will be reworked in the future.

**Comment by alexqbm** [comment]
Still waiting for that future to come. Any hints on when will this be ready?

**Comment by peresbruno** [comment]
Any news about this?

**Comment by NoNameProvided** [comment]
Features in open-source project are like wizards: They are never late, nor they are early, they arrive precisely when they mean to.

Serious part: There is a lot of refactoring and this is a breaking change. First, those parts will be refactored which didn't break the API, and breaking changes will be grouped together.

**Comment by NoNameProvided** [comment]
Closing this for now, but this is on my radar.
