### ISSUE TITLE
Custom validation in validation schema(no using decorator)

### ISSUE THREAD

**Issue by Alessia958** [typestack/class-validator#186]
Hi,
I've just started using this beautiful library and I was wondering if there was a way to have a custom validation without the use of decorators. 
I found an example online and applying it to my use case I do not understand what is not going on and whyit is not working, this is my code:
**MyValidationSchema.ts**
```typescript
import { ValidationSchema } from 'class-validator';

export const MyValidationSchema: ValidationSchema = {
    name: 'myValidationSchema', // must be unique
    properties: {
        title: [{
            type: 'isString',
            constraints: [],
            options: {},
            groups: ['myValidationSchema']
        },
        {
            type: 'isDefined',
            constraints: [],
            options: {},
            groups: ['myValidationSchema']
        }],
        description: [{
            type: 'isString',
            constraints: [],
            options: {},
            groups: ['myValidationSchema']
        },
        {
            type: 'isDefined',
            constraints: [],
            options: {},
            groups: ['myValidationSchema']
        }],
        color:[  { type: 'conditionalValidation', constraints: [(object: any, value: any) => {
                return object['color'] !== null && object['color'] !== undefined && object['color'] === 'green'  && object['color'] === 'red';
            }],  groups: ['myValidationSchema'], options: undefined },
      { type: 'isBoolean', constraints: [], options: undefined }]
    }
};
```
I want to limit the values ​​of the color field and make it required.
I'using groups because I have more than one schema registered

**Comment by skrosoft** [comment]
Si someone could deals with this issue?

**Comment by braaar** [comment]
Schema based validation is being deprecated, so this will not be fixed.

**Comment by NoNameProvided** [comment]
If you want to use a JSON schema-based validation, I suggest using one of the libraries working exclusively with JSON schemas like [colinhacks/zod](https://github.com/colinhacks/zod) or [hapijs/joi](https://github.com/hapijs/joi).
