### ISSUE TITLE
fix: Module '"class-validator"' has no exported member 'IsStrongPassword'

### ISSUE THREAD

**Issue by fgcoelho** [typestack/class-validator#1874]
### Description
class-validator does not provide IsStrongPassword, although is listed on GitHub

**Minimal code-snippet showcasing the problem**
```js
import { ApiProperty } from "@nestjs/swagger"

//Validator 
import { IsEmail,  IsString, MinLength, IsStrongPassword } from "class-validator"


export class CreateUserDto {
    @ApiProperty()
    @IsString()
    @MinLength(3, { message: 'O usuário precisa ter mais de 3 caracteres' })
    name: string

    @ApiProperty()
    @IsString()
    @IsEmail({}, { message: 'O email fornecido é inválido' })
    email: string

    @ApiProperty()
    @IsString()
    @MinLength(8, { message: 'A senha precisa ter mais de 8 caracteres' })
    password: string
}
```

### Expected behavior
IsStrongPassword should be a class-validator exported member, as described on GitHub

### Actual behavior
class-validator does not provide IsStrongPassword, although is listed on GitHub

**Comment by Fgc17** [comment]
Just found out that this was added last month,  neither `npm install` and `npm update` worked,  so I had to add manually by finding it here on Github and pasting into my `node_modules`

**Comment by Fgc17** [comment]
Just found out that this was added last month, neither npm install and npm update worked, so I had to do this:

1. create the file `node_modules/class-validator/types/decorator/string/IsStrongPassword.d.ts`
2. paste the contents of `IsStrongPassowrd` provided here on Github inside `IsStrongPassword.d.ts`
3. Add the line `export * from './string/IsStrongPassword'` in 
`node_modules/class-validator/types/decorator/decorators.d.ts`

**Comment by bijela-gora** [comment]
@Fgc17 but it does!

![image](https://user-images.githubusercontent.com/102924398/211767978-be978e2c-856b-46bb-8f97-072c494e591a.png)

**Comment by braaar** [comment]
This works in version 0.14 at least:

```ts
import {
  IsEmail,
  IsString,
  MinLength,
  IsStrongPassword,
  validate,
} from "class-validator";

export class CreateUserDto {
  @IsString()
  @MinLength(3, { message: "O usuário precisa ter mais de 3 caracteres" })
  name: string;

  @IsString()
  @IsEmail({}, { message: "O email fornecido é inválido" })
  email: string;

  @IsString()
  @IsStrongPassword()
  @MinLength(8, { message: "A senha precisa ter mais de 8 caracteres" })
  password: string;
}

const plain = { name: "hallo", email: "test@example.com", password: "hunter2" };

const instance = new CreateUserDto();
instance.name = "John";
instance.email = "test@example.com";
instance.password = "hunter2";

const errors = await validate(instance);

console.log(errors);
```

Result:
```
[
  ValidationError {
    target: CreateUserDto {
      name: 'John',
      email: 'test@example.com',
      password: 'hunter2'
    },
    value: 'hunter2',
    property: 'password',
    children: [],
    constraints: {
      minLength: 'A senha precisa ter mais de 8 caracteres',
      isStrongPassword: 'password is not strong enough'
    }
  }
]
```

If you are still having trouble, please provide more details so we can reproduce the issue.
