### ISSUE TITLE
fix: custom object construction in plainToInstance

### ISSUE THREAD

**Issue by jasperverbeet** [typestack/class-validator#1882]
### Description
There is an issue when using `plainToInstance` with objects that do not support being constructed using `new (targetType as any)()` and already have the correct type. This results in an error being thrown when trying to transform the object.

**Minimal code-snippet showcasing the problem**
```ts
import { BigNumber } from 'ethers'

class FailingTransform {
  test: BigNumber
}

plainToInstance(FailingTransform, {
  // BigNumber does not use a regular constructor
  test: BigNumber.from(1),
})
```

See: https://docs.ethers.org/v5/api/utils/bignumber/#BigNumber--creating

### Expected behavior
The object should be correctly transformed using a custom method for constructing the object, such as `.from`, or call the transformation decorators when performing a `CLASS_TO_CLASS` transformation.

The error occurs at [TransformOperationExecutor.ts#L160](https://github.com/typestack/class-transformer/blob/develop/src/TransformOperationExecutor.ts#L160).

### Actual behavior
The transformation fails due to the use of `new (targetType as any)()`, which is not supported by the object.

Note: This issue only occurs if the object being transformed is already of the correct type. If the object is not already of the correct type, the transformation will proceed as expected.

**Comment by bijela-gora** [comment]
@jasperverbeet hi!

How this issue related to `class-validator`?

**Comment by braaar** [comment]
This is a class-transformer issue. Setting up a `@Transform` function that handles each possible case correctly should also solve your problem.
