### ISSUE TITLE
defaultMessage in ValidatorConstraintInterface fails to return err.message

### ISSUE THREAD

**Issue by lewibs** [typestack/class-validator#1896]
### Description
For some reason I am having an issue where the default message does not work when using err.message from a thrown Error. However, when using a string nothing changes. I have console logged all the outputs right before and it seems near identical. Both are strings.

**Minimal code-snippet showcasing the problem**
source code can be found at: https://github.com/lewibs/ducktyper/blob/2b0164405360beffb54af3932ed6b523bf713cae/test/src/functions/duckorate.test.ts
```ts
    @ValidatorConstraint({ name: 'customText', async: false })
    class DuckValidation implements ValidatorConstraintInterface {
      validate(val:any, args: ValidationArguments) {
        return false;
        return duck(val, {
            ...options,
            throw: false,
        });
      }
    
      defaultMessage(args: ValidationArguments) {
        let err = ISDUCK_OPTIONS.message;
        try {
            duck(undefined, {
                allowUndefined: false,
                throw: true,
            });
        } catch (error) {
            err = error.message;
        }
        console.log(err)
        return err; //this value seems to be incorrectly altered later in the code
        return "error"; //this value works as intended
        //in both cases it is a string
      }
    }
```

### Expected behavior
see comments. The first should return the string that is logged. However it does not. The second return correctly creates a validation error with the string "error"

### Actual behavior
expect(received).toBe(expected) // Object.is equality
Expected: "Not a string"
Received: "Not A Duck: Input failed to follow specifications"

from:
console.warn
    Not a string

      83 |             err = error.message;
      84 |         }
    > 85 |         console.warn(err);
         |                 ^
      86 |         return err;
      87 |       }
      88 |     }

**Comment by braaar** [comment]
Could you post an easily runnable complete reproduction without external dependencies? I would prefer not to have to stitch together your code from multiple files.

**Comment by lewibs** [comment]
I looked into it a bit more. I no longer think the issue is coming from this library. It was from an odd nuance that came from both this library and the other that I was using that caused the issue.
