### ISSUE TITLE
validate throw a TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by rmeja** [typestack/class-validator#1901]
### Description
After upgrading class-validator to version 0.14, I got the following error message when running my unit tests: 

`TypeError: Right-hand side of 'instanceof' is not an object`

After searching, it turns out that the problem comes from this piece of code in `src/metadata/MetadataStorage.ts`:

![image](https://user-images.githubusercontent.com/10611767/212371798-80bd2687-bed0-42b7-a823-1fe3bc573370.png)

### Expected behavior
No TypeError at runtime

### Actual behavior
The `validate` function throw a `TypeError: Right-hand side of 'instanceof' is not an object`

**Comment by braaar** [comment]
Could you provide a runnable reproduction of this?

**Comment by rmeja** [comment]
Of course. Sorry for not doing it sooner
```ts
import {
  validate,
  Length,
  registerSchema,
} from 'class-validator';

export class Post {
  @Length(10, 20)
  title: string;
}

const brandSchema = {
  name: 'brand',
  properties: {
    "title": [{
      "type": "minLength",
      "constraints": [10]
    },
    {
      "type": "maxLength",
      "constraints": [20]
    }],
  }
}

registerSchema(brandSchema);

let post = new Post();
post.title = 'Hello';

validate(post).then(errors => {
  if (errors.length > 0) {
    console.log('validation failed. errors: ', errors);
  } else {
    console.log('validation succeed');
  }
});
```

**Comment by braaar** [comment]
Schema-based validation has been dropped from this project, I'm afraid. This won't get fixed.
