### ISSUE TITLE
fix: forbidUnknownValues doesn't default to true when validatorOptions are undefined

### ISSUE THREAD

**Issue by cduff** [typestack/class-validator#1906]
### Description
0.14.0 is supposed to make `forbidUnknownValues` default to `true`. However, it only defaults to `true` when a `validatorOptions` object is passed.

**Minimal code-snippet showcasing the problem**
```ts
await validateOrReject({}); // resolves
await validateOrReject({}, {}); // rejects
```

### Expected behavior
`forbidUnknownValues` should default to `true` unless explicitly specified as `false`.

### Actual behavior
`forbidUnknownValues` continues to default to `false` when no `validatorOptions` object is specified.

**Comment by braaar** [comment]
Could you provide a reproduction of this?

**Comment by cduff** [comment]
> Could you provide a reproduction of this?

@braaar I just created a CodeSandbox reproduction https://codesandbox.io/p/sandbox/class-validator-forbidunknownvalues-issue-p3zfyy

It just runs the following code:

``` js
const { validateSync } = require("class-validator");
console.log(validateSync({}));
console.log(validateSync({}, {}));
```

The current output is:

```
[]
[
  ValidationError {
    target: {},
    value: undefined,
    property: undefined,
    children: [],
    constraints: {
      unknownValue: 'an unknown value was passed to the validate function'
    }
  }
]
```

This is unexpected as both `validateSync` calls should result in a `ValidationError`.

**Comment by braaar** [comment]
Curious. I need to look further into this.

**Comment by cduff** [comment]
> Curious. I need to look further into this.

@braaar just from a quick look, is the problem on this line?

https://github.com/typestack/class-validator/blob/5f0d424c164672ec981e24d6e634354803abf25f/src/validation/ValidationExecutor.ts#L70

It shouldn't require `this.validatorOptions` to be truthy?

**Comment by muzichen** [comment]
I have encountered the same problem, since the default value of forbidUnknownValues is false, if the validatorOptions is passed some value, the forbidUnknownValues value will be changed to true.

**Comment by braaar** [comment]
> > Curious. I need to look further into this.
> 
> @braaar just from a quick look, is the problem on this line?
> 
> https://github.com/typestack/class-validator/blob/5f0d424c164672ec981e24d6e634354803abf25f/src/validation/ValidationExecutor.ts#L70
> 
> It shouldn't require `this.validatorOptions` to be truthy?

I think you're onto something. Do you want to make a test that confirms your hypothesis and submit a PR?

**Comment by cduff** [comment]
> > > Curious. I need to look further into this.
> > 
> > 
> > @braaar just from a quick look, is the problem on this line?
> > https://github.com/typestack/class-validator/blob/5f0d424c164672ec981e24d6e634354803abf25f/src/validation/ValidationExecutor.ts#L70
> > 
> > It shouldn't require `this.validatorOptions` to be truthy?
> 
> I think you're onto something. Do you want to make a test that confirms your hypothesis and submit a PR?

@braaar I have submitted a PR for this: https://github.com/typestack/class-validator/pull/2196
