### ISSUE TITLE
fix: s/TransformClassToPlain/TransformInstanceToPlain in readme

### ISSUE THREAD

**Issue by sqwishy** [typestack/class-validator#1913]
I was trying to read the documentation for this library (just the readme as far as I can tell) and it mentions `TransformClassToPlain`, but that doesn't appear to be defined anywhere.

It looks like it was renamed to TransformInstanceToPlain in 01db22254fd3c2ae03279c567d27312afa2ad14f.

The documentation should probably be updated.

**Comment by braaar** [comment]
This issue belongs in [class-transformer](https://github.com/typestack/class-transformer#plaintoclass)
