### ISSUE TITLE
Is there a way to validate multiple keys using a single decorator?

### ISSUE THREAD

**Issue by juanGoesElectric** [typestack/class-validator#1952]
**I was trying to...**

I have the following class:
```
class ValidDayHour implements MappedDays {
  monday: string;
  tuesday: string;
  wednesday: string;
  thursday: string;
  friday: string;
  saturday: string;
  sunday: string;
}
```

Whose values are string **hours** in the following format: `HH:ss`. Example: **08:30**
Each one of these values should have the following decorators:
```
@IsString()
@IsNotEmpty()
@Matches(/^([01]\d|2[0-3]):?([0-5]\d)$/)
```

**The problem:**

Can I somehow validate all the keys in `ValidDayHour` using a single set of those 3 decorators? Or maybe encapsulating them into one? I'd be interested in avoiding copying/pasting the decorators for each day.

**Comment by braaar** [comment]
I don't believe that is possible. You could place all of these in an array or an object and use a [custom validator](https://github.com/typestack/class-validator#custom-validation-decorators) to validate that array or object, leveraging `isString()`, `isNotEmpty()` and `matches()` from the internal API.

**Comment by juanGoesElectric** [comment]
Thanks @braaar , that's exactly what I ended up doing.
Something like this, for reference: 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/114180888/220672912-fbbd68b2-1b5b-4a17-abf4-3d37fb040f87.png">
