### ISSUE TITLE
ValidateNested and Type

### ISSUE THREAD

**Issue by keenondrums** [typestack/class-validator#198]
Currently to make ValidateNested work with array we have to manually apply Type decorator from class-transformer. Can't we change ValidateNested's signatures, so if someone passes a type function in it (() => YourType) it automatically applies Type decorator?

In other words this
```ts
class MySubClass {
  @IsNotEmpty()
  name: string
}
class MyClass {
  @ValidateNested()
  @Type(() => MySubClass)
  names: MySubClass[]
}
```
becomes this
```ts
class MySubClass {
  @IsNotEmpty()
  name: string
}
class MyClass {
  @ValidateNested(() => MySubClass)
  names: MySubClass[]
}
```

**Comment by MistyKuu** [comment]
This is what I did in the project:

```
export const ValidateNestedEx = (typeFunction?: (type?: TypeOptions) => Function) => {
  return (object, prop) => {
    ValidateNested()(object, prop);
    IsNotEmptyEx()(object, prop);
    Type(typeFunction)(object, prop);
  };
};
```

However doing this in sources itself would be nice.

**Comment by chrisjpalmer** [comment]
Yeah i second that

**Comment by Kunepro** [comment]
For me ValidateNested doesn't work even with non-array Objects. I checked the examples and I can't get it to work, can anybody confirm that it's not just me?
```
export class Class {
  @ValidateNested({ message: "doesn't matter" })
  nested: SubClass;
}

export class SubClass {
  @IsEmpty({ message: "empty" })
  @IsNotEmpty({ message: "not empty" })
  iNeverTriggerAnyError: string;
}

const example = new Class({
  nested: {
    iNeverTriggerAnyError: "Yes"
  }
});

const validator = new Validator();
validator.validate(example).then(result => console.log(result));
```

**Comment by chrisjpalmer** [comment]
Thats because in this jnstance you created your class from a javascript object which contains no typescript class information. So class-validator doesnt actually know what class it needs to compare nested with. If you add the @type decorator lile this:

```ts
@ValidateNested({ message: "doesn't matter" })
@Type(() => SubClass)
  nested: SubClass;
```

It will transform the javascript object to have typescript information at validation time

**Comment by Kunepro** [comment]
In the examples @Type is not used: https://github.com/typestack/class-validator/tree/master/sample/sample3-nested-objects

However I tried to apply Type like you suggested, but I still get nothing:
https://plnkr.co/edit/D0gvBwnj1nb32MRjckez?p=catalogue

My related dependencies:
		"class-transformer": "^0.1.9",
		"class-validator": "^0.8.5",
		"reflect-metadata": "^0.1.12",
		"ts-node": "6.0.1",
		"typescript": "2.8.3"

**Comment by NoNameProvided** [comment]
> Currently to make ValidateNested work with array we have to manually apply Type decorator from class-transformer. 

You need to specify the `each: true` option on the `ValidateNested` decorator:

```ts
import { IsString, ValidateNested, validate  } from "class-validator";

class MySubClass {
  @IsString()
  name: string
}

class MyClass {
  @ValidateNested({ each: true })
  names: MySubClass[]
}

const subOne = new MySubClass();
const subTwo = new MySubClass();
const instance = new MyClass();

subOne.name = 'John';
subTwo.name = <any>5;

instance.names = [subOne, subTwo];

// properly returns one error
//  errors[0].children[0].children[0].constraints properly contains the error message
validate(instance).then(console.warn);
```

> If you add the @type decorator lile this:

It should work without the `@Type` decorator when real classes are passed in.

```ts
import { IsString, ValidateNested, validate  } from "class-validator";

class SubClass {
  @IsString()
  public prop: string;
}

class ShouldWork {

  @ValidateNested()
  child: SubClass;
}

const child = new SubClass()
const instance = new ShouldWork();

child.prop = <any>5;
instance.child = child;

validate(instance).then(console.warn); // works
```

You only need the `@Type` decorator when you are assigning an object where a class should be:

```ts
import 'reflect-metadata';

import { Type, plainToClass } from 'class-transformer';
import { IsString, ValidateNested, validate  } from "class-validator";

class SubClass {
  @IsString()
  public prop: string;
}

class NeedsType {

  @ValidateNested()
  @Type(() => SubClass)
  child: SubClass;
}

// This is what routing contoller does to transform: 
const request = { child: { prop: 5 } };
const instance = plainToClass(NeedsType, request);

// This is the validation part
validate(instance).then(console.warn) // works, but only if type is specified
```

@Kunepro please update to `0.9.0` and if you see 

```
No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.
```

Then your class-validator instance propably has multiple installation:

```
node_modulues/
  class-validator@x.x.x
  some-module
    class-validator@x.x.y
```

This way registers the validation rules (the global one) but you call validate on a different version which has no rules registered so it will pass. 

Note: you can also set `forbidUnknownValues: true` in `ValidatorOptions` to not allow validations to pass when no metadata is found.
