### ISSUE TITLE
feature: add link to class-validator-extended

### ISSUE THREAD

**Issue by pigulla** [typestack/class-validator#2003]
### Description
I've been working on a set of additional validators and published them as [`class-validator-extended`](https://github.com/pigulla/class-validator-extended). We've been using them in various major projects for almost two years now. It'd be appreciated if a link was added on this project's README so that others who might consider them useful can find them more easily.

### Proposed solution
Add a link to [`class-validator-extended`](https://github.com/pigulla/class-validator-extended) in the [Extensions](https://github.com/typestack/class-validator#extensions) section of the README.

**Comment by braaar** [comment]
Seems alright to me. 

The repository description mentions non-decorator based validation. Does this project use the deprecated schema-based validation?

**Comment by pigulla** [comment]
No, that simply is meant to indicate that - just like class-validator does - both the decorator and the underlying validation function are exported (i.e., `IsMap` *and* `isMap`). I'm happy to update the documentation if this is confusing.

**Comment by braaar** [comment]
I would appreciate a clarification of that text. It should be made obvious that the validators in that project are written just like the ones in `class-validator` itself.

**Comment by pigulla** [comment]
Fair enough, I've updated the readme.

**Comment by pigulla** [comment]
Is there anything else I should do to get this merged?

**Comment by braaar** [comment]
Wait for @NoNameProvided's review :)

**Comment by pigulla** [comment]
Pinging @NoNameProvided ...

**Comment by pigulla** [comment]
Any chance of this getting merged, @NoNameProvided ?

**Comment by NoNameProvided** [comment]
Thanks, it has been merged!
