### ISSUE TITLE
feature: allow to blacklist or whitelist country codes in the IsIBAN decorator

### ISSUE THREAD

**Issue by spotlesscoder** [typestack/class-validator#2048]
### Description
I want to build an API that only accepts german IBANs for payments.

### Proposed solution
Add options to the decorators that allow to either
* whitelist country codes
* blacklist country codes

Each of the two params should allow an array of ISO3166-2 country codes as strings (or maybe use an enum for TS?).

Should look something like this for the API

```
class MyClass {
  @IsIBAN({whitelistCountries: ["DE"]})
  germanIBAN: string;

  @IsIBAN({blacklistCountries: ["US"]})
  nonUSIBAN: string;
}

```

**Comment by edilson** [comment]
@CodingSpiderFox looks like in order to achieve that it would be necessary to make some changes on library that checks the IBAN.

**Comment by spotlesscoder** [comment]
I would just follow a naive approach (pseudocode)

let matchesValid = false;
whitelistCountries.forEach((country) => {
  if(iban.startsWith(countryCode)) {
    matchesValid = true;
  }
)}

return matchesValid && <result from IBAN validation library>

**Comment by edilson** [comment]
Maybe for now we could use your approach whilst the lib that checks the IBAN doesn't implement this feature.

**Comment by braaar** [comment]
I suggest you resubmit this in [validator.js](https://github.com/validatorjs/validator.js). This library is not in the habit of augmenting validators from validator.js with custom logic unless there is a particularly strong reason for it. In the meantime you can use a custom validator for this.

**Comment by edilson** [comment]
Hey @braaar actually there's a [PR](https://github.com/validatorjs/validator.js/pull/2235) opened in [validator.js](https://github.com/validatorjs/validator.js) for that purpose, once it gets merged maybe we could implement it here.
