### ISSUE TITLE
Multiple @Matches

### ISSUE THREAD

**Issue by cinoss** [typestack/class-validator#207]
I want to make a normal password field that should have at least
- 1 uppercase letter
- 1 lowercase letter
- 1 digit
Three @Matches with 1 RegExp for each does not seem work (only one takes effect). So want to ask if there is any workaround for this.

**Comment by NoNameProvided** [comment]
Yes, decorators are used once and the one defined last will take effect. If you want such custom logic you can use [custom validation classes][cvc] or [custom validation decorators][cvd]

[cvc]: https://github.com/typestack/class-validator#custom-validation-classes
[cvd]: https://github.com/typestack/class-validator#custom-validation-decorators
