### ISSUE TITLE
question: How to validate an array of string or number type?

### ISSUE THREAD

**Issue by winkcc** [typestack/class-validator#2087]
I'm trying to validate an array in my DTO using class-validator, but I'm not sure how to validate an array that can contain both string and number values. 
```Typescript
export class dto{
  @IsArray()
  layerIds: (string | number)[]
}
```
```Typescript
class dto {
  @IsArray()
  @IsNumber({ each: true })
  @IsString({ each: true })
  layerIds: (string | number)[];
}
```
However, the above code does not work as expected, as both @IsNumber() and @IsString() decorators are used to validate the elements, which are mutually exclusive.Can you provide some guidance on how to achieve this?

**Comment by Dauniusha** [comment]
Hey you can implement a simple custom decorator that will check your conditions:

```
@ValidatorConstraint({ name: 'IsStringOrNumber', async: false })
export class IsStringOrNumber implements ValidatorConstraintInterface {
  validate(value: string | number): boolean {
    return typeof value === 'string' || typeof value === 'number';
  }
}
```

Usage:

```
@IsArray()
@Validate(IsStringOrNumber, { each: true })
layerIds: (string | number)[];
```

**Comment by winkcc** [comment]
The end
`export function IsNumberOrString(validationOptions?: ValidationOptions): PropertyDecorator {
  return ValidateBy(
    {
      name: 'IsNumberOrString',
      validator: {
        validate(value: any): boolean {
          return isString(value) || isNumber(value)
        },
        defaultMessage: buildMessage((eachPrefix: string, args?: ValidationArguments) => `${eachPrefix}${args?.property} must be a number or a string`, validationOptions),
      },
    },
    validationOptions,
  )
}
`
