### ISSUE TITLE
fix: decorator @IsUUID not validating

### ISSUE THREAD

**Issue by BetterCallTom** [typestack/class-validator#2100]
### Description
I'm attempting to validate an UUID but seems like the decorator isn't recognising the output format in response body. I performed type checking with `typeof` operator inside the `console.log` to certify if the generated UUID is a string because I'm using the `RandomUUID()` function from `crypto` lib to generate it but it seems like don't change nothing to class-validator.

I'm using the Prisma ORM alongside PostgreSQL and Nest.js just to be more specific

## Code showcase

```ts
// create.dto.ts

import { User } from '@prisma/client'

export default class CreateUserDto implements User {
  @IsUUID('4')
    id: string
}
```

### API Submission

```ts
// users.controllers.ts

import { UsersPrismaService } from './users.service'
import { RandomUUID } from 'crypto'

export class UsersControllers {
  constructor (private readonly UserPrismaService: UsersPrismaService) {}
  // [...]

  const NewUser = await this.UserPrismaService.CreateUser({
    id: randomUUID(),
    // [...]
  }
}
```

### Current behaviour on response body
```json
{
  "statusCode": 400,
  "message": [
    "id must be a UUID"
  ],
  "error": "Bad Request"
}
```

### Expected behaviour on response body

```json
{
  "statusCode": 201,
  "data": {
    "id": "<UUID>",
    "name": "User",
    "creation_date": "<timestamp>"
  }
}
```

**Comment by kpkonghk01** [comment]
It should be `randomUUID` instead of `RandomUUID`

Also, after remove all unrelated context, the class-validator looks fine:
```ts
/* eslint-disable no-process-exit */
import { plainToInstance } from 'class-transformer';
import { IsUUID, validate } from 'class-validator';
import { randomUUID } from 'crypto';

class CreateUserDto {
  @IsUUID('4')
  id: string;
}

(async () => {
  const idInstance = plainToInstance(CreateUserDto, { id: randomUUID() });
  console.log(idInstance); // CreateUserDto { id: 'da3af07d-6430-45b3-9eef-b5f3e74b7b7c' }
  console.log(await validate(idInstance)); // []
})()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.log(error);
    process.exit(1);
  });

```

Please check where the error comes from, what is the id value before the validation.

**Comment by kpkonghk01** [comment]
@T0mAlexander 

can you reproduce the problem by the above minimal reproducible example?

**Comment by BetterCallTom** [comment]
> It should be `randomUUID` instead of `RandomUUID`
> 
> Also, after remove all unrelated context, the class-validator looks fine:
> 
> ```ts
> /* eslint-disable no-process-exit */
> import { plainToInstance } from 'class-transformer';
> import { IsUUID, validate } from 'class-validator';
> import { randomUUID } from 'crypto';
> 
> class CreateUserDto {
>   @IsUUID('4')
>   id: string;
> }
> 
> (async () => {
>   const idInstance = plainToInstance(CreateUserDto, { id: randomUUID() });
>   console.log(idInstance); // CreateUserDto { id: 'da3af07d-6430-45b3-9eef-b5f3e74b7b7c' }
>   console.log(await validate(idInstance)); // []
> })()
>   .then(() => {
>     process.exit(0);
>   })
>   .catch((error) => {
>     console.log(error);
>     process.exit(1);
>   });
> ```
> 
> Please check where the error comes from, what is the id value before the validation.

Sorry for the mispelling it on this sample but in my code, was written in lowercase (randomUUID) and the error keeps being throwed when I try to create a new user

Do you have further solutions for it, mate?

**Comment by kpkonghk01** [comment]
@T0mAlexander 
It'd be difficult to find out the reason if you don't provide the payload you passed into the validation function and the code of how you invoke the validator.

Just a guess, maybe the data returned by prisma has some getter function to let you use the syntax of `user.id` to access the `id`, but the id doesn't really there. Maybe it exists in some hidden field like `user._doc`(mongoose does something like this). So that the decorator of the Dto can't see the `id` field and throws validation error.

It's impossible for me to investigate what happens when there's no minimal code to reproduce the problem.

**Comment by braaar** [comment]
Please provide a full reproduction of this issue. You can comment here or resubmit as a new issue
