### ISSUE TITLE
[Feature Request] @NotNull Decorator

### ISSUE THREAD

**Issue by oleersoy** [typestack/class-validator#214]
Similar to Hibernate's [@NotNull](http://docs.jboss.org/ejb3/app-server/HibernateAnnotations/api/org/hibernate/validator/NotNull.html) unless I missed something and there is a simpler solution in typescript. 

I'm pretty sure I can provide the implementation if the idea sounds ok.

**Comment by 19majkel94** [comment]
`@IsDefined`?

**Comment by oleersoy** [comment]
Just read the code for that - Yes that should do it!  I'll close this.  Thanks for this awesome library!!

**Comment by oleersoy** [comment]
I'm also wondering whether something like a `@GreaterThan` decorator is possible for checking whether one class property is greater than another.  I wrote this up on SO, but would very much appreciate feedback from you, as you are obviously pretty brilliant at this stuff.

https://stackoverflow.com/questions/50710163/controlling-the-order-in-which-typescript-decorators-are-applied
