### ISSUE TITLE
fix: `@IsBoolean` always transforms the value of a boolean query param to true

### ISSUE THREAD

**Issue by SLSJL** [typestack/class-validator#2170]
### Description

`@IsBoolean` alway transforms the value of a boolean query param to `true`
even if the `transformOptions.enableImplicitConversion.true` is set as `true`

Definition of a boolean query parameter is as below.

**Minimal code-snippet showcasing the problem**
 

```ts
  @IsBoolean()
  @IsOptional()
  @Transform((object) => {
    console.log(object);
    return object.value;
  })
  isMuted?: boolean;
```

### Expected behavior

```ts
// For query param value as  'true'
{
value: true,
key: 'isMuted',
object: {isMuted: 'true', ...}
...
}
{
value: false,
key: 'isMuted',
object: {isMuted: 'fale', ...}
...
}
```
### Actual behavior
<img width="613" alt="image" src="https://github.com/typestack/class-validator/assets/16145313/db753398-e97e-4008-97cb-eaee74c6cfb8">

**Comment by NoNameProvided** [comment]
This works as expected. Any non-empty string value is transformed to boolean true by Javascript. 

Closing as wontfix.
