### ISSUE TITLE
@IsUrl() with options has bad feedback when invalid

### ISSUE THREAD

**Issue by Y0hy0h** [typestack/class-validator#223]
When you pass the URL `test.org` to the `isUrl()` validator with the option `require_protocol`, it simply returns `"url must be an URL address"`. This is the same for the other options, like `require_tld`. A user will not be able to understand what they did wrong.

I understand that class-validator [delegates the URL validation to another library](https://github.com/typestack/class-validator/issues/49#issuecomment-260555269), but it looks like that library simple [returns false](https://github.com/chriso/validator.js/blob/fdea1d79e6ab0fb256f29dd651641dcf7c46012e/lib/isURL.js#L84) without further information. Now, I'm not sure whether to open the issue here or on [that library](https://github.com/chriso/validator.js).

Is it possible to add discrimination of these errors here?

**Comment by NoNameProvided** [comment]
Hi @Y0hy0h! 

As you wrote we do not have the reason why the validation failed, so we can show only a general error message. You can try opening an issue at that repo to see if they are willing to add different function calls for it.
