### ISSUE TITLE
question: how to differentiate between IsOptional and ValidateIf decorators

### ISSUE THREAD

**Issue by haiweilian** [typestack/class-validator#2242]
**I was trying to...**

I want to differentiate between IsOptional and ValidateIf decorators

**The problem:**

For some reason I need to know if the property has the `IsOptional` decorator added. But their types are both `conditionalValidation`, so is there any other way to distinguish?

```ts
const store = getMetadataStorage() as any;
const validationMetadatas = store.validationMetadatas as ValidationMap;
const validator = [...validationMetadatas.values()].flat();
validator.forEach((v) => {
  if (v.type === 'conditionalValidation') {
    // IsOptional or ValidateIf ?
  }
});
```

**Comment by braaar** [comment]
The difference between these is explained well [in this comment](https://github.com/typestack/class-validator/pull/689#issuecomment-1514355052).
