### ISSUE TITLE
question: <your-title-goes-here>

### ISSUE THREAD

**Issue by KauaWB02** [typestack/class-validator#2257]
Well, I was creating validations with class-validator and I started testing some things and came across the following error (I don't know if it's in my code or in the library), Custom functions with @Validate() are taking priority when execution of validations and I come to this question how can I solve this problem and if the library has anything to help me.

 **Observation**
 
 I've tried every way from bottom to top and top to bottom, I heard that the library validates from bottom to top but I was unsure and tested from all sides lol and it didn't work.

**Comment by braaar** [comment]
Could you provide a reproduction, and also update the issue title?

**Comment by braaar** [comment]
Feel free to open a new issue in the future, and please try to provide a code snippet that reproduces your error.
