### ISSUE TITLE
question: Sorry for the strange question, but the class-validator project is still alive?

### ISSUE THREAD

**Issue by alex-kovalchuk** [typestack/class-validator#2265]
Due to the fact that I am choosing a class-validator for a new project, I would like to know if this project has a future since the last release was Dec 9, 2022, and the number of issues is growing.

_PS. Another project of the author - class-transformer, I would also like to use, but there is the same situation with the absence of any changes._

**Comment by braaar** [comment]
Thanks for checking in!

See [the pinned issue](https://github.com/typestack/class-validator/issues/1775) for some context about the state of this project. I'll close this issue as not planned. Hopefully your question will be answered by that and you can comment there or start a discussion in the discussions tab if you want to discuss this further.
