### ISSUE TITLE
@IsEmail() - how to make it support '+' sign?

### ISSUE THREAD

**Issue by rajivkr** [typestack/class-validator#2284]
Recently learnt that gmail has an option to test as multiple id's by adding '+1', '+2', i.e, if you have `hello@gmail.com`, you can use `hello+1@gmail.com, hello+2@gmail.com` etc. to get emails to same`hello@gmail.com` inbox.

**The problem:**
However, with this logic, i see that `@IsEmail()` is throwing an error for emails with '+' sign, is there a way i can get around this?
Currently using this regex instead, but can this be done using `isEmail()` itself?

```js
  @ValidateIf((_, value) => {
    return value === null || /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(value);
  })
```

**Comment by eladchen** [comment]
IMO the email should be validated according to RFC 2822, which should allow using the "+" in the local part

**Comment by braaar** [comment]
I can't reproduce your behavior. Plus sign in email passes validation. This was [discussed in the underlying validation framework validatorjs 8 years ago](https://github.com/validatorjs/validator.js/issues/414)

Here's my snippet, I get `Validation success`:
```ts
import { validate, IsEmail } from "class-validator";

class User {
  @IsEmail()
  email: string;
}

let user = new User();
post.user = "stephen+spam@gmail.com";

validate(user).then((errors) => {
  if (errors.length > 0) {
    console.log("Validation failed. errors: ", errors);
  } else {
    console.log("Validation success");
  }
});
```
