### ISSUE TITLE
question: docs link are broken

### ISSUE THREAD

**Issue by cesarve77** [typestack/class-validator#229]
must of links in https://github.com/typestack/class-validator/tree/master/docs
are broken

Thanks!

**Comment by NoNameProvided** [comment]
Hi @cesarve77 

It's just a dummy table of content, I have started to split the documentation into some more readable parts, but haven't finished.

**Comment by rxst** [comment]
@NoNameProvided When do you plan to complete the documentation?

**Comment by NoNameProvided** [comment]
I don't know, re-writing and re-structuring the current docs would be more than a week worth of effort.

**Comment by NoNameProvided** [comment]
Closing this as non-actionable. No offense, it will be done when we have the time.
