### ISSUE TITLE
add complete es5/es6 support

### ISSUE THREAD

**Issue by pleerock** [typestack/class-validator#23]
Right now its possible to use validator with es5/es6, but we can provide more features to make this experience smoother. List of todos:
- [ ] add support of registering validation schema for target class
- [ ] add support of registering custom validations without using decorators
- [ ] make schema validation better
- [ ] cover schema validation with tests
- [ ] add samples with javascript, or javascript + babel + decorators?
- [ ] add docs how to use class-validator with javascript
- [ ] add docs how to use class-validator with system-js

**Comment by NoNameProvided** [comment]
Closing in favor of #178.
