### ISSUE TITLE
How to make it multi language

### ISSUE THREAD

**Issue by mahdiprog** [typestack/class-validator#230]
Hi
Firstly, I should say you done a very good job guys.
Secondly, how can I implement globalization (using i18n service or ngx-translate)?
I mean as validation message is inside the model, how can I use TranslateService to get an appropriate message for each localization?
regards

**Comment by NoNameProvided** [comment]
Hi @mahdiprog!

class-validator doesn't provide any localization data beside the default error messages. However, you can build a util function which takes the two parameters the list of validation errors and a `FormGroup` then you can loop through your validation errors and set the errors on the form.

```ts
// not a complete example
export function markInvalidInputs(errors: ValidationErrors[], form: FormGroup) {
  errors.forEach(error => {
    form.controls[error.property].setErrors(error.constraints)
  });
}
```
