### ISSUE TITLE
@IsOptional not working as expected

### ISSUE THREAD

**Issue by fsanzv** [typestack/class-validator#232]
Hello,
I'm trying to use class-validator with typeorm and I have find a problem with an email field:
``` TypeScript
@Column()
@IsOptional()
@IsEmail()
public email?: string;
```
When I use PUT to replace entity info, if I want to clear email field I must replace the received req.body.email="" with _null_ to get it working.

I think @IsOptional should work with _null_, _undefined_ or "".

**Comment by 19majkel94** [comment]
https://github.com/typestack/class-validator/pull/110

**Comment by fsanzv** [comment]
I understand the points, but how must I handle PUT request, nulling optional string fields?

Maybe it should be named @NotSoOptional ;-)

**Comment by 19majkel94** [comment]
`TypeORM` works the same way - you need to set the field value to null to clear it in DB.
In JS we have `undefined` that tells there's no value and `null` that tells that somebody explicitly set the value to be empty.

So yes, empty string or 0 are falsy values but they are legit values. You should use null to indicate explicitly that you want to remove the value.

**Comment by fsanzv** [comment]
I have tested this solution but `TypeORM` deletes the email field if it is set to _null_ so doing this way you can not clear the field value if was previously set.

To solve it, I have created a custom validator (@IsEmailOptional) and I perform a manual validation when the email has value and return true when it is empty. Another problem I've found this way is that I can't set a default message to handle it so I must set the message in every email field of my App :-(

I still think @IsOptional should allow empty strings ("") in string fields.
