### ISSUE TITLE
question: Could someone also bump the package.json version from 0.14.0 to 0.14.1?

### ISSUE THREAD

**Issue by sph3rex** [typestack/class-validator#2371]
Could someone bump the package.json version so that the npm release works? Right now the 0.14.1 pipeline fails because of that: https://github.com/typestack/class-validator/actions/runs/7485872569/job/20375115027 with `403 Forbidden - PUT https://registry.npmjs.org/class-validator - You cannot publish over the previously published versions: 0.14.0.`

Thank you. :pray:

**Comment by braaar** [comment]
This was my mistake. I'm new to having write access here and was unfamilar with the npm release action (I'm used to the action updating the version automatically). 

I can't push directly to `develop` and can't approve my own PRs, so I need an approving review on #2373 to resolve this. A review would be greatly appreciated!

**Comment by sph3rex** [comment]
No worries, as I have mentioned [here](https://github.com/typestack/class-validator/pull/2372#issuecomment-1888638722) I guess this should be done automatically by the Github actions. I'll try to come up with a PR related to that if I have time.

**Comment by braaar** [comment]
@sph3rex could you create a PR like #2373 so that I can approve it and merge it?

**Comment by sph3rex** [comment]
sure

> @sph3rex could you create a PR like #2373 so that I can approve it and merge it?

Done ... https://github.com/typestack/class-validator/pull/2375
