### ISSUE TITLE
Serializing of Map with any type not working

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [typestack/class-validator#242]
It seems like a Map MUST have the @Type decorator otherwise it does not deserialize it at all. However, when using default types, eg. any/string/... this is not possible.

For example, de-serializing  `myMap: Map<string, any> = new Map();` is not possible. And writing 
```
@Type(() => any)
myMap: Map<string, any> = new Map();`
```
does not work either because the compiler does not know what todo with `any`.

I found a workaround by creating a class that acts like any 
```
class ActLikeAny{
    [P: string]: any;
}
```

then I can write

```
@Type(() => ActLikeAny)
myMap: Map<string, ActLikeAny> = new Map();`
```

**Comment by Tarik02** [comment]
It can't validate map/set at all.

**Comment by vlapo** [comment]
Support for Map/Set is addded by https://github.com/typestack/class-validator/pull/365
