### ISSUE TITLE
fix: the 'whitelist' option doesn't seem to work

### ISSUE THREAD

**Issue by RubenVermeulen** [typestack/class-validator#249]
**Version**: ^0.9.1

Hi all

I've been struggling to get the whitelist option working when validating an object. I want to strip all properties that are not defined in my class, but do exists on the plain JS object. If I'm correct, passing the option `whitelist: true` should to the trick.

**My class**
```typescript
export class Dto {
  @IsNotEmpty()
  @IsString()
  name: string;

  @IsNotEmpty()
  @IsUrl({
    require_protocol: true,
    protocols: ['http', 'https']
  })
  src: string;
}
```
**Plain JS object**
```typescript
const dto = new Dto();

dto.name = 'Ghent';
dto.src = 'http://example.be';
(dto as any).foo = 'foo';
(dto as any).bar = 'bar';
```
**Validation**
```
validate(dto, {whitelist: true});
```
The moment I validate I expect that `foo` and `bar` are stripped from the plain object, but they aren't. I also tried adding `foo` and `bar` to the class without decorators, but that doesn't change the behaviour.

Could anyone shed some light on this?

**Comment by robertmain** [comment]
I'm running into this now. I'd be interested to know what you meant @BenjD90 regarding class-transformer.  I'm already using it to hide fields like `deletedAt` from my output when my controllers return entities.

**Comment by NoNameProvided** [comment]
Cannot reproduce on the latest 0.14.0 version. Works as expected:
```ts
import { IsEmail, IsNotEmpty, IsOptional, IsString, IsUrl, MinLength, validate } from 'class-validator';

export class Dto {
  @IsNotEmpty()
  @IsString()
  name: string;

  @IsNotEmpty()
  @IsUrl({
    require_protocol: true,
    protocols: ['http', 'https']
  })
  src: string;
}

const dto = new Dto();

dto.name = 'Ghent';
dto.src = 'http://example.be';
(dto as any).foo = 'foo';
(dto as any).bar = 'bar';

// validation passes
validate(dto, { whitelist: true }).then(console.log);

// logs: <Dto>{ name: "Ghent", src: "http://example.be"}
console.log(dto)
```
