### ISSUE TITLE
ValidatidationError .toString() 

### ISSUE THREAD

**Issue by sanex3339** [typestack/class-validator#26]
It would be nice to define `.toString()` method for `ValidationError` which will return ValidationError.constraints messages as string.

``` ts
if (errors.length) {
    for (let error of errors) {
         console.log(error.toString());
    }
}
```

Format for message something like (formatted string with new lines):

```
PROPERTY_NAME errors
    length: "PROPERTY_NAME must be shorter than 10 characters"
    contains: "PROPERTY_NAME must contain a hello string"

or

PROPERTY_NAME errors
    - PROPERTY_NAME must be shorter than 10 characters
    - PROPERTY_NAME must contain a hello string
```

**Comment by sanex3339** [comment]
Use case:

Right now i do something like
```
if (errors.length) {
    throw new ReferenceError(`Validation failed. errors:\n${Options.formatErrors(errors)}`);
}

    private static formatErrors(validationErrors: ValidationError[]): string {
        let errorsArray: string[] = [];

        for (let error of validationErrors) {
            let errorsString: string = `\`${error.property}\` errors:\n`;

            for (let constraint in error.constraints) {
                if (!error.constraints.hasOwnProperty(constraint)) {
                    continue;
                }

                errorsString += `    - ${error.constraints[constraint]}\n`;
            }

            errorsArray.push(errorsString);
        }

        return errorsArray.join('\n');
    }
```

It will cool if i could simplify `formatErrors` method or completely remove them.

With simplification it will looks like:
```ts
 private static formatErrors(validationErrors: ValidationError[]): string {
        let errorsArray: string[] = [];

        for (let error of validationErrors) {
             errorsString += error.toString();
        }

        return errorsArray.join('\n');
    }
```

With completely removing of this method it is need to define `.toString` method for `ValidationErrors[]` array. Or replace `ValidationErrors[]` array on wrapper class with various methods like `getErrorsAsString`, `getErrorsCount`, `hasErrors`. But this is breaking change.

**Comment by pleerock** [comment]
Custom arrays in javascript is more problem then solution, so its better to avoid it. Also regarding to `ValidationErrors` I would like to keep it as plain object - without additional methods defined. Regarding to your proposal, also I don't think such formatting generally needed. Who really needs this specifically defined string and for what purposes? - don't think lot of people need it

**Comment by sanex3339** [comment]
for example in `Joi` following code
```ts
        Joi.validate(obfuscatorOptions, this.schema, (error: Joi.ValidationError) => {
            if (error) {
                throw error;
            }
        });
```
output:
```
ValidationError: child "sourceMapMode" fails because ["sourceMapMode" must be one of [inline, separate]]
```
If we use validator in public packages, we expect that error messages will easy understandable by other people. Of course we can create custom formatter, but i think there must be a way to get that kind of messages from validator.

**Comment by 19majkel94** [comment]
It's a good task for learning functional programming - concate all with map to receive array of error string in format:
```
property x must be shorter than 10 characters
property x.y.z must contain a hello string
```
For humans it looks nice as Rest API response but the original error is better for mapping response to frontend's form inputs.

**Comment by pleerock** [comment]
for form inputs there is a "message" inside validation error object

**Comment by NoNameProvided** [comment]
Which one would be the preferred way? 

```
The RootClass has failed the following constraints:
  - title (property) 
    - isString: {alias} must be a string 
	  - minLength: {alias} must be longer than or equal to 15 characters 
  - nestedObj (class)
    - name (property)
      - isString: {alias} must be a string
    - url (property)
      - isUrl: {alias} must be an URL address
    - insideNested (class)
      - name (property)
        - isString: {alias} must be a string
      - url (property)
        - isUrl: {alias} must be an URL address
```
vs

```
The RootClass has failed the following constraints:
	- property 'title' failed the 'minLength' constraint': title must be longer than or equal to 15 characters
	- property 'title' failed the 'isString' constraint': title must be a string
	- property 'nestedObj.name' failed the 'isString' constraint': name must be a string
	- property 'nestedObj.url' failed the 'isUrl' constraint': url must be an URL address
	- property 'nestedObj.insideNested.name' failed the 'isString' constraint': name must be a string
	- property 'nestedObj.insideNested.url' failed the 'isUrl' constraint': url must be an URL address
	- property 'nestedArr.0.name' failed the 'isString' constraint': name must be a string
	- property 'nestedArr.0.url' failed the 'isUrl' constraint': url must be an URL address
	- property 'nestedArr.1.name' failed the 'isString' constraint': name must be a string
	- property 'nestedArr.1.url' failed the 'isUrl' constraint': url must be an URL address
```

**Comment by sanex3339** [comment]
For me - second one

**Comment by NoNameProvided** [comment]
Added and released in `0.8.2`. 

You can simply call `validationError.toString()` from now. You can also pretty print it. (It just makes the property names bold for better readability.)

**Comment by sanex3339** [comment]
Wow, amazing!

**Comment by sanex3339** [comment]
It gives me `[object Object]` when i was called `validationError.toString()`

**Comment by NoNameProvided** [comment]
Are you sure you are trying with `0.8.2`? It seems to work for me.

Here is an [online fiddle](https://stackblitz.com/edit/class-valiator-error-tostring?embed=1&file=app.ts).

**Comment by sanex3339** [comment]
Yes. 0.8.2, and this error related to new code that was added in `0.8.2`.

**Comment by NoNameProvided** [comment]
Please, give me a full example of how you use it.

**Comment by sanex3339** [comment]
Step 1: validateSync
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/options/Options.ts#L239

Step 2: format errors
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/options/ValidationErrorsFormatter.ts#L8

In step 2 before line 12 i just added `console.log(error.toString())`

**Comment by NoNameProvided** [comment]
And this only happens when you call `toString` right? 

Ok, I have found it, you set the `ValidatorOptions.validationError.target` key to `false`, so it's not exposed. I didn't think of that. Fixed now, can you try with `0.8.3` please?

**Comment by sanex3339** [comment]
Working now. 

But i more like detailed messages like `title must be a string`, instead of `isString`. 

Anyway, great job, thank you.

**Comment by sanex3339** [comment]
But i think it will better to keep old messages like `title must be a string`

For example: current message in 0.8.3 is:
```
An instance of Options has failed the validation:
 - property identifierNamesGenerator has failed the following constraints: isIn 
```

Old error message:
```
    - identifierNamesGenerator must be one of the following values: hexadecimal,mangled
```

As you can see, old message displayed available values.

This error messages will show to users (validation of options), so they should know what they doing wrong with options.

**Comment by NoNameProvided** [comment]
`toString()` is added for developers, not for displaying messages to the users. The problem with the old format is that every constraint fail would be a new line, what makes the error message huge really fast, I prefer the one property, one line approach.

Later, however, we can consider adding some util functions to print messages for users as well.
