### ISSUE TITLE
question: usage of complementary rules

### ISSUE THREAD

**Issue by ns16** [typestack/class-validator#263]
How to apply two complementary rules to the field? For example, if a field can be a string or an array of strings.

```
import { IsString, validate } from 'class-validator'

class Foo {
  @IsString()
  public bar: string | string[]
}

async function start(bar) {
  const foo = new Foo()
  foo.bar = bar
  console.log(await validate(foo))
}

start('qwe') //Success
start(['qwe']) //Error, must be a success
```

I want to apply to bar @IsString() or @IsString({each: true})

**Comment by 19majkel94** [comment]
> It would be less error prone, if you have two separate properties:
> 
> ```ts
> class Foo {
>   @IsString()
>   public foo: string
> 
>   @IsString({ each: true })
>   public bar: string[]
> }
> ```

**Comment by ns16** [comment]
@19majkel94 Unfortunately, this solution does not suit me. I need a field that can be either a string or an array of strings.

**Comment by NoNameProvided** [comment]
Closing as expired.
