### ISSUE TITLE
Decorator ValidateNested is not working

### ISSUE THREAD

**Issue by henrikra** [typestack/class-validator#281]
I am using `class-validator` version `0.9.1`.

Here I have simple case where I have `RootObject` which has property `myEpicNestedObject` and we want to validate that nested object. Then [according to documentation](https://github.com/typestack/class-validator#validating-nested-objects) you should use `ValidateNested` but isn't actually doing anything.

Here is a simple sample code to try this out:
```ts
import { IsInt, ValidateNested, validate, IsString } from 'class-validator';

class NestedObject {
  @IsInt()
  myCoolNumber!: number;
}

class RootObject {
  @IsString()
  myAwesomeName!: string;

  @ValidateNested()
  myEpicNestedObject!: NestedObject;
}

const someObject = new RootObject();
someObject.myAwesomeName = 'lol';
someObject.myEpicNestedObject = { myCoolNumber: 1.2 }; // should fail because not integer

validate(someObject)
  .then(errors => {
    console.log('all fine', errors);
  })
  .catch(error => {
    console.log(error);
  });

```

What is wrong with `ValidateNested` or am I misusing it?

**Comment by 19majkel94** [comment]
nested object has to be an instance, created using `new`

**Comment by skrosoft** [comment]
Yes, it works using `new `... I could be great if this could works without the `new` operator ...

**Comment by henrikra** [comment]
@19majkel94 You were correct!
