### ISSUE TITLE
Feature Request: Support for Normalizing Values

### ISSUE THREAD

**Issue by nonplus** [typestack/class-validator#284]
A common use for class-validator is validation of web request data.  This works great for body content of POST and PUT requests.

However, when validating (Express, Restify, etc.) [`Request.query`](https://expressjs.com/en/api.html#req.query) and [`Request.params`](https://expressjs.com/en/guide/routing.html#route-parameters), all values are of type `string`.  This forces you to use, for example, `@IsNumberString` rather than the preferable `@IsInt` (or write your own `@IsIntString` validator).  The corresponding class property must then also be declared `string` rather than simply `number` and the route handler will need to have type conversion code.  A similar issue occurs when a query parameter may contain an array of values.  A single item will be a `string` and multiple items will become a `string[]`.  Again, the route handler may need to normalize this.

It would be great if a validator could (optionally?) normalize the value it's validating.  So, for example, an `@AsNumber` validator would accept a `number` or a `string` containing a valid number.  Anything else would be rejected.  If a string is passed in, the resulting property would be converted to a number.  Similarly, an `@AsArray` validator could convert a `string` into a single-element array.  You would then be able to do the following:

```typescript
class User {
  @AsNumber() // Converts numeric string to number, if necessary
  @IsInt()
  userId: number;
}
class UserQuery {
  @AsArray()  // Converts non-array to a single-element array, if necessary
  @IsString({ multiple: true })
  options: string[];
}
router.get('/users/:userId', (req, res, next) => {
  const user = Object.assign(new User(), req.params);
  const query = Object.assign(new UserQuery(), req.query);
  Promise.all([
    validator.validate(user),
    validator.validate(query)
  ]).then(([userErrors, queryErrors] => {
    if (!userErrors.length && !queryErrors.length) {
      // user.userId is now always a number and query.options is always an array
      ...
    }
  })
});
```

FWIW, I _can_ actually mutate the property value in my custom validator (see below), but the changed value isn't visible to subsequent validators (and it feels dirty).  That is, applying two validators like this `@AsNumber() @IsInt()` does not work.

It would be great to have something like a `@Normalize(transformCallback)` validator which would allow us to provide this functionality.  It would allow you to do cool things like:
```typescript
class Test {
  @Normalize(Number) // Converts numeric strings to proper numbers
  @IsInt()
  userId: number;

  @IsDateString()
  @Normalize(Date) // Converts string value to a Date instance
  timestamp: Date;

  @Normalize(value => value || "default value") // Provides default value
  optionalWithDefault: string;
}
```

Here's the hacky workaround I currently use to normalize `/users/:userId` route parameters during validation (probably wouldn't work on array properties):
```typescript
import {
  registerDecorator,
  ValidationArguments,
  ValidationOptions
} from "class-validator";

export function AsInt(validationOptions?: ValidationOptions) {
  return (object: object, propertyName: string) => {
    registerDecorator({
      name: "asInt",
      target: object.constructor,
      propertyName,
      options: validationOptions,
      validator: {
        validate(value: any, args: ValidationArguments) {
          if (typeof value === "string") {
            value = Number(value);
          }
          if (!Number.isInteger(value)) {
            return false;
          }
          (args.object as any)[args.property] = args.value = value;
          return true;
        }
      }
    });
  };
}
```

**Comment by lazarljubenovic** [comment]
Are you looking for [`class-sanitizer`](https://github.com/typestack/class-sanitizer)?

**Comment by nonplus** [comment]
Yes, something like that, though `class-sanitizer` looks a little half-baked (no nested sanitation, no tests, etc.)  For my needs (express middleware for validation/sanitation or params and query) I _could_ call `class-sanitizer` before `class-validator`.

But it would be nice to have some of it integrated in `class-validator` so that it can be used in places that already have built-in `class-validator` support (like [`routing-controllers`](https://github.com/typestack/routing-controllers)) and support nested sanitation.

**Comment by lazarljubenovic** [comment]
I'd like an all-in-one solution as well but given how `class-validator`, `class-transformer` and `class-sanitizer` are separate libs, it looks like (at least for now) there are no plans to have a single one. :thinking:

**Comment by Harukisatoh** [comment]
It would be nice a feature like that! The fact that I need to normalize params inside the request handler bothers me.

**Comment by NoNameProvided** [comment]
This is an old issue, but giving my feedback before closing: This is out-of-scope for `class-validator` if you want to convert query and route params you can use it alongside with `class-transformer`. 

It's quite simple to create a helper function that converts the received plain object first to a target class with `class-transformer` and validates the instance of the class with `class-validator` after the conversion.

Also worth mentioning, this behavior is built-in for `routing-controllers` and NestJS.
