### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by TomerSalton** [typestack/class-validator#289]
Hello, 

I was looking into this project, and it seems very elegant and useful.
I've seen other projects of you with MIT license and I was wondering, what kind of license does this project have?

Thank you and keep up with the excellent work,
Tomer.

**Comment by chrisdostert** [comment]
looks like MIT from package.json; would be nice to have LICENSE.md too to complement it

https://github.com/typestack/class-validator/blob/95916a33abb077c3c63eb30eeeafc7cd19eb7c24/package.json#L6
