### ISSUE TITLE
ValidationNest can throw plain error?

### ISSUE THREAD

**Issue by muyu66** [typestack/class-validator#290]
If i create a very deeply object and use @ValidationNest()
When input error params, it will throw very long nest error object,
like:

This is very scary.

How to get flat error message? Even if it throw large nest error, class-validator will give me Error[]

**Comment by muyu66** [comment]
who can help me, thinks

**Comment by vlapo** [comment]
You have to write your own function and get error message what you need.

**Comment by muyu66** [comment]
Now, i used a recipe: 
I use the object toString() and then use the regular expression to get the data I want.
