### ISSUE TITLE
Add the severity of validation errors

### ISSUE THREAD

**Issue by grin0c** [typestack/class-validator#293]
Example:
```javascript
@Contains("hello", {
    level: 'warn'
})
text: string;
```
Can be add decorator
```javascript
@Level('warn')
@Contains("hello")
text: string
```
Will somebody be interested?

**Comment by nomadoda** [comment]
Could you add an example where this would be useful? I think you could use validation groups instead

**Comment by grin0c** [comment]
I decided to use context. Thank you!
