### ISSUE TITLE
instanceof Promise breaks under some circumstances

### ISSUE THREAD

**Issue by otbe** [typestack/class-validator#294]
Hi there,

I encountered an issue while using a custom async validator. My project includes some magic from continuation-localstorage (`cls-hooked` package) which (I guess) wraps the native Promise so  [`instanceof Promise`](https://github.com/typestack/class-validator/blob/df6a6e48a7836bfba89da6733e4bc4bb9c05c4c9/src/validation/ValidationExecutor.ts#L237) will result in false negatives. 

Observed behavior is that the validation is triggered, the pending state is ignored and the object validates fine even if the validator returns false.

I propose to replace the instanceof check with something like this https://www.npmjs.com/package/is-promise. If its fine for you I will provide a PR.

Thanks a lot for this great module :)

**Comment by otbe** [comment]
As a side note:
`async-listener` overrides the `global.Promise` with a `WrappedPromise` which passes the instanceof check, but the Promise returned by an async function (native async/await) is the unpatched version. So `nativePromise instanceof WrappedPromise` fails. I configured TypeScript to output es6 which compiles async/await down and now it works, but I would prefer to keep the native async/await.

Thanks

**Comment by andrewwa-kainos** [comment]
I have opened https://github.com/typestack/class-validator/pull/310 because I faced a similar problem

**Comment by vlapo** [comment]
Close since #310 is already merged. Feel free to test using `0.10.0-rc.0`.
