### ISSUE TITLE
question: question regarding validation of optional fields

### ISSUE THREAD

**Issue by Rud156** [typestack/class-validator#298]
#### Question

Is there anything that this library supports similar to https://github.com/hapijs/joi/blob/master/API.md#objectorpeers. 

This basically says that if there are a set of optional properties, then I can define that at least one of the optional fields must be present to validate the class.

There is a similar issue #209. But the solution of implementing a custom class will lose context as I'll need to implement checking for all the properties which is not ideal.

**Comment by NoNameProvided** [comment]
Closing as expired.
