### ISSUE TITLE
🅰️ Use ClassValidator in Angular 7+ Reactive Forms

### ISSUE THREAD

**Issue by EndyKaufman** [typestack/class-validator#299]
I have made a library that turns your validators into an angular validators and adds to the FormGroup, can you add to your readme? https://github.com/typestack/class-validator#extensions

:)

my lib: https://github.com/EndyKaufman/ngx-dynamic-form-builder

**Comment by myanbin** [comment]
Nice job! It's very useful to me.

**Comment by vlapo** [comment]
Done. Sorry for delay :/
