### ISSUE TITLE
Cannot use validate inside constructor of a parent class

### ISSUE THREAD

**Issue by Skullflow** [typestack/class-validator#300]
Hi guys,

I want to use validateSync in object constructor, but I'm not able to use it with inheritance.

I've got something like this:

```ts
import { IsNotEmpty, IsString, validateSync, validate } from 'class-validator';

class Animal {

    @IsNotEmpty()
    @IsString()
    public name: string;

    constructor(name: string) {
        this.name = name;
        this.validate() // this method calls validate of class Dog, since this is an instance of Dog
    }

    protected validate() {
        const errors = validateSync(this);
        if (errors.length > 0) {
            console.log("Animal validation error: ", errors)
        }
    }
}

class Dog extends Animal {

    @IsNotEmpty()
    @IsString()
    public breed: string;

    constructor(name: string, breed: string) {
        super(name);
        this.breed = breed
        this.validate()
    }

    protected validate() {
        const errors = validateSync(this);
        if (errors.length > 0) {
            console.log("Dog validation error: ", errors)
        }
    }

}

const dog = new Dog('Aaron', 'Golden Retriever')
```

The result is:
```
Dog validation error:  [ ValidationError {
    target: Dog { name: 'Aaron' },
    value: undefined,
    property: 'breed',
    children: [],
    constraints:
     { isString: 'breed must be a string',
       isNotEmpty: 'breed should not be empty' } } ]
```

When I call `Dog` constructor, the code runs `super()` and then `this.validate()` of the `Animal` class.  This method validates an instance of `Dog` and since `Animal` doesn't have breed attribute, the code throw the error above.

I don't know how to solve this issue and maybe put validation inside constructors is not a good idea.

Is there a workaround or a better way to do that?

**Comment by vlapo** [comment]
`class-validator` search target metadata by `object.contructor` so validation is against `Dog` class. Currently it is not possible overwrite target. But maybe we can introduce some new option to specify target.... but still `this.validate()` in your `Animal` constructor will call validate method in Dog class. It is like JS/TS works.

**Comment by NoNameProvided** [comment]
There is an inheritance between validation decorators. If you run validation on `Dog` that extends `Animal` then all decorators of animal will run too. This means all you need to do is to remove the `this.validate` in your `Animal` constructor call. (Assuming `Animal` is not initiated on its own.)

<details>
<summary>Updated code sample</summary>

```ts
import { IsNotEmpty, IsString, validateSync, validate } from 'class-validator';

class Animal {

    @IsNotEmpty()
    @IsString()
    public name: string;

    constructor(name: string) {
        this.name = name;
    }

    protected validate() {
        const errors = validateSync(this);
        if (errors.length > 0) {
            console.log("Animal validation error: ", errors)
        }
    }
}

class Dog extends Animal {

    @IsNotEmpty()
    @IsString()
    public breed: string;

    constructor(name: string, breed: string) {
        super(name);
        this.breed = breed
        this.validate()
    }

    protected validate() {
        const errors = validateSync(this);
        if (errors.length > 0) {
            console.log("Dog validation error: ", errors)
        }
    }

}

const GoodDog = new Dog('Aaron', 'Golden Retriever')
const badDog = new Dog(undefined, 'Golden Retriever')
```

</details>

If this is not what you want, then I don't know any other workaround, as @vlapo said, the validation will always target the class definition of the passed-in value. This means when `Animal.constructor` is called via `super(name)` in `Dog.constructor` it will always validate against the `Dog` class.
