### ISSUE TITLE
registerDecorator askes for ValidatorOptions instead of ValidationOptions

### ISSUE THREAD

**Issue by baocancode** [typestack/class-validator#302]
Hi,

In the example of custom validation decorator https://github.com/typestack/class-validator#custom-validation-decorators I can see a `options` object with type `ValidationOptions` is passed to `registerDecorator`:

```
export function IsLongerThan(property: string, validationOptions?: ValidationOptions) {
   return function (object: Object, propertyName: string) {
        registerDecorator({
            name: "isLongerThan",
            target: object.constructor,
            propertyName: propertyName,
            constraints: [property],
            options: validationOptions,
...
```

But in https://github.com/typestack/class-validator/blob/master/src/register-decorator.ts, the `options` field is of type `ValidatorOptions` (line 36).

```
options?: ValidatorOptions;
```

Is that a mistake? Sorry if this has been asked before.

**Comment by ngryman** [comment]
I'm facing the same issue. As a consequence, I can't find a way to customize the error message as `ValidatorOptions` does not expose a `message` property.

**Comment by itstimetogoleft** [comment]
> I'm facing the same issue. As a consequence, I can't find a way to customize the error message as `ValidatorOptions` does not expose a `message` property.

You can add a customized message by adding a defaultValue method on the class.
```

 defaultMessage() {
    return "$value is taken!";
  }
```

**Comment by AlysonBasilio** [comment]
Any updates regarding this issue?

**Comment by vlapo** [comment]
I think this is just a small typing issue. It should be `ValidationOptions`.
