### ISSUE TITLE
how to apply Decorator pattern to class-validator

### ISSUE THREAD

**Issue by ape-casear** [typestack/class-validator#307]
i get a question that i want to re-use my code at query DTO

i have sql where options like this
```
class DateTimeDTO {
    @IsString()
    startTime: string;
    @IsString()
    endTime: string;
}
```
and this
```
class paginationDTO {
    @IsNumber()
    offset: number;
    @IsNumber()
    size: number;
}
```

now. i have so many interfaces to implement.  i don't want to use extends to add so many DTOs to every interface. what i want like this
```
class AnotherOne extends paginationDTO ,DateTimeDTO  {
}
```
but multi-extends is not available in js;  
and at nest.js
this is not ok
```
async getUsers(@Body condition: paginationDTO & DateTimeDTO )
```

Is there any good way for class-validator to use the decorating pattern to create a new class?

**Comment by 19majkel94** [comment]
You may try this:
https://github.com/justinfagnani/mixwith.js

**Comment by ape-casear** [comment]
> You may try this:
> https://github.com/justinfagnani/mixwith.js

I want a new class which contains properties from A and B, instead of 
```js
 foo() {
    console.log('foo from MyMixin');
    // this will call superclass.foo()
    super.foo();
  }
```
decorate a method.
how can i get a new class which contains  properties from A and B
```typescript
export class A{ 
@IsString()
name: string
}
export class B{
@IsNumber()
age: number
}
class ClassIWant{
@IsNumber()
age: number
@IsString()
name: string
}
```
by mixwith.js

**Comment by 19majkel94** [comment]
JS doesn't support multiple inheritance, so you can't.

You can achieve something like multiple inheritance by using the ES6 class mixins pattern:
http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/

**Comment by ape-casear** [comment]
> JS doesn't support multiple inheritance, so you can't.
> 
> You can achieve something like multiple inheritance by using the ES6 class mixins pattern:
> http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/

thank you for your help.
maybe I can only validate DTO manually like this
```typescript
export class ModelA {
  @IsString()
  name: string;
  @IsNumber()
  age: number;
}
export class ModelB {
  @IsJSON()
  club: string;
}
function validateMy (object: any, arr: {new(): any}[]){
  arr.forEach(Model =>{
    const post = new Model();
    Object.assign(post, object);
    validate(post).then(res =>{
      if (res.length > 0) {
        console.error('get error')
      }
    })
  })
}
validateMy({name: 'wdw', age: 23, club: '{1}'}, [ModelA, ModelB])
```
