### ISSUE TITLE
question: How validate nested schema?

### ISSUE THREAD

**Issue by diosney** [typestack/class-validator#316]
Hi,

Can' find a way to properly set validation using separate Schemas since I'm using interfaces, not classes.

For instance, can find a way to have schema validation working with the following simple object:

```
// sample object:
{
    containerId: 'xxx',
    experience: {
        flow: 'redirect'
    }
}

// Sample schema:
export const ButtonClientConfigSchema: ValidationSchema = {
  name      : 'ButtonClientConfigSchema',
  properties: {
    containerId: [
      {
        type: ValidationTypes.IS_DEFINED
      },
      {
        type: ValidationTypes.IS_STRING
      },
      {
        type: ValidationTypes.IS_NOT_EMPTY
      },
      {
        type       : ValidationTypes.MATCHES,
        constraints: [
          /^[A-Za-z]+[\w\-\:\.]*$/
        ]
      }
    ],
    experience : [
      {
        type: ValidationTypes.NESTED_VALIDATION
        // How set here the `experience` nested schema?
      }
    ]
  }
};

```

Related issue: https://github.com/typestack/class-validator/issues/225

But I'm latest release at the moment (0.9.1) and still have the same issue at the #225 issue.

Thanks!

**Comment by diosney** [comment]
I tested by curiosity to check if using the decorators and a classes based system worked for my use case and it did, the bad part is that I had to duplicate all my interfaces as classes too, and maintain that will be cumbersome, I know for sure, so in the meantime I use this solution, it could be great you keep this issue open until the same funcionality gets added into the schema-based validations.

Thanks

**Comment by oreshkoandrei** [comment]
Could anyone help ?)

**Comment by jacktuck** [comment]
See https://github.com/typestack/class-validator/blob/f6fcdc53452512869116370232ecabcfa1ce8c8e/test/functional/nested-validation.spec.ts#L25

**Comment by diosney** [comment]
@jacktuck I did tested it, see comment above, but was too cumbersome to maintain all the duplicated code.

I ended up using `ajv` https://ajv.js.org, super happy with it until now.
