### ISSUE TITLE
[Question] Is there a way to define a callback function for `validate` that would extend custom decorators?

### ISSUE THREAD

**Issue by XanderEmu** [typestack/class-validator#319]
I'd like to add a custom decorator that would check if e.g. an email is unique. To do so, the validator would need to access a database. 

Since my dependency injection container is not global, I'd imagine I'd have to pass a callback function to a validate function (or a Validator class instance) that would access a proper service and ask for an email uniqueness.

Is that possible with class-validator?

**Comment by vlapo** [comment]
Hi @XanderEmu, 

You have to write your own async validator:
 - https://github.com/typestack/class-validator#custom-validation-classes
 - https://github.com/typestack/class-validator#custom-validation-decorators

**Comment by XanderEmu** [comment]
This might work and there's actually an example in docs, however, this example assumes that I used the globally available container and I don't.

For a decorator to have access to my container I'd have to configure it differently, maybe add something to the `validate`/`validateOrReject` function that could react to rules defined in decorators. In this case, the decorator would only define that the email is supposed to be unique, while additional callback passed to the validate function could react to that and perform the actual check.

**Comment by vlapo** [comment]
I see what you mean now. Maybe global validation context I mentioned here https://github.com/typestack/class-validator/pull/584#issuecomment-616165389 should resolve your problem. But it is just in phase of idea.

**Comment by NoNameProvided** [comment]
This is not possible currently. 

If this is something you are still interested in, please open a [feature idea discussion](https://github.com/typestack/class-validator/discussions/categories/feature-ideas) so the community can brainstorm, iterate, define the ideal API and reach a consensus about this should work.

Some items to consider:
- how other decorators with multiple inputs handle this currently
- what is the problem with the current solution
- how would an improved solution look like
- how can we handle backward compatibility
- how other frameworks handle this (if applies)

The end goal of the discussion should be to define an elegant solution with consensus from the community.
