### ISSUE TITLE
IsEmail issues (maybe validator.js dependency)

### ISSUE THREAD

**Issue by artmadeit** [typestack/class-validator#321]
I create a small sample for testing `@IsEmail` decorator

```typescript
import { IsString, MaxLength, IsEmail, Length, validate } from 'class-validator'

class CreateUserInput {
  @IsString()
  @MaxLength(20)
  name: string;
  @IsEmail()
  email: string;
  @Length(6, 20)
  password: string;
}

let post = new CreateUserInput();
post.email = "andre@gmail.com"; // should not pass

validate(post).then(errors => { // errors is an array of validation errors
    if (errors.length > 0) {
        console.log("validation failed. errors: ", errors);
    } else {
        console.log("validation succeed");
    }
});
```
Sadly andre@gmail.com is not working...
I also test that with validator.js `10.11.0` , is last version... and it works perfectly

```js
import * as validator from 'validator';

console.log(validator.isEmail('holla@gmail.com'))
console.log(validator.isEmail('andre@gmail.com'))
```

Pd: When I use the current version of validator.js used by class-validator, which is `10.4.0`...it also fails. So is probably an upgrade version issue.
pd2: sorry for my bad English, i'm from Perú...

**Comment by davidolivier1337** [comment]
Hi, 
I got the same issue,

Fixed here: https://github.com/typestack/class-validator/pull/333

**Comment by vlapo** [comment]
Close as https://github.com/typestack/class-validator/pull/378 is merged. Feel free reopen if the problem persists
