### ISSUE TITLE
Validate extra params.

### ISSUE THREAD

**Issue by yantrab** [typestack/class-validator#322]
Hi, there is an option, that prevent from client to add extra params to my request?

for example, if i have this class:

```
export class LoginRequest {
    @IsEmail()
    email:string;

    @Length(5, 10)
    password: string;
}
```

i wont to this `{email:"some@some.com",password:123456, extra:1} `to be fails .

**Comment by ningacoding** [comment]
i came here by the same type of issue

import { IsString, IsInt, IsBoolean, IsNotEmpty, IsEmpty } from 'class-validator';

```
export class ConversationDto {

  @IsInt()
  @IsNotEmpty()
  readonly id: number;

  @IsBoolean()
  readonly enabled: boolean;

  // @ts-ignore
  @IsEmpty()
  public [x: string]: any; // <- this should validate any other property is empty/null/undefined

}

```

**Comment by ningacoding** [comment]
take a look of:

https://github.com/typestack/class-validator#passing-options

with the option

`forbidUnknownValues?: boolean;`

But is not working

**Comment by yantrab** [comment]
`forbidUnknownValues `work for me.

**Comment by vlapo** [comment]
Seems like resolved.
