### ISSUE TITLE
`getFromContainer` is called too early

### ISSUE THREAD

**Issue by satanTime** [typestack/class-validator#328]
When I want to use own container, I call it in my `index.ts`
```typescript
import {useContainer} from 'class-validator';
import {Container} from 'typedi';

useContainer(Container);
```
but the problem is, that `MetadataStorage` in this case will be replaced with a brand new instance of `MetadataStorage`, because the call of `useContainer` is made after all annotations have been parsed and my `Container` from `typedi` doesn't them yet and wasn't used to collect them. Therefore the conclusion that we can't use `MetadataStorage` and `getContainer`, and should exclude it from the `getFromContainer `.

The problem is caused by decorators from `src/decorator/decorators.ts` because they use `getFromContainer(MetadataStorage)` too early, before the very first place where we could call `useContainer`.

Currently I investigated `class-transformer` because it doesn't have this issue, looks like it happens because it uses own `MetadataStorage` without container.

I've created a pull request to fix the issue, please check it and let me know what you think.

Thank you in advance.

**Comment by humbertowoody** [comment]
Same problem here! Without calling `useContainer` everything works just fine.

**Comment by satanTime** [comment]
Possible fix: https://github.com/typestack/class-validator/pull/335

**Comment by jotamorais** [comment]
@satanTime and @humbertowoody, can you please test again using the pre-release version [`0.8.1-alpha.2`](https://github.com/typestack/routing-controllers/releases/tag/0.8.1-alpha.2) and let me know how it goes?

I've published the [pre-release](https://www.npmjs.com/package/routing-controllers/v/0.8.1-alpha.2) to NPM to make it easier to test.

**Comment by satanTime** [comment]
Hi @jotamorais, the problem is not with the `routing-controllers` but with the `class-validator`. If you check how `routing-controllers` and and `class-validator` gather metadata from decorators you can see that actually `routing-controllers` does it directly to the `MetadataArgsStorage` (without `getFromContainer` call) and `class-validator` uses own `getFromContainer` to get `MetadataStorage` object. More info you can find in the https://github.com/typestack/class-validator/pull/335. The pull request simply changes behaviour of gathering data into `MetadataStorage` to the same way as `routing-controllers` does, directly without `getFromContainer`.

**Comment by satanTime** [comment]
Hi @vlapo, 

could you leave any thoughts or to point to the right person for the review?

Implementation in routing-controllers was changed a bit, you can find it here:
https://github.com/typestack/routing-controllers/blob/master/src/index.ts#L103-L108

Implementation in typeorm is quite the same:
https://github.com/typeorm/typeorm/blob/master/src/index.ts#L176-L190

Please let me know which way you prefer and I'll update my PR.

**Comment by satanTime** [comment]
Hi @vlapo, any update?

**Comment by satanTime** [comment]
Hi @jotamorais,

do you know anyone from `class-validator` I could ping for the review?

**Comment by satanTime** [comment]
Hi, any update on this?

**Comment by vlapo** [comment]
Happy testing https://www.npmjs.com/package/class-validator/v/0.12.0-rc.0. Please give me a feedback.

**Comment by satanTime** [comment]
On my project it works well now with `useContainer(container);` without any extra magic.
