### ISSUE TITLE
Validation on array according to index?

### ISSUE THREAD

**Issue by abhyuditjain** [typestack/class-validator#332]
Let's say, my DTO is this: 

```
export class CoordinatesDTO {
    @IsString({ message: 'Type must be a string' })
    @IsEnum(['Point'], { message: `Type must contain only ${['Point']}` })
    readonly type: string;

    @IsArray({ message: 'Coordinates must be an array' })
    @ArrayMinSize(2, { message: 'Coordinates array must be of size 2' })
    @ArrayMaxSize(2, { message: 'Coordinates array must be of size 2' })
    readonly coordinates: number[];
}
```

It represents a GeoJSON. I want  to validate that `coordinates[0]` be in range `[-180, 180]` and `coordinates[1]` be in range of `[-90, 90]`.

Can this be achieved?

**Comment by vlapo** [comment]
In this case you have to write your own custom validator/decorator 
 - https://github.com/typestack/class-validator#custom-validation-classes, 
 - https://github.com/typestack/class-validator#custom-validation-decorators

**Comment by NoNameProvided** [comment]
As mentioned a custom validator is required for this. Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
