### ISSUE TITLE
Use custom validations with json-schema file

### ISSUE THREAD

**Issue by christophercr** [typestack/class-validator#34]
Hi,

Currently, it is not possible to use custom validations with json-schemas in a JSON file.

Eventhough you can specify this in your schema file:

```
{
"name": "mySchema",
  "properties": {
      "myProperty": [
       { "type": "customValidation", "constraintCls": "myConstraintClass" }
      ],
  }
}
```

The custom constraint class is not picked up so the custom validation is not performed.

This does work when you use an schema object rather than a json file. so it seems that the mechanism that picks up the metadatas, expects an actual class in the "constraintCls" field of the schema, but for obvious reasons you can't provide such class instance in a JSON file.

**Comment by pleerock** [comment]
Each custom validation may have a name, take a look on `@ValidatorConstraint` decorator - it accepts optional name. if name is not given, then its generated from the class name. So, I think its possible to specify a custom validation name in the schema.

**Comment by christophercr** [comment]
sorry, I didn't put the full example in my previos comment. In fact I do use the @ValidatorConstraint({ name: "myConstraintClass"}) like this:

```javascript
@ValidatorConstraint({name: "myConstraintClass", async: false})
export class MyConstraintClass implements ValidatorConstraintInterface {
   validate(...) { ... }
   defaultMessage(...) { ... }
}
```

So in the json file I have something like this:

```json
{
"name": "mySchema",
  "properties": {
      "myProperty": [
       { "type": "customValidation", "constraintCls": "myConstraintClass" }
      ],
  }
}
```

But the custom constraint is not picked up so it is not performed.

**Comment by pleerock** [comment]
so it looks like it should work, but it does not work yet because its not implemented, and you suggest to implement it?

**Comment by christophercr** [comment]
Well, I expected it to work since the same scenario using a json object works. Because of that and also thinking about consistency, you should be able to use custom validations in a JSON file as well right?

**Comment by pleerock** [comment]
Looks like this [feature it not supported yet](https://github.com/pleerock/class-validator/blob/master/src/validation-schema/ValidationSchema.ts#L20), there is no "constraintCls" thing. And yeah we should make it to work because schema validation also should support this feature.

**Comment by Piliponful** [comment]
Is it added yet?

**Comment by braaar** [comment]
Schema based validation has been deprecated: https://github.com/typestack/class-validator/commit/7cd7546fe965ea668b49feccf435badc130d9490

Could you close this, @christophercr?

**Comment by christophercr** [comment]
Alright, thanks for the heads up :wink:
