### ISSUE TITLE
Validation not working on Partial class

### ISSUE THREAD

**Issue by mdhelaluddin-ctg-bd** [typestack/class-validator#344]
In nestjs If I use dto class as Partial<UseDTO> validation not applying to any column. I mean validation totally not working!

**user.dto.ts**

```
import { IsString, IsNotEmpty, IsEmail } from "class-validator";

export class UserDTO {

    @IsNotEmpty()
    @IsString()
    readonly name: string;

    @IsEmail()
    readonly email: string;

    @IsNotEmpty()
    @IsString()
    readonly password: string;
}
```

**user.controller.ts**

```
@Put(':id')
    @UsePipes(new ValidationPipe())
    update(@Param('id') id: string, @Body() data: Partial<UserDTO>) {
        Logger.log(data, "PRODUCT_CONTROLLER_UPDATE")
        return this.userService.update(id, data);
}
```

**Comment by nolazybits** [comment]
I would really like this one too...

**Comment by vlapo** [comment]
I think this is issue for `nestjs` and `class-transformer`. `class-validator` just validate input class. 

This is problem of transforming body data into `Partial<XY>` class. Check this https://github.com/typestack/class-transformer#working-with-generics.
