### ISSUE TITLE
ValidateIf not work

### ISSUE THREAD

**Issue by zieglar** [typestack/class-validator#345]
```
@ValidateIf(o => o.type === 'doctor')
@IsNotEmpty()
@Column({nullable: true})
testcolumn: string;
```
this code not check if type === doctor.

**Comment by vlapo** [comment]
I tested it and it works. please check object passed into validation. If you still experience this issue please add small class and example of input data here.

**Comment by dantehemerson** [comment]
@vlapo  Yes, i tested and it works. @zieglar please provide context and an example to reproduce the issue.

**Comment by zieglar** [comment]
```
export class MyTestClass {
  fillLate: boolean;

  @ValidateIf(o => o.fillLate === false)
  @IsNotEmpty({ groups: [CREATE] })
  @IsOptional({ groups: [UPDATE] })
  visitType: VisitType;

  @ValidateIf(o => o.fillLate === false)
  @IsNotEmpty({ groups: [CREATE] })
  employeeId: string;
}
```
when fillLate is false, `"isNotEmpty": "employeeId should not be empty"` 
when fillLate is true,  `"isNotEmpty": "visitType should not be empty"`

@dantehemerson @vlapo please test it

**Comment by zieglar** [comment]
if IsNotEmpty has groups option, ValidateIf can't work

**Comment by vlapo** [comment]
Problem is with `@ValidateIf` options. You have to specify which groups to work with. So you have to change your class like this:
```ts
class MyTestClass {
    fillLate: boolean;

    @ValidateIf(o => o.fillLate === false, { groups: ["create", "update"] })
    @IsNotEmpty({ groups: ["create"] })
    @IsOptional({ groups: ["update"] })
    visitType: VisitType;

    @ValidateIf(o => o.fillLate === false, { groups: ["create", "update"] })
    @IsNotEmpty({ groups: ["create"] })
    employeeId: string;
}
```
Now `class-validator` know about groups in context of `ValidateIf`

**Comment by vlapo** [comment]
Also you can use `always` option:
```ts
@ValidateIf(o => o.fillLate === false, { always: true })
```

**Comment by zieglar** [comment]
> Also you can use `always` option:
> 
> ```ts
> @ValidateIf(o => o.fillLate === false, { always: true })
> ```

please complete document

**Comment by vlapo** [comment]
```
There is also a special flag always: true in validation options that you can use. This flag says that this validation must be applied always no matter which group is used.
```
There is already note under example :)

**Comment by vlapo** [comment]
Looks like problem is solved. Reopen if necessary
