### ISSUE TITLE
@IsOptional cannot work with @MinLength()

### ISSUE THREAD

**Issue by nikdale** [typestack/class-validator#347]
Hello, I've tried using this too together but it's not pssoible.
```
@IsOptional()
@MinLength(3)
comment: string;
```
So, the ide was to MinLength work only if comment is present. If it's not present the length should not be important. It gives "must be at least 3 chars long error"

**Comment by vlapo** [comment]
Hy @nikdale I tested this and I am sure you are passing empty string into `comment` property. As described here https://github.com/typestack/class-validator/pull/110 `@IsOptional` will omit only `undefined` and `null` values. Empty string will pass and `@MinLength(3)` will throw error.

**Comment by nikdale** [comment]
Unfortunately, no. I'm not sending anything.
I'm checking that currently on req. 
Thanks anyway! It can be closed for now.
