### ISSUE TITLE
Empty object accepted as valid

### ISSUE THREAD

**Issue by ismayilmalik** [typestack/class-validator#349]
I have class like this:

```javascript
export class CreateAccountInput {
  @IsDefined()
  @IsNotEmpty()
  @Length(3, 50)
  firstName: string;

  @IsDefined()
  @IsNotEmpty()
  @Length(3, 50)
  lastName: string;

  @IsDefined()
  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @Min(8)
  password: string;
}
```
`validate` function accepts empty object `{}` as valid.
```javascript
const errors = await validate(input, { skipMissingProperties: true });
    console.log('err', errors)
```

console logs `[]`.
Am I doing something wrong?

**Comment by NoNameProvided** [comment]
You can enable the `forbidUnknownValues` option to prevent this behavior. From the docs: 

> It's highly advised to enable on forbidUnknownValues what prevent unknown objects to pass validation.

It's not turned on by default because it would be a breaking change.

**Comment by vlapo** [comment]
Closed for lack of response from reporter.
