### ISSUE TITLE
Support validating parameter properties

### ISSUE THREAD

**Issue by raffomania** [typestack/class-validator#350]
When using the `--strictPropertyInitialization` flag, I often assign properties in a classes constructor:
```ts
class User {
  @IsEmail()
  email: string;

  constructor(email: string) {
    this.email = email;
  }
}
```

To avoid repetition, I like to use parameter properties:

```ts
class User {
  constructor(
    public email: string
  ) { }
}
```
however, class-validator doesn't seem to support annotating these parameters. I would like to use them like this:
```ts
class User {
  constructor(
    @IsEmail
    public email: string
  ) { }
}
```

**Comment by npwork** [comment]
+1 Really useful feature!!!

**Comment by NoNameProvided** [comment]
You can use the definite assignment assertion (`!`) to tell Typescript it will be assigned later.

```ts
class User {
  @IsEmail()
  email!: string;
}
```

The above code will compile successfully with `--strictPropertyInitialization` option enabled.

**Comment by raffomania** [comment]
that's cool, but in my case I actually need the constructor for other places where class-validator is not used. This forces me to add an extra line for every property to get that constructor.

**Comment by NoNameProvided** [comment]
I don't understand what do you mean. 

> This forces me to add an extra line for every property to get that constructor.

Your example needs extra line, in mine the constructor can be omitted as it's empty.

**Comment by raffomania** [comment]
I mean that I have to include the extra line *in cases where I need a constructor*. I need a constructor when initializing my object in unit tests, for example. 
So if I already need to write the constructor, it would be nice to be able to omit the property declaration and only include the constructor.

**Comment by NoNameProvided** [comment]
It's an entirely different scenario to validate constructor properties during class creation than validating existing classes. This library won't support that format because we have `class-transformer` for class creation. So this library will always check the properties of existing class instances.

**Comment by raffomania** [comment]
I'm perfectly happy validating existing classes, there's nothing that needs to happen during class creation. I just want to put the decorators from `class-validator` in a different spot.

The normal decorators `class-validator` uses are "property decorators". I would like to have support for [parameter decorators](https://www.typescriptlang.org/docs/handbook/decorators.html#parameter-decorators). These should automatically work with constructors.
