### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by ramoncr** [typestack/class-validator#354]
Hello,

We are interested in using your package, although we were not able to find any licensing file. We already found the license type as described in: https://github.com/typestack/class-validator/issues/289. 

Would it be possible to add a licensing file to the repository? 

Thank you, we really appreciate the work!

**Comment by vlapo** [comment]
I think this is possible. PR created.

**Comment by ramoncr** [comment]
Thank you! We will wait for the PR

**Comment by megamen909** [comment]
Is there any indication of when this will be released?

**Comment by vlapo** [comment]
I hope soon. For now merged.
