### ISSUE TITLE
How to read the declared metadata on a field or prop ?

### ISSUE THREAD

**Issue by binaryangel-noa** [typestack/class-validator#356]
Hi,

is there a way to get the initially declared Metadata on a decorator ?,
For example with the MaxLength decorator. MaxLength(255, { message: "somemessage" }) ,
i am looking for a way to retrive that 255 .

Thanks alot!

**Comment by LiamEntrostat** [comment]
I'm also interested in this, I'm trying to generate forms with required fields using the @IsDefined decorator metadata.

**Comment by vlapo** [comment]
You have to use internal API to get this kind of data. Check a code and how internally `class-validator` works/store data you need.

**Comment by LiamEntrostat** [comment]
Hey again, 

I spent a bit of time looking at this today and the best I could come up with is the following:

```typescript
import { getFromContainer, MetadataStorage } from 'class-validator';

const validatorStorage: MetadataStorage = getFromContainer(MetadataStorage);

const createUserDtoValidationMetadata = validatorStorage.getTargetValidationMetadatas(CreateUserDto, null, null);

console.log(validatorStorage.groupByPropertyName(createUserDtoValidationMetadata));
```

For reference here is what the CreateUserDto looks like:

```typescript
export class CreateUserDto {
    @IsString({
        message: 'Name must be a text value'
    })
    name: string;
    @IsString({
        message: 'Surname must be a text value'
    })
    surname: string;
    @IsString()
    @IsOptional()
    password?: string;
    @IsEmail()
    email: string;
    @IsString()
    type: UserType;
    @IsOptional()
    @IsString()
    cellphoneNumber?: string;
}
```

**Comment by Flashantik** [comment]
> Hey again,
> 
> I spent a bit of time looking at this today and the best I could come up with is the following:
> 
> ```ts
> import { getFromContainer, MetadataStorage } from 'class-validator';
> 
> const validatorStorage: MetadataStorage = getFromContainer(MetadataStorage);
> 
> const createUserDtoValidationMetadata = validatorStorage.getTargetValidationMetadatas(CreateUserDto, null, null);
> 
> console.log(validatorStorage.groupByPropertyName(createUserDtoValidationMetadata));
> ```
> 
> For reference here is what the CreateUserDto looks like:
> 
> ```ts
> export class CreateUserDto {
>     @IsString({
>         message: 'Name must be a text value'
>     })
>     name: string;
>     @IsString({
>         message: 'Surname must be a text value'
>     })
>     surname: string;
>     @IsString()
>     @IsOptional()
>     password?: string;
>     @IsEmail()
>     email: string;
>     @IsString()
>     type: UserType;
>     @IsOptional()
>     @IsString()
>     cellphoneNumber?: string;
> }
> ```

Unfortunately, this solution does not work at the moment.

**Comment by joelybahh** [comment]
Is there any update on this? We are looking to generate a form using this metadata, as we have a mono-repo, all of our types are easily accessible between our frontend/backend apps, figured there must be a way to get the decorator data somehow, has anyone figured this out?

**Comment by NoNameProvided** [comment]
We do not expose the metadata about classes officially but you can access it. Keep in mind that this API is considered private and can break without any mention in the changelog.
