### ISSUE TITLE
[question] Does object to validate have to be instance of class

### ISSUE THREAD

**Issue by davidjohnbell** [typestack/class-validator#357]
I am looking into this library and wondering if someone can answer some quick questions for me. I am using Express and TypeOrm:
1. is it possible to validate the request body as an object literal against a class? 
2. If not, do you recommend just dereferencing the properties from the request body assign and then validate them?
3. Using your validateSync method I would like to throw an error right away in the format \``property ${key} expected type ${expected} but got ${type}`\` whats the best pattern for this?

Thank you in advance, really cool!

**Comment by vlapo** [comment]
> 1. is it possible to validate the request body as an object literal against a class?
> 2. If not, do you recommend just dereferencing the properties from the request body assign and then validate them?

You have to use `class-transformer` library and convert JSON into instance of class and then validate. Or validate JSON without decorators using https://github.com/typestack/class-validator#defining-validation-schema-without-decorators

> Using your validateSync method I would like to throw an error right away in the format `property ${key} expected type ${expected} but got ${type}` whats the best pattern for this?

We have method `validateOrReject` but it will throw `ValidationError` object. So you have to check this object and extract only first constraint message.

**Comment by davidjohnbell** [comment]
@vlapo thanks!
