### ISSUE TITLE
Cross-field validation

### ISSUE THREAD

**Issue by Carlovan** [typestack/class-validator#362]
I need to check a field value relatively to another field. I have this

    class Event {
        startTimestamp: number;
        endTimestamp: number;
    }

and I want `endTimestamp` to be greater than `startTimestamp`.

This should be similar to [Joi references](https://github.com/hapijs/joi/blob/v15.0.3/API.md#refkey-options)

**Comment by vlapo** [comment]
I think this is pretty well documented here https://github.com/typestack/class-validator#custom-validation-decorators. It is exact example with custom cross-field validation

**Comment by vlapo** [comment]
@Carlovan Did custom validator resolve your problem?

**Comment by Carlovan** [comment]
It did! Thank you for the support
