### ISSUE TITLE
Schema string validation breaking for nulls

### ISSUE THREAD

**Issue by pedrodagraca** [typestack/class-validator#363]
I've noticed when using schema validation, all string based validators return false if the value is null or undefined. As an example. I have a field that is not required and has a max length of 128. I create the following validation schema....
```

export let ChecklistQuestionValidationSchema: ValidationSchema = {
  name: "ChecklistQuestionSchema",
  
  properties: {
    question: [
      {
        type: "maxLength", constraints: [500], message: "validationGenericMaxLength"
      }]
  }
};
```
This fails if the "question" property is null, because of the following lines of code in Validator.js...

```
   Validator.prototype.maxLength = function (value, max) {
        return typeof value === "string" && this.length(value, 0, max);
    };
```

Surely it should be something like this

```
Validator.prototype.maxLength = function (value, max) {
		if (value===undefined || value===null || value === "")
			return true;

        return typeof value === "string" && this.length(value, 0, max);
    };
```

And then you can use the IsNotEmpty validator if the field is also required?

**Comment by vlapo** [comment]
I think you have to use `IsOptional` validator in combination with your `maxLength` validator. As docs says:
```
@IsOptional() | Checks if given value is empty (=== null, === undefined) and if so, ignores all the validators on the property.
```
It is current behaviour of `class-validator`. If you want accept `null` and `undefined` you have to mark property as optional. 
Maybe I am wrong and someone will kick me.

**Comment by vlapo** [comment]
@pedrodagraca Did you resolve your problem?

**Comment by vlapo** [comment]
Close as no answer from reporter.
