### ISSUE TITLE
Mobile phone number validation

### ISSUE THREAD

**Issue by oreshkoandrei** [typestack/class-validator#366]
Hello !
Is there a way to validate any mobile phone number without explicitly setting regions?
I just want to check, that string is a mobile phone number.

**Comment by vlapo** [comment]
Did you try this?
```ts
@IsMobilePhone("any")
```
From docs:
```
@IsMobilePhone(locale: string) | Checks if the string is a mobile phone number.
```

**Comment by oreshkoandrei** [comment]
No, i didn't, but I will, thanks

чт, 13 июн. 2019 г., 23:42 Vlad Poluch <notifications@github.com>:

**Comment by oreshkoandrei** [comment]
So, IsMobilePhone("any") do not works properly
It says, that '3' is not ok, '33' is not ok, but '333' is ok
But looks like it works good, if i enter '+' symbol as the first string symbol

btw, i try to check mobile phone through schema using this structure:
        phoneNumber: [{
            type: 'isMobilePhone',
            constraints: ['any']
        }],

Maybe, i'm doing something wrong ?

**Comment by vlapo** [comment]
`class-validator` use https://www.npmjs.com/package/google-libphonenumber to check phone numbers. Maybe check there what format is supported. But I think lead `+` is international standard.

I think your schema structure is ok.

**Comment by vlapo** [comment]
@oreshkoandrei Did you resolve your problem?

**Comment by oreshkoandrei** [comment]
yeah, sorry for the delay
