### ISSUE TITLE
question: how validate array of objects with validation schema

### ISSUE THREAD

**Issue by Demogorrgon** [typestack/class-validator#368]
Hi
I can't find any info how can i use validation schema with property, that represents an array of objects with determined properties. Could someone help me plz ? Thanks

**Comment by oreshkoandrei** [comment]
Any update on this ?

**Comment by Christo676** [comment]
Any update on this? Same problem over here. 

```
[
{},
{},
{}
]
```

**Comment by dantehemerson** [comment]
An example of validation that you want to do?
I use for Arrays: 
```
@ValidateNested()
@Type(() => ReqSegmentationVariableRuleDto)
```

**Comment by oreshkoandrei** [comment]
> An example of validation that you want to do?
> I use for Arrays:
> `ValidateNested` and `Type`(from [class-transformer](https://github.com/typestack/class-transformer))
> Ejm:
> 
> ```
> class DtoToValidate {
>     @IsString()
>     Field: string
> }
> 
> class ReqArrayValidation {
>     @ValidateNested()
>     @Type(() => DtoToValidate)
>     Elements: Array<DtoToValidate>
> }
> ```

i guess, this is not about schemas

**Comment by NoNameProvided** [comment]
The validation schema is deprecated and will be removed.
