### ISSUE TITLE
how to validate like this

### ISSUE THREAD

**Issue by adminparry** [typestack/class-validator#371]
```ts
export class RolesAddVo {
   @IsString()
    name: string;
    @IsString()
    detail: string;
    @IsEmpty()
    [x: string]: any;
}
```

i want to validate exclude props must be empty

**Comment by vlapo** [comment]
I think you are searching for https://github.com/typestack/class-validator#whitelisting
> If you would rather to have an error thrown when any non-whitelisted properties are present, pass another flag to validate method:
> ```ts
> import {validate} from "class-validator";
> // ...
> validate(post, { whitelist: true, forbidNonWhitelisted: true });
> ```

**Comment by adminparry** [comment]
Thanks for your response. This is can be resolve for my question
