### ISSUE TITLE
IsDate and isDateString are failing

### ISSUE THREAD

**Issue by anwarhamr** [typestack/class-validator#373]
I'm getting this error "VitalsByDateRangePathDTO.startDate is $constraint1 characters, but actual is 2015-05-01"

using node `new Date('2015-05-01')` returns 2015-05-05T00:00:00.000Z
I can't seem to get either decorator to work.  Please help.

my code
``` 
   @IsDateString({ // here, $constraint1 will be replaced with "10", and $value with actual supplied value
    message: `$target.$property is $constraint1 characters, but actual is $value`
  })
  @IsNotEmpty()
  @ApiModelProperty({ required: true, description: 'an starting date for vitals for the patient' })
  endDate: Date;
```

**Comment by vlapo** [comment]
`@IsDateString` validate string not a `Date` object. If `endDate` is a string `2015-05-0` current implementation of `IsDateString` do not support partial date strings (only full iso date string `2015-05-05T00:00:00.000Z`) Related issue - https://github.com/typestack/class-validator/issues/387

**Comment by vlapo** [comment]
@anwarhamr Did you resolve your issue?

**Comment by anwarhamr** [comment]
I did, I was able to use @Type from class-transformer to convert the value to date then it worked
```
  @IsOptional()
  @IsDate()
  @Type(() => Date)
  startDate: Date;
```
