### ISSUE TITLE
How to validate nested arrays

### ISSUE THREAD

**Issue by lkostrowski** [typestack/class-validator#374]
Hi, I want to create a deeper structure like this

```
class InnerDTO {
  @IsString()
  foo: string;
}
```

and later have outer one

```
class OuterDTO {
  @ValidateNested()
  outer: InnerDTO[]
}

```

I tried several combitantions, including `ValidateNested({each: true})`, adding `IsArray`, `IsArray({each: true})`

None of them is working - validation is passing even if `foo` is not there

**Comment by vlapo** [comment]
We use in prod: 
```ts
@IsArray()
@ValidateNested({ each: true })
@Type(() => ImageDataObjectDto)
```
and it works. Are you sure your `outer` is filled with array of `InnerDTO ` objects?

**Comment by lkostrowski** [comment]
I added you example and I guess `@Type` did the job. 
I see this is a part of the class-transformer, so I will check it deeper. Maybe worth to add some cross-links to the docs?
