### ISSUE TITLE
Validate Array Of object In which Object have some properties I have to check that one property contains specific value 

### ISSUE THREAD

**Issue by ankurgupta12** [typestack/class-validator#375]
Lets suppose I have Json Example .
{
"vgwGroups": ["service"],
    "basicSetContainer": {
      "serviceUserData": [
        {
	        "company": "ankur",
          "firstName": "初",
          "lastName": "RASecond",
          "userId": "98218145",
          "mail": "abctest@com",
          "type": "contactMain",
          "role": "zDeveloper"
        },
         {
          "company": "ankuu",
          "firstName": "初",
          "lastName": "RASecond",
          "userId": "98218145",
          "mail": "abctest@.com",
          "type": "contactSub",
          "role": "ankur"
        }
      ]
    }
  }
Now I want that In  serviceUserData Array of object have type property contains some specific value such as service . This particular value is unique ie. it should be in only single object other object can have some different values

**Comment by vlapo** [comment]
Please format your post.

I think you have to write your own validator https://github.com/typestack/class-validator#custom-validation-decorators and use them on `serviceUserData` property.

**Comment by vlapo** [comment]
@ankurgupta12 Did custom validator resolve your problem?

**Comment by vlapo** [comment]
Closing this out due to inactivity. Please file a new issue if you are encountering a similar or related problem.
