### ISSUE TITLE
Unclear how to apply Max/Min to number string

### ISSUE THREAD

**Issue by jcford73** [typestack/class-validator#376]
I have numeric parameters coming in as strings, but I need to restrict their range. How can I accomplish this?

```
@IsNumberString()
@Min(1)
@Max(12)
month: int;
```
The above fails validation even if the value of the number string is within the range.

**Comment by vlapo** [comment]
You should use `class-transformer` and convert string into number.
```ts
@IsNumber()
@Min(1)
@Max(12)
@Type(() => Number)
month: number;
```
Otherwise you have to create custom validator.

**Comment by vlapo** [comment]
@jcford73 Did `class-transformer` resolve your problem?

**Comment by julianomqs** [comment]
Not the OP but confirming @vlapo suggestion works.

**Comment by vlapo** [comment]
Close for no answer from author. @julianomqs thank you for confirming :)
