### ISSUE TITLE
Validating nested subtypes

### ISSUE THREAD

**Issue by danloiterton** [typestack/class-validator#385]
I was hoping I could validate a nested property using it's subtype (in combination with the class-transformer `@Type` decorator)

However,  this doesn't seem to work:
```
export class TaskDTO {
   
   @IsNotEmpty()
   @IsEnum(TaskType)
   taskType: TaskType;

   @IsNotEmpty()
   @ValidateNested()
   @Type(() => TaskLinks, {
      discriminator: {
         property: 'taskType',
         subTypes: [
            { value: TaskType1Links, name: TaskType.TASK_TYPE1 },
            { value: TaskType2Links, name: TaskType.TASK_TYPE2 },
         ],
      },
   })
   taskLinks: TaskLinks;
}

export class TaskLinks {}

export class TaskType1Links extends TaskLinks {
   @IsNotEmpty() someProp1: string;
   @IsNotEmpty() someProp2: string;
}

export class TaskType2Links extends TaskLinks {
   @IsNotEmpty() someProp3: string;
}
```

However, when I send an object like: 
```
{ taskType:'TASK_TYPE1', taskLinks: {} }
```
validation does not fail. 

Is this expected behaviour or am I missing something? I was hoping it would fail if I did not pass all the properties required in the nested subtype.

**Comment by vlapo** [comment]
Problem is in your code. You need `taskType` inside of `TaskLinks` not in `TaskDTO`. Check https://github.com/typestack/class-transformer#providing-more-than-one-type-option again :)

Close as it is not in a scope of `class-validadtor`.

**Comment by danloiterton** [comment]
Ahh, right you are! Going blind.

Many thanks
