### ISSUE TITLE
skipMissing:true and error.target:false

### ISSUE THREAD

**Issue by jerradpatch** [typestack/class-validator#39]
Tried this but it doesnt seem to work, ie, the errors thrown by validation failure still have the "target" field.

``` javascript
validate(modelTradeByPartnerCountry,
                    {
                        skipMissingProperties: true,
                        error: { target: false }
                    })
```

**Comment by pleerock** [comment]
are you sure? Just checked it and seems to work fine. Even added test for this case: #4d5f31c

**Comment by pleerock** [comment]
did you fix your issue?

**Comment by jerradpatch** [comment]
Yes, I was spelling a key wrong, not sure if me or docs, but you helped me with your example.

**Comment by jerradpatch** [comment]
I think its the docs, this is what you have when you dont want the target to be exposed

validator.validate(post, { validationError: { target: false } });

should be

validator.validate(post,
                    {
                        error: { target: false }
                    })
