### ISSUE TITLE
Module has no exported member 'IsDecimal'

### ISSUE THREAD

**Issue by W4G1** [typestack/class-validator#393]
```typescript
import { IsDecimal } from 'class-validator'
```

Gives the error:
>Module '"path/to/node_modules/class-validator"' has no exported member 'IsDecimal'.ts(2305)

Other validators like `IsNumber` do exist and work though. Am I missing something?

**Comment by vlapo** [comment]
`IsDecimal` is new decorator in `0.10.0-rc.1`. I will publish `0.10.0` as stable version today :)
