### ISSUE TITLE
IsNumberString decorator doesn't accept IsNumericOptions

### ISSUE THREAD

**Issue by PachowStudios** [typestack/class-validator#400]
Release 0.1.0 made it so `isNumberString` on `Validator` accepts `IsNumericOptions`, but the `IsNumberString` decorator still doesn't have a parameter for these options.

**Comment by l2ubin** [comment]
it seems that decorater is missing the IsNumericOptions parameter. May be i can add that

**Comment by l2ubin** [comment]
added this on #406

**Comment by rubiin** [comment]
@vlapo  i have added this kindly see it

**Comment by rubiin** [comment]
@vlapo kindly check this one too
