### ISSUE TITLE
IsPort is missing validation error message

### ISSUE THREAD

**Issue by zavarka** [typestack/class-validator#403]
No error message is provided when `isPort` validation fails (#282).  If you could add message for `IS_PORT` that would be great!

https://github.com/typestack/class-validator/blob/35ec04daa7995439049d42c61006bd167661c5e8/src/validation/ValidationTypes.ts#L113

**Comment by l2ubin** [comment]
I have added that in this pr [#404 ]()

**Comment by l2ubin** [comment]
added that in pr [#404](https://github.com/typestack/class-validator/pull/404)

**Comment by vlapo** [comment]
Closed by #404
