### ISSUE TITLE
how can i use isDate()

### ISSUE THREAD

**Issue by a416237796** [typestack/class-validator#407]
I use the isDate() to verify whether "2019-09-18" is in date format, but I get false.
How can I use this func
What kind of characters can be verified
please help me， thanks alot

**Comment by l2ubin** [comment]
You can check the documentation

**Comment by vlapo** [comment]
For string dates you have to use `IsDateString` but you need full format date:

> Checks if a string is a complete representation of a date (e.g. "2017-06-07T14:34:08.700Z", "2017-06-07T14:34:08.700 or "2017-06-07T14:34:08+04:00").

We do not have validator for only date/month/year portion "2019-09-18". You have to write custom validator.

**Comment by vlapo** [comment]
Hey @a416237796. Please use `isISO8601` validator. `isISO8601` accepts also "only date string" formats - check https://en.wikipedia.org/wiki/ISO_8601

**Comment by a416237796** [comment]
> Hey @a416237796. Please use `isISO8601` validator. `isISO8601` accepts also "only date string" formats - check https://en.wikipedia.org/wiki/ISO_8601

thanks
