### ISSUE TITLE
[Feature Request] @IsCoordinate() / @IsLatitude() / @IsLongitude()

### ISSUE THREAD

**Issue by olafwrieden** [typestack/class-validator#415]
I was recently working with coordinates and thought of this helpful feature.

**Explanation**
Validating Latitude and Longitude is a frequent use case for many location-based applications and while `@Min()` and `@Max()` may be used in conjunction with lower and upper bounds respectively, a `@IsCoordinate()` solution would seem more appropriate.

**`@IsCoordinate(...)` Arguments**
Perhaps the data to be validated appears in comma-separated form (ie. `latitude, longitude`) so a boolean argument may tell the validation engine whether to check the input as singular lat/lng value or both in combination (as above).

**Possible Alternatives**
* `@IsLatitude()`
* `@IsLongitude()`

**Comment by rubiin** [comment]
@vlapo @NoNameProvided

**Comment by vlapo** [comment]
Sure why not. But I would like to follow some standards as e.g. https://en.wikipedia.org/wiki/ISO_6709. There is multiple formats and we should cover them all or say exactly what formats we support.

**Comment by rubiin** [comment]
@vlapo I think we can do like validatorjs https://github.com/validatorjs/validator.js/blob/master/lib/isLatLong.js

**Comment by vlapo** [comment]
If there is validator.js solution let`s adopt them. Maybe we should check all missing validators from validator.js.

**Comment by rubiin** [comment]
Yeah that seems right. If we adopt the solutions that are present, this reduces the encounter with bugs ,also we do not have to search around for solutions @vlapo

**Comment by rubiin** [comment]
I will be doing a pr in a while

**Comment by rubiin** [comment]
@vlapo @NoNameProvided  I have adopted validatorjs solutiona and made isLatLong() function for this. https://github.com/typestack/class-validator/pull/427 check this pull request
