### ISSUE TITLE
Groups Validator does not work when is used over the @Validate decorator

### ISSUE THREAD

**Issue by dmitrirussu** [typestack/class-validator#422]
if we try to create a custom validator function with a group, that is not working, once we remove group from over the Validator it ok
`@Validate(MyCustomValidator, {
    message: 'Invalid data',
   groups: ['myCustom']
  })
  customObject: object;`

Will not work
`    const errors = validateSync(MyCustomObject, { groups: ['myCustom'] }); `

**Comment by vlapo** [comment]
Create stackblitz with your example: https://stackblitz.com/edit/class-validator-gh-422?file=index.ts

```ts
@ValidatorConstraint({ name: "testConstraint", async: false })
class MyCustomValidator implements ValidatorConstraintInterface {
    validate(value: any) {
        return value.test === 'hello'
    }
}

export class Test {
   
    @Validate(MyCustomValidator, { message: 'Invalid data', groups: ['myCustom'] }) 
    customObject: object;
}

const test = new Test();
test.customObject = {test: 'not-hello'};

console.log(validateSync(test, {groups: ['myCustom'] }));

console.log(validateSync(test, {groups: ['myCustom2'] }));
```
First validation produce error and second one no. Look likes everything works. Am I missing something? Could you please create small reproduction of your problem?
