### ISSUE TITLE
Benchmark testing

### ISSUE THREAD

**Issue by moltar** [typestack/class-validator#423]
Hi,

I have been using `class-validator` and other similar runtime type checking libraries on various projects.

I decided to run some benchmarks on all of these libraries and do a write up about all of the options and pros and cons of each.

My preliminary results are [published in this repo](https://github.com/moltar/typescript-runtime-type-benchmarks).

I was wondering if you could take a look at that repo and see if the usage is fair and if I am not using the library in some disadvantaged way.

Here is `class-validator` specific test: https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/cases/class-validator.ts

The goal is to get the object validated and type guarded or returned type established.

Thanks!

**Comment by vlapo** [comment]
Hi @moltar, I think you use library as intended.
