### ISSUE TITLE
feat: new isLocale validator

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#425]
I was working on a project that passed the language header to request the response in desired language. However I could not find it in the class-validator. How about making one. Can do a pr

**Comment by rubiin** [comment]
@vlapo @NoNameProvided  what do you say?

**Comment by vlapo** [comment]
I think we have one PR about extending error messages https://github.com/typestack/class-validator/pull/238. But this is kind of advanced topic and I do not decide how to handle it, yet.

**Comment by rubiin** [comment]
i mean do we have something to check whether a given string is a valid language?

**Comment by rubiin** [comment]
i mean do we have something to check whether a given string is a valid language like isLanguage or isLocale ? @vlapo

**Comment by rubiin** [comment]
I checked validator.js but there is no such validator available perhaps we have to make a new one @vlapo

**Comment by vlapo** [comment]
Looks like there is FR https://github.com/validatorjs/validator.js/issues/954 and PR https://github.com/validatorjs/validator.js/pull/1072. I would like to wait and use validatorjs function (if PR will be merged in some reasonable time).

**Comment by arkus7** [comment]
@vlapo @rubiin mentioned PR has been merged :)

**Comment by rubiin** [comment]
@arkus7 thanks for the info. I will be doing a pr shortly

**Comment by johannesschobel** [comment]
merged but not released :D

**Comment by johannesschobel** [comment]
Dear @vlapo and @rubiin ,
the`isLocale()` function has now been released in `validatorjs 13.0.0`!

**Comment by rubiin** [comment]
let md work on that

**Comment by vlapo** [comment]
@rubiin please also create new added validators (isEthereumAddress, isIBAN, ...)

**Comment by rubiin** [comment]
Sure

**Comment by vlapo** [comment]
@rubiin please wait with this changes. I have one big PR with lot of changes almost ready.

**Comment by rubiin** [comment]
@vlapo sure

**Comment by vlapo** [comment]
@rubiin I synced validatorjs lib to v13 (isLocale included). Thank you for help with provide this new validator.
