### ISSUE TITLE
Validation pipe returns empty DTO object when dto object has no class validations

### ISSUE THREAD

**Issue by sindhurasadanand** [typestack/class-validator#426]
I am using a global validation pipe.

I have a DTO with no class validations->

export class UserDto {
  constructor(data: Map<string, string>) {
    this.data = data;
  }

  data: Map<string, string>;
}

await validate in Validation pipe returns an empty object and hence passes an empty input object to the controller. It works if I add a @isString or any decorator on top of data.

Eg, this works fine -
export class UserDto {
  constructor(data: Map<string, string>) {
    this.data = data;
  }
  @IsString({
    each: true,
  })
  data: Map<string, string>;
}

**Comment by vlapo** [comment]
Could you please format your code and provide options you pass to `ValidationPipe` ?

**Comment by vlapo** [comment]
Closed for lack of response from reporter.
