### ISSUE TITLE
@ValidateNested does not seem to work?

### ISSUE THREAD

**Issue by richarddd** [typestack/class-validator#431]
Using the latest version: **0.10.1**

Please check: https://codesandbox.io/s/gallant-wildflower-1pwls

```typescript
import { Validator } from "class-validator";
import { Post } from "./Post";
import { Tag } from "./Tag";

let validator = new Validator();

let tag1 = new Tag();
tag1.name = "ja";

let tag2 = new Tag();
tag2.name = "node.js";

let post1 = new Post();
post1.title = "Hello world";
post1.tags = [tag1, tag2];

validator.validate(post1).then(result => {
    console.log("1. should not pass: ", result);
});
```

The first example works fine.

But when you add some other object to tags validation does not fail:

```typescript
let post2 = new Post();
post2.title = "Hello world";
post2.tags = [1, 2] as any;

validator.validate(post2).then(result => {
    console.log("2. should not pass: ", result);
});
```

Furthermore, omitting tags altogether passes validation:
```typescript
let post2 = new Post();
post2.title = "Hello world";

validator.validate(post2).then(result => {
    console.log("2. should not pass: ", result);
});
```

Plese see this codesandbox to replicate the issue: 
https://codesandbox.io/s/gallant-wildflower-1pwls

**Comment by vlapo** [comment]
Hi @richarddd, 

Thank you for so detailed description and example.
But this is how `@ValidateNested()` works. It will not check instance type or array size. You have to define more validators. E.g.

```ts
export class Post {
  @Length(10, 20, {
    message: "Incorrect length!"
  })
  title!: string;

  @IsArray()
  @ArrayNotEmpty()
  @IsInstance(Tag, { each: true })
  @ValidateNested()
  tags!: Tag[];
}
```

This will check If:
- `tags` is not empty array
- all items in array are instance of `Tag` class

Hope this helps :)

**Comment by richarddd** [comment]
Thanks! Sorry for the missunderstanding!
