### ISSUE TITLE
@MinDate, @MaxDate and @IsDate decorator throw `date.getTime is not a function`

### ISSUE THREAD

**Issue by ccocoual** [typestack/class-validator#437]
Hi,

## Issue description

In a NodeJS app with NestJS and Typescript, I try to use decorators to validate my class properties but when I try to validate dates, an error is thrown `date.getTime is not a function`.

I tried to use the decorators and manual ways but still have the issue.
Here is a code sample of class creation with a unit test made with Jest.

## Code to reproduce the issue

__company.ts:__
```
import { MinDate, ValidationError, Validator } from 'class-validator';
import { isEmpty } from 'lodash';

export default class Company {
  @MinDate(new Date(1800, 1), {
    message: 'A company creation date must be after January 1st, 1800',
  })
  creationDate: Date;

  constructor(creationDate: Date) {
    this.creationDate = creationDate;

    this.validate();
  }

  private validate(): void {
    const validator: Validator = new Validator();
    const errors: ValidationError[] = validator.validateSync('Company', this);
    if (!isEmpty(errors)) {
      throw new DomainValidationError('Company creation error', errors);
    }
  }
}
```

__company.spec.ts__
```
import Company from '../company';

describe('ompany', () => {
    describe('creationDate', () => {
        it('should throw an exception when creationDate is before January 1st, 1800', () => {
            // given
            const creationDate: Date = new Date(1789, 7);

            // when
            const result = () => new Company(creationDate);

            // then
            expect(result).toThrow('Company creation error:\n - A company creation date must be after January 1st, 1800');
        });
    });
});
```

## Versions

Node v10.16.3
Npm 6.11.3

typescript@3.6.3
ts-jest@24.1.0
jest@24.9.0
class-validator@0.10.2

I don't understant what is happening as I pass a object instantiated with Date constructor and when I try to debug with breakpoints, prototype of `creationDate` have `getTime` implementation.

Thanks for your help.

**Comment by vlapo** [comment]
I tried your test and all works. Also our tests are passing. Could you please create reproduction of problem here https://stackblitz.com/edit/class-validator-boilerplate-gh437?file=index.ts ?

**Comment by ccocoual** [comment]
Thanks for the quick response. You are right, the mistake was due to a bad mocking for Date class in my test. 
Have a good day and thanks for the help.
