### ISSUE TITLE
Object as map

### ISSUE THREAD

**Issue by weristas** [typestack/class-validator#447]
Is it possible to validate an object as a map? I can not use js maps.

**Comment by vlapo** [comment]
I do not understand your question. Nested validation. https://github.com/typestack/class-validator#validating-nested-objects. Give me please some example if nested validation does not answer your question.

**Comment by marcalj** [comment]
How to validate this?

```ts
class B {
  @IsString()
  @IsNotEmpty()
  name: string;
}

class A {
  @IsNotEmpty()
  @ValidateNested({each: true})
  @Type(() => B)
  aMap: Map<string, B>;
}
```

This throws: ```TypeError: Cannot read property 'constructor' of null```

**Comment by vlapo** [comment]
@marcalj I think problem is in your Map property. One of the entry is null. Maybe related to https://github.com/typestack/class-validator/issues/312

Close as no answer from original issue creator.
