### ISSUE TITLE
how to use with nested elements

### ISSUE THREAD

**Issue by Egistar** [typestack/class-validator#455]
Hi there,

I´m new with this and I need to understand how to use with nested elements.

I have a jSON-Schema like this:

`{
   "name": {
         "firstName": "my firstname",
         "lastName": "my lastname"
   }
}`

I tried to validate with:

@IsString()
  public firstName?: string;
  public lastName?: string;

But I always get an error 400 that "firstName" must be a string.

How should I do the validation settings on this issue?

Thx to all...

**Comment by vlapo** [comment]
Please provide more informations (class definition, how do you transform data from json to class, ...) or minimal reproduction using [stackblitz](https://stackblitz.com/edit/class-validator-boilerplate-gh455?file=index.ts).

**Comment by Egistar** [comment]
I have a function sending request directly to the validation:

`import { plainToClass } from 'class-transformer';
import { validate, ValidationError } from 'class-validator';
import * as express from 'express';
import HttpException from '../exceptions/HttpException';

function validationMiddleware<T>(type: any, skipMissingProperties = false): express.RequestHandler { 
  return (req, res, next) => {     
    validate(plainToClass(type, req.body), { skipMissingProperties })
      .then((errors: ValidationError[]) => {
        if (errors.length > 0) {
          const message = errors.map((error: ValidationError) => Object.values(error.constraints)).join(', ');
          next(new HttpException(400, message));
        } else {
          next();
        }
      });
  };
}

export default validationMiddleware;`

My interface is looking like this

`interface Person {  
  name: {
    firstName: string,
    lastName: string,
  };
}
export default Person;
`
and my model:

'import * as mongoose from 'mongoose';
import Person from './person.interface';

const personSchema = new mongoose.Schema({
  name:{
    firstName: String,
    lastName: String,
  }
}, { collection: 'persons' });

const personModel = mongoose.model<Person & mongoose.Document>('Person', personSchema);

export default personModel;'


did this help?

**Comment by rubiin** [comment]
@Egistar please format the code as it is barely readble

**Comment by Egistar** [comment]
> 
> 
> @Egistar please format the code as it is barely readble

Done

**Comment by vlapo** [comment]
You have to define class for person and also for person name:
```ts
export interface PersonName {
	firstName: string;
	lastName: string;
}

export interface Person {
	name: PersonName
}

export class PersonNameDto implements PersonName {
	@IsString()
	firstName: string;
	
	@IsString()
	lastName: string;
}

export class PersonDto implements Person {
	@ValidateNested()
	name: PersonNameDto;
}
```

**Comment by Egistar** [comment]
okay thank will do so...
