### ISSUE TITLE
How to validate only if the attribute is not null or not undefined?

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#456]
Ok so I am receiving values in my dto and i would like to enforce the validation only if the fields are provided from the client

**Comment by rubiin** [comment]
tried
```
 @ValidateIf(o => o !== undefined)
```

**Comment by vlapo** [comment]
Looks like perfect job for `@IsOptional`. From docs:

@IsOptional() | Checks if given value is empty (=== null, === undefined) and if so, ignores all the validators on the property.
-- | --

**Comment by rubiin** [comment]
ok looks good thanks
