### ISSUE TITLE
@IsUUID decorator returns no errors on invalid input

### ISSUE THREAD

**Issue by KonstantinSchuette** [typestack/class-validator#457]
This issue explains exactly my problem:
https://github.com/typestack/class-validator/issues/401

When I am passing an empty string, the validator returns no error.

**Comment by vlapo** [comment]
Tested and all works. Looks like some issue on your side.

https://stackblitz.com/edit/class-validator-boilerplate-gh457?file=index.ts

**Comment by rubiin** [comment]
I tested it locally and seems to be working fine, perhaps you can share your code

**Comment by sergiupris** [comment]
Actually, it always return `<property> must be an UUID`.
@vlapo - even in your link, try it with a valid uuid.

**Comment by vlapo** [comment]
Close due to no response from creator.
