### ISSUE TITLE
Dynamic @IsIn validator

### ISSUE THREAD

**Issue by bogdan** [typestack/class-validator#459]
Sometimes the list of values to be passed into `IsIn` validator need to come from database itself.

In this case I would like to be able to do something like this:

``` typescript
class Country {
  static async getAllNames(): Promise<string[]>
}

class City { 
  @IsIn(Country.getAllNames())
  countryName: CountryName
}
```

Or a different style without DB query:

``` typescript
class Asset {
  @IsIn(object => object.availableCategories)
  mainCategory: Category

  availableCategories: Category[]
}
```

So I would expect the `IsIn` to accept `Promise<any[]>` and `(object: this) => any[]` as values.

Are you insterested in such a feature?

**Comment by vlapo** [comment]
We already have this kind of functionality (or sort of it). https://github.com/typestack/class-validator#custom-validation-classes. You can write your own async validators.
