### ISSUE TITLE
ValidateNested for array of objects is not generating swagger doc

### ISSUE THREAD

**Issue by rohitkdn** [typestack/class-validator#461]
I am using class-validator decorators to generate Swagger doc in NestJs. In the case of primitive data types or plain custom objects, it's working fine, but in case of a nested array of objects, it's generating empty object in swagger docs. 

```
export class DemoClass {
  @IsNumber()
  @IsNotEmpty()
  readonly testNumber?: number;

  @ValidateNested()
  @Type(() => TestObjectDto)
  readonly testObject?: TestObjectDto;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TestObjectDto)
  readonly testArrayOfObject?: TestObjectDto[];
}
```

Following is my swagger doc generated - 

![Screenshot 2019-11-15 at 12 05 18 PM](https://user-images.githubusercontent.com/10166409/68921923-40b53280-07a0-11ea-865e-971902e34dc2.png)

**Error:**
```
Resolver error at paths./playground/test.put.parameters.0.schema.properties.testArrayOfObject.items.$ref
Could not resolve reference: Could not resolve pointer: /definitions/Array does not exist in document 
```

**Comment by vlapo** [comment]
`class-validator` is about validation and does not generate any swagger doc. Please check nestjs doc better - https://docs.nestjs.com/recipes/swagger
