### ISSUE TITLE
IsNumericOptions is missing no_symbols

### ISSUE THREAD

**Issue by PachowStudios** [typestack/class-validator#463]
As the title says. Validator.js accepts a no_symbols argument, but IsNumericOptions doesn't declare it.

**Comment by rubiin** [comment]
@PachowStudios for which validator it is missing in.?

**Comment by rubiin** [comment]
will be doing a pr to solve this, thanks for pointing out

**Comment by rubiin** [comment]
thanks for the feedback, i have added this in the pr #467

**Comment by vlapo** [comment]
@rubiin what is status of this one?

**Comment by rubiin** [comment]
@vlapo i have submitted a pr already

**Comment by vlapo** [comment]
PR is closed

**Comment by rubiin** [comment]
looks like it was already resolved
