### ISSUE TITLE
Validating each character in a string with array of forbidden characters is missing.

### ISSUE THREAD

**Issue by libikroizer** [typestack/class-validator#464]
You only have the option to validate the entire string with array of forbidden values, but missing the option to validate each character with array of forbidden characters.

**Comment by rubiin** [comment]
can you provide a snippet to show your usecase

**Comment by libikroizer** [comment]
let name = 'Libi@'; //invalid value
let forbiddenCharacters = ['@', '%', '/'];

**Comment by rubiin** [comment]
you can use the match decorator and provide a regex to filter

**Comment by vlapo** [comment]
I'm convinced match validator helps.
