### ISSUE TITLE
fix: error TS2503: Cannot find namespace 'ValidatorJS'.

### ISSUE THREAD

**Issue by cjancsar** [typestack/class-validator#468]
Just installed `class-validator` into a new `Nest.js` project, also manually intalled types.

Getting the above error for basically all validators when trying to start app:

```
node_modules/class-validator/validation/Validator.d.ts:383:38 - error TS2503: Cannot find namespace 'ValidatorJS'.

383     isISSN(value: unknown, options?: ValidatorJS.IsISSNOptions): boolean;
```

**Comment by rubiin** [comment]
can you share a repo ? I am not having any problems so I can tr to reproduce and if found , fix the problem

**Comment by cjancsar** [comment]
Can close this, not sure what happened, but doing a `yarn install` somehow fixed it...?

**Comment by cjancsar** [comment]
This is now happening on a new project, so bizarre...

**Comment by cjancsar** [comment]
This is the cause of the issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40477

**Comment by iam4x** [comment]
I'm using `validator` itself in my project and I'm running into this issue as well.

* `$ yarn add -D @types/validator@10.11.3`

Solves the issue in the meantime

**Comment by vlapo** [comment]
Looks like breaking changes in `@types/validator`. But why you need `@types/validator` in your project? `validator` and `@types/validator` are only internal `class-validator` dependencies. I think you can completely remove them from your package.json.

**Comment by iam4x** [comment]
I'm using `import { normalizeEmail } from 'validator';` in my codebase.

**Comment by cjancsar** [comment]
@vlapo I need `validator` and `types-validator` because I am using `sequelize-typescript` (https://www.npmjs.com/package/sequelize-typescript) which also has them as a dependency. They should be made `peer depedencies` of this lib to avoid conflicts like this.

**Comment by zcong1993** [comment]
@cjancsar try to add this  to your `tsconfig.json`

**Comment by vlapo** [comment]
Please try `class-validator@0.12`. It should be fixed
