### ISSUE TITLE
Detect properties that shouldn't exist on the object

### ISSUE THREAD

**Issue by TomMarius** [typestack/class-validator#47]
There could be an option to emit a validation error if the object contains a property it shouldn't (e.g. the property isn't declared and decorated in the class).

**Comment by TomMarius** [comment]
Maybe it should be part of your https://github.com/pleerock/class-transformer library instead of this one, I'm not sure.

**Comment by pleerock** [comment]
decide where it should be and create more detailed proposal

**Comment by NoNameProvided** [comment]
This is now possible with the `whitelist` option.
