### ISSUE TITLE
 How do I put the verification information in a custom response?

### ISSUE THREAD

**Issue by AHRL** [typestack/class-validator#470]
I use it in koa.

For example：
```
@MaxLength(10, { message: 'username too long' })
@IsNotEmpty({ message: 'must include username' })
@Column()
username: string
```

How do I put message in data of response?
```
async add(user: User): Promise<IResponse> {
    try {
      const res = await this.repository.insert(user)
      return { status: 1, msg: '添加成功', data: res.raw.ops[0]}
    } catch (err) {
      return { status: 0, msg: '添加失败', data: err }
    }
  }
```
It doesn't seem to go into the interface method.
I hope to response a unified format.
Thanks.

**Comment by rubiin** [comment]
you can throw a http exception with the status and error in place of message.

**Comment by AHRL** [comment]
Sorry. I don‘t understand how to do? Could you show me an example? Thanks.

**Comment by AHRL** [comment]
@rubiin

**Comment by rubiin** [comment]
You can do something like 
```
throw new HttpException()
```

**Comment by vlapo** [comment]
Sorry but this is not related to `class-validator` library. You have to ask in koa repo or stackoverflow.
