### ISSUE TITLE
@IsISO8601 strict mode

### ISSUE THREAD

**Issue by carlocorradini** [typestack/class-validator#471]
To start I want to say thanks for the new update that brought ISO 8601 Dates support.
In the Docs I read that @IsISO8601 decorator support a strict mode and i wanto to use it.

_Class Exampel with @IsISO8601 decorator strict mode_
```ts
class Film {
    id: number;
    title: string;

    @IsISO8601({ message: '$property must be a valid Date', strict = true })
    release_date: string;
}
```

![Annotation 2019-11-20 183332](https://user-images.githubusercontent.com/21266147/69340044-e6681600-0c66-11ea-9073-99e780a105d8.jpg)

**However, as you can see from the image, the strict mode is not recognized.
Am I doing something wrong?**

**Comment by vlapo** [comment]
Sorry for the confusion caused using README as docs. We have this change already in doc but as you can see in CHANGELOG it is not released yet.

https://github.com/typestack/class-validator/blob/master/CHANGELOG.md

I will try release new version this week.

**Comment by carlocorradini** [comment]
Perfect, thanks :dizzy_face:
