### ISSUE TITLE
Excluding google-libphonenumber

### ISSUE THREAD

**Issue by binaryangel-noa** [typestack/class-validator#472]
Google libphonumber is a large depdendency of the class-valdiator package (450KB vs 50KB of class-valdiator). Is there an option to use it optionally ?

**Comment by rubiin** [comment]
i dont think you can use it optionally or may be i am wrong, perhaps @vlapo  can tell you more

**Comment by vlapo** [comment]
Sorry there is such option.

**Comment by alex-nishikawa** [comment]
Does this library support just using the modules you want?  Example: 
`
import length from 'class-validator/length`
`

**Comment by vlapo** [comment]
No this library do not support tree shaking and modules yet.

**Comment by AndrinGautschi** [comment]
Is someone working on this issue?

**Comment by vlapo** [comment]
Duplicate of https://github.com/typestack/class-validator/issues/248
