### ISSUE TITLE
Error in 0.11.0. maxDecimalPlaces

### ISSUE THREAD

**Issue by SergeyAlexsandrovich** [typestack/class-validator#475]
Hello. In version `class-validator` 0.11.0, I receive errors from my code 
`Cannot read property \'maxDecimalPlaces\' of null'`.  If I do downgrade version to 0.10.2 then the error disappear. Can you help me?

**Comment by rubiin** [comment]
can you share your code

**Comment by SergeyAlexsandrovich** [comment]
I researched reason of this issue. 
In version 0.11.0 the below string throw exception because `option` is null.   
In version 0.10.0 the below string is valid.
`@IsNumber(null, {message: 'Параметр должен быть числом'})`

**Comment by SergeyAlexsandrovich** [comment]
Thanks for help.
