### ISSUE TITLE
Validate array of objects programatically

### ISSUE THREAD

**Issue by affanshahid** [typestack/class-validator#476]
So I have an array of objects of type `Foo`, how do I validate them programatically? 

```ts
const arrayOfItems = await getFromSomeWhere();
validate(arrayOfItems, ???) // what do I do here?.
```

**Comment by vlapo** [comment]
We do not have any option to validate arrays as input to `validate` method. U have to handle this in your codebase.

**Comment by omer-morad-ni** [comment]
@vlapo, can you give a recommended pattern to do so?

**Comment by vlapo** [comment]
You should create a wrapper class. E.g.:
```ts
class ArrayWrapper {
   @ValidateNested({ each: true })
   items: Item[];
}

const arrayOfItems = await getFromSomeWhere();
const wrapper = new Wrapper();
wrapper.items = arrayOfItems;

validate(wrapper);
```

or use simple for and validate each item separately.

**Comment by vlapo** [comment]
@affanshahid @omer-morad-ni Did my comment help?

**Comment by affanshahid** [comment]
Yes, the wrapper class works perfectly
