### ISSUE TITLE
How to validate array of uuids

### ISSUE THREAD

**Issue by Isahara86** [typestack/class-validator#479]
How can I validate an array of UUIDs

``` ts
class SubscriptionDTO {
  @IsArray()
  @ArrayNotEmpty()
  taskIds: string[]; // - this should be an array of uuids what should I add to validate this
}
```

**Comment by rubiin** [comment]
i think you can use each: true in your validation. Refer to validating arrays though

**Comment by Isahara86** [comment]
Thank you it works!!!

`
class SubscriptionDTO {
    @IsArray()
    @ArrayNotEmpty()
    @IsUUID(undefined, { each: true })
    taskIds: string[]; // - this should be an array of uuids what should I add to validate this
}
`
