### ISSUE TITLE
Context doesn't get passed with async custom validator

### ISSUE THREAD

**Issue by dolsem** [typestack/class-validator#480]
#292 was closed and locked prematurely.

There were two PRs to fix the issue - #296 and #391. #296 was merged, but unfortunately it doesn't fix the bug that results in context not being passed when validation is performed asynchronously.

If you put `async` in the beginning of the following line
https://github.com/typestack/class-validator/blob/e19502578045a74ebd5bfed47f2ab4382aa9cedc/test/functional/validation-options.spec.ts#L949
the test will fail with `TypeError: Cannot read property 'isLongerThan' of undefined`.

#391 was based on #296, but it did fix this bug (there was a test case included for that).

**Comment by Larsrdev** [comment]
We also ran into this problem. we need context to store some internal errorcodes, but this does not work with custom async validators.

**Comment by dolsem** [comment]
@Larsrdev I can rebase my fork off the latest master and create a new PR if maintainers express an interest in merging it.

**Comment by Larsrdev** [comment]
That would be great @dolsem. We currently cant check if a user is exisiting in database with custom async validation. And this is in my opinion a normal use case.

**Comment by Larsrdev** [comment]
I did it by myself. Thanks for your work @dolsem 👍

**Comment by vlapo** [comment]
Sorry @Larsrdev. My fault. I didn't notice your note about async validators. Could you please create PR with fix and test from actual code base?
