### ISSUE TITLE
question: Express Request Object In Custom Validator

### ISSUE THREAD

**Issue by ofuochi** [typestack/class-validator#482]
How do I get the express request object in a custom validator?
```ts
@ValidatorConstraint()
class IsPublic implements ValidatorConstraintInterface {
	
	validate(isPublic: boolean, args: ValidationArguments) {
		// I want to use the request object here
		return true;
	}

	defaultMessage(args: ValidationArguments) {
		return "You don't have the right to create a public group";
	}
}
```

**Comment by irojasag** [comment]
Same issue here! I need to be able to get the request headers on the validation to validate that for example an user is allowed to use an specific resource.

**Comment by vlapo** [comment]
Right now we do not have option to pass additional context (like request object) into validation process.

**Comment by lalalalaluk** [comment]
i need it too

**Comment by shinelp100** [comment]
me too

**Comment by Axedyson** [comment]
me tooo!

**Comment by NoNameProvided** [comment]
This is currently not possible.
