### ISSUE TITLE
validate countryname

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#483]
How about adding a validator for country?

**Comment by rubiin** [comment]
@vlapo

**Comment by vlapo** [comment]
@rubiin

**Comment by rubiin** [comment]
I checked validator js but this method doesnt exist perhaps we can make a native function for this
@vlapo

**Comment by vlapo** [comment]
What country name? English, Spanish, Czech...? I think this could be really huge validator. Lets see if more users will find this feature useful. 

Note: Please do not tag me in every issue, PR and comment. I check every new comment/PR/issue and your tags just spam my email. Thnx a lot.
