### ISSUE TITLE
@matches with my regex shows true sometimes while false sometimes

### ISSUE THREAD

**Issue by rubiin** [typestack/class-validator#484]
I am using class-validator with nestjs. I have a password field like this:

```
  @Matches(/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{6,64}$/gm, {
    message:
      'Password must be between 6 and 64 characters long with 1 special character and capital character each',
  })
```
but sometimes the password passes this while sometimes it doesnt

**Comment by rubiin** [comment]
@vlapo also when is the release of next version. I like to use the uuid fix

**Comment by yardenshoham** [comment]
I've also encountered this with `@Matches`.

Here's my user class:
```ts
import {
  IsEmail,
  Matches,
  IsOptional,
  IsPhoneNumber,
  IsDefined,
  validateSync
} from "class-validator";

export class User {
  @IsDefined()
  @IsEmail()
  public email: string;

  @IsDefined()
  @Matches(/[a-zA-Z0-9_-]{2,20}/)
  public username: string;

  @IsDefined()
  @Matches(/^\$2[ayb]\$[\d]{2}\$[./A-Za-z0-9]{53}$/)
  private _password: string;

  @IsOptional()
  @IsPhoneNumber(null)
  public phoneNumber?: string;

  constructor(
    email: string,
    username: string,
    password: string,
    phoneNumber?: string
  ) {
    this.email = email;
    this.username = username;
    this.password = password;
    if (phoneNumber) {
      this.phoneNumber = phoneNumber;
    }
  }
}
```

The test I've run:

```ts
console.log(
  validateSync(
    new User(
      "test.user@test.domain.com",
      "I'm way too long to be a username, much too long",
      "$2y$12$E6I8o3kUs8CsSs0WnyYiGOmBeVxfhvaEbxPGgJ334jfpB//gEwFYO"
    )
  )
);
```

This yields no errors: `[]`

**Comment by insanebaba** [comment]
Same here

I'm trying to use class validator for validating my inputtype in type-graphql but the @matches decorator, is not working, All other decorators with suffix 'Is' are working, but not this one.

`

const mobileNumberRegex = /^(\+[0-9]{1,3}[- ]?)?[0-9]{9,10}$/;

@Field()
@Matches(mobileNumberRegex)
mobileNumber!: string;
`
I'm expecting error when the mobile number is not matching, but it's not there. Validate method also doesn't pass as expected

**Comment by yardenshoham** [comment]
> Same here
> 
> I'm trying to use class validator for validating my inputtype in type-graphql but the @matches decorator, is not working, All other decorators with suffix 'Is' are working, but not this one.
> 
> ``
> 
> ```
> const mobileNumberRegex = /^(\+[0-9]{1,3}[- ]?)?[0-9]{9,10}$/;
> 
> @Field()
> @Matches(mobileNumberRegex)
> mobileNumber!: string;
> ```
> 
> ``
> I'm expecting error when the mobile number is not matching, but it's not there. Validate method also doesn't pass as expected

For your use case I'd recommend the `@IsPhoneNumber(null)` decorator.

**Comment by insanebaba** [comment]
> @insanebaba
> 
> > Same here
> > I'm trying to use class validator for validating my inputtype in type-graphql but the @matches decorator, is not working, All other decorators with suffix 'Is' are working, but not this one.
> > ``
> > ```
> > const mobileNumberRegex = /^(\+[0-9]{1,3}[- ]?)?[0-9]{9,10}$/;
> > 
> > @Field()
> > @Matches(mobileNumberRegex)
> > mobileNumber!: string;
> > ```
> > 
> > 
> > ``
> > I'm expecting error when the mobile number is not matching, but it's not there. Validate method also doesn't pass as expected
> 
> For your use case I'd recommend the `@IsPhoneNumber(null)` decorator.

Thanks for suggestion, `@IsPhoneNumber(null)` works, but I want to have more control over the pattern.

I solved my issue by stepping down to version **0.10.2**

Thank you everyone, I hope this issue gets addressed in later versions.

**Comment by rubiin** [comment]
@vlapo do you know how can i resolve this

**Comment by yardenshoham** [comment]
@rubiin Please provide an example of an input that fails.

**Comment by windok** [comment]
Facing the same issue with class-validator package version **0.11.0**
```
import {  IsArray,  IsOptional,  Matches } from 'class-validator';

export class MyDto {
  @IsArray()
  @IsOptional()
  @Matches( /^[\w .,-]+$/gi, { each: true })
  readonly rangeFilters?: string[];
}
```
values that pass only each second time: `price`, `price.amountToPay,500,600`
```
        {
            "target": {
                "rangeFilters": [
                    "price.amountToPay,500,600"
                ]
            },
            "value": [
                "price.amountToPay,500,600"
            ],
            "property": "rangeFilters",
            "children": [],
            "constraints": {
                "matches": "each value in rangeFilters must match /^[\\w .,-]+$/gi regular expression"
            }
        }
```

**Comment by aozisik** [comment]
@windok , @rubiin 
Please read the following thread on the use of `g` flag.
It makes the regex object stateful, which explains this bug.

I guess you'll have to avoid that flag to fix the issue.

https://stackoverflow.com/questions/6739136/consecutive-calls-to-regexp-test-fail-for-pattern-with-global-option

**Comment by ilterkaganocal** [comment]
After having the same problem and wasting an hour, found that this is because the regex modifier `g`

Removing `global` identifier solved my problem.

https://stackoverflow.com/questions/6739136/consecutive-calls-to-regexp-test-fail-for-pattern-with-global-option

**Comment by vlapo** [comment]
@rubiin Did you resolve your issue?

**Comment by DUDY206** [comment]
I have the same problem
`@IsString()
    @MinLength(8)
    @MaxLength(20)
    @Matches(/((?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@$!%*?&])[A-Za-z0-9@$!%*?&]+)+/g)
    password: string;`

response sometime true, sometime false

**Comment by kazemimorteza68** [comment]
> I have the same problem
> 
> ```
> @IsString()
>  @MinLength(8)
>  @MaxLength(20)
>  @Matches(/((?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@$!%*?&])[A-Za-z0-9@$!%*?&]+)+/g)
>  password: string;
> ```
> 


  @Matches('^09[0-9]{9}',"",{"message":"phone is incorrect"}) 
  phone:      string;


after regex pattern we need pass empty string and third argument be our message

**Comment by bezenson** [comment]
Hm, issue opened from 2019. Got the same issue.

https://user-images.githubusercontent.com/3227120/174649929-ee1309d6-f427-4702-9721-880fdd4228c8.mp4

![IMAGE 2022-06-20 20:03:58](https://user-images.githubusercontent.com/3227120/174649939-95c84544-deef-4514-8554-fed5d4135a5d.jpg)

I fixed it by removing `/g` flag from regular expression

**Comment by ibrahimwithi** [comment]
Got the same issue I want to validate time format '/^(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)?([0-5]?\d)$/' but it fails on 08:30

**Comment by jampack** [comment]
removing /g doesn't solve the issue. any help on this?

**Comment by lublot** [comment]
> Hm, issue opened from 2019. Got the same issue.
> 
>  wtf.mp4 
> ![IMAGE 2022-06-20 20:03:58](https://user-images.githubusercontent.com/3227120/174649939-95c84544-deef-4514-8554-fed5d4135a5d.jpg)
> 
> I fixed it by removing `/g` flag from regular expression

Thank you! It worked for me.

**Comment by soufianerafik** [comment]
I had a similar issue, to fix it i went from 
From 

`@Matches(/[a-zA-Z0-9_]*$/, {message: 'Username can only contains letters, numbers and underscores.'})`

to

`@Matches(/"^[a-zA-Z0-9_]*$/, {message: 'Username can only contains letters, numbers and underscores.'})`


Before : `/[a-zA-Z0-9_]*$/,` Fix `/"^[a-zA-Z0-9_]*$/`

I hope this helps 🙂

**Comment by NoNameProvided** [comment]
As @aozisik explained correctly this is how the `g` flag works with Regexes. From MDN - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test:

> JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags set (e.g., /foo/g or /foo/y). They store a [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) from the previous match. Using this internally, test() can be used to iterate over multiple matches in a string of text (with capture groups).


Closing this as there is no action to take from our side.
