### ISSUE TITLE
question: how mock mock custom Validator in end-to-end tests using the NestJS framework

### ISSUE THREAD

**Issue by atanasovdragan** [typestack/class-validator#494]
Hi, I have an issue using class-validator and custom validator classes. The framework that I'm using is NestJS. The problem is not in the validation itself, but when I'm writing end-to-end tests using Jest as a framework, I am not able to mock the custom validation classes created using class-validator.

You can check the issue more in details at the following issue link that I opened in the official NestJS repo, but I was diverted here:
https://github.com/nestjs/nest/issues/3426

**Comment by ayoubgm** [comment]
Hello, did you solve this issue ?

**Comment by littlegubs** [comment]
i managed to mock my custom validator by adding `useContainer` in my test file

```typescript
 app = moduleFixture.createNestApplication()
 useContainer(app, { fallbackOnErrors: true })
 app.useGlobalPipes(new ValidationPipe())
```

**Comment by gabrielbull** [comment]
This is how I mock my class-validator custom validators: 

```ts
function mockCustomValidator<
  T extends abstract new (...args: unknown[]) => unknown,
>(
  target: T,
  property: keyof InstanceType<T>,
  name: string,
): jest.SpyInstance<boolean, [unknown, ValidationArguments]> {
  const storage = getMetadataStorage();
  const metadatas = storage.getTargetValidationMetadatas(
    target,
    target.name,
    true,
    true,
  );
  const metadata = metadatas.find((a) => {
    if (a.propertyName === property) {
      const c = storage.getTargetValidatorConstraints(a.constraintCls);
      if (c.find((a) => a.name === name)) {
        return true;
      }
    }
    return false;
  });
  return jest.spyOn(
    metadata.constraintCls.prototype,
    "validate",
  ) as jest.SpyInstance<boolean, [unknown, ValidationArguments]>;
}

```

And then you can just call it like so in your tests:

```
mockCustomValidator(UserInput, 'username', 'isUsernameExists').mockImplementation(() => true)
```

**Comment by DBJuanperezc** [comment]
> This is how I mock my class-validator custom validators:
> 
> ```ts
> import {
>   getMetadataStorage,
>   ValidationArguments
> } from "class-validator";
> 
> function mockCustomValidator<
>   T extends abstract new (...args: unknown[]) => unknown,
> >(
>   target: T,
>   property: keyof InstanceType<T>,
>   name: string,
> ): jest.SpyInstance<boolean, [unknown, ValidationArguments]> {
>   const storage = getMetadataStorage();
>   const metadatas = storage.getTargetValidationMetadatas(
>     target,
>     target.name,
>     true,
>     true,
>   );
>   const metadata = metadatas.find((a) => {
>     if (
>       a.propertyName === property &&
>       storage
>         .getTargetValidatorConstraints(a.constraintCls)
>         .find((a) => a.name === name)
>     ) {
>       return true;
>     }
>     return false;
>   });
>   return jest.spyOn(
>     metadata.constraintCls.prototype,
>     "validate",
>   ) as jest.SpyInstance<boolean, [unknown, ValidationArguments]>;
> }
> ```
> 
> And then you can just call it like so in your tests:
> 
> ```ts
> mockCustomValidator(UserInput, 'username', 'isUsernameExists').mockImplementation(() => true)
> ```

Hi, could you show a complete example, for whatever reason it gives me a metadata error. 
Thanks in advance

**Comment by NoNameProvided** [comment]
Closing this as expired.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
