### ISSUE TITLE
Libphonenumber AssertionError

### ISSUE THREAD

**Issue by Maxi98** [typestack/class-validator#497]
When I try to validate with **validateOrReject()** I receive that error (even if I **haven't set any @IsPhoneNumber** decorator):

`goog.asserts.AssertionError {message: "Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", …}`

"AssertionError: Assertion failed\n    at new goog.asserts.AssertionError (/node_modules/google-libphonenumber/dist/libphonenumber.js:1139:20)\n    at Object.goog.asserts.doAssertFailure_ (/node_modules/google-libphonenumber/dist/libphonenumber.js:1162:7)\n    at Object.goog.asserts.assert [as assert] (/node_modules/google-libphonenumber/dist/libphonenumber.js:1169:53)\n    at new goog.proto2.FieldDescriptor (node_modules/google-libphonenumber/dist/libphonenumber.js:3992:16)\n    at Function.goog.proto2.Message.createDescriptor (/node_modules/google-libphonenumber/dist/libphonenumber.js:4246:22)\n    at i18n.phonenumbers.PhoneMetadata.getDescriptor (/node_modules/google-libphonenumber/dist/libphonenumber.js:5193:79)\n    at i18n.phonenumbers.PhoneMetadata.goog.proto2.Message (/node_modules/google-libphonenumber/dist/libphonenumber.js:4071:23)\n    at new i18n.phonenumbers.PhoneMetadata (/node_modules/google-libphonenumber/dist/libphonenumber.js:4583:23)\n    at Object.1 (/node_modules/google-libphonenumber/dist/libphonenumber.js:6791:56)\n    at o (/node_modules/google-libphonenumber/dist/libphonenumber.js:1:639

package-lock.json:
```
        "class-validator": {
            "version": "0.11.0",
            "resolved": "https://registry.npmjs.org/class-validator/-/class-validator-0.11.0.tgz",
            "integrity": "sha512-niAmmSPFku9xsnpYYrddy8NZRrCX3yyoZ/rgPKOilE5BG0Ma1eVCIxpR4X0LasL/6BzbYzsutG+mSbAXlh4zNw==",
            "requires": {
                "@types/validator": "10.11.3",
                "google-libphonenumber": "^3.1.6",
                "validator": "12.0.0"
            }
        }

 "google-libphonenumber": {
            "version": "3.2.6",
            "resolved": "https://registry.npmjs.org/google-libphonenumber/-/google-libphonenumber-3.2.6.tgz",
            "integrity": "sha512-6QCQAaKJlSd/1dUqvdQf7zzfb3uiZHsG8yhCfOdCVRfMuPZ/VDIEB47y5SYwjPQJPs7ebfW5jj6PeobB9JJ4JA=="
        }
```

**Comment by vlapo** [comment]
@Maxi98 Did your problem persist?

**Comment by jbdemonte** [comment]
@vlapo I'm having the same issue, 

I have no clue why, It was working till there, and suddenly, I got the same assertion

```
  ● Test suite failed to run

    AssertionError: Assertion failed

      at new goog.asserts.AssertionError (node_modules/google-libphonenumber/dist/libphonenumber.js:1072:20)
      at Object.goog.asserts.doAssertFailure_ (node_modules/google-libphonenumber/dist/libphonenumber.js:1095:7)
      at Object.goog.asserts.assert [as assert] (node_modules/google-libphonenumber/dist/libphonenumber.js:1102:53)
      at i18n.phonenumbers.PhoneMetadata.goog.proto2.Message.checkFieldType_ (node_modules/google-libphonenumber/dist/libphonenumber.js:4256:112)
      at i18n.phonenumbers.PhoneMetadata.goog.proto2.Message.set$Value (node_modules/google-libphonenumber/dist/libphonenumber.js:4245:39)
      at i18n.phonenumbers.PhoneMetadata.setInternationalPrefix (node_modules/google-libphonenumber/dist/libphonenumber.js:4955:8)
      at Object.1 (node_modules/google-libphonenumber/dist/libphonenumber.js:6825:54)
      at o (node_modules/google-libphonenumber/dist/libphonenumber.js:1:639)
      at r (node_modules/google-libphonenumber/dist/libphonenumber.js:1:805)
      at node_modules/google-libphonenumber/dist/libphonenumber.js:1:834
      at node_modules/google-libphonenumber/dist/libphonenumber.js:1:88
      at Object.<anonymous> (node_modules/google-libphonenumber/dist/libphonenumber.js:1:330)
      at node_modules/class-validator/bundles/index.umd.js:2:125
      at Object.<anonymous> (node_modules/class-validator/bundles/index.umd.js:5:2)
```

I'm wondering if it's due to the fact I tried to add the `google-libphonenumber` by my own to use it, but I finally remove it, and clean the yarn cache

I'm still searching...

**Comment by jbdemonte** [comment]
Ok, I found the origin and a workaround but no idea why.

On my side, this seems to be due to a `jest.mock` of a mongoose model module in a test file : `jest.mock('../models/Client');` 

I replaced it by a `jest.spyOn` with `jest.spyOn(Client, 'find')` and the error fully disappear

**Comment by Maxi98** [comment]
> @Maxi98 Did your problem persist? Please try the newest `0.12` version.

It wasn’t a version related problem it was that I modified the Object interface (check below an example) due to add some custom functions and it broke the validation. But I didn't retry with the new version to find out if the problem persists I just removed my snipped of code and find a workaround adding that custom function to the ObjectConstructor interface.

`declare global {
    interface Object {
        isEmpty(obj: Object): Boolean;
    }
}`

**Comment by NoNameProvided** [comment]
Closing as solved, if your issue still persist please comment and we will reopen the issue.
