### ISSUE TITLE
@IsDefined() and IsOptional(), what will be the meaning

### ISSUE THREAD

**Issue by binarytracer** [typestack/class-validator#501]
Im currently using the  following:
- class-validator **0.11.0**
- typeorm **0.2.22**
- @nestjsx/crud  **4.4.1**
- @nestjsx/crud-request **4.4.1**
- @nestjsx/crud-typeorm **4.4.1**

Ive read this case, https://github.com/typestack/class-validator/issues/120.

here is my update version on that case,
```ts
 @IsOptional({ groups: [UPDATE] })
  @IsDefined({ groups: [CREATE] })
  @IsNotEmpty()
  @IsString()
  @Column()
  name: string;
```

The intent of this definitions is that the **name** will be necessary in creation but optional on updates, If ever during update the **name** is provided it should evaluate against the IsString, IsNotEmpty.

My question is:
- What will be the concluded validation for **name** field? Im afraid the @IsDefined is ignored on this case, not sure here as indicated here, https://github.com/typestack/class-validator#validation-decorators.

**Comment by NoNameProvided** [comment]
Closing as expired without answering the question. If you still encounter the problem please open a new one with a minimal reproducible example.
