### ISSUE TITLE
Decorators for IsLatitude and IsLongitude have wrong types

### ISSUE THREAD

**Issue by scottcollins** [typestack/class-validator#502]
The IsLatitude decorator defines a type of IS_LONGITUDE and the IsLongitude decorator defines a type of IS_LONGITUDE.  Should be the other way around

**Comment by scottcollins** [comment]
I have a pull request ready for this, but I do not have access to push to a branch. how can I get access?

**Comment by vlapo** [comment]
You have to fork this repository, commit in forked one and create PR https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

**Comment by vlapo** [comment]
@rubiin could you please check this one? Check if it is real bug and create PR - looks like a simple fix.

**Comment by rubiin** [comment]
@vlapo fixed in pr https://github.com/typestack/class-validator/pull/563
