### ISSUE TITLE
IsAlpha in String Validator npm 'class-validator'

### ISSUE THREAD

**Issue by afaqkhan362** [typestack/class-validator#503]
IsAlpha() doesn't seem to work properly, it is by passing the values including special characters like @!#$

**Comment by vlapo** [comment]
Tested by I think `IsAlpha` works as intended and do not accept special characters `@!#$`

https://stackblitz.com/edit/class-validator-boilerplate-gh503?file=index.ts

**Comment by afaqkhan362** [comment]
Thanks it worked !

**Comment by afaqkhan362** [comment]
Thank you for your response but for some reason it isn't working on my project,
