### ISSUE TITLE
Values should be marked as readonly

### ISSUE THREAD

**Issue by vityas-off** [typestack/class-validator#506]
For example this will fail
```ts
import { IsIn } from 'class-validator';

const genders = ['male', 'female', 'other'] as const;

export class CreateUserDto {
  @IsIn(genders)
  readonly gender: typeof genders[number];
}
```
with error 
`Argument of type 'readonly ["male", "female", "other"]' is not assignable to parameter of type 'any[]'.
  The type 'readonly ["male", "female", "other"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.`

**Comment by vlapo** [comment]
Feel free create PR or use `@IsIn(genders as any[])`

**Comment by vlapo** [comment]
Closed by https://github.com/typestack/class-validator/pull/600
