### ISSUE TITLE
Validators become optional if `each` is set to `true`

### ISSUE THREAD

**Issue by dbartholomae** [typestack/class-validator#507]
Currently whether validators allow optional values is a bit confusing. E. g. `IsString()` only allows for a `null` value if there is also `IsOptional()`, but `IsString({ each: true })` by default allows for `null` values (unless combined with `IsDefined()`). This is due to the following check:
https://github.com/typestack/class-validator/blob/master/src/validation/ValidationExecutor.ts#L233

It would be great to have simple consistent logic in place, e. g. everything is required unless `IsOptional()` is defined. This would be a breaking change, so it could be hidden behind a switch - or taken on when moving to version 1.0.0.

**Comment by NoNameProvided** [comment]
Cannot reproduce, however `null` and undefined values will never pass. However `each: true` doesn't handle correctly when it receives something else than an array. This is tracked in https://github.com/typestack/class-validator/issues/1858.
