### ISSUE TITLE
IsNumberString ignores maxDecimalPlaces option

### ISSUE THREAD

**Issue by y-moroz** [typestack/class-validator#508]
`IsNumberString` decorator  accepts `IsNumberOptions` as the second argument but ignores maxDecimalPlaces option. 
So if we have next class:
```typescript
export class Dto {
  @IsNumberString({}, {maxDecimalPlaces: 1})
  id: string;
}
```
And next object: 
```typescript
{
  id: "1.123"
}
```
ER: This object is invalid because there are 3 decimal digits.
AR: The object is valid.

**Comment by vlapo** [comment]
Related PR https://github.com/typestack/class-validator/pull/518

**Comment by vlapo** [comment]
`IsNumberString` accepts `IsNumericOptions` not `IsNumberOptions`. Fixed by https://github.com/typestack/class-validator/commit/62b993f3d360c8844687c8856ae9d84bb50b8654
