### ISSUE TITLE
Question:    data?: Array<string | Binary>; how to validate this array

### ISSUE THREAD

**Issue by Setitch** [typestack/class-validator#509]
i have object
```
{
...
  @ApiProperty({
    type: 'array',
    items: {
      oneOf: [
        {type: 'string', format: 'binary'},
        {type: 'string', format: 'uri'}
      ]
    },
  })
  images?:  Array<string | Buffer>;
...
}
```

I need to validate the input. Strings are urls, buffer is binary. And im not really sure how to even start with class-validator to be able to validate this.

**Comment by vlapo** [comment]
You have to create your own validator for this case. 
 - https://github.com/typestack/class-validator#custom-validation-classes
 - https://github.com/typestack/class-validator#custom-validation-decorators
