### ISSUE TITLE
A non-object value where an object is expected throws an error

### ISSUE THREAD

**Issue by Hainesy** [typestack/class-validator#515]
When the `ValidatedNested` and `Type` decorators are used on a property, but the property contains a non-object value, e.g. a string or number, the code throws an error `Cannot read property 'map' of undefined` from the recursive `getErrors` function.

**Comment by weihanchen** [comment]
I have the same issue

**Comment by vlapo** [comment]
Duplicate of https://github.com/typestack/class-validator/issues/193
