### ISSUE TITLE
question: How can I have optional properties in validation schema?

### ISSUE THREAD

**Issue by incompletude** [typestack/class-validator#517]
How can I implement an optional parameter? I cannot find anything about optional inside types.

```
import { ValidationSchema } from 'class-validator'

export const PersonCreateValidationSchema: ValidationSchema = {
  name: 'PersonCreate',

  properties: {
    email: [{ type: 'isEmail', constraints: [] }],
    password: [{ type: 'minLength', constraints: [8] }],
    some: [{ type: 'minLength', constraints: [8] }] // this is optional
  }
}
```

**Comment by vlapo** [comment]
Did you try `isOptional` type?

**Comment by kaykhancheckpoint** [comment]
isOptional type does not appear to work in version 0.11 (latest version breaks validation-schema completely)
```
Validation schema emailSchema#from as incorrect type isOptional

      at src/validation-schema/ValidationSchemaToMetadataTransformer.ts:17:27
          at Array.forEach (<anonymous>)
```

**Comment by NoNameProvided** [comment]
Schema-based validation will be deprecated in the future probably as a result marking this as low prio.

**Comment by NoNameProvided** [comment]
Schema-based validation is deprecated, it has been removed from the docs in https://github.com/typestack/class-validator/commit/7cd7546fe965ea668b49feccf435badc130d9490. If you need to use schema-based validation I recommend using one of the other available libraries.
