### ISSUE TITLE
Split validators.ts into multiple files to allow proper tree shaking

### ISSUE THREAD

**Issue by gempain** [typestack/class-validator#519]
In [validators.ts](https://github.com/typestack/class-validator/blob/90a663866eaeb5a0cb38cce5501e0aa28984ed34/src/validation/Validator.ts), line 20-22:
```
private libPhoneNumber = {
    phoneUtil: require("google-libphonenumber").PhoneNumberUtil.getInstance(),
};
```
When `class-validator` is bundled with webpack, `google-libphonenumber`, which represents 71% of the bundle size, is embedded, even if you don't use the phone number validator. See this bundle analysis made with [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer):

<img width="1406" alt="Screenshot 2020-02-08 at 17 43 41" src="https://user-images.githubusercontent.com/13135149/74089078-8cc0fc00-4a9d-11ea-8524-787798da002c.png">

Validators should be split into different files, allowing to import only the needed files without extra code and thus enabling proper tree shaking when bundling dependencies with webpack.

**Comment by Larsrdev** [comment]
here some older PR and more to read: https://github.com/typestack/class-validator/pull/258

**Comment by gempain** [comment]
@Larsrdev right ! Weird, I thought I had searched properly before even taking the time to investigate. Anyways, closing in favor of #258. Sorry for the noise 😄
