### ISSUE TITLE
IsNumber cannot check for zero decimal places

### ISSUE THREAD

**Issue by tmtron** [typestack/class-validator#523]
checking for zero decimal places does not work:

```typescript
    class ZeroDecimalPlacesTest {
        @IsNumber({ maxDecimalPlaces: 0 })
        someProperty: number;
    }
```

The following validation logic is wrong: 
https://github.com/typestack/class-validator/blob/90a663866eaeb5a0cb38cce5501e0aa28984ed34/src/validation/Validator.ts#L438

instead it  should check if `maxDecimalPlaces` is `undefined`:
```typescript
if (options.maxDecimalPlaces !== undefined) {
```

**Comment by vlapo** [comment]
Closed by https://github.com/typestack/class-validator/pull/524
