### ISSUE TITLE
Is there a way to validate a number that could be in two non overlapping ranges of numbers?

### ISSUE THREAD

**Issue by elanbmiller** [typestack/class-validator#526]
I have a field called someNumber:
```
@Min(1)
@Max(10)
someNumber: number;
```

I'd like this field to be able to take on the value -1 as well. Is there a way to add this possibility? In general, can you set multiple ranges of numbers a field can take on without creating a custom validator?

**Comment by elanbmiller** [comment]
Nevermind! Added @NotEquals(0).

**Comment by elanbmiller** [comment]
But there must be a better way to validate multiple non overlapping ranges of numbers.

**Comment by vlapo** [comment]
`notequals` or `IsIn` validators are proper way how to solve this issue. We do not need new validator for this.
