### ISSUE TITLE
Validate file in DTO

### ISSUE THREAD

**Issue by amit12cool** [typestack/class-validator#531]
Is there any decorator to validate file in DTO i.e. I want to know if user has given a file or not?

Below is my dto

```
export class FileUploadRequest {
   @ApiProperty({
     format: 'binary'
   })
   file: string
}
``` 

I need to validate if file is binary and the file key is present.

**Comment by vlapo** [comment]
We do not have this kind of validator. Feel free submit PR.

**Comment by NoNameProvided** [comment]
Closing this as wontfix as this feature doesn't translate well between browser and NodeJS and between use-cases. You can do basic checks already like validate if a property exists or not. If you want to validate the content, you can create a custom property for that.
