### ISSUE TITLE
Bug in @Validate decorator

### ISSUE THREAD

**Issue by svetoslav0** [typestack/class-validator#540]
It seems Validate decorator is not reached when I try to use it. Let me give an example:

Lets say we have a Constant Class (like the given one in the documentation):

```ts
import {ValidatorConstraint, ValidatorConstraintInterface, ValidationArguments} from "class-validator";

export class CustomTextLength implements ValidatorConstraintInterface {

    validate(text: string, args: ValidationArguments) {
        return text.length > 3 && text.length < 10; // for async validations you must return a Promise<boolean> here
    }

    defaultMessage(args: ValidationArguments) { // here you can provide default error message if validation failed
        return "Text ($value) is too short or too long!";
    }

}
```

Then we create some dummy class where we'll validate some fields:

```ts
import { validate, Validate } from "class-validator";
import { CustomTextLength } from "./customTextLength";

export class Test {

    @Validate(CustomTextLength, {
        message: "Hmm, something's wrong"
    })
    title!: string;

}
```

And then we create an instance of this class and try to set a invalid value of the __title__ field:

```ts
const test = new Test();
test.title = "Testing test for test purposes";

validate(test).then(errors => {
    if(errors.length) {
        console.log("Some errors:");
        console.log(errors);
    } else {
        console.log("Success!");
    }
});
```

It looks like the __validate__ method in the Contraint Class is never reached, because when I compile this code and run it, it only prints 'Success!'.

**Comment by vlapo** [comment]
`@ValidatorConstraint({ name: "customTextLength", async: false })` is missing.
 - https://stackblitz.com/edit/class-validator-biolerplate-gh540?file=index.ts
 - https://github.com/typestack/class-validator#custom-validation-classes

**Comment by svetoslav0** [comment]
I see... You seem to be totally right. I do not know how I have missed it. Thank you :)
