### ISSUE TITLE
IsNotEmpty allow empty Strings

### ISSUE THREAD

**Issue by tiagovbarreto** [typestack/class-validator#543]
If a blank string of length bigger than one is passed there is no validation. It would be nice to implement this validation inside IsNotEmpty or create a new validation isNotBlank.

Regards

**Comment by Larsrdev** [comment]
You can also create a custom validation:

```
@ValidatorConstraint({name: 'isNotBlank', async: false})
export class IsNotBlankConstraint implements ValidatorConstraintInterface {
    // tslint:disable-next-line:no-any
    validate(value: any) {
        return typeof value === 'string' && value.trim().length > 0;
    }

    defaultMessage(args: ValidationArguments) {
        return `"${args.property}" should not be empty`;
    }
}

export function isNotBlank() {
    return function(object: Object, propertyName: string) {
        registerDecorator({
            target: object.constructor,
            propertyName,
            constraints: [],
            options: {},
            validator: IsNotBlankConstraint,
        });
    };
}
```

**Comment by vlapo** [comment]
Feel free to submit PR.

**Comment by smtaha512** [comment]
@vlapo I want to submit PR? Should I extend the functionality in IsNotEmpty or create separate isNotBlank validator?

**Comment by vlapo** [comment]
We do not accept new/modify validators currently. I will check this issue after finish refactoring. Thank you for your understanding

**Comment by NoNameProvided** [comment]
You can easily achieve this via the `@Matches` decorator with `/.+/` RegEx. If you worry about readability you can create a custom decorator as @Larsrdev suggested.
