### ISSUE TITLE
I can not use class-validator decorator for nested object

### ISSUE THREAD

**Issue by annguyn09910** [typestack/class-validator#545]
I used [Class-Validator](https://github.com/typestack/class-validator) and I have structure objects as:
<pre>
export class Member {
  @Field({ nullable: true })
  public firstName?: string;

  @Field({ nullable: true })
  public lastName?: string;

  @Field(_type => MemberTeam)
  public memberTeam?: MemberTeam;
}
</pre>

<pre>
export class MemberTeam {
  @Field ( {nullable: false })
  @Matches(/^[A-Za-z]+$/gm, {
    message: 'We only use letters',
  })
  public name: string;
}
</pre>

`@Matches` in `MemberTeam` is not working.
I also use `ValidatorConstraint` to custom validator but it's also not working.

Can we use class-validator for data structure as above?

**Comment by vlapo** [comment]
You have to use `@ValidateNested()` - https://github.com/typestack/class-validator#validating-nested-objects

**Comment by vlapo** [comment]
```ts
export class Member {
  // ...

  @Field(_type => MemberTeam)
  @ValidateNested()
  public memberTeam?: MemberTeam;
}
```
