### ISSUE TITLE
How can I validate the attribute of object?

### ISSUE THREAD

**Issue by Gavin-TW** [typestack/class-validator#552]
I use global validatePipe() in nestjs:

` app.useGlobalPipes(new ValidationPipe({ skipMissingProperties: true }));`

and my controller is:
`  async getByDto(@Query() dto: Dto) `

my Dto is :
```
export class Dto {

  @IsNumberString()
  id?: number;

  @IsNumberString()
  parentId?: number;

  @IsString()
  key?: string;

  @IsBooleanString()
  isPopularCategory?: boolean;

  @IsObject()
  recommended?: {
    month?: number;
    recommendedCategoryId?: number;
  };
}
```
if I type URL： localhost:3000/xxx?sdfasdf=1 in chrome(means Dto doesn't have 'sdfasdf' attribute)

it can't validate this and I should do some other validate in backend server.

I would really appreciate it if some guys can add some comments to solve this issues

**Comment by vlapo** [comment]
Did you try https://github.com/typestack/class-validator#whitelisting ? `forbidNonWhitelisted` looks like solution of your problem.
