### ISSUE TITLE
question: shared validators

### ISSUE THREAD

**Issue by pietrobelluno** [typestack/class-validator#562]
Is it possible to do shared validators? For example build a DTO with class-validator for array, string, number validators that can be used in other places.

`function(@Query('id') id:QueryNumberDto)`

```
import { IsNumber, Max, IsNotEmpty } from 'class-validator';
import { Transform } from 'class-transformer'
export class id:QueryNumberDto {
    @IsNumber()
    @IsNotEmpty()
    @Transform(value => Number(value))
    (dynamic): Number;
}

```
something like that, that in error i can return a dynamic field

**Comment by vlapo** [comment]
You can create own validators https://github.com/typestack/class-validator#custom-validation-decorators or inherit from another classes https://github.com/typestack/class-validator#inheriting-validation-decorators.

**Comment by johannesschobel** [comment]
You can also create a new Decorator for your Validator, that calls the other decorators. In JS/TS decorators are just functions that are called.

**Comment by kenberkeley** [comment]
@pietrobelluno 
https://github.com/typestack/class-validator/pull/161/files

**Comment by NoNameProvided** [comment]
As others said, you can create your own reusable custom decorator that calls other decorators. 

Closing as answered.
