### ISSUE TITLE
@length(), default message wording

### ISSUE THREAD

**Issue by jerradpatch** [typestack/class-validator#57]
with a length decorator of '@Length(0, 4)', with an field value of '12334', I get a error of 'XXXX must be shorter than 4 characters'. What the error means to me is XXXX < 4, but its actually XXXX<= 4 ?

**Comment by pleerock** [comment]
you can send a PR with correct validation message ;)

**Comment by MHeironimus** [comment]
I have submitted PR #141 to address this issue and align the messages with `@MinLength` and `@MaxLength`.
