### ISSUE TITLE
Validation message is not working for @IsPositive

### ISSUE THREAD

**Issue by rfgamaral** [typestack/class-validator#570]
I'm using `class-validator@0.11.1` with `type-graphql@0.18.0-beta.15` and I have the following class:

```ts
@ArgsType()
class Arguments {
    @Field(() => String, { nullable: true })
    after?: Cursor;

    @Field(() => Int, { nullable: true })
    @IsPositive({ message: 'Argument `first` must be a non-negative integer' })
    first?: number;

    @Field(() => String, { nullable: true })
    before?: Cursor;

    @Field(() => Int, { nullable: true })
    @IsPositive({ message: 'Argument `last` must be a non-negative integer' })
    last?: number;
}
```

But when I make a GraphQL request which is using this `Arguments` class with `first: -1`, for instance, I always get this:

```json
{
    "errors": [
        {
            "message": "Argument Validation Error",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "launchesConnection"
            ]
        }
    ],
    "data": null
}
```

I now `@IsPositive()` is working because I've removed the decorator, did another request with `first: -1` and the error was gone (well, not exactly, there was a different error because my code broke with `first: -1`, that's why I'm using `class-validator` in the first place).

So, what am I missing? Why isn't my `message` working?

**Comment by vlapo** [comment]
I tested `@IsPositive` with custom message and all works without `type-graphql`. Doesnt look like a problem in `class-validator`.

**Comment by rfgamaral** [comment]
> I tested `@IsPositive` with custom message and all works without `type-graphql`. Doesnt look like a problem in `class-validator`.

You are correct and I apologize for the confusion.

It seems that `type-graphql` ignores the `validationErrors` property and expects the servers to handle it by themselves. Which, in my case, it was not working because I'm using `fastify-gql` which doesn't do anything with that property. Apollo Server, on the other hand, returns the `validationErrors` within an `extensions` property of a `GraphQLError`.

Thank you for your time @vlapo.
