### ISSUE TITLE
@IsMobilePhone(locale: string) missing strict mode and documentation

### ISSUE THREAD

**Issue by carlocorradini** [typestack/class-validator#576]
Checking [validatorjs](https://github.com/validatorjs/validator.js) documentation i can  use @IsMobilePhone decorator with _any_ as locale and _strictMode_ enabled.
However in class-validator i can only set _locale_ and none _strictMode_.
Moreover the documentation for this decorator is missing some part from validatorjs docs(_any and strictMode_):

**validatorjs docs:**

![Untitled](https://user-images.githubusercontent.com/21266147/78596979-f9156d00-784c-11ea-880f-209b62c2d0c5.png)

**class-validator docs:**

![Untitled](https://user-images.githubusercontent.com/21266147/78596827-bb184900-784c-11ea-9148-b5a4232dce57.png)

Is possible to fix this?
Thanks in advance

**Comment by vlapo** [comment]
Sure. We can include this fix in `0.12.x`. Hope in few weeks after https://github.com/typestack/class-validator/pull/568 merge
