### ISSUE TITLE
ValidateNested with IsOptional throws a BadRequest

### ISSUE THREAD

**Issue by Jhonnyc** [typestack/class-validator#577]
Currently using - 
* class-transformer - 0.2.3
* class-validator - 0.11.0
* express - 4.15.4
* node version - 13.9.0 

I have 2 classes - 

```
export class A {
    @IsNotEmpty()
    @Length(2, 32)
    public someField: string;

    @IsOptional()
    @IsEnum(EnumClass)
    public someEnum: EnumClass;
}
```

```
export class B {
    @ValidateNested({ each: true })
    @Type(() => A)
    public arrayOfAs: A[];
}
```
For some reason - I get a BadRequest when I don't send the enum type although it's decorated with "IsOptional", am I doing something wrong or is that a bug? Couldn't find any sample of code to validate a nested object array with isOptional decoraror.

**Comment by vlapo** [comment]
You did not post any output, either inputs to validation. So it is hard to say where is problem. But I tested it https://stackblitz.com/edit/class-validator-gh577 and there is no error in case someEnum is not set.
```ts
export enum EnumClass {
  A = 'a',
  B = 'b'
}

export class A {
    @IsNotEmpty()
    @Length(2, 32)
    public someField: string;

    @IsOptional()
    @IsEnum(EnumClass)
    public someEnum: EnumClass;
}

export class B {
    @ValidateNested({ each: true })
    public arrayOfAs: A[];
}

const a = new A();
a.someField = 'asd';
const t = new B();
t.arrayOfAs = [a];

console.log(validateSync(t));
```

**Comment by Jhonnyc** [comment]
Hi,
Sorry for that, after some more googling I found out it does work and the problem was on my input formatting.
The error I get is - 
```
{
    "name": "BadRequestError",
    "message": "Invalid body, check 'errors' property for more info.",
    "stack": "Error: \n    at BadRequestError.HttpError [as constructor] (/Users/yoni/Desktop/Yoni/Dev/src/http-error/HttpError.ts:19:22)\n    at new BadRequestError (/Users/yoni/Desktop/Yoni/Dev/src/http-error/BadRequestError.ts:10:9)\n    at /Users/yoni/Desktop/Yoni/Dev/src/ActionParameterHandler.ts:238:40\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "errors": {}
}
```
I wanted to mark this as closed since I saw someone posted how to get the error message on this kind of situation (validating a nested array) in which the error message "hides" in the error object, but I can't find it - any chance you can post a sample code?

Thanks! 🙏

**Comment by vlapo** [comment]
Sorry, I dont understand what do you mean by error message "hides" in error object. Do you want to find error messages in ValidatorError object?

**Comment by yonikselina** [comment]
@vlapo I meant that once I'm trying to validate an array of object by using the "ValidateNested" decorator I get an empty "errors" object which means I can propagate back to the client what was done wrong. For instance if for one of the objects the "someField" has a length > 32 or < 2 than I don't see the relevant error. Hopes it's clearer.

**Comment by Jhonnyc** [comment]
@vlapo I meant that once I'm trying to validate an array of object by using the "ValidateNested" decorator I get an empty "errors" object which means I can propagate back to the client what was done wrong. For instance if for one of the objects the "someField" has a length > 32 or < 2 than I don't see the relevant error. Hopes it's clearer.

**Comment by vlapo** [comment]
Did you find solution? :)

**Comment by Jhonnyc** [comment]
Hi @vlapo, Not really, but after a clean build + set and unset of defaultErrorHandler on routing-controller options I got data on the "errors" property of the error object, not sure why (as per the documentation of routing controllers defaultErrorHandler is set by default on dev environment, but explicitly setting it to true building and then back to false then a rebuild solved the problem) might have been a cache problem? 0_o
