### ISSUE TITLE
@IsOptional() + @NotEquals(null) not working

### ISSUE THREAD

**Issue by chutiphon-k** [typestack/class-validator#579]
I want to validate displayName with optional and not equal null but it not working. it does not validate `@NotEquals(null)`.

```ts
export class UpdateDto implements Partial<UserEntity> {
  @ApiProperty()
  @IsOptional()
  @NotEquals(null)
  displayName?: string;
}
```

this case is pass
input:
```json
{
 displayName: null
}
```

**Comment by vlapo** [comment]
What are your `ValidatorOptions` https://github.com/typestack/class-validator#passing-options. Maybe you skip missing properties.

**Comment by chutiphon-k** [comment]
I don't set `ValidatorOptions`. I use the default.

**Comment by tmtron** [comment]
This does not work, because `@IsOptional()` notices that the value is `null` and then all other validators (including `@NotEquals(null)`) are ignored

[@IsOptional() docs](https://github.com/typestack/class-validator#validation-decorators):
>Checks if given value is empty (=== null, === undefined) and if so, ignores all the validators on the property.

I could also not make this work the other way around: [Stackoverflow: "How to allow null, but forbid undefined?"](https://stackoverflow.com/questions/61211664/how-to-allow-null-but-forbid-undefined)

**Comment by tmtron** [comment]
**Recommended**
I suggest, that you remove ` @NotEquals(null)` and set `skipMissingProperties` to `true` in the [validation options](https://github.com/typestack/class-validator#passing-options)  
see this [Stackblitz example](https://stackblitz.com/edit/class-validate-not-null-2)

**Alternative** 

When you want to use the default validation options, you can use `ValidateIf` to make it work:
```
export class UpdateDto {
  @IsString()
  @NotEquals(null)
  @ValidateIf((object, value) => value !== undefined)
  displayName?: string;
}
```
This will pass the validation when `displayName` is `undefined` or a string, but fail for `null`.

see this [Stackblitz example](https://stackblitz.com/edit/class-validate-not-null)

**Comment by chutiphon-k** [comment]
Great, it works. 😄 

> **Recommended**
> I suggest, that you remove ` @NotEquals(null)` and set `skipMissingProperties` to `true` in the [validation options](https://github.com/typestack/class-validator#passing-options)
> see this [Stackblitz example](https://stackblitz.com/edit/class-validate-not-null-2)
> 
> **Alternative**
> 
> When you want to use the default validation options, you can use `ValidateIf` to make it work:
> 
> ```
> export class UpdateDto {
>   @IsString()
>   @NotEquals(null)
>   @ValidateIf((object, value) => value !== undefined)
>   displayName?: string;
> }
> ```
> 
> This will pass the validation when `displayName` is `undefined` or a string, but fail for `null`.
> 
> see this [Stackblitz example](https://stackblitz.com/edit/class-validate-not-null)
