### ISSUE TITLE
Validate Object key only when have value

### ISSUE THREAD

**Issue by sandip-j** [typestack/class-validator#580]
If have the following class object:
```ts
export class ClanDetail {
    @IsUUID()
    public clanId?: string;

    @IsNotEmpty()
    @MaxLength(20)
    public clanName: string;

    @IsUUID()
    @IsNotEmpty()
    public clanPositionId: string;

    @IsUUID()
    @IsNotEmpty()
    public gameId: string;
}
```

`clanId` is optional but when `clanId` have value then it should be UUID. but class-validator throwing validation fail error  when `clanId` have `null`.
From my view validation should happen when object key have value. For the required value `IsNotEmpty` is available.

**Comment by vlapo** [comment]
You have to use `@IsOptional()` annotation or use `skipMissingProperties` validation option.

https://github.com/typestack/class-validator#skipping-missing-properties
https://github.com/typestack/class-validator#validation-decorators

**Comment by sandip-j** [comment]
Thanks for 

> You have to use `@IsOptional()` annotation or use `skipMissingProperties` validation option.
> 
> https://github.com/typestack/class-validator#skipping-missing-properties
> https://github.com/typestack/class-validator#validation-decorators

It worked
