### ISSUE TITLE
Question: How do you check a string if it contains at least 1 number, at least 1 of these special character !@#$%^&, and at least 1 Upper Case

### ISSUE THREAD

**Issue by artoodeeto** [typestack/class-validator#583]
Hello. thank you for this awesomeness. just a question. How would you check a string with the said conditions? `Contains()` cant accept an array of strings. Should I create a custom validator for this? 

Use case:
Check a password before saving it in the database.

Thank you sir!

**Comment by satanTime** [comment]
Hi,

you can add several `@Contains`, but because your task sounds more like regexp I would suggest to use `@Matches`.

```typescript
@Matches(/[0-9]/)
@Matches(/[!@#$%^&]/)
@Matches(/[A-Z]/)
public password: string;
```

**Comment by artoodeeto** [comment]
@satanTime thank you man. I didnt that on the documentation last night. Maybe was just tired. thanks again. will close this now.
