### ISSUE TITLE
[question] Integration/Extension.  Possible to get list of all possible validation errors and messages?

### ISSUE THREAD

**Issue by kalani96746** [typestack/class-validator#594]
I'm trying to integrate class-validator with ng-bootstrap-form-validation and Angular forms and want to share my result with the community because I believe domain based validation is way better than what angular offers but the forms are super nice when it can make its way all the way to the UI.  I use class validator but Angular is deprecating ngModel so class-validator doesnʻt have a long shelf life on the client side if I canʻt get this working (close).

To get it working I need to understand how I can get list of constraints of all properties on a Class (rather than an instance) and a list of all error messages for each of those constraints.

There are other decorators (non validator related) on the domain properties and these shouldnʻt be included (class-transformer, for firestore indexing, etc).

I want to call:
`validatorsMetadata(NewUserRegistration); //where NewUserRegistration is a class`
I want to get something back like this: (pretend other properties are filled in..ideally would work with sub object verification too...
```
 {
		firstName: {
                         "constraints": {
			      "isNotEmpty": "firstName should not be empty",
			       "minLength":  "firstName must be longer than or equal to 2 characters",
                         }
		},
		lastName: {},
		email: {},
		password: {},
		confirmPassword: {},
		acceptsAgreement: {}
	}
}
```

I would use this in conjuction with a custom validator I used which uses class validator as well as constructs the form controls and error messages needed for the ui to handle all the fancy things it does like make the borders red or green, checkboxes, and error messages show when its left and field is dirty; Iʻm also able to update the domain object with every validation so even though angular is deprecating ngModel it would still work with class-validator.

Can you give me some hints/instructions on how to get this metadata in an easy to consume way..?  .I saw decorator metadata somewhere in my memory but I want to know how you might go about assembling something like this so class-validator can be used in conjunction with angular forms.

Mahalo!

Kalani

PS - this is prior to the object needing to be validated...so I want to get the properties for a class...I know validateSync will return some of this if validating an object..but I want the complete schema used for validation and error messages.  Thanks!

**Comment by NoNameProvided** [comment]
What you ask (getting all possible errors for a validated class) is currently not possible.
