### ISSUE TITLE
`constraints` property not always present on ValidationError, despite type definitions

### ISSUE THREAD

**Issue by jjhbw** [typestack/class-validator#599]
Hi! First off, thanks for this amazing lib. It has saved me countless hours.

The title of this issue basically explains it. See the below repro case. I would expect this test to pass, as `ValidationError` should always have a `constraints` property according to its type def.

```typescript
import { MinLength, ValidateNested, validate } from 'class-validator'
import { Type, plainToClass } from 'class-transformer'

class Company {
    @MinLength(3)
    name!: string
}

class CompanySnapshot {
    @ValidateNested()
    @Type(() => Company)
    company!: Company

    @MinLength(3)
    some_other_prop!: string
}

test('validation error typedef', async () => {
    const snapshot = {
        company: { name: 's' },
        some_other_prop: 'asdf'
    }
    const validation_errors = await validate(plainToClass(CompanySnapshot, snapshot))

    console.log(validation_errors)

    expect(validation_errors).toHaveLength(1)
    for (const err of validation_errors) {
        expect(err.constraints).toBeDefined()
    }
})
```

Just let me know if you think I can help with this.

**Comment by jjhbw** [comment]
Note that this seems to happen when the validation error in question originates from the `ValidateNested` validator. Maybe the type definitions of `ValidationError` should be changed?

**Comment by vlapo** [comment]
What version of `class-validator` do you use? We change this in `0.12.0`.

**Comment by jjhbw** [comment]
Wow, you're right. I completely forgot to check. I was still running `0.11.1`. Sorry for wasting your time!
