### ISSUE TITLE
@Matches acting weird

### ISSUE THREAD

**Issue by Berger92** [typestack/class-validator#601]
Hi there,

I think it is a bug, but I might be doing something wrong.

### Description

See the following class:
```
class Example {
    @Matches(/^[0-9]{2}\/[0-9]{4}$/g)     // MM/YYYY format
    @IsOptional()
    from?: string;

    @Matches(/^[0-9]{2}\/[0-9]{4}$/g)     // MM/YYYY format
    @IsOptional()
    to?: string;
}
```

When I am only populating either of the fields, it works as expected.

```
const a = new Example();
a.from = "05/2017";

validate(a);    // gives no error
```

But when I am populating both fields, it gives me an error:

```
const a = new Example();
a.from = "05/2017";
a.to = "05/2020";

validate(a); // gives an error
```

> from must match `/^[0-9]{2}\\/[0-9]{4}$/g` regular expression

There is an extra `\` in the error message, it might have something to do with.

### Environment

- [x] nodejs: 12
- [ ] browser
- [ ] framework/library

**class-validator version:** <code>0.11.1</code>

If someone could have a look it would be appreciated.
Cheers

**Comment by vlapo** [comment]
I do not see any error. It has to be on your side.

repro: https://stackblitz.com/edit/class-validator-gh601?file=index.ts

**Comment by Berger92** [comment]
Thanks @vlapo for taking a look. Yes, it is interesting that it works on your link. It's been acting really strange.

If you run with this:

```
let t = new Test();
t.from = "05/2017";
console.log(validateSync(t));

t = new Test();
t.to = "05/2020";
console.log(validateSync(t));

t = new Test();
t.from = "05/2017";
t.to = "05/2020";

console.log(validateSync(t));
```

This will give an error for the last one.

If you run with this:

```
let t = new Test();
t.from = "05/2017";
t.to = "05/2020";

console.log(validateSync(t));

t = new Test();
t.from = "05/2017";
console.log(validateSync(t));


t = new Test();
t.to = "05/2020";
console.log(validateSync(t));
```

It gives you error for the last two ones.

I find it really strange. Am I right to assume it is an invalid behavior?

**Comment by vlapo** [comment]
It is because of `g` flag in your `RegExp`. We do not recreate instance of RegExp and use it over and over. `g` flag caused some state changes inside of instance of RegExp, so validation failed every second time. 

More info - You can find more info here https://stackoverflow.com/questions/24084926/javascript-regexp-cant-use-twice.

However I dont think so this is bug in our code. It is how `RegExp` works.

**Comment by Berger92** [comment]
@vlapo Thanks again for taking a look.

I don't think either. I don't need `g` actually.
I never came across this before, so I really appreciate your efforts.

**Comment by vlapo** [comment]
Yeah. It was my "first time" either. 😄
