### ISSUE TITLE
Documentation link is broken?

### ISSUE THREAD

**Issue by vitordhers** [typestack/class-validator#608]
### Description

Upon access this link I got a 404 error: [https://github.com/typestack/class-validator/tree/master/docs](url)

Is documentation link broken? What happened? I tried to access it a few days ago, it was offline. I just tried again to no avail and got a 404 error.

**Comment by dantehemerson** [comment]
I can acces: https://github.com/typestack/class-validator/tree/master/docs

**Comment by vlapo** [comment]
https://github.com/typestack/class-validator/tree/master/docs is up for me too.
