### ISSUE TITLE
IsInstance validator

### ISSUE THREAD

**Issue by isergey** [typestack/class-validator#62]
Is exists like isInstanse validator for run time checking?
```
class Post {
  @isInstance(User);
  user: User;
}
```
Thanks a lot!

**Comment by pleerock** [comment]
no I think there i no. However its easy to implement, you can create a PR for small feature if you need it urgently

**Comment by NoNameProvided** [comment]
Hi @isergey! 

The `@IsInstance` decorator has been added and will be included in the next release.
