### ISSUE TITLE
Each option for IsEmail decorator support 

### ISSUE THREAD

**Issue by LuisCarrilloR** [typestack/class-validator#621]
### Description

 Hello, is there anyway to validate an array of Emails? I tried to add the each option to IsEmail but it seems like it is not supported. 

`// Not supported`
 ` @IsEmail({ each: true })`
 ` from: string[];`

### Environment
- [ ] framework/library: NestJs

**Comment by smolinari** [comment]
Try doing this.

`@IsEmail({}, { each: true })`

Scott

**Comment by LuisCarrilloR** [comment]
It worked!

Thanks
