### ISSUE TITLE
@IsNotEmpty not working on non-existent field

### ISSUE THREAD

**Issue by colleeseum** [typestack/class-validator#627]
### Description

I would expect `@IsNotEmpty` to fail if the attribute is not included. For example, I have the following DTO

```ts
export class ServiceDto {
  @ApiProperty({ description: 'The type unique id of the service' })
  readonly id: number;
    
  @IsNotEmpty()
  @ApiProperty({ description: 'The type of service' })
  readonly type: string
}

export class CreateServiceDto extends PartialType(
  OmitType(ServiceDto, ['id'] as const),
) {}

```

When I pass the following object:
```ts
{ id: 1, type: "" }
```
validation works saying the field may not be empty however, when I pass the following object it will not complain:
```ts
{ id: 1 }
```

After reading the documentation I found that there is an `@IsOptional` decorator, so I would assume all other fields are mandatory by default if not set. After some experiments, this behavior is true for other decorators such as `@IsNumber`.  

### Reproduction

I tried it via the main app and the e2e app and I get the same behavior. I simply used it in the `main.ts` of my NestJS app 

```ts
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000)
```

where my DTO is called by my controller with the following code
```ts
  @ApiTags('Service')
  @ApiOperation({summary: "This will create a new service record"})
  @Post()
  @ApiCreatedResponse({ description: "Record created" , type: ServiceDto})
  create(@Body() createServiceDto: CreateServiceDto) {
    return this.serviceRepository.createService(createServiceDto)
  }
```

**class-validator version:** <code>0.12.2</code>

**Comment by scmindstep** [comment]
Actually, I found the issue is a feature interaction between two feature. 

If rather than using this, 
```
export class CreateServiceDto extends PartialType(
    OmitType(ServiceDto, ['id'] as const),
  ) {}
```

it will work as expected.  Thought I would not say there not an issue since I need to duplicate code, but I also can say if the issue is with how NestJs pass the data or with class-validator or both :-)

**Comment by Sagaryal** [comment]
Why not use below code as docs say?

> app.useGlobalPipes(new ValidationPipe());

https://docs.nestjs.com/techniques/validation#auto-validation

**Comment by NoNameProvided** [comment]
Cannot reproduce. The following works as expected:

```ts
import { IsNotEmpty, validate } from 'class-validator';

class MyPayload {
  readonly id: number;
    
  @IsNotEmpty()
  readonly type: string;

  constructor(id: number, type?: string) {
    this.id = id;
    this.type = type;
  }
}

const validInstance = new MyPayload(1, 'test');
const invalidInstance = new MyPayload(1, '');
const invalidInstance2 = new MyPayload(1);

validate(validInstance).then(console.log); // passes
validate(invalidInstance).then(console.log); // validation error type should not be empty
validate(invalidInstance2).then(console.log); // validation error type should not be empty
```

I assume your problems come from the following bit:
```ts
export class CreateServiceDto extends PartialType(
  OmitType(ServiceDto, ['id'] as const),
) {}
```

This is a weird way to extend classes I don't even understand what `PartialType` and `OmitType` is in this example. 

As long as you use `class MyClass extends OtherConstructableClass {}` validation should work.

**Comment by braaar** [comment]
> This is a weird way to extend classes I don't even understand what PartialType and OmitType is in this example.

In case you're curious, those are [GraphQL mapped types](https://docs.nestjs.com/graphql/mapped-types) used in NestJS to extend GraphQL classes. It's kind of weird syntax, but the end result is that you can extend your graphql models and keep the decorator based metadata on the class properties. For example, you can use `PartialType` to make an input model that is identical to your view model, except that all the fields are optional (or nullable, in graphql terms).
