### ISSUE TITLE
IsBtcAddress not working with testnet addresses

### ISSUE THREAD

**Issue by CamposBruno** [typestack/class-validator#639]
### Description

`IsBtcAddress` decorator not working with bitcoin testnet addresses.
As described in this [link](https://en.bitcoin.it/wiki/List_of_address_prefixes)
Testnet address are different from the mainet ones.
 * eg testnet address: `mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn`
 * eg mainet address: `17VZNX1SN5NtKa8UQFxwQbFeFc3iqRYhem`

### Reproduction
validation this example address `mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn` returns :

`"isBtcAddress": "receiver must be a BTC address"`

```
import { IsBtcAddress } from 'class-validator';

export class SendBtcTransactionDto {
    @IsBtcAddress()
    receiver: string;
}


```

### Environment
- node v12.16.1
- nestjs 
- class-validator: ^0.12.2

**Comment by Kiliandeca** [comment]
Hello,
This lib uses validator.js internally to perform validation. Extract from the source code:

```typescript
import validator from "validator";

/**
 * Check if the string is a valid BTC address.
 * If given value is not a string, then it returns false.
 */
export function isBtcAddress(value: unknown): boolean {
    return typeof value === "string" && validator.isBtcAddress(value);
}
```

If you go [in validor.js code](https://github.com/validatorjs/validator.js/blob/master/src/lib/isBtcAddress.js) you can see that they use the regex: `/^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$/`, so I think you should open an issue upstream for your question

**Comment by NoNameProvided** [comment]
Closing this as this is an upstream issue, once it gets fixed there we will include it in the next release.
