### ISSUE TITLE
How do I customize the data format

### ISSUE THREAD

**Issue by MutelyMilo** [typestack/class-validator#640]
Default:
`{
  "statusCode": 400,
  "message": [
    "Email phoenix@gmail.com already exists. Choose another email."
  ],
  "error": "Bad Request"
}`

How do I change the data format to look like this

`{
  "code": 12345,
  "message": "Email phoenix@gmail.com already exists. Choose another email."
  "otherField": "xxxxxx",
  "otherField": "xxxxxx",
}`

**Comment by Kiliandeca** [comment]
Hello, you seem to be using Nest.js and the `ValidationPipe` wich handle the statusCode and use the default class-validator error message. [Link to the documentation of the ValidationPipe](https://docs.nestjs.com/techniques/validation#auto-validation)

You can change the class-validator error message [link to the documentation](https://github.com/typestack/class-validator#validation-messages)

ex:
```ts
    @MinLength(10, {
        message: "Title is too short"
    })
    title: string;
```

If you want to change the structure (code and add other fields) you have to create your own validation pipe, please refer to the [Nest.js documentation](https://docs.nestjs.com/pipes)
