### ISSUE TITLE
Validating deep level of nested arrays (GeoJSON objects)

### ISSUE THREAD

**Issue by abouroubi** [typestack/class-validator#650]
### Description

I'm trying to validate GeoJSON objects, unfortunately I have to validate deeply nested arrays of number.

I represent my GeoJSON objects this way :

```typescript

export type PositionVm = [number, number] | [number, number, number]; 

export interface GeoJsonObjectVm {
    type:string;
    bbox?: BBoxVm;
}

export class PolygonVm implements GeoJsonObjectVm {
    type = "Polygon";

    @ArrayNotEmpty()
    @IsArray({ each: true })
    coordinates: PositionVm[][];
}

```

I have a custom validator for polygon, but I want to use the built in Latitude and Longitude validators, and arraymin.

How do you think I can address that ?

Thank you

### Environment

- [X] nodejs: 
- [ ] browser: 
- [ ] framework/library:

**Comment by NoNameProvided** [comment]
You can always crate custom validators that can validate any complex data structure the way you need it while preserving your desired typing information. 

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
