### ISSUE TITLE
question: different validation decorator based on other key's value

### ISSUE THREAD

**Issue by Asafkbalink** [typestack/class-validator#653]
### Description
Is it possible to have a different validation based on other key's value? for example, I have an array which receives an object with different types of data, having the following DTO:
```typescript
enum IBasicInfoTypes {
  text = 'text',
  number = 'number',
  boolean = 'boolean',
  datetime = 'datetime',
  currency = 'currency'
}

class BasicInfo {
  @IsString()
  translationKey: string;

  @IsNotEmpty()
  value: any;

  @IsEnum(IBasicInfoTypes)
  type: IBasicInfoTypes;
}
```
What I wanted to do, is for example when the data I receive is for example with type: `datetime`, then validate the value against: `IsISO8601`. If it's a number - validate it's a number. If it's a text - validate it's a string and so on. I couldn't find any issue / documentation regarding this. ValidateIf is not designed for this type of issue.

### Environment

- [x] nodejs: `12.18.2`
- [ ] browser: 
- [x] framework/library: NestJS `7.1.2`

**class-validator version:** <code>0.12.2</code>

**Comment by fan-tom** [comment]
Need the same functionality, seems that the only way is to create custom validator for each specific case

**Comment by NoNameProvided** [comment]
This is not possible. What I would do is create subclasses and initialize the correct class based on the received property key.

```ts
class StringBasicInfo {
  @IsString()
  translationKey: string;

  @IsNotEmpty()
  @IsString()
  value: string;

  @IsIn([IBasicInfoTypes.Text])
  type: IBasicInfoTypes.Text;
}

class NumberBasicInfo {
  @IsString()
  translationKey: string;

  @IsNotEmpty()
  @IsNumber()
  value: number;

  @IsIn([IBasicInfoTypes.Number])
  type: IBasicInfoTypes.Number;
}
```
