### ISSUE TITLE
Map validation fails

### ISSUE THREAD

**Issue by idrisadetunmbi** [typestack/class-validator#654]
### Description

I have a validation class like this just like in the docs:

```
class Invoice {
  @IsPositive({ each: true })
  invoice: Map<string, number>;
}
```

And the validation fails with `each value in invoice must be a positive number`. Not sure what I am doing wrong.

**Comment by SeWaS** [comment]
Hello there,

Were you able to solve the issue already?
I've played with this kind of validation and it seems to work fine for me 🤔. Maybe you could share the actual map that is validated or provide some code snippets here?

Cheers

**Comment by idrisadetunmbi** [comment]
Looks like the problem isn't with class-validator. I will close this now. Thanks.
