### ISSUE TITLE
"options" in ValidationDecoratorOptions interface should be optional

### ISSUE THREAD

**Issue by christophercr** [typestack/class-validator#66]
Hi,

I'm using this awesome library in my project and now I enabled the strictNullChecks option from TS to have more explicit types. Then I noticed that the "options" property in the ValidationDecoratorOptions interface is required. However, digging a bit in the source code I noticed that it is used [ValidationMetadata](https://github.com/pleerock/class-validator/blob/master/src/metadata/ValidationMetadata.ts) class but only if is defined. This class implements the corresponding [ValidationMetadataArgs](https://github.com/pleerock/class-validator/blob/master/src/metadata/ValidationMetadataArgs.ts) interface where indeed the "options" (alias "validationOptions") are optional.

Therefore I think that the "options" property should be marked as optional in the ValidationDecoratorOptions.

It's an easy and quick fix...

**Comment by pleerock** [comment]
yes it should be there can you check latest version?
