### ISSUE TITLE
`@IsNotEmptyObject()` and `@Type` does not work in conjunction

### ISSUE THREAD

**Issue by peresbruno** [typestack/class-validator#660]
### Description

Hi guys,

Basically, the `@IsNotEmptyObject()` does not work together with `@Type`. 

### Reproduction

I have a class structure like (other fields omitted for the sake of simplicity):

```
@Exclude()
export class GenerateOptions {
  constructor(partial: Partial<GenerateOptions>) {
    Object.assign(this, partial);
  }

  (...)

  @Expose()
  @IsDefined()
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => GroupOptions)
  groupers: GroupOptions;

  (...)

}

@Exclude()
class GroupOptions {
  constructor(partial: Partial<GroupOptions>) {
    Object.assign(this, partial);
  }

  @Expose()
  @IsBoolean()
  @IsOptional()
  year: boolean;

  @Expose()
  @IsBoolean()
  @IsOptional()
  month: boolean;
  (...)
}
```

Making a request with this payload to my API endpoint (the classes above are DTOs):

```
{
	(...)
	"groupers": {
	}
        (...)
}
```
However, if I remove the `@Type(() => GroupOptions)` from `groupers` property the `@IsNotEmptyObject()` works as expected and the related error is returned. The problem is that this way I can send any data inside groupers object, since without `@Type(() => GroupOptions)` the object is not validated.

https://typescript-tlbcs6.stackblitz.io

### Environment

- [x] nodejs: 12.16.1
- [x] framework/library: NestJS 7.4.1

**class-validator version:** (From my `package.json`)
```
    "class-transformer": "^0.2.3",
    "class-validator": "^0.11.1",
    "reflect-metadata": "^0.1.13",
```

**UPDATE:**

I noticed that removing all `@Expose` and `@Exclude` everything works as expected.

**Comment by vlapo** [comment]
Problem is that `class-transformer` will create object with year and month equal undefined. But in version `class-validator@0.13` we have an option to validate empty object with all properties equal undefined or null. `@IsNotEmptyObject({ nullable: true })` 

Reference: https://github.com/typestack/class-validator/pull/635

I hope this helps :)
