### ISSUE TITLE
fix:  Unable to resolve signature of property decorator when called as an expression - typescript

### ISSUE THREAD

**Issue by kacluk123** [typestack/class-validator#684]
I can't use class-validator because of typescript bug

```
import { isNotEmpty } from 'class-validator'

export class GetTokenDto {
  @isNotEmpty() code: string;
}
```
and the compile error is:

> error TS1240: Unable to resolve signature of property decorator when called as an expression.
>   This expression is not callable.
>     Type 'Boolean' has no call signatures.
> 
> 4   @isNotEmpty() code: string;

**Comment by NoNameProvided** [comment]
Hi @kacluk123! 

You have a typo in your example `isNotEmpty` => `IsNotEmpty`. With this fix applied I cannot reproduce your issue. Working example:

```ts
import 'reflect-metadata';
import { IsNotEmpty, validateSync} from 'class-validator';

export class GetTokenDto {
  @IsNotEmpty() code: string;
}

const instance = new  GetTokenDto();

const errors = validateSync(instance)
// proper error is thrown here

console.log(errors);
```
