### ISSUE TITLE
Example for use this awesome module in angular 2 form validation. 

### ISSUE THREAD

**Issue by yantrab** [typestack/class-validator#69]
There is a way to avoid writing all the rules again?

**Comment by mesche** [comment]
Hi,
I created a simple angular 2 custom validator for my purposes.
The validator uses this class-validator lib to validate the form control.

You can find the source code here:
[DynaValidator](https://github.com/mesche/angular-collection/blob/master/Angular4-Example-Dynamic-Form-And-Validation/src/app/dyna/dyna.validator.ts)
and the complete example project here:
[Example-Dynamic-Form-And-Validation](https://github.com/mesche/angular-collection/blob/master/Angular4-Example-Dynamic-Form-And-Validation)

I know it is not perfect or really performant, but it works for my use case.

I hope there is a better solution soon.

**Comment by FortinFred** [comment]
Wow that's very interesting !!!

I was thinking of having this kind of validation which is somehow not attached to Angular but consumed by it.  This way, the same model class can be used server side for validation.

**Comment by joeldatabox** [comment]
@mesche Congratulations on your work. It was excellent! Your code will help me a lot. Thank you!
