### ISSUE TITLE
add stopAtFirstError to ValidatorOptions.

### ISSUE THREAD

**Issue by sptGabriel** [typestack/class-validator#695]
could you add to
stopAtFirstError?: boolean for the validatorOptions?

```
/**
 * Options passed to validator during validation.
 */
export interface ValidatorOptions {
    /**
     * If set to true then validator will skip validation of all properties that are undefined in the validating object.
     */
    skipUndefinedProperties?: boolean;
    /**
     * If set to true then validator will skip validation of all properties that are null in the validating object.
     */
    skipNullProperties?: boolean;
    /**
     * If set to true then validator will skip validation of all properties that are null or undefined in the validating object.
     */
    skipMissingProperties?: boolean;
    /**
     * If set to true validator will strip validated object of any properties that do not have any decorators.
     *
     * Tip: if no other decorator is suitable for your property use @Allow decorator.
     */
    whitelist?: boolean;
    /**
     * If set to true, instead of stripping non-whitelisted properties validator will throw an error
     */
    forbidNonWhitelisted?: boolean;
    /**
     * Groups to be used during validation of the object.
     */
    groups?: string[];
    /**
     * If set to true, the validation will not use default messages.
     * Error message always will be undefined if its not explicitly set.
     */
    dismissDefaultMessages?: boolean;
    /**
     * ValidationError special options.
     */
    validationError?: {
        /**
         * Indicates if target should be exposed in ValidationError.
         */
        target?: boolean;
        /**
         * Indicates if validated value should be exposed in ValidationError.
         */
        value?: boolean;
    };
    /**
     * Settings true will cause fail validation of unknown objects.
     */
    stopAtFirstError?: boolean;
    forbidUnknownValues?: boolean;
}
```

**Comment by ytetsuro** [comment]
I've added it, but does that mean it's not working?
If it doesn't work, what is your expected and actual behavior?

https://github.com/typestack/class-validator/pull/620

**Comment by sptGabriel** [comment]
> Eu adicionei, mas isso significa que não está funcionando? 
> Se não funcionar, qual é o seu comportamento esperado e real?
> 
> [# 620](https://github.com/typestack/class-validator/pull/620)

i don't know why i used yarn add class-validator, but said there was no stopAtFirstError in the interface, but it worked normally after I added the interface manually works

**Comment by ytetsuro** [comment]
Please wait to create a release.

Not yet publish #620 merged version.

https://github.com/typestack/class-validator/releases
https://github.com/typestack/class-validator/actions?query=workflow%3ACD

**Comment by cristian-chis** [comment]
This should be in the current release (**0.12.2**) but I don't see any update in the code. The spec appears in the readme file, though. I tried to manually update `ValidatorOptions` interface manually, but the code in `ValidationExecutor` regarding this change is missing. Manually updating all files does not seem the best solution.

Could somebody give me a hand?

Thanks!

**Comment by s524797336** [comment]
Not support for async validators
