### ISSUE TITLE
How to format error message response?

### ISSUE THREAD

**Issue by swapnil-gawali** [typestack/class-validator#707]
I do not want to wrap error message inside an array, I just want plain text as per the expected result.

**This is what i am expecting:**
 
 

```
{
    "statusCode": 400,
    "message": "This is a custom error message",
    "error": "Bad Request"
}
```

**This is what I am getting:**
 

```
{
    "statusCode": 400,
    "message": [
        "This is a custom error message"
    ],
    "error": "Bad Request"
}
```

**Comment by Kiliandeca** [comment]
Hi, you seem to be using NestJS and the built-in validation pipe which use this library.

You can find [the source code here](https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L102) but here the interesing part:
```ts
    const errors = await classValidator.validate(entity, this.validatorOptions);
    if (errors.length > 0) {
      throw this.exceptionFactory(errors);
    }
```

As you can see, the default `exceptionFactory` is responsible for the result you are getting, it add every validation error message to the array. This is something done by NestJS and not class-validator.

As stated in [the NestJs documentation](https://docs.nestjs.com/techniques/validation#using-the-built-in-validationpipe) you can create and specify a custom `exceptionFactory` to change this behavior and get the result you want (display only the first error message or concatenate them in a string)

**Comment by swapnil-gawali** [comment]
@Kiliandeca thanks for the suggestion.

I have implemented the following solution and it is working as expected:

```
app.useGlobalPipes(new ValidationPipe({
        exceptionFactory: (errors: ValidationError[]) => {
            return new BadRequestException(errors[0].constraints[Object.keys(errors[0].constraints)[0]]);
        }
    }));
```

this might help someone in the future.
