### ISSUE TITLE
question: How i can pass a custom message to @isEmail validator?

### ISSUE THREAD

**Issue by veronesecoms** [typestack/class-validator#718]
There's a way to define a custom message to @isEmail validator?

Something like i pass in other validators like IsNotEmpty:

`@IsNotEmpty({ message: 'You don't fill this required field!' })`

Thanks for this lib :) <3

**Comment by NickKelly1** [comment]
You can achieve it like this:

```typescript
// some complicated validators allow additional options in the first argument
// for these validators, ValidationOptions is the second argument
@IsEmail(undefined, { message: 'Custom message goes here :)' })
```
