### ISSUE TITLE
Bug? validator.isDate("2") is true

### ISSUE THREAD

**Issue by zifnab87** [typestack/class-validator#72]
Hi,

I am trying this manual validator logic 
```
let validator: Validator = new Validator();
validator.isDate("2")
``` 

and I get true. Also I wonder how I can provide local date format so it works properly. Thanks!

**Comment by NoNameProvided** [comment]
Yes, it's valid because `new Date('2')` is a valid date and equals to

```
Thu Feb 01 2001 00:00:00 GMT+0100 (CET)
```
