### ISSUE TITLE
question: How to create Conditional Custom Validation?

### ISSUE THREAD

**Issue by dennbagas** [typestack/class-validator#733]
Here is my DTO:
```typescript
export class ApplyCashbackDto {
@IsNotEmpty()
promoCode: string

// Conditional Validation
extras: string
}
```
I was trying to conditionally validate the `extras` property based on `promoCode` property, but i have to check first to the DB if the `promoCode` need some `extras` data because not all the `promoCode` must include the `extras` property

How to achieve this custom coditional validation?

**Comment by Kiliandeca** [comment]
Hi, you can take a look at the [Conditional validation](https://github.com/typestack/class-validator#conditional-validation) in the documentation.

ex:
```ts
export class ApplyCashbackDto {
  @IsNotEmpty()
  promoCode: string

  @ValidateIf(o => {
      // business logic to check if o.promoCode need extras property, return boolean
      // if false all validation decorators for this field are ignored
    })
  @IsNotEmpty()
  extras: string
}
```

**Comment by dennbagas** [comment]
`@ValidateIf()` can be used to conditionally validate on a property **based on other property** from the object being validated. What i need is to conditionally validate based on data from other sources like from databases, in this case the `promoCode` property. 

It is something like creating [custom validation classes](https://github.com/typestack/class-validator#custom-validation-classes) so i can inject my repository class and perform some query to the database, if the `promoCode` property match with the data from database then do validation, otherwise skip the validation.

**Comment by NickKelly1** [comment]
Hi @dennbagas

You can create a [custom async validator](https://github.com/typestack/class-validator#custom-validation-classes) that may access your database. Furthermore, if using a service container, you can [connect it connect Class Validator](https://github.com/typestack/class-validator#using-service-container) to access your services.

However, accessing your database in a validator has [some limitations](https://github.com/typestack/class-validator/issues/631), as you cannot provide arguments on a per-validation basis.

**Comment by dennbagas** [comment]
Hi @NickKelly1 

Yes, i can create [custom async validator](https://github.com/typestack/class-validator#custom-validation-classes), but that wasn't an **optional validator**. Its like regular validator that validate the value is right or not. 

What i want is a custom **optional** async validation. Something like `@ValidateIf()` but async version

**Comment by NoNameProvided** [comment]
Currently, you can achieve this only if you put the optional validation logic in your async validator.  Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
