### ISSUE TITLE
ValidateIf ignore all other validators. How to ignore only some of them?

### ISSUE THREAD

**Issue by candunaj** [typestack/class-validator#740]
I have property which is required only if other property is true. But format still needs to be validated.

class SomeClass{
    shouldBeRequired: boolean;

    @ValidateIf(o=>o.shouldBeRequired)
    @IsNotEmpty()
    @Matches(/test/)
    someProperty: string;
}

If validateIf return false then all validators are ignored. How can I make validateIf to ignore only IsNotEmpty validator?

**Comment by Kiliandeca** [comment]
Hi, this is related to #651 and you can be achieved by creating a custom validator.
You can check NickKelly1 answer

```ts
function IsOptionalIf(allowOptional: (obj: any, value: any) => boolean, options?: ValidationOptions) {
  // If required, do validate. Otherwise if null|undefined, don't validate
  return ValidateIf((obj, value) => !allowOptional(obj, value) || value != null), options)
}

class SomeClass{
  shouldBeRequired: boolean;

  @IsOptionalIf(o=>o.shouldBeRequired)
  @IsNotEmpty()
  @Matches(/test/)
  someProperty: string;
}
```

**Comment by NoNameProvided** [comment]
As mentioned possible via a custom validator. Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
