### ISSUE TITLE
Validate with @IsIn and transform with @Transform later is not working as expected

### ISSUE THREAD

**Issue by adrianwix** [typestack/class-validator#752]
### Description

I am trying to use `@Transform` and `@IsIn` together to perform validation and then transform a string value to a class.
I am using Nestjs and TypeORM and to save relationships they expect that one assigns an object containing the primary key to the property with the relationship `product.category = { id }` instead of `product.category = id`. 

**Minimal code-snippet showcasing the problem**
 

```ts
@Transform((id) => plainToClass(Category, { id }))
@IsIn(["Key1", "Key2"])
@ManyToOne(() => Category)
category: Category
```

### Expected behavior

The validation should be run first and then the transformation

### Actual behavior

I am getting a validation error even when then value is right

This work though, first transforming and then running the validation:
```ts
@ValidateNested()
@Transform((id) => plainToClass(Category, { id }))
@ManyToOne(() => Category)
category: Category
```
But I don't want to get a validation error like "category.id must be one of the following values: " because the client sended a "category" property not a "category.id"

Packages:
-   "@nestjs/common": "^7.4.4"
-   "class-transformer": "^0.3.1",
-   "class-validator": "^0.12.2",

**Comment by rubiin** [comment]
a simple repo for reproducing the issue?
