### ISSUE TITLE
Why was IsDateString decorator removed?

### ISSUE THREAD

**Issue by HLayton** [typestack/class-validator#77]
In commit 6d58881bc15fac323dbd8dfaf2bab03a28233d39 you removed the @IsDateString decorator. I can not see the reason for this from the documentation available on GitHub and am curious why this was done. This is a feature that would come in very handy for me and as such I am really curious as to why it was removed, and would really appreciate it if it could be brought back.

**Comment by anhchienhoang** [comment]
Same for me. Don't know why you removed it? Is that only `IsDate` is enough, isn't it?

**Comment by st-clair-clarke** [comment]
Requesting the reinstallation of @IsDateString() please. I get date as string directly from a callendar.

Thanks

**Comment by drew-r** [comment]
Please reinstate

**Comment by stonecold123** [comment]
Any news? I want to use `IsDateString()` with typeorm entity.

**Comment by NoNameProvided** [comment]
It's not removed from the library. It's in [decorator.ts#L292-L302][1]

[1]: https://github.com/typestack/class-validator/blob/master/src/decorator/decorators.ts#L292-L302

**Comment by NoNameProvided** [comment]
I am going ahead and close this if you have any issues using the `@IsDateString` decorator, please open a new issue. Thanks!
