### ISSUE TITLE
question: how check the length of double byte characters 

### ISSUE THREAD

**Issue by sanjitbauli** [typestack/class-validator#775]
### Description
Double byte character's actual length is different than what we from .length
Due to that when someone enters some double-byte characters, even if the class-validator passes it, it may fail during insert query to the database.

Example: Lenth of this string "Test" is 4, 
测试 length is 2.
but the actual length of 测试 is 30.

### Proposed solution
Adding a flag to the MaxLength decorator which will tell the codes whether it should consider the double bit chars length or not.

**Comment by ytetsuro** [comment]
I think the solution to use `IsByteLength` decorator.

> but the actual length of 测试 is 30.

really?
I think `测试` is 6 byte.

**Comment by sanjitbauli** [comment]
@ytetsuro i tried with the following:

<img width="299" alt="Screenshot 2020-10-07 at 12 26 16 PM" src="https://user-images.githubusercontent.com/272230/95297600-5b9d0380-0898-11eb-85ed-70ce5918c8e7.png">
But still the length is not 2. which may create the same issue as i decribed.

**Comment by ytetsuro** [comment]
Thanks, response.
Why using `encode`?

If you want bytes length, do the following

```typescript
(new Blob(['测试'])).size;
```

`IsByteLength` is validation to byte length.

We would like to receive the following information.

* Code that reproduces the problem you are feeling.
* Your ideal outcome.
* Your actual results.

**Comment by NoNameProvided** [comment]
Closing this as answered.
