### ISSUE TITLE
question: Is it possible to validate dynamic keys?

### ISSUE THREAD

**Issue by rafaelluz-f** [typestack/class-validator#779]
**I was trying to...**
I'm wrapping an external api inside my NestJS api and  start to face the problem when comes to validate a dynamic key. This external api expect that this key match a named row and then try to update.

**The problem:**
My JSON looks like:

`
"grid": [
    {
      "dynamic-row-name": [
        {
          //nestedObject
        }
      ]
    }
  ]
`

This is it possible to validate using class-validator?

**Comment by Kiliandeca** [comment]
Hi, what I would usually do in this case is converting object with the dynamic key to a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) before doing the validation:

```ts
class MyClass {
  @ValidateNested({ each: true })
  myMap: Map<string, MyOtherClass>; 
}

const obj = new MyClass();
for (const [key, value] of Object.entries(plainJsObjectWithDynamicKey)) {
    const valueInstance = // Transform value as an instance of MyOtherClass
    obj.myMap.set(key, valueInstance); // will do obj.myMap.set("dynamic-row-name", valueInstance);
}
```

But I'm pretty sure it **won't work in your case** because it will do an array of map of array and this library doesn't currently support multi-dimensional arrays:
```ts 
grid: Map<string, MyNestedObjectClass[]>[];
```

Maybe you can try to decompose your JSON into multiple small nested Class but it won't look really nice

**Comment by rafaelfigueiredo-l** [comment]
Hi @Kiliandeca 

Thanks for your answer. I will look into this.

The "full" structure is like this:

` 
"grid": [
    {
      "gridName": [
        {
          "add": {
            "values": {
              "field1": "something",
              "field2": "Something"
            }
          },
          "update": {
            "id": "2",
            "values": {
              "field1": "new Something",
              "field1": "new Something"
            }
          },
          "remove": {
            "id": 1
          }
        }
      ]
    }
  ]
`
Between arrays has an object. There is some hope? rs

**Comment by NoNameProvided** [comment]
No. We don't support validation with dynamic keys.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
