### ISSUE TITLE
question: how can I customize the array error

### ISSUE THREAD

**Issue by semenov-ol** [typestack/class-validator#781]
**I was trying to...**
when I validate the nested properties of an array with such decorator `@IsString({message: '$target.$property must be a string'})` 
I get such error `0.Clasification.id must be a string`.

**The problem:**
The question is where the index `0` is taken and how i can manage it?
And how i can write down such error message for all properies in array without writing it in each decorator?

**Comment by NoNameProvided** [comment]
You cannot customize the generated error messages and we already have a few open issues discussing how to allow this. 

> The question is where the index 0 is taken and how i can manage it?

The `0` is added because the validation error happened in an array with the element at 0 index.
