### ISSUE TITLE
Is this library currently maintained?

### ISSUE THREAD

**Issue by moar55** [typestack/class-validator#788]

**Comment by harm-less** [comment]
I was coincidentally just wondering the same thing. Things have been merged recently to develop, but no release is made since April.

I started using this package at my own risk:
https://github.com/typestack/class-validator/pull/743#issuecomment-689128670

**Comment by bgdsh** [comment]
the latest version on npm registry is released at 6 months ago

**Comment by Kiliandeca** [comment]
Hi, FYI there was recently a call for maintainer and contributor for TypeStack projects/repositories https://github.com/typestack/routing-controllers/issues/579

Some of us wanted to participate in `class-validator` and help sorting issues and answering questions. You should ask @NoNameProvided for PR and release but he's quite busy and as you know maintaining a FOSS project (many TypeStack projects in this case) is time-consuming

I'm sure you're more than welcome if you want to take part and contribute

**Comment by mickaelmesdocteurs** [comment]
@NoNameProvided Is there a new release planed in the near future ?
We need this feature https://github.com/typestack/class-validator/pull/680 to improve groups usage

**Comment by nolazybits** [comment]
Coming here for the same reason as everyone.
Changes to group have been added which makes this library even nicer but are still in the develop branch which is not ideal (we can pull from develop but as it is mutable it's risky)
Could you please create a new release?

**Comment by JamesMcFall** [comment]
I've just tried to use some code from a merged PR (#680) just to find out it was merged to develop 4 months ago and still hasn't been released to master. Can this be released to master please @NoNameProvided? Much appreciated.

**Comment by nolazybits** [comment]
See my comment here
https://github.com/typestack/class-validator/issues/812#issuecomment-739612691

**Comment by NoNameProvided** [comment]
Yes. Sorry for the delayed release, I thought it was released a long ago. You can always ping me on the TypesStack Slack channel. (kinda hidden currently, but you can request to join via writing to `typestack-slack-invite@outlook.com`.
