### ISSUE TITLE
feature: Language support

### ISSUE THREAD

**Issue by aurelien-robineau** [typestack/class-validator#789]
### Description
`class-validator` is usefull but errors are only in english (or have I missed something ?) It is quite inconvenient to manually enter messages when it could be automatic.

### Proposed solution
This could be done in the `ValidatorOptions` interface via a `locale` property.
``` javascript
export interface ValidatorOptions {
    locale: 'fr',
}
```
Or in the decorators options.
``` javascript
@Max(10, { locale: 'fr' })
```

**Comment by Kiliandeca** [comment]
Hi, it's a duplicate of #169
