### ISSUE TITLE
What value should I provide to @isNotEmpty validator?

### ISSUE THREAD

**Issue by kentforth** [typestack/class-validator#790]
I have a field of type string. I don't want somebody to create as record with empty value in field
I tried to use isNotEmpty Validator like this, but it throws an error:
"An argument for 'value' was not provided."

**What value should I provide to this validator?** 

![Screenshot_1](https://user-images.githubusercontent.com/17134421/96997977-f6fecb80-155c-11eb-9765-c3a0b6e4d8fa.jpg)

```
import { Entity, Column, PrimaryGeneratedColumn} from 'typeorm';
import {isNotEmpty} from 'class-validator';

@Entity()
export class CategoryText {
  @isNotEmpty()
  @Column()
  name: string;
}
```

**Comment by Kiliandeca** [comment]
Hi,

You should use `@IsNotEmpty` with an uppercase I.

`IsNotEmpty` is the decorator and `isNotEmpty` is the function used by the decorator, this is why you got the error ! Both of them are exported in [src/decorator/common/IsNotEmpty.ts](https://github.com/typestack/class-validator/blob/master/src/decorator/common/IsNotEmpty.ts)

**Comment by kentforth** [comment]
@Kiliandeca Thank you!
