### ISSUE TITLE
question: Nested validation to multiple possible types

### ISSUE THREAD

**Issue by Ripolak** [typestack/class-validator#791]
**I was trying to...**
My code looks something like this:
```typescript
class TypeOne {
    @IsString()
    @IsNotEmpty()
    @IsOptional()
    stringValue?: string

    @IsNumber()
    numValue: number
}


class TypeTwo {
    @IsString()
    @IsNotEmpty()
    otherValue: string
}

class MyType {
    @ValidateNested()
    @Type(() => ? /* What should go here in this case? */)
    param: TypeOne | TypeTwo
}

```

**The problem:**
Right now, I can't use the validator of TypeOne and TypeTwo without specifying one type in the class itself. Is there currently a "right" way to validate both by checking which of the types I actually get each time? I know I can create a "bigger" class which includes all possible parameters from TypeOne and TypeTwo, but that's problematic when trying to use optional parameters or having parameters by the same name but different validations.

Is there a good solution for this?

**Comment by nyotiemon** [comment]
I still havent successfully aplying it, but you should check this [guide](https://github.com/typestack/class-transformer#providing-more-than-one-type-option)

**Comment by nyotiemon** [comment]
I successfully make it work by adding `@ValidateNested()`

``` typescript
export class Album {
  id: number;
  name: string;

  @ValidateNested()
  @Type(() => Photo, {
    discriminator: {
      property: '__type',
      subTypes: [
        { value: Landscape, name: 'landscape' },
        { value: Portrait, name: 'portrait' },
        { value: UnderWater, name: 'underwater' },
      ],
    },
  })
  topPhoto: Landscape | Portrait | UnderWater;
}

```

**Comment by vlapo** [comment]
Glad to see you resolve your problem ;) But this is `class-tranformer` related issue next time
