### ISSUE TITLE
feature: IsNotEmpty with only spaces validation

### ISSUE THREAD

**Issue by lyorix** [typestack/class-validator#794]
### Description
When using IsNotEmpty decorator, I would expect values with spaces only not to be validated.

Example: value `'    '` should be empty.

### Current implementation
```
export function isNotEmpty(value: unknown): boolean {
    return value !== "" && value !== null && value !== undefined;
}
```
### Proposed solution
```
export function isNotEmpty(value: unknown): boolean {
  return value !== null && value !== undefined && ((typeof value === 'string') ? value.trim() !== '' : value !== '');
}
```

**Comment by Kiliandeca** [comment]
Hi, just add another `Matches` decorator with a negative regex for spaces, something with a char negator `[^ ]` or maybe a negative lookahead like `(?!^ +$)` (didn't test)

**Comment by Kiliandeca** [comment]
Hi,

Thanks for your feedback, I get what you're saying but I think there are cases where spaces characters are considered as valid and not empty and modifying the behaviour of `IsNotEmpty` would be a breaking change.

In your case, I would suggest doing some sanitizing like trimming spaces for some fields before doing the validation. There is a Typestack library named [class-sanitizer](https://github.com/typestack/class-sanitizer) which got a `@Trim()` decorator but it's now deprecated. (Here's the issue talking about porting it into [class-tranformer](https://github.com/typestack/class-transformer): https://github.com/typestack/class-transformer/issues/401)

Using a custom decorator as you did is another way and it works great

have a great day

**Comment by lyorix** [comment]
Hi,

I get the point. I will continue using my custom decorator so.

Have a great day too.
