### ISSUE TITLE
question: Validation for index signatures?

### ISSUE THREAD

**Issue by bulatgab** [typestack/class-validator#795]
**I was trying to...**
add validation to an object having an index signature. In JSON:
```
"reviewed": {
  "207299": false,
  "207369": false
}
```

**The problem:**
I could do:
```
class Reviewed {
  @IsBoolean()
  [key: string]: boolean
}

class Parent {
  @ValidateNested
  reviewed: Reviewed
}
```
But it gives me `TS1206: Decorators are not valid here`

**Comment by bulatgab** [comment]
Used `Map` instead:
```
  @IsInstance(Map)
  @IsBoolean({each: true})
  reviewed: Map<string, boolean>
```

**Comment by vlapo** [comment]
I dont think it is possible create property decorator for index signature. Your solution using Map is fair enough.
