### ISSUE TITLE
question: ValidationMetadata module not found when testing

### ISSUE THREAD

**Issue by htorjmen** [typestack/class-validator#798]
Hello, 
I'm new here and this is my first topic.
Lately, i updated class-validator from 0.11.1 to 0.12.2.
I have a folder which contains customized validators and in the index i export ValidationMetadata which before the import was like this:
`export { ValidationMetadata } from 'class-validator/metadata/ValidationMetadata';`
after the major update, the route changed to : `export { ValidationMetadata } from 'class-validator/types/metadata/ValidationMetadata';` 
when i want to run tests there is an error which says : Error: Cannot find module 'class-validator/types/metadata/ValidationMetadata'

does anyone knows why ?

**Comment by cstst** [comment]
Facing same issue

**Comment by NoNameProvided** [comment]
Hi!

Sorry for the late reply. If you are still facing the issue please provide a **minimal** reproducible example in a new issue. Thanks.
