### ISSUE TITLE
@MinDate() class date argument causing error

### ISSUE THREAD

**Issue by oleersoy** [typestack/class-validator#80]
I'm trying to use `@MinDate(this.purchaseDate)` as documented in this [SO post](http://stackoverflow.com/questions/43728627/using-the-mindate-from-class-validator-results-in-typeerror-cannot-read-proper).  Am I doing something wrong or is it a bug?

**Comment by oleersoy** [comment]
[Apparently this type of use case is not supported by decorators.](http://stackoverflow.com/questions/43742615/is-it-possible-to-pass-typescript-decorator-object-values-in-at-runtime).  I'll leave this open just in case there's a way for class validator to support this in another way.  Please close the issue when appropriate.

**Comment by NoNameProvided** [comment]
Hi @oleersoy! 

Sorry for the late reply. You are right, you cannot use the `this` keyword that way.
