### ISSUE TITLE
question: element implicitly has an 'any' type on custom validation

### ISSUE THREAD

**Issue by theprobugmaker** [typestack/class-validator#801]
I tried to copy this to my project https://github.com/typestack/class-validator/issues/168#issuecomment-373944641 as I need at least one field to be defined but I'm getting this error:

> Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Object'.

The actual thing I need to do is: I have two fileds, one of them `must` be filled but can't be both.

**Comment by NoNameProvided** [comment]
Please provide a __minimal__ reproducible example showcasing your problem. The example should:

- be as short as possible why showcasing the problem
- has no external dependencies used, only this lib
- the expected and actual behavior should be explained
