### ISSUE TITLE
question: a new lightweight angular reactive form extension library

### ISSUE THREAD

**Issue by abarghoud** [typestack/class-validator#803]
I saw that there was an angular extension library https://github.com/EndyKaufman/ngx-dynamic-form-builder to use with reactive forms.

I tried it, and the problem is, it use a fork of `class-validator` library https://github.com/endykaufman/class-validator-multi-lang that includes translations, but using it will increase the bundle size by ~4MB ans it will force you to depend on a deserialization library.

So I decided to create a deserialization agnostic angular reactive form library (150KB, 3KB minified instead of 4MB), containig better features (clear dynamic validation, combine dynamic "class-validator" and custom validators, etc.).

If you may add it to https://github.com/typestack/class-validator#extensions.

The library: https://github.com/abarghoud/ngx-reactive-form-class-validator

**Comment by NoNameProvided** [comment]
I have added it.
