### ISSUE TITLE
bug: ValidatorOptions stopAtFirstError

### ISSUE THREAD

**Issue by AndreasDvrs** [typestack/class-validator#804]
Cannot use the option stopAtFirstError (nestJS) in validate method. Typescript says: 

  Overload 1 of 2, '(object: Object, validatorOptions?: ValidatorOptions): Promise<ValidationError[]>', gave the following error.
    Argument of type '{ stopAtFirstError: boolean; }' is not assignable to parameter of type 'ValidatorOptions'.
      Object literal may only specify known properties, and 'stopAtFirstError' does not exist in type 'ValidatorOptions'.

**Comment by ggriffin** [comment]
@AndreasDvrs The feature has not been released yet.

**Comment by AndreasDvrs** [comment]
@ggriffin  Oh, i saw it in the documentation thus the confusion.. Thank you for the reply!
