### ISSUE TITLE
Can this be made automatic without having to manually initiate validation?

### ISSUE THREAD

**Issue by trusktr** [typestack/class-validator#81]
For example, I'd like something like this:

```ts
class Foo {
  @Min(0)
  @Max(10)
  bar: number

  constructor() {
    this.bar = 4 // no error
  }
}

let f = new Foo
f.bar = 5 // no error
f.bar = 20 // error
```

without having to manually use `validate` or `validateSync`.

**Comment by jerradpatch** [comment]
So when should it validate? Every variable set?

**Comment by trusktr** [comment]
Yeah, I think so. I know it has performance implications, but that would
make usage simple. It would be nice for modifying data models that aren't
related to animation (f.e. user chat messages, or payment transactions). It
wouldn't be a good idea to use this on data models where values changing
every 16ms for an animation is desired.

I think it would be nice. And maybe it can be opt-in somehow?

Ideally there would be a way to do this stuff at compile time. TypeScript
is becoming pluggable soon, so maybe it can happen in the near future.

**Comment by trusktr** [comment]
It would be nice for it to be automatic because you can pass classes around without having to write validation code every place where an instance if modified. Seems like a lot of development overhead.

On the other had, the manual validation is useful for cases where the model can contain anything, then is validated right before (for example) being inserted into a database.

**Comment by 19majkel94** [comment]
You can do that kind of magic with `Proxy` and apply it with custom decorator like `@AutoValidate`. I could try to do it one day, maybe even as a PR 😉

**Comment by 19majkel94** [comment]
Ok @trusktr, sample code looks like this:
```ts
const AutoValidate: ClassDecorator = (target: FunctionConstructor) => {
    return class extends target {
        constructor(...args: any[]) {
            super(...args);
            const errors = validateSync(this);
            if (errors.length) {
                throw errors;
            }
            return new Proxy(this, {
                set: (object, key, value, proxy) => {
                    const oldValue = object[key];
                    object[key] = value;
                    const errors = validateSync(object);
                    if (errors.length) {
                        object[key] = oldValue;
                        throw errors;
                    }
                    return true;
                }
            });
        }
    }
}
```
Usage:
```ts
@AutoValidate
class SampleValidateClass {
    
    constructor(
        @MinLength(10)
        public property: string,
    ) {}

    printProperty() {
        console.log(this.property);
    }
}

try {
    const sample = new SampleValidateClass("class-validator");
    sample.printProperty();
    sample.property = "Hello World!";
    console.log(sample.property);
    sample.property = "Short";
    console.log(sample);
} catch(err) {
    console.log(err);
}
```

Works great but it perform validation on all properties so it's impossible to set some data to an empty object with more properties. All properties has to be set in constructor.

If `class-validator` expose an API to perform manual validation like `validate(Class, propertyName)` we could to it more efficient.

**Comment by jerradpatch** [comment]
One question that comes to mind is the reasoning to want to validate at every setter. Typescript is useful for build time validation. This package is useful when taking in user data for validation (or other uncontrolled inputs). What case is not covered with the above that dynamic validation (inner code) would be needed? If worried about passing validation code then its all in the class except the validator call in which the group is also passed, but thats about it. Another question is, what kind of code is being passed for validation thats not already in the class? In the negative this would add unneeded over head to code.

**Comment by trusktr** [comment]
@jerradpatch 

Library authors may want for their classes to be used a certain way and to ensure that certain types of numbers are received on properties, and not all end users of a library use TypeScript, so in this case of non-TS user using a library, it'd be nice for the library  (and for the library author) to throw runtime errors about invalid data without requiring the end user to write validation code, and thus preventing the non-TS user from creating unexpected error conditions and asking for support in the issue tracker, when instead a runtime error can say something like "this property only accepts numbers between 0 (inclusive) and 1 (inclusive)" for example. If we don't make those checks, it is possible the user's code may work outside of the design, but eventually might cause some weird error.

Yes, the overhead is unneeded, but it's a convenient way for non-TS users of a library so that they use a library in the expected and designed way.

True, if everyone used TypeScript, and we disallowed `any`, then we could eliminate tons of runtime performance overhead.

@19majkel94 That's a way to do it, in that case the `AutoValidate` tool is basically a ["class factory mixin"](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/).

The only problem I forsee with it is if one class author writes a class that is already AutoValidated, and adds another layer of AutoValidate. It would create duplicate AutoValidators in the prototype chain.

I guess maybe AutoValidate can detect if AutoValidate already exists in the chain, then just return the same class if it already has AutoValidate, or something.

**Comment by trusktr** [comment]
> This package is useful when taking in user data for validation (or other uncontrolled inputs).

Yes, agreed, it would be great for an API on top of Mongo, which receives an object literal to add to a collection, it would for example check that the object matched the "Book" spec for a collection of "Book" metadatas. In this case, the library author would be writing the validation checker, and re-using it in the API.

It's different than a class, and the end-user manipulating instances of that class.

Another possibility, for example, could be not to check on every set of a property, but maybe on a setInterval created by the class, or perhaps a rendering library does the check on each render (but that is expensive).

Honestly, build-time checking is the way to go, but we just don't have it in every end-user's app. 

What would be interesting would be a way to have TypeScript remove runtime type-checking code when compiling the library to JS if the end-user is also using TypeScript, and otherwise the pre-compiled library would come with runtime type checks for the non-TS users.

**Comment by 19majkel94** [comment]
> The only problem I foresee with it is if one class author writes a class that is already AutoValidated, and adds another layer of AutoValidate on the subclass. It would create duplicate AutoValidators in the prototype chain.
I guess maybe AutoValidate can detect if AutoValidate already exists in the chain, then just return the same class if it already has AutoValidate, or something.

Yeah, it's a common decorator inheritance problem. In this situation I always set some property on class to true and check it before applying "the patch". I can fix it if you want to use `@AutoValidate` 😉

**Comment by 19majkel94** [comment]
So in case you want to return lib users some helpfull error, not runtime weird bugs, it can works like the react proptypes. Only in dev environment to not slow down the app with constant checking (when it's about constant parameters, not validating entity created from recceived JSON).

**Comment by NoNameProvided** [comment]
Hi! 

Closing this as this functionality is out-of-scope for this library. As @19majkel94 pointed out, this functionality can be easily achieved with a light wrapper.
