### ISSUE TITLE
question: release?

### ISSUE THREAD

**Issue by cojack** [typestack/class-validator#812]
@NoNameProvided any information when develop will be merged into master? Many ppl awaiting for this feature: https://github.com/typestack/class-validator/pull/680

**Comment by lbennett-simplestream** [comment]
Would love a release for smaller `google-libphonenumber` too

**Comment by LucaDe** [comment]
+1

**Comment by nolazybits** [comment]
I'm sick of waiting and created a fork of this repo here
https://github.com/ts-revival/class-validator

which got released on npm here
https://www.npmjs.com/package/@ts-revival/class-validator

I understand creators want to keep control but when you have such a community keen to help and nothing is moving the best thing is to accept this and get more help even if you loose some of the stearing of the library.

So anyone who's keen to push PR there, I will be happy to make them contributor etc to have this library moving forward.

And thanks to all the contributor / creators of the class-validator libs, I'm using it in all my projects!

**Comment by NoNameProvided** [comment]
Just made a release yesterday. Sorry for the delay, I thought the latest `develop` was released but it was not.
