### ISSUE TITLE
feature: isNotEmptyString

### ISSUE THREAD

**Issue by titovb** [typestack/class-validator#818]
### Description
In work with class-validator, I often need to check if the field is not an empty string. In the case of using class-validator I need to add two decorators:
```
class Test {
  @IsString()
  @IsNotEmpty()
  field: string;
}
```
And also use a trim() function on field and check if it's not empty then too.
I found a solution to create a custom decorator, but I want to use that thing in different projects and I think, that this small feature will be useful for the community of class-validator.

### Proposed solution
Solution: To check if the string is not an empty string we should to use 2 class-validator functions: isString(value) and isNotEmpty(value.trim()).
```
export function IsNotEmptyString(validationOptions?: ValidationOptions) {
  return (object: unknown, propertyName: string) => {
    registerDecorator({
      name: 'isNotEmptyString',
      target: object.constructor,
      propertyName,
      options: validationOptions,
      validator: {
        validate: (value: any): boolean => isString(value) && isNotEmpty(value.trim()),
        defaultMessage: (validationArguments?: ValidationArguments): string => `${validationArguments.property} should not be an empty string`
      }
    })
  }
}
```

**Comment by NoNameProvided** [comment]
Hi! 

We only provide the basic blocks to build up your validation logic, if we would provide every combination for every checked type, we would drown in the decorators. So I am afraid you need to keep providing both decorators or as you did write a custom one this scenario is very common for your use-case.

I will go ahead and close this as wontfix.
