### ISSUE TITLE
feature: @NullIf

### ISSUE THREAD

**Issue by adhranjan** [typestack/class-validator#822]
### Description
Clear the Property if matches certain condition
### Proposed solution
```
@NullIf((obj)=>{
  return (obj.thereisomerandomthing)
})
```

### Implementation
```
NullIfImplementation(obj, func, property){
   if(func(obj)){
     obj[property] = null;
   }
}
```
```
@NullIf((obj)=>{
  return (obj.thereisomerandomthing)
})
readonly: clearIfTheConditionMatch:any;
```

**Comment by vlapo** [comment]
`class-validator` purpose is validate not modify data structures. `class-transformer` should be use in this case.

Maybe you are looking for conditional validations https://github.com/typestack/class-validator#conditional-validation.
