### ISSUE TITLE
fix: Required 'app version' is missing

### ISSUE THREAD

**Issue by proIT324** [typestack/class-validator#825]
### Environment
- react-native-plaid-link-sdk: v6.0.4

### Code snippet
```js
<PlaidLink token={token} onSuccess={() => {}} onError={() => {}}>Connect</PlaidLink>
```

### Steps to reproduce
1. Open Plaid
2. Select a bank institution (e.g. "Revolut")
3. Enter phone number
4. Enter pin code

### Error message
> Required 'app version' is missing

How can I resolve this issue?

**Comment by vlapo** [comment]
Looks like this is not related to `class-validator` 😄
