### ISSUE TITLE
No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.

### ISSUE THREAD

**Issue by hengkx** [typestack/class-validator#833]
### Description

**Minimal code-snippet showcasing the problem**
 

```bash
class-validator@0.12.2 
```

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/101855413-53b25600-3b9e-11eb-8dba-d3b5eae89f95.png)

**Comment by hsiaosiyuan0** [comment]
here is the related commit contains some context: https://github.com/typestack/class-validator/commit/3b7c79a8bcb6bd88d84d8d1e15f958be534997d3

**Comment by NoNameProvided** [comment]
Fixed in 68ed35d7b96348cd060dd86878773551c38c2b3f.
