### ISSUE TITLE
question: dynamic isPostalCode

### ISSUE THREAD

**Issue by btilford** [typestack/class-validator#840]
### Description
I've got a situation where I don't know the `PostalCodeLocale` and need to provide it dynamically. Could the decorator be updated to take a deferred locale? 

### Proposed solution
Current:
```typescript
export declare function IsPostalCode(
  locale?: validator.PostalCodeLocale, 
  validationOptions?: ValidationOptions
): PropertyDecorator;
```

Updated:
```typescript
export declare function IsPostalCode(
  locale?: validator.PostalCodeLocale | (target:any) => validator.PostalCodeLocale, 
  validationOptions?: ValidationOptions
): PropertyDecorator;
```

This would allow writing
```typescript
class Address {
   countryCode:string;

   @IsPostalCode(_ => _.countryCode)
   postalCode:string;
}
```

**Comment by NoNameProvided** [comment]
Not really. Maybe you can try to write a custom async validator wrapping it, and wait for the data there, but I would just validate the object in two go. Much easier. 

To answer the question: I think handling missing validation data (aka waiting until it arrives) is out of scope and won't be implemented. See my first sentence for a workaround.

**Comment by paulhill** [comment]
@NoNameProvided  how does one validate it in 'two go'?
I can't find any useful examples of two phase validation.
