### ISSUE TITLE
@IsOptional and @ValidateNested don't work together...

### ISSUE THREAD

**Issue by JimLynchCodes** [typestack/class-validator#843]
This fails for me even though to me it should be valid:
```
export class SomeConfig {
    @IsString()
    @Matches(DEFAULT_STRING_REGEX)
    @MaxLength(DEFAULT_STRING_MAX_LENGTH)
    localeToken: string;
    
    @IsNumber()
    @Min(DEFAULT_NUMBER_MIN)
    @Max(DEFAULT_NUMBER_MAX)
    pairId: number;
}

export class Foo {
    
    @isNumber
    num: number;

    @IsOptional()
    @ValidateNested()
    @Type(() => SomeConfig)
    someConfig?: SomeConfig;
}

```

someConfig is optional, but I get validation errors for all of its fields (localeToken and pairId) when I send this payload:
```
{ num: 42 }
```

**Comment by mickaelmesdocteurs** [comment]
Are you sure you really send `{ num: 42 }` ?
Because I use the same code and it works, your code is ok and class-validator too

**Comment by vlapo** [comment]
Please provide proper example. Right now it looks like you have a problem with converting data into object. You can use https://stackblitz.com

**Comment by JimLynchCodes** [comment]
hmm yeah I am not sure why it was failing for me before, but it seems like it's giving me the expected behavior now.

thx guys
