### ISSUE TITLE
question: How can I use class-validator setting the object type with keyword 'as'

### ISSUE THREAD

**Issue by Haytam95** [typestack/class-validator#845]
I was trying to implement ``class-validator`` in firebase functions. But when I tried validate the body I got this error:

> No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.

Here is the source code:

```typescript

// index.ts
export const proponerReserva = functions.https.onRequest(async (req, res) => {

    corsHandler(req, res, async () => {

        // const propuesta = req.body.data as PropuestaEventoDto;  This is what I need, but it's not working

        const propuesta = new PropuestaEventoDto();  // This is a simple test, that is working propertly

        await validateOrReject(propuesta).then(_ => {
            res.status(200).json({"data": 'Todo OK: ' + JSON.stringify(propuesta)});

        }).catch(error => {
            res.status(400).json({"error": error});
        });

    });
});

// PropuestaEventoDto.ts
export class PropuestaEventoDto {


    @IsNotEmpty({message: 'El id del usuario no fue definido. ¿Estás logueado?'})
    @IsUUID()
    public userId: string;

    @IsNotEmpty({message: 'No se definió la fecha de la reserva'})
    public date: Date;

    @IsNotEmpty({message: 'No se definió el menú a encargar'})
    @IsFirebasePushId({message: 'El id de comida no es válido'})
    public idComida: string;

    public observaciones: string;

    constructor(
        userId: string = null,
        date: Date = null,
        idComida: string = null,
        observaciones: string = null,
    ) {
        this.userId = userId;
        this.date = date;
        this.idComida = idComida;
        this.observaciones = observaciones;
    }

}
```

How can I read the body and get the validations working?

P.S: I'm using version ``0.12.2``

**Comment by vlapo** [comment]
I asume `req.body.data` is plain object. You have to convert it to instance of object for example using https://github.com/typestack/class-transformer

`as` is just a TypeScript syntax to force change type.

**Comment by NoNameProvided** [comment]
> as is just a TypeScript syntax to force change type.

To elaborate on this sentence: the `as` syntax is a compile-time check/modification when you mark a variable with it, TypeScript will think that variable has the type specified but this __won't change the type during the code execution__ and `class-validator` checks the type at the time of execution (what really is in the variable). So as @vlapo said, you have to transform the variable to the desired type first, we have a library for that: https://github.com/typestack/class-transformer.

I will go ahead and close this question as solved.
