### ISSUE TITLE
question: google-libphonenumber is big - is there any solution?

### ISSUE THREAD

**Issue by JuhG** [typestack/class-validator#851]
I've seen that this was already discussed, but the current version in npm still installs `google-libphonenumber`, which is huge. As I see the github dependencies, it already has `libphonenumber-js`, which is much smaller. Can this be tagged in npm as a new version? Any other way we can use it? Is there maybe a fork without phone number validation?
Thanks!

We wanted to use this for validation in the browser so the rules are consistent, but it's not really possible in it's current form.

Current size of the phonenumber lib that we don't use at all:
![Screenshot from 2021-01-11 15-12-02](https://user-images.githubusercontent.com/10765158/104192650-67600f00-541f-11eb-8851-a205a54a53f2.png)

Current dependencies in npm:
![Screenshot from 2021-01-11 14-59-22](https://user-images.githubusercontent.com/10765158/104193032-ee14ec00-541f-11eb-90a0-21c25ecc91bc.png)

**Comment by NoNameProvided** [comment]
Hmm, I thought that version was released months ago. 😱 Anyway released now as `0.13.0`.

**Comment by JuhG** [comment]
Awesome, thank you!
