### ISSUE TITLE
fix: documentation incorrect for @IsPhoneNumber decorator in v0.13.0

### ISSUE THREAD

**Issue by asmimo** [typestack/class-validator#871]
### Description
v0.13.0 throws error on code using "@IsPhoneNumber" when passing "ZZ" or null as parameter

**Comment by NoNameProvided** [comment]
Can you try passing `undefined`?

**Comment by asmimo** [comment]
`undefined` works but is the same as `"ZZ"`

**Comment by NoNameProvided** [comment]
I have updated the documentation of the function in 1fa074d63078346238a6a7becf1f698b09a67350. 

Undefined
