### ISSUE TITLE
feature: simple custom validators

### ISSUE THREAD

**Issue by ghost** [typestack/class-validator#882]
### Description

I tend to want to include quite a few custom validators but I find the amount of boilerplate code required to creates a lot of noise especially when you need to create many of them.

### Proposed solution

A decorator called CustomValidation:

    import { CustomValidation } from 'class-validator'

    @CustomValidation(
        (value: string, obj: any) => {
            // ...validation logic
            return true
        },
        () => {
            return 'Some validation error message'
        }
    )
    field: string

OR a simple function for making validators:

    import { makeCustomValidator } from 'class-validator'

    const MyValidator = makeCustomValidator(
        (value: string, args: ValidationArguments) => {
            // ...validation logic
            return true
        },
        (args: ValidationArguments) => {
            return 'Some validation error message'
        }
    )

    //... use as decorator

    class MyThing {
        @MyValidator(/* ... constraints ... */)
        field: string
    }

**Comment by rubiin** [comment]
I cant agree more :)

**Comment by pra-richardg2-sportsbet** [comment]
Any more consideration for this?

**Comment by pra-richardg2-sportsbet** [comment]
@pleerock @NoNameProvided Are there any pointers as to where I might start trying to implement this if I were to have a go? If a PR were raised would it be considered, is this still an actively maintained repo?

**Comment by braaar** [comment]
I support this idea and it has also been discussed in #386. I'll close this as a duplicate and we can continue the conversation there.
