### ISSUE TITLE
Cannot validate a class property named "metadata"

### ISSUE THREAD

**Issue by xorbis** [typestack/class-validator#885]
### Description
I am getting this when when trying to validate a class with a property named "metadata".

Using:
NestJs 7.5.4

**Minimal code-snippet showcasing the problem**
```ts
export class MyDto {
	@IsString()
	metadata: string
}
```

### Expected behavior
Expecting "metadata" to behave like any other property name.

### Actual behavior
Compilation throws an error: 
      Types of property 'metadata' are incompatible.
        Type 'string' is not assignable to type 'Emptyable<MetadataParam>'.

**Comment by vlapo** [comment]
Could you please provide more informations (stack trace)? What is `Emptyable`? This doesnt look like class-validator problem.

**Comment by xorbis** [comment]
It is probably something to do with NestJs types. My guess is that is that a DTO class in NestJs uses the metadata property and thus it cannot be used as a DTO property and use validation on it. Probably not a class-validator problem like you say. If you confirm this, I can forward this issue to NestJs instead.

**Comment by vlapo** [comment]
Try reproduce your problem without validation. Or could you post full class with metadata property? I can check it but I have to see minimal reproducible example.
