### ISSUE TITLE
question: IsISO8601Options is not on validator object

### ISSUE THREAD

**Issue by fselcukcan** [typestack/class-validator#913]
**I was trying to use the `IsISO8601` via `IsDateString` and could find no options available from validator js as written in code as `ValidatorJS.IsISO8691Options` in the validator.js `validator` object export.**
 
 

https://github.com/validatorjs/validator.js/issues/1607

**Comment by NoNameProvided** [comment]
I cannot understand your problem. Closing as cannot reproduce.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
