### ISSUE TITLE
question: Validating Object after creation with class-transformer

### ISSUE THREAD

**Issue by engshorouq** [typestack/class-validator#920]
## I was trying to transform value using class-transformer to object then make validation but it does not work and the data inside class gone
this code is a sample of my code 
the filter comes as a string from the query =>  https://example.com/api/endpoint?filter={name: "test"}
```
import { IsOptional, IsString, ValidateNested } from 'class-validator';
import { Transform, Type } from 'class-transformer';

class SampleFilterDto {
  @IsString()
   name: text
}
class Filter {
   @IsOptional()
  @ValidateNested()
  @Transform((value) => JSON.parse(value))
  @Type(() => SampleFilterDto)
  filter: SampleFilterDto;
}
```

but the problem I think the Transform and ValidateNested not work with each other
because the incoming data to the Dto is {filter: "{name: \"test\"}"}
and then the data after validation is coming like that {filter: {}}
- when deleting the ValidateNested the filter it will be like that {filter: {name: "test"}}

my question is there is any way to transform the text to an object then make the nested validation ???

**Comment by luanxuechao** [comment]
me,too

**Comment by luanxuechao** [comment]
@engshorouq  you can try 
```ts
import { IsOptional, IsString, ValidateNested } from 'class-validator';
import { Transform, Type,plainToClass} from 'class-transformer';

class SampleFilterDto {
  @IsString()
   name: text
}
class Filter {
   @IsOptional()
  @ValidateNested()
  @Transform((value) => plainToClass(SampleFilterDto,JSON.parse(value)))
  @Type(() => SampleFilterDto)
  filter: SampleFilterDto;
}
```

**Comment by NoNameProvided** [comment]
Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
