### ISSUE TITLE
feature: allow relying on `libphonenumber`'s `isPossible` for phone numbers validation

### ISSUE THREAD

**Issue by fwoelffel** [typestack/class-validator#939]
### Description

The phone numbers validation relies on `libphonenumber`'s [`isValid`](https://github.com/ruimarinho/google-libphonenumber/blob/master/src/phonenumberutil.js#L3059) function. This function operates a strict validation, but there's also the [`isPossible`](https://github.com/ruimarinho/google-libphonenumber/blob/master/src/phonenumberutil.js#L3356) function that basically only checks the number's format.

### Proposed solution

I'd like to be able to pass some options to the `IsPhoneNumber` decorator to make it rely on `isPossible`.

The best, non-breakin, approach would be for the decorator to accept either a `CountryCode` (current behavior) or a `{ region?: CountryCode; strategy: 'valid' | 'possible'; }` argument. The default behavior wouldn't change.

**Comment by NoNameProvided** [comment]
This won't be implemented for now. See https://github.com/typestack/class-validator/pull/940#issuecomment-1353722358 for more details.
