### ISSUE TITLE
question: Specific validation with custom decorators

### ISSUE THREAD

**Issue by i-kohan** [typestack/class-validator#943]
**I was trying to...**
In my project I use Nest.js along with GraphQL. I would like the ValidationPipe to be responsible for all the validation in my project.

I have a form where a user can create an activity named in multiple languages. Each activity belongs to a certain shop.

There are entities:

**Activity**
```
@ObjectType()
export class Activity {
  @Field()
  shopId: string;

  @Field()
  id: string;

  @Field(() => [MultiLanguageField])
  name: [MultiLanguageField];
}
```

**MultiLanguageField**
```
@ObjectType()
export class MultiLanguageField {
  @Field()
  lang: string;

  @Field()
  value: string;
}
```

Thus, when creating these entities, I use the following InputTypes:

**CreateActivityDto**
```
@ArgsType()
export class CreateActivityDto {
  @Field()
  readonly shopId: string;
   
  @Field(() => [ActivityNameInput])
  @ValidateNested({ each: true })
  @Type(() => ActivityNameInput)
  // @ValidateNameOuter
  readonly name: [ActivityNameInput];
}
```

**ActivityNameInput**
```
@InputType()
export class ActivityNameInput {
  @Field()
  lang: string;

  @Field()
  // @ValidateNameInner
  value: string;
}
```

Also, one of the requirements is to check that the name does not match in some language with the already existing activity that belongs to the same shop.

For example: 
We have the following activity in the database
```
{
    id: '1',
    shopId: '1',
    name: [
        { lang: 'de', value: 'Aktivitätsname' },
        { lang: 'en', value: 'activity name' }
    ]
}
```
We cannot create an activity
```
{
    shopId: '1',
    name: [
        { lang: 'de', value: '123'},
        { lang: 'en', value: 'activity name' }
    ]
}
```
because we already have `{ lang: 'en', value: 'activity name' }` for the shop with `id = 1`  in the database.

**The problem:**

I need to somehow use Custom validation decorators to validate the situation when the user creates an activity with an existing name in some language and I need to return only those languages where there is an error.

I was thinking about two solutions:
1. Use a decorator in CreateActivityDto (@ValidateNameOuter)
2. Use decorator in ActivityNameInput (@ValidateNameInner)

In the **first** solution, I can look at the names of all activities that belongs to the current shop and compare them with those that came, but I cannot return the language and value in which there is an error, because after validation, the entire name field will be returned in full, with all languages.

In the **second** solution, I can return an single language error, but I do not have access to the `shopId` field, so I cannot take all the activities of the current shop.

**Comment by NoNameProvided** [comment]
Sorry I cannot provide support for general programming-related problems. 

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
