### ISSUE TITLE
Why not do some auto transform in decorator validation?

### ISSUE THREAD

**Issue by ruiming** [typestack/class-validator#95]
Sometime I want to use an interface to validate both body or queryParams. But there only exist string type in queryParams which make some decorators such as `@IsNumber` always validate failure.
So I have to write a custom validator to validate and meantimes not breaking body validation.
For example: 
``` typescript
export function IsNumber (validationOptions?: ValidationOptions) {
  return (object: Object, propertyName: string) => {
    registerDecorator({
      name: 'IsNumber',
      target: object.constructor,
      propertyName: propertyName,
      constraints: [],
      options: validationOptions,
      validator: {
        validate (value: any, args: ValidationArguments) {
          const type = Reflect.getMetadata('design:type', args.object, args.property)
          if (type === Number && typeof value === 'string') {
            value = parseInt(value, 10)
          }
          return typeof value === 'number' && !isNaN(value)
        },
        defaultMessage () {
          return 'Must be a number or string that can be parsed into number'
        }
      }
    })
  }
}
```
In this decorator, '10', 10' can both pass the validation, and will auto be transformed into 10 if value is '10'.
I think it is ok to do such auto transform in decorator. Or maybe an option to do so? What do you think?

**Comment by ericzon** [comment]
Hi @ruiming , I do query parameters validation and I found your same issue. You need to define your field on your dto as type number:

````
@IsInt()
@Type(() => Number)
public year: number;
````

You can import "Type" from class-transformer library.

With this added, you onlye have to call the method:

````
const object = plainToClass(classType, rawDto);
````
Before your validation.

Cheers!

**Comment by ruiming** [comment]
Great, thank you guy.
