### ISSUE TITLE
Exclusive Field

### ISSUE THREAD

**Issue by BishoyNarouz** [typestack/class-validator#971]
i want to check that, at least one field exists and if for example cardId exists loanId should not exist and vice versa
how can i implement that without custom decorator?

	@ValidateIf(req => !req.loanId)
	@IsUUID('all', { message: 'RESIDENCE_TYPE_ID_IS_INVALID' })
	cardId?: string;

	@ValidateIf(req => !req.cardId)
	@IsUUID('all', { message: 'RESIDENCE_TYPE_ID_IS_INVALID' })
	loanId?: string;

**Comment by lytc** [comment]
@BishoyNarouz This hacky way will work!
```ts
@IsUUID('all', { message: 'RESIDENCE_TYPE_ID_IS_INVALID' })
cardId?: string;

@IsUUID('all', { message: 'RESIDENCE_TYPE_ID_IS_INVALID' })
loanId?: string;

@ValidateIf((o) => !o.cardId && !o.loanId)
@IsNotEmpty()
get atLeastCardOrLoan() {
  return this.cardId || this.loadId;
}
```

**Comment by NoNameProvided** [comment]
The above example would work, you can also create a custom validation decorator for this.

Closing this as solved.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help.
