### ISSUE TITLE
Add validation to picked properties of existing interface

### ISSUE THREAD

**Issue by lveillard** [typestack/class-validator#972]
Hello there! 

I have an interface, let's say this one:

```ts
export interface UserResponseObject extends ResponseObject {
  id: string;
  email: string;
  username: string | null;
  createdAt: Date;
}
```
I want to reuse it (DRY) and validate it on the way.  So let's say I have a `specialUser`, a "fragment" of User that has only the email and the id:

`export type FragmentUserObject = ResponseObject & Pick<User, 'email' |  'id'>`

But let's say I want to apply the validator `@IsEmail` to the `email` property. Of course, this does not work but maybe helps to better get the idea:

`export type FragmentUserObject = ResponseObject & Pick<User,  @IsEmail() 'email' |  'id'>`

Do you know about a beautiful way to do this?

Note: Adding it to the original interface is not an option. (It comes from a model inside a schema.prisma file, as I'm using Prisma as my ORM. So the point actually is that I want to use the model of this file, build some fragments of those models with pick<>, and some _extended_ versions, and do the validations on the fly) 

Of course i could just rewrite every single model, but that would be not DRY at all). Also from each model i'm creating 3 or 4 nearly identic things.

**Comment by NoNameProvided** [comment]
You cannot apply validation metadata to types. What you ask (adding validation to Typescript type) is not possible. 

You can achieve something similar with sub-classing and going the other way around: 
- having a minimal user class (your fragment)
- having a full class that extends the minimal class
