### ISSUE TITLE
question: validate Patch request

### ISSUE THREAD

**Issue by samuellasmi100** [typestack/class-validator#975]
Hi..
Im trying to validate a patch request .. so i use IsOptional to ignore the other lines that the user does not update., but the problem is.. that after the update, it leaves only what the user has updated ,and all the other details he deletes ..someone can help?
 i hope  i explained well..

**Comment by NoNameProvided** [comment]
I don't understand your problem. 

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/class-validator/discussions/categories/questions-answers) and someone from the community may be able to help. When opening a new Q&A please provide a minimal reproducible case showcasing your problem.
