### ISSUE TITLE
Add IsFinite

### ISSUE THREAD

**Issue by thevtm** [typestack/class-validator#98]
Hello! I really enjoy using this lib, saves a ton of time and the code looks pretty good.

I like using Number.isFinite is quite a useful function to validate for NaNs, etc. I think it would be a nice adition.

```javascript
Number.isFinite(Infinity);  // false
Number.isFinite(NaN);       // false
Number.isFinite(-Infinity); // false

Number.isFinite(0);         // true
Number.isFinite(2e64);      // true

Number.isFinite('0');       // false, would've been true with
                            // global isFinite('0')
Number.isFinite(null);      // false, would've been true with
                            // global isFinite(null)
```
[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite)

**Comment by NoNameProvided** [comment]
Hey @thevtm! 

Thanks for the report! It has been fixed and will be released in the version. The new signature for `@IsNumber` is

```ts
@IsNumber(allowNan: boolean = false)
```

**Comment by NoNameProvided** [comment]
Hey @thevtm! 

Thanks for the report! The behavior of `@IsNumber`  has been changed and now it only validates values with `typeof == number` The new signature for `@IsNumber` is

```ts
@IsNumber(options: IsNumberOptions
```
