### ISSUE TITLE
fix: code-base must use Array.isArray

### ISSUE THREAD

**Issue by tmtron** [typestack/class-validator#988]
### Description

The codebase should always use `Array.isArray` instead of `instanceof Array` checks.

Quote from: [Require Array.isArray() instead of instanceof Array](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/no-instanceof-array.md)  
>The instanceof Array check doesn't work across realms/contexts, for example, frames/windows in browsers or the vm module in Node.js.

see also:
* [MDN: instanceof vs isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray)
* [Stackoverflow: Difference between using Array.isArray and instanceof Array](https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array)

**Minimal code-snippet showcasing the problem**
 

Note, that this test can only be executed when there is at least 1 network interface.  
This test fails with the current version of class-validator because [isArray()](https://github.com/typestack/class-validator/blob/v0.13.1/src/decorator/typechecker/IsArray.ts#L10) uses an `instanceof Array` check

```ts
  it('should work for all arrays', () => {
    const osInterfaces = os.networkInterfaces();
    if (Object.keys(osInterfaces).length > 0) {
      const networkInterfaceArray = Object.values(os.networkInterfaces())[0]!;
      expect(Array.isArray(networkInterfaceArray)).toBeTruthy();
      expect(isArray(networkInterfaceArray)).toBeTruthy();
    } else {
      console.warn('cannot execute test: no network interfaces found');
    }
  });  
```

I am not sure how to make a better test, that will also work when there are no network interfaces. To my surprise the following tests works. This test also returns an array from the `node.os` package:
```ts
  it('should work for all arrays 2', () => {
      const anArray = Object.values(os.loadavg());
      expect(Array.isArray(anArray)).toBeTruthy();
      expect(isArray(anArray)).toBeTruthy();
  }); 
```

### Expected behavior

`isArray()` should work for all arrays

### Actual behavior

`isArray()` sometimes fails

**Comment by NoNameProvided** [comment]
As of `0.14.0` the codebase doesn't contain any `instanceof Array` checks.
