### ISSUE TITLE
feat: `@IsISO8601` decorator should only accept basic or extended format but not both

### ISSUE THREAD

**Issue by by-zhou** [typestack/class-validator#996]
The `isISO8601` validator should only accept either basic or extended format, but not a mix of them.

For example, the following should return false
2021-03-29T010000Z

Only the following two should be valid:
2021-03-29T01:00:00Z or 20210329T010000Z

Reference:
https://en.wikipedia.org/wiki/ISO_8601#General_principles
This is also implemented in `moment`: https://github.com/moment/moment/issues/2025

**Comment by NoNameProvided** [comment]
Closing this as `wontfix` because the implementation of date validation comes from the upstream `validator` library. You should open your feature request in [their repository](https://github.com/validatorjs/validator.js).
